import {defineRemediationDestinations,evaluateTollgateReadiness,tollgateDestination} from './tollgate';

const projectId='project-42';
const completeCharter={projectSummary:'Executive summary with quantified opportunity.',targetDate:'2026-12-01',businessCase:'Material customer and financial case for action.',problemStatement:'Defects exceed the approved threshold.',goalStatement:'Reduce defects below one percent.',scopeIn:'Assembly',scopeOut:'Suppliers',team:[{name:'Belt'}],stakeholders:[{name:'Sponsor'}],timeline:[{date:'2026-09-01'}],financialImpact:'100000',risks:[{risk:'Delay',mitigation:'Escalate'}],assumptions:'Stable demand',constraints:'Current equipment',approvals:[{name:'Sponsor',status:'Approved'}]};

test('every Define remediation preserves project identity and uses professional destinations',()=>{const links=defineRemediationDestinations(projectId);expect(links).toEqual({charter:'/projects/project-42/charter',owner:'/projects/project-42?tab=project-settings&focus=owner',sponsor:'/projects/project-42?tab=project-settings&focus=sponsor',team:'/projects/project-42?tab=team&focus=reviewer',sipoc:'/projects/project-42/documents/sipoc',voc:'/projects/project-42/documents/voc',ctq:'/projects/project-42/documents/ctq-tree',tollgate:'/projects/project-42?tab=tollgates&phase=Define',binder:'/projects/project-42?tab=project-binder&phase=Define'});Object.values(links).forEach(destination=>{expect(destination).toContain(projectId);expect(destination).not.toContain('guided');expect(destination).not.toContain('Measure')})});
test('Define readiness emits focused owner and sponsor actions plus canonical document routes',()=>{const result=evaluateTollgateReadiness({id:projectId,charter:completeCharter,owner:'',champion:''},'Define',{}),byCode=Object.fromEntries(result.missingRequirements.map(item=>[item.code,item]));expect(byCode.owner).toEqual(expect.objectContaining({actionLabel:'Assign Owner',destination:defineRemediationDestinations(projectId).owner}));expect(byCode.sponsor).toEqual(expect.objectContaining({actionLabel:'Assign Sponsor',destination:defineRemediationDestinations(projectId).sponsor}));expect(byCode.sipoc.destination).toBe(defineRemediationDestinations(projectId).sipoc);expect(byCode.voice.actions.map(item=>item.destination)).toEqual([defineRemediationDestinations(projectId).voc,defineRemediationDestinations(projectId).ctq])});
test('canonical remediation updates recompute readiness and remove resolved blockers',()=>{const before=evaluateTollgateReadiness({id:projectId,charter:completeCharter,owner:'',champion:''},'Define',{});expect(before.blockers.map(item=>item.code)).toEqual(expect.arrayContaining(['owner','sponsor']));const after=evaluateTollgateReadiness({id:projectId,charter:completeCharter,owner:'Black Belt',champion:'Sponsor',sharedFields:{owner:'Black Belt',sponsor:'Sponsor'}},'Define',{});expect(after.blockers.map(item=>item.code)).not.toEqual(expect.arrayContaining(['owner','sponsor']));expect(after.completedRequirements.map(item=>item.code)).toEqual(expect.arrayContaining(['owner','sponsor']))});
test('Define gate remains the lifecycle boundary before Measure',()=>{expect(tollgateDestination(projectId,'Define')).toBe(defineRemediationDestinations(projectId).tollgate);expect(defineRemediationDestinations(projectId).tollgate).not.toContain('/documents/data-collection-plan')});
