export const LEAN_RECORD_VERSION=1;
export const LEAN_RECORD_TYPES=Object.freeze(['value-stream-map','standard-work','yamazumi','kanban-loop','heijunka','smed','a3','kaizen','kaizen-event','gemba-observation','process-audit','daily-management','abnormality','x-matrix','catchball']);
const now=()=>new Date().toISOString();
const uid=prefix=>window.crypto?.randomUUID?.()||`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
export function assertLeanScope(record,context){if(!context?.userId)throw new Error('Authenticated user is required.');if(!context.organizationId||!context.projectId)throw new Error('Organization and project scope are required.');if(record?.organizationId&&record.organizationId!==context.organizationId)throw new Error('Organization scope mismatch.');if(record?.projectId&&record.projectId!==context.projectId)throw new Error('Project scope mismatch.');}
export function normalizeLeanRecord(record={},context={}){assertLeanScope(record,context);if(!LEAN_RECORD_TYPES.includes(record.type))throw new Error('Unsupported Lean record type.');const stamp=now();return{schemaVersion:LEAN_RECORD_VERSION,id:record.id||uid('lean'),organizationId:record.organizationId||context.organizationId,projectId:record.projectId||context.projectId,type:record.type,title:record.title||`Untitled ${record.type}`,status:record.status||'Draft',revision:Number(record.revision)||1,priorRevisionId:record.priorRevisionId||null,isCurrent:record.isCurrent!==false,ownerId:record.ownerId||context.userId,createdBy:record.createdBy||context.userId,updatedBy:record.updatedBy||context.userId,createdAt:record.createdAt||stamp,updatedAt:record.updatedAt||stamp,effectiveAt:record.effectiveAt||null,changeSummary:record.changeSummary||'Initial version',payload:record.payload&&typeof record.payload==='object'?record.payload:{},metadata:record.metadata&&typeof record.metadata==='object'?record.metadata:{}}}
export function reviseLeanRecord(record,updates,context,changeSummary){assertLeanScope(record,context);if(!changeSummary?.trim())throw new Error('A change summary is required.');const protectedFields=new Set(['id','organizationId','projectId','createdBy','createdAt','revision','priorRevisionId']),changes={};Object.entries(updates||{}).forEach(([key,value])=>{if(!protectedFields.has(key)&&JSON.stringify(record[key])!==JSON.stringify(value))changes[key]={prior:record[key]??null,next:value??null}});if(!Object.keys(changes).length)return{prior:record,current:record,revision:null};const stamp=now(),revisionId=uid('lean-revision'),current=normalizeLeanRecord({...record,...Object.fromEntries(Object.entries(changes).map(([key,value])=>[key,value.next])),revision:record.revision+1,priorRevisionId:revisionId,updatedBy:context.userId,updatedAt:stamp,changeSummary},context);return{prior:{...record,isCurrent:false},current,revision:{id:revisionId,organizationId:record.organizationId,projectId:record.projectId,recordId:record.id,revision:current.revision,priorRevision:record.revision,snapshot:record,changes,changeSummary,createdBy:context.userId,createdAt:stamp}}}
export function linkLeanObjects(from,to,relationship,context,metadata={}){assertLeanScope(from,context);assertLeanScope(to,context);if(!from.id||!to.id||!from.type||!to.type||!relationship)throw new Error('Canonical object identities and relationship are required.');return{organizationId:context.organizationId,projectId:context.projectId,createdBy:context.userId,fromType:from.type,fromId:from.id,toType:to.type,toId:to.id,relationship,metadata}}
export function normalizeLeanRows(rows,context){return(rows||[]).map(row=>normalizeLeanRecord(row,context)).filter(row=>row.isCurrent)}
