import{correctiveActionContext}from'./correctiveAction';
import{TOLLGATE_PHASES,TOLLGATE_STATUSES,evaluateTollgateReadiness,tollgateDetail}from'./tollgate';

const AREA_TITLES={Define:'Define / Project Definition',Measure:'Measurement & Baseline',Analyze:'Root Cause & Analysis',Improve:'Improvement & Corrective Actions',Control:'Control & Sustainment'};
const gateDestination=(projectId,phase)=>`/projects/${projectId}?tab=tollgates&phase=${encodeURIComponent(phase)}`;
const latestFor=(reviews,phase)=>reviews.map(tollgateDetail).filter(item=>item.phase===phase).sort((a,b)=>(b.attempt||1)-(a.attempt||1))[0]||null;
const firstAction=item=>item?{label:item.label,actionLabel:item.actionLabel,destination:item.destination,code:item.code,severity:item.severity}:null;

export function computeOEProjectHealth(project,context={}){
 const resources={documents:context.documents||[],datasets:context.datasets||[],analyses:context.analyses||[],evidence:context.evidence||[],artifacts:context.artifacts||[],correctiveActions:context.correctiveActions||[]},reviews=context.tollgateReviews||[],actions=correctiveActionContext(resources.correctiveActions,context.now||new Date()),phaseIndex=Math.max(0,TOLLGATE_PHASES.indexOf(project?.currentPhase)),projectId=project?.id||'';
 const areas=TOLLGATE_PHASES.map((phase,index)=>{const readiness=evaluateTollgateReadiness(project,phase,resources),gate=latestFor(reviews,phase),completed=readiness.completedRequirements,total=completed.length+readiness.missingRequirements.length,score=total?Math.round(completed.length/total*100):100,approved=gate&&[TOLLGATE_STATUSES.APPROVED,TOLLGATE_STATUSES.CONDITIONAL].includes(gate.status),activeReview=gate&&[TOLLGATE_STATUSES.SUBMITTED,TOLLGATE_STATUSES.IN_REVIEW].includes(gate.status),status=approved?'Complete':readiness.blockers.length?'At risk':readiness.warnings.length?'Needs attention':'Ready',next=firstAction(readiness.blockers[0]||readiness.warnings[0])||{label:activeReview?`${phase} Tollgate is ${gate.status}`:`${phase} Tollgate is ready to submit`,actionLabel:`Open ${phase} Tollgate`,destination:gateDestination(projectId,phase),code:'tollgate',severity:'action'};return{id:phase.toLowerCase(),phase,title:AREA_TITLES[phase],status,score,isCurrent:index===phaseIndex,isPast:index<phaseIndex,gateStatus:gate?.status||'Not Submitted',readyToSubmit:readiness.readyToSubmit,complete:completed,blockers:readiness.blockers,warnings:readiness.warnings,nextAction:next}});
 const current=areas[phaseIndex]||areas[0],overdueCurrent=(current.phase==='Improve'||current.phase==='Control')?actions.overdue[0]:null,recommended=overdueCurrent?{label:`Corrective action overdue: ${overdueCurrent.title}`,actionLabel:'Open Corrective Action',destination:`/projects/${projectId}?tab=corrective-actions&correctiveAction=${encodeURIComponent(overdueCurrent.id)}`,code:'overdue-corrective-action',severity:'blocker'}:current.nextAction,totalComplete=areas.reduce((sum,item)=>sum+item.complete.length,0),totalRequirements=areas.reduce((sum,item)=>sum+item.complete.length+item.blockers.length+item.warnings.length,0),blockers=areas.flatMap(item=>item.blockers.map(entry=>({...entry,phase:item.phase}))),warnings=areas.flatMap(item=>item.warnings.map(entry=>({...entry,phase:item.phase})));
 return{projectId,currentPhase:current.phase,overall:{score:totalRequirements?Math.round(totalComplete/totalRequirements*100):100,status:blockers.some(item=>item.phase===current.phase)?'At risk':warnings.some(item=>item.phase===current.phase)?'Needs attention':'On track'},phases:areas.map(({phase,status,score,isCurrent,isPast,gateStatus,readyToSubmit})=>({phase,status,score,isCurrent,isPast,gateStatus,readyToSubmit,destination:gateDestination(projectId,phase)})),areas,blockers,warnings,recommendedNextAction:recommended,correctiveActions:{open:actions.open.length,overdue:actions.overdue.length,pendingEffectiveness:actions.pendingEffectiveness.length}};
}
