import {attachEvidence,createProductRecord,normalizeVerification,productReadiness,reviseProductRecord,traceabilityRows,transitionVerification}from'./productDevelopmentRecords';
const context={userId:'user-1',organizationId:'org-1',projectId:'project-1'};
describe('durable product-development records',()=>{
 test('creates, revises, reopens and preserves material history',()=>{const requirement=createProductRecord('requirement',{requirementKey:'REQ-1',title:'Force requirement'},context),revision=reviseProductRecord('requirement',requirement,{title:'Revised force requirement'},context,'Customer revision');expect(revision.record).toMatchObject({id:requirement.id,revision:2,title:'Revised force requirement'});expect(revision.revision.changes.title).toEqual({prior:'Force requirement',next:'Revised force requirement'});expect(createProductRecord('requirement',revision.record,context).id).toBe(requirement.id)});
 test('creates and edits CTQs without overwriting identity',()=>{const ctq=createProductRecord('ctq',{ctqKey:'CTQ-1',name:'Force',unit:'N',usl:30},context),change=reviseProductRecord('ctq',ctq,{usl:28},context,'Customer tightened spec');expect(change.record.id).toBe(ctq.id);expect(change.record.usl).toBe(28);expect(change.revision.changes.usl).toEqual({prior:30,next:28})});
 test('normalizes malformed legacy verification records safely',()=>{expect(normalizeVerification({id:'DV-legacy',status:'Unknown',evidence:'old-report'},context)).toMatchObject({id:'DV-legacy',status:'Draft',revision:1,evidenceLinks:[expect.objectContaining({type:'external-reference',objectId:'old-report'})]})});
 test('enforces authorization scope',()=>{const requirement=createProductRecord('requirement',{title:'Scoped'},context);expect(()=>reviseProductRecord('requirement',requirement,{title:'x'},{...context,userId:''})).toThrow('Authenticated');expect(()=>reviseProductRecord('requirement',requirement,{title:'x'},{...context,organizationId:'org-2'})).toThrow('Organization');expect(()=>reviseProductRecord('requirement',requirement,{title:'x'},{...context,projectId:'project-2'})).toThrow('Project')});
});
describe('verification execution and evidence',()=>{
 test('blocks PASS without canonical evidence and analysis',()=>{let record=createProductRecord('verification',{verificationKey:'DV-1',requirementIds:['R1'],ctqIds:['C1'],testName:'Force test',status:'In Progress',rationale:'Criterion met'},context);expect(()=>transitionVerification(record,'Passed',context)).toThrow('PASS requires');record=attachEvidence(record,{type:'analysis',objectId:'analysis-1'},context);record=reviseProductRecord('verification',record,{linkedAnalysisIds:['analysis-1']},context).record;expect(transitionVerification(record,'Passed',context).status).toBe('Passed')});
 test('supports fail, inconclusive, duplicate-safe evidence and rejects bad transitions',()=>{let record=createProductRecord('verification',{status:'In Progress',testName:'Test'},context);const attached=attachEvidence(record,{type:'report',objectId:'report-1'},context);expect(attachEvidence(attached,{type:'report',objectId:'report-1'},context).evidenceLinks).toHaveLength(1);expect(transitionVerification(record,'Failed',context).status).toBe('Failed');expect(transitionVerification(record,'Inconclusive',context).status).toBe('Inconclusive');expect(()=>transitionVerification(record,'Ready',context)).toThrow('cannot transition')});
 test('traces missing relationships, evidence, failures and findings',()=>{const requirements=[createProductRecord('requirement',{id:'R1'},context),createProductRecord('requirement',{id:'R2'},context)],ctqs=[createProductRecord('ctq',{id:'C1',requirementIds:['R1']},context)],verifications=[createProductRecord('verification',{id:'V1',ctqIds:['C1'],requirementIds:['R1'],status:'Failed'},context)],findings=[{id:'F1',verificationId:'V1',status:'open'}],rows=traceabilityRows({requirements,ctqs,verifications,findings});expect(rows.find(item=>item.requirement.id==='R2').flags).toContain('Missing CTQ');expect(rows.find(item=>item.verification?.id==='V1').flags).toEqual(expect.arrayContaining(['Missing Evidence','Failed Verification','Open Finding']))});
 test('returns deterministic readiness state without granting release approval',()=>{const requirement=createProductRecord('requirement',{id:'R1'},context),ctq=createProductRecord('ctq',{id:'C1',requirementIds:['R1']},context),verification=createProductRecord('verification',{id:'V1',requirementIds:['R1'],ctqIds:['C1'],status:'Failed'},context),summary=productReadiness({requirements:[requirement],ctqs:[ctq],verifications:[verification],msaStatus:'Pass'});expect(summary.status).toBe('Not Ready');expect(summary.statement).toContain('not a formal release')});
});
