import {createProjectPlacement,normalizePlacement,placementDestinations,placementLabel,suggestProjectPlacement,UNFILED_LOCATION,upsertProjectPlacement} from './projectPlacement';
import {sortReportItemsByPhase} from '../context/ReportContext';

test.each([['msa','Measure','Measurement System'],['capability-analysis','Measure','Process Performance'],['control-chart','Control','Process Control'],['hypothesis','Analyze','Hypothesis & Comparison'],['anova','Analyze','Hypothesis & Comparison'],['regression','Analyze','Relationships & Prediction'],['logistic','Analyze','Relationships & Prediction'],['distribution-analysis','Analyze','Verification & Synthesis'],['doe-rsm','Improve','Experimentation']])('%s receives canonical smart placement',(toolId,phase,cluster)=>expect(suggestProjectPlacement(toolId)).toEqual(expect.objectContaining({phase,workflowCluster:cluster})));
test('manual placement override is retained',()=>{const location=placementDestinations().find(item=>item.workflowCluster==='Verification & Synthesis'),placement=createProjectPlacement({projectId:'p1',artifactId:'a1',location});expect(placementLabel(placement)).toBe('Analyze → Verification & Synthesis')});
test.each([true,false])('report inclusion remains independent when %s',reportIncluded=>{const placement=createProjectPlacement({projectId:'p1',artifactId:'a1',reportIncluded});expect(placement.reportIncluded).toBe(reportIncluded);expect(placement.objectLink.metadata.reportIncluded).toBe(reportIncluded)});
test('canonical artifact identity is referenced rather than copied',()=>{const placement=createProjectPlacement({projectId:'p1',artifactId:'analysis-1',metadata:{title:'Capability'}});expect(placement.artifactId).toBe('analysis-1');expect(placement).not.toHaveProperty('result');expect(placement.objectLink.fromId).toBe('analysis-1')});
test('contract permits multiple references to one canonical artifact',()=>{const primary=createProjectPlacement({projectId:'p1',artifactId:'analysis-1'}),secondary=createProjectPlacement({projectId:'p1',artifactId:'analysis-1',isPrimary:false,location:{suite:'Project Management',suiteId:'project-management',phase:'Monitoring & Controlling',phaseId:'monitoring-controlling',workflowCluster:'Change & Quality',workflowClusterId:'change-quality'}});expect(primary.artifactId).toBe(secondary.artifactId);expect(primary.placementId).not.toBe(secondary.placementId);expect(secondary.objectLink.relationship).toBe('references')});
test('placement modification preserves canonical identity and created date',()=>{const original=createProjectPlacement({projectId:'p1',artifactId:'a1'}),changed=createProjectPlacement({...original,location:suggestProjectPlacement('regression'),updatedAt:'later'});expect(changed.artifactId).toBe(original.artifactId);expect(changed.placementId).toBe(original.placementId);expect(changed.createdAt).toBe(original.createdAt);expect(changed.updatedAt).toBe('later')});
test('primary placement upsert does not duplicate the canonical artifact',()=>{const original=createProjectPlacement({projectId:'p1',artifactId:'a1'}),changed=createProjectPlacement({...original,location:suggestProjectPlacement('regression'),updatedAt:'later'}),stored=upsertProjectPlacement([original],changed);expect(stored).toHaveLength(1);expect(stored[0]).toEqual(changed)});
test('legacy analysis derives safe placement without changing analysis',()=>{const legacy={id:'old',toolId:'anova',result:{value:42}},snapshot=JSON.stringify(legacy),placement=createProjectPlacement({projectId:'p1',artifactId:legacy.id,location:suggestProjectPlacement(legacy.toolId),metadata:{legacyDerived:true}});expect(placement.workflowCluster).toBe('Hypothesis & Comparison');expect(JSON.stringify(legacy)).toBe(snapshot)});
test.each(['control-chart','capability-analysis','anova','doe-rsm'])('%s placement move preserves result, canonical ID, and uniqueness',toolId=>{const analysis={id:`saved-${toolId}`,result:{immutable:true}},before=JSON.stringify(analysis),original=createProjectPlacement({projectId:'p1',artifactId:analysis.id,location:suggestProjectPlacement(toolId),reportIncluded:false}),moved=createProjectPlacement({...original,location:UNFILED_LOCATION,reportIncluded:true,updatedAt:'later'}),stored=upsertProjectPlacement([original],moved);expect(stored).toHaveLength(1);expect(stored[0].artifactId).toBe(analysis.id);expect(stored[0].reportIncluded).toBe(true);expect(JSON.stringify(analysis)).toBe(before)});
test('malformed placement location falls back to Unfiled / General',()=>{const malformed={...createProjectPlacement({projectId:'p1',artifactId:'a1'}),suiteId:'bad',phaseId:'bad',workflowClusterId:'bad'},normalized=normalizePlacement(malformed);expect(normalized.phase).toBe('Project');expect(normalized.workflowCluster).toBe('Unfiled / General')});
test('unknown tool and malformed location fall back to Unfiled',()=>{expect(suggestProjectPlacement('future-unknown')).toEqual(UNFILED_LOCATION);const valid=createProjectPlacement({projectId:'p1',artifactId:'a1'}),normalized=normalizePlacement({...valid,suiteId:'bad',phaseId:'bad',workflowClusterId:'bad'});expect(normalized.workflowCluster).toBe('Unfiled / General');expect(normalizePlacement({bad:true})).toBeNull()});
test('project context is required without damaging canonical payload',()=>{expect(()=>createProjectPlacement({artifactId:'a1'})).toThrow(/project/)});
test('existing report DMAIC sequencing is unchanged',()=>{const items=[{phase:'Control',id:5},{phase:'Define',id:1},{phase:'Improve',id:4},{phase:'Analyze',id:3},{phase:'Measure',id:2},{phase:'Other',id:6}];expect(sortReportItemsByPhase(items).map(item=>item.id)).toEqual([1,2,3,4,5,6])});
