import {NAVIGATION} from '../config/navigation';
import {navigationItems} from '../utils/navigationTools';
import {createObjectLink} from './sharedContracts';

export const PLACEMENT_SCHEMA_VERSION=1;
export const UNFILED_LOCATION=Object.freeze({suite:'Platform',suiteId:'platform',phase:'Project',phaseId:'project',workflowCluster:'Unfiled / General',workflowClusterId:'unfiled-general'});
const analysisItems=()=>navigationItems(NAVIGATION).filter(item=>item.type==='analysis');
const uuid=()=>window.crypto?.randomUUID?.()||'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,char=>{const value=Math.random()*16|0;return(char==='x'?value:((value&3)|8)).toString(16)});
export function placementDestinations(){const seen=new Set();return[UNFILED_LOCATION,...navigationItems(NAVIGATION).filter(item=>item.suiteId&&item.phase&&item.cluster).map(item=>({suite:item.suite,suiteId:item.suiteId,phase:item.phase,phaseId:item.phaseId,workflowCluster:item.cluster,workflowClusterId:item.clusterId})).filter(item=>{const key=`${item.suiteId}:${item.phaseId}:${item.workflowClusterId}`;if(seen.has(key))return false;seen.add(key);return true})]}
const aliases={hypothesis:'/hypothesis',doe:'/doe','doe-rsm':'/doe','capability-analysis':'/tool/capability',msa:'/tool/msa',regression:'/tool/regression',multiregression:'/tool/multiregression',logistic:'/tool/logistic','distribution-analysis':'/tool/distribution-analysis'};
const canonicalContext={
 'control-chart':{phaseId:'control',clusterId:'process-control'},
 'attribute-chart':{phaseId:'control',clusterId:'monitoring-audit'},
 'run-chart':{phaseId:'control',clusterId:'monitoring-audit'},
};
export function suggestProjectPlacement(toolId){const route=aliases[toolId]||`/tool/${String(toolId||'').replace(/^tool-/,'')}`,matches=analysisItems().filter(item=>item.path===route),preferred=canonicalContext[toolId],match=matches.find(item=>(!preferred?.phaseId||item.phaseId===preferred.phaseId)&&(!preferred?.clusterId||item.clusterId===preferred.clusterId))||matches[0];return match?{suite:match.suite,suiteId:match.suiteId,phase:match.phase,phaseId:match.phaseId,workflowCluster:match.cluster,workflowClusterId:match.clusterId}:UNFILED_LOCATION}
export function createProjectPlacement(input={}){if(!input.projectId||!input.artifactId)throw new Error('Project placement requires a project and canonical artifact.');const location=input.location||UNFILED_LOCATION,createdAt=input.createdAt||new Date().toISOString(),placementId=input.placementId||uuid(),link=createObjectLink({id:placementId,organizationId:input.organizationId||'',projectId:input.projectId,fromType:input.artifactType||'analysis',fromId:input.artifactId,toType:'project_location',toId:`${location.suiteId}:${location.phaseId}:${location.workflowClusterId}`,relationship:input.isPrimary===false?'references':'primary_placement',createdBy:input.createdBy||'',createdAt,metadata:{suite:location.suite,suiteId:location.suiteId,phase:location.phase,phaseId:location.phaseId,workflowCluster:location.workflowCluster,workflowClusterId:location.workflowClusterId,reportIncluded:Boolean(input.reportIncluded),reportItemId:input.reportItemId||'',datasetIds:input.datasetIds||[],datasetVersionIds:input.datasetVersionIds||[],method:input.method||'',sourceWorkflow:input.sourceWorkflow||'',...(input.metadata||{})}});return{schemaVersion:PLACEMENT_SCHEMA_VERSION,placementId,organizationId:link.organizationId,projectId:link.projectId,artifactType:link.fromType,artifactId:link.fromId,suite:location.suite,suiteId:location.suiteId,phase:location.phase,phaseId:location.phaseId,workflowCluster:location.workflowCluster,workflowClusterId:location.workflowClusterId,isPrimary:input.isPrimary!==false,createdBy:link.createdBy,createdAt,updatedAt:input.updatedAt||createdAt,reportIncluded:Boolean(input.reportIncluded),reportItemId:input.reportItemId||'',metadata:link.metadata,objectLink:link}}
export function normalizePlacement(value){if(!value||typeof value!=='object'||!value.projectId||!value.artifactId)return null;const valid=placementDestinations().find(item=>item.suiteId===value.suiteId&&item.phaseId===value.phaseId&&item.workflowClusterId===value.workflowClusterId)||UNFILED_LOCATION;return createProjectPlacement({...value,location:valid,placementId:value.placementId,createdAt:value.createdAt,updatedAt:value.updatedAt||value.createdAt})}
export function upsertProjectPlacement(placements,next){return[...(placements||[]).filter(item=>item.placementId!==next.placementId&&!(item.artifactId===next.artifactId&&item.projectId===next.projectId&&item.isPrimary&&next.isPrimary)),next]}
export const connectAnalysisToProject=(analysis,{projectId,organizationId})=>({...analysis,projectId,organizationId:organizationId||analysis.organizationId||'',updatedAt:new Date().toISOString()});
export const placementLabel=placement=>`${placement?.phase||UNFILED_LOCATION.phase} → ${placement?.workflowCluster||UNFILED_LOCATION.workflowCluster}`;
