import{correctiveActionDetail,isCorrectiveActionOverdue}from'./correctiveAction';
import{charterCompletionState,charterQualityState}from'../config/charterTemplate';
export const TOLLGATE_TYPE='oe-dmaic-tollgate';
export const TOLLGATE_PHASES=['Define','Measure','Analyze','Improve','Control'];
export const TOLLGATE_STATUSES={SUBMITTED:'Submitted',IN_REVIEW:'In Review',RETURNED:'Returned for Revision',CONDITIONAL:'Conditionally Approved',APPROVED:'Approved',REJECTED:'Rejected'};
const text=value=>String(value||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const identity=item=>String(item?.templateId||item?.toolId||item?.id||'').replace(/^document-/,'');
const hasIdentity=(items,ids)=>items.some(item=>ids.includes(identity(item)));
const action=(actionLabel,destination)=>({actionLabel,destination});
const requirement=(code,label,done,severity='blocker',actions=[])=>({code,label,done,severity,actions});
const documentAction=(projectId,templateId,label)=>action(label||`Open ${templateId}`,`/projects/${projectId}/documents/${templateId}`);
const uniqueById=items=>[...new Map(items.filter(Boolean).map(item=>[item.id||item.templateId||item.title,item])).values()];
export function canonicalTollgateState(project,resources={}){const embeddedDocuments=Object.values(project?.documents||{}),documents=uniqueById([...(resources.documents||[]),...embeddedDocuments]),evidence=uniqueById([...(resources.evidence||[]),...(project?.evidenceLibrary||[])]),artifacts=uniqueById([...(resources.artifacts||[]),...(project?.artifacts||[])]);return{projectId:project?.id||'',charter:project?.charter||null,owner:text(project?.owner||project?.sharedFields?.owner),sponsor:text(project?.champion||project?.sharedFields?.sponsor),documents,evidence,artifacts,analyses:resources.analyses||[],datasets:resources.datasets||[],correctiveActions:resources.correctiveActions||[]}}
export const canonicalDocument=(state,templateId)=>state.documents.find(item=>item.templateId===templateId||item.id===`document-${templateId}`||item.id===templateId);
const completedDocument=(state,templateId)=>{const document=canonicalDocument(state,templateId);return Boolean(document&&(Number(document.completion)>0||Object.values(document.values||{}).some(value=>Array.isArray(value)?value.length:Boolean(text(value)))))};
export const tollgateDetail=row=>({...row,...(row?.content||{}),id:row?.id||'',projectId:row?.project_id||row?.projectId||'',organizationId:row?.organization_id||row?.organizationId||'',createdBy:row?.created_by||row?.createdBy||'',phase:row?.lifecycle_phase||row?.content?.phase||row?.phase||'Define',status:row?.status||TOLLGATE_STATUSES.SUBMITTED,updatedAt:row?.updated_at||row?.updatedAt||'',createdAt:row?.created_at||row?.createdAt||''});
export const isTollgate=row=>row?.content?.item_type===TOLLGATE_TYPE;

export function evaluateTollgateReadiness(project,phase,resources={}){
 const state=canonicalTollgateState(project,resources),{documents,analyses,evidence,artifacts,datasets}=state,actions=state.correctiveActions.map(correctiveActionDetail),all=[...documents,...evidence,...artifacts],phaseItems=all.filter(item=>!item.phase||String(item.phase).toLowerCase()===phase.toLowerCase()),charter=state.charter,charterCompletion=charterCompletionState(charter),charterQuality=charterQualityState(charter),charterReady=charterCompletion.complete&&charterQuality.reviewReady,projectBase=`/projects/${state.projectId}`;
 const criticalOpen=actions.filter(action=>action.severity==='Critical'&&action.status!=='Verified / Closed'),overdue=actions.filter(action=>isCorrectiveActionOverdue(action)),pendingEffectiveness=actions.filter(action=>action.status==='Pending Effectiveness'||(action.actionStatus==='Complete'&&action.effectivenessResult!=='Effective'));
 const rules={
  Define:[requirement('charter',!charterCompletion.complete?'Complete required Charter sections':!charterQuality.reviewReady?`Improve Charter quality before submission (${charterQuality.score}/${charterQuality.threshold})`:'Project Charter ready',charterReady,'blocker',[action('Open Charter',`${projectBase}/charter`)]),requirement('owner','Assign project owner',Boolean(state.owner),'blocker',[action('Project Settings',`${projectBase}?tab=project-settings`)]),requirement('sponsor','Assign project sponsor',Boolean(state.sponsor),'blocker',[action('Project Settings',`${projectBase}?tab=project-settings`)]),requirement('sipoc','Complete SIPOC',completedDocument(state,'sipoc'),'warning',[documentAction(state.projectId,'sipoc','Open SIPOC')]),requirement('voice','Record VOC or CTQ evidence',completedDocument(state,'voc')||completedDocument(state,'ctq-tree'),'warning',[documentAction(state.projectId,'voc','Open VOC'),documentAction(state.projectId,'ctq-tree','Open CTQ Tree')])],
  Measure:[requirement('measurement-plan','Complete a measurement or data-collection plan',completedDocument(state,'measurement-plan')||completedDocument(state,'data-collection-plan'),'blocker',[documentAction(state.projectId,'data-collection-plan','Open Data Collection Plan'),documentAction(state.projectId,'measurement-plan','Open Measurement Plan')]),requirement('baseline','Record a baseline dataset or baseline metrics',datasets.length>0||completedDocument(state,'baseline-metrics'),'blocker',[documentAction(state.projectId,'baseline-metrics','Open Baseline Metrics'),action('Open Datasets',`${projectBase}?tab=datasets`)]),requirement('process-baseline','Document the process baseline',completedDocument(state,'process-map')||completedDocument(state,'process-capability-study')||analyses.some(item=>['capability','histogram','descriptive'].includes(identity(item))),'blocker',[documentAction(state.projectId,'process-map','Open Process Map'),action('Open Analysis Catalog',`/analysis?project=${encodeURIComponent(state.projectId)}`)]),requirement('msa','Record MSA evidence or justification',completedDocument(state,'msa-workspace')||analyses.some(item=>['msa','gage-rr','measurement-system-analysis'].includes(identity(item))),'warning',[documentAction(state.projectId,'msa-workspace','Open MSA Workspace')])],
  Analyze:[requirement('analysis','Record Analyze-phase evidence',analyses.some(item=>String(item.phase||'Analyze').toLowerCase()==='analyze'),'blocker',[action('Open Analysis Catalog',`/analysis?project=${encodeURIComponent(state.projectId)}`)]),requirement('root-cause','Complete root-cause investigation',hasIdentity(documents,['fishbone-workspace','five-whys','root-cause-verification']),'blocker',[documentAction(state.projectId,'root-cause-verification','Open Root Cause Verification'),documentAction(state.projectId,'fishbone-workspace','Open Fishbone')]),requirement('finding','Record evidence supporting the conclusion',evidence.length>0,'warning',[action('Open Evidence Library',`${projectBase}?tab=evidence-library`)])],
  Improve:[requirement('solution','Document the selected solution',hasIdentity(documents,['solution-selection-matrix','impact-effort-matrix']),'blocker',[documentAction(state.projectId,'solution-selection-matrix','Open Solution Selection')]),requirement('implementation','Record implementation or pilot evidence',hasIdentity(documents,['implementation-plan','pilot-plan']),'blocker',[documentAction(state.projectId,'implementation-plan','Open Implementation Plan'),documentAction(state.projectId,'pilot-plan','Open Pilot Plan')]),requirement('critical-actions','Resolve blocked critical corrective actions',criticalOpen.every(item=>item.actionStatus!=='Blocked'),'blocker',[action('Open Corrective Actions',`${projectBase}?tab=corrective-actions`)]),requirement('risk-review','Record FMEA or risk-review evidence',hasIdentity(all,['fmea','risk-review']),'warning',[action('Open Project Binder',`${projectBase}?tab=project-binder`)]),requirement('overdue-actions','Resolve overdue corrective actions',overdue.length===0,'warning',[action('Open Corrective Actions',`${projectBase}?tab=corrective-actions`)])],
  Control:[requirement('control-plan','Complete a control or reaction plan',completedDocument(state,'control-plan')||completedDocument(state,'reaction-plan'),'blocker',[documentAction(state.projectId,'control-plan','Open Control Plan'),documentAction(state.projectId,'reaction-plan','Open Reaction Plan')]),requirement('sustainment','Record sustainment and operational handoff',completedDocument(state,'project-closure')||completedDocument(state,'monitoring-plan'),'blocker',[documentAction(state.projectId,'project-closure','Open Project Closure'),documentAction(state.projectId,'monitoring-plan','Open Monitoring Plan')]),requirement('effectiveness','Resolve corrective-action effectiveness',pendingEffectiveness.length===0,'blocker',[action('Open Corrective Actions',`${projectBase}?tab=corrective-actions`)]),requirement('critical-actions','Close critical corrective actions',criticalOpen.length===0,'blocker',[action('Open Corrective Actions',`${projectBase}?tab=corrective-actions`)]),requirement('control-evidence','Record Control-phase evidence',phaseItems.length>0,'warning',[action('Open Project Binder',`${projectBase}?tab=project-binder`)])],
 };
 const requirements=rules[phase]||[],descriptor=({code,label,severity,actions})=>({code,label,severity,actions,destination:actions[0]?.destination||'',actionLabel:actions[0]?.actionLabel||''}),blockers=requirements.filter(item=>!item.done&&item.severity==='blocker').map(descriptor),warnings=requirements.filter(item=>!item.done&&item.severity==='warning').map(descriptor);
 return{phase,readyToSubmit:blockers.length===0,blockers,warnings,completedRequirements:requirements.filter(item=>item.done).map(descriptor),missingRequirements:requirements.filter(item=>!item.done).map(descriptor),charterReadiness:{completion:charterCompletion.completion,qualityScore:charterQuality.score,qualityThreshold:charterQuality.threshold},evidenceSnapshot:{projectId:state.projectId,charterUpdatedAt:charter?.updatedAt||'',documentIds:documents.map(item=>item.id),analysisIds:analyses.map(item=>item.id),evidenceIds:evidence.map(item=>item.id),artifactIds:artifacts.map(item=>item.id),datasetIds:datasets.map(item=>item.id),correctiveActionIds:actions.map(item=>item.id)}};
}

export const canReviewTollgate=({user,organizationRole,review})=>Boolean(user?.id&&review&&review.submittedBy!==user.id&&(['owner','admin'].includes(organizationRole)||review.assignedReviewerId===user.id||text(review.assignedReviewerEmail).toLowerCase()===text(user.email).toLowerCase()));
export const appendTollgateEvent=(review,event)=>({...review,events:[...(review.events||[]),{id:event.id||crypto.randomUUID(),at:event.at||new Date().toISOString(),...event}]});
export const nextPhase=phase=>TOLLGATE_PHASES[TOLLGATE_PHASES.indexOf(phase)+1]||phase;
export const phaseAfterDecision=(phase,status)=>status===TOLLGATE_STATUSES.APPROVED||status===TOLLGATE_STATUSES.CONDITIONAL?nextPhase(phase):phase;
export function createTollgateSubmission({project,phase,readiness,submitter,reviewer,priorReviews=[],note='',at=new Date().toISOString(),eventId}){if(!readiness?.readyToSubmit)throw new Error('tollgate-submission-blocked');if(!reviewer?.email&&!reviewer?.userId)throw new Error('tollgate-reviewer-required');const attempt=Math.max(0,...priorReviews.filter(item=>tollgateDetail(item).phase===phase).map(item=>tollgateDetail(item).attempt||1))+1;return{project_id:project.id,organization_id:project.organizationId,created_by:submitter.id,title:`${phase} Tollgate — Attempt ${attempt}`,status:TOLLGATE_STATUSES.SUBMITTED,methodology:'lean-six-sigma',lifecycle_phase:phase,content:{phase,attempt,submittedBy:submitter.id,submittedByName:submitter.name||submitter.email,submittedAt:at,assignedReviewerId:reviewer.userId||'',assignedReviewerName:reviewer.name||reviewer.email,assignedReviewerEmail:reviewer.email||'',readiness,evidenceSnapshot:readiness.evidenceSnapshot,reviewComments:'',decision:'',decisionBy:'',decisionByName:'',decisionAt:'',returnReason:'',events:[{id:eventId||crypto.randomUUID(),type:attempt>1?'resubmitted':'submitted',at,actorId:submitter.id,actorName:submitter.name||submitter.email,comments:text(note)}]}}}
export function applyTollgateDecision(review,{status,actor,organizationRole='',comments='',at=new Date().toISOString(),eventId}){const gate=tollgateDetail(review);if(!canReviewTollgate({user:actor,organizationRole,review:gate}))throw new Error('tollgate-review-not-authorized');if(![TOLLGATE_STATUSES.SUBMITTED,TOLLGATE_STATUSES.IN_REVIEW].includes(gate.status))throw new Error('tollgate-review-not-active');const note=text(comments);if([TOLLGATE_STATUSES.RETURNED,TOLLGATE_STATUSES.CONDITIONAL,TOLLGATE_STATUSES.REJECTED].includes(status)&&!note)throw new Error('tollgate-decision-comments-required');const eventType=status===TOLLGATE_STATUSES.IN_REVIEW?'review-started':status===TOLLGATE_STATUSES.RETURNED?'returned-for-revision':'decision',next=appendTollgateEvent(gate,{id:eventId,type:eventType,at,actorId:actor.id,actorName:actor.name||actor.email,status,comments:note});return{status,content:{...review.content,...next,reviewComments:note||gate.reviewComments,decision:status===TOLLGATE_STATUSES.IN_REVIEW?'':status,decisionBy:status===TOLLGATE_STATUSES.IN_REVIEW?'':actor.id,decisionByName:status===TOLLGATE_STATUSES.IN_REVIEW?'':actor.name||actor.email,decisionAt:status===TOLLGATE_STATUSES.IN_REVIEW?'':at,returnReason:status===TOLLGATE_STATUSES.RETURNED?note:gate.returnReason}}}
export function getTollgateContext(project,reviews,now=new Date()){
 const rows=reviews.map(tollgateDetail),latest=TOLLGATE_PHASES.map(phase=>rows.filter(item=>item.phase===phase).sort((a,b)=>(b.attempt||1)-(a.attempt||1))[0]).filter(Boolean),agingDays=item=>Math.max(0,Math.floor((now-new Date(item.submittedAt||item.createdAt))/86400000));return{projectId:project?.id,currentPhase:project?.currentPhase||'Define',gates:TOLLGATE_PHASES.map(phase=>({phase,status:latest.find(item=>item.phase===phase)?.status||'Not Submitted'})),blockedGates:latest.filter(item=>(item.readiness?.blockers||[]).length),pendingReviews:latest.filter(item=>[TOLLGATE_STATUSES.SUBMITTED,TOLLGATE_STATUSES.IN_REVIEW].includes(item.status)).map(item=>({...item,agingDays:agingDays(item)})),returnedForRevision:latest.filter(item=>item.status===TOLLGATE_STATUSES.RETURNED),conditions:latest.filter(item=>item.status===TOLLGATE_STATUSES.CONDITIONAL).map(item=>({phase:item.phase,conditions:item.reviewComments||item.decisionComments||''})),approvedPhases:latest.filter(item=>item.status===TOLLGATE_STATUSES.APPROVED).map(item=>item.phase)};
}
export const tollgateReportItem=(review,project)=>{const gate=tollgateDetail(review);return{assetType:'tollgate',reportKey:`${project.id}:tollgate:${gate.id}`,projectId:project.id,organizationId:gate.organizationId,title:`${gate.phase} Tollgate — ${gate.status}`,toolId:'dmaic-tollgate',phase:gate.phase,timestamp:gate.decisionAt||gate.updatedAt||gate.submittedAt,statsSummary:{Phase:gate.phase,Decision:gate.decision||gate.status,Reviewer:gate.decisionByName||gate.assignedReviewerName||'Unassigned',Date:gate.decisionAt||'Pending',Attempt:gate.attempt||1},interpretation:text(gate.decisionComments||gate.reviewComments||gate.returnReason||''),structuredOutput:{phase:gate.phase,status:gate.status,conditions:gate.status===TOLLGATE_STATUSES.CONDITIONAL?text(gate.decisionComments):''}}};
