import {clearAnalysisHandoff,consumeAnalysisHandoff,createAnalysisHandoff,DOE_REGRESSION_DESTINATION,DOE_REGRESSION_PATH,getAnalysisHandoff,normalizeDoeRegressionHandoff} from './analysisHandoff';

const base={sourceTool:'doe',destination:'multiregression',sourceAnalysisId:'doe-123',sourceLabel:'DOE — Full Factorial Analysis',projectId:'project-1',datasetId:'dataset-1',datasetVersion:3,datasetVersionId:'version-3',response:'Yield',factorDefinitions:[{name:'Temperature',type:'continuous',low:100,high:200,coding:'coded'},{name:'Pressure',type:'continuous',low:10,high:20,coding:'coded'}],coding:'coded',regressionRows:[{Temperature:-1,Pressure:-1,Yield:42},{Temperature:1,Pressure:-1,Yield:48},{Temperature:-1,Pressure:1,Yield:45},{Temperature:1,Pressure:1,Yield:55}],naturalRows:[{Temperature:100,Pressure:10,Yield:42}],interactions:[['Temperature','Pressure']],polynomialTerms:[],modelTerms:['Temperature','Pressure','Temperature:Pressure']};

beforeEach(clearAnalysisHandoff);
test('DOE follow-up targets the registered multiple-regression route',()=>{expect(DOE_REGRESSION_DESTINATION).toBe('multiregression');expect(DOE_REGRESSION_PATH).toBe('/tool/multiregression')});
test('full-factorial handoff preserves predictors, interaction, dataset and provenance',()=>{const {context,warning}=normalizeDoeRegressionHandoff(base);expect(warning).toBeNull();expect(context).toEqual(expect.objectContaining({response:'Yield',factorNames:['Temperature','Pressure'],interactions:[['Temperature','Pressure']],datasetVersionId:'version-3',sourceAnalysisId:'doe-123'}))});
test('fractional factorial transfers only explicitly supported interactions',()=>{const result=normalizeDoeRegressionHandoff({...base,sourceLabel:'DOE — Fractional Factorial Analysis',interactions:[['Temperature','Pressure'],['Unknown','Pressure']]});expect(result.context.interactions).toEqual([['Temperature','Pressure']]);expect(result.warning).toMatch(/some rows or model terms/)});
test('RSM preserves main, interaction and quadratic term contracts',()=>{const result=normalizeDoeRegressionHandoff({...base,sourceLabel:'DOE — Central Composite RSM',polynomialTerms:[{name:'Temperature',degree:2},{name:'Pressure',degree:2}],modelTerms:['Temperature','Pressure','Temperature:Pressure','Temperature^2','Pressure^2']});expect(result.context.polynomialTerms).toEqual([{name:'Temperature',degree:2},{name:'Pressure',degree:2}]);expect(result.context.coding).toBe('coded');expect(result.context.naturalRows).toHaveLength(1)});
test('missing handoff and direct regression initialization are optional',()=>{expect(normalizeDoeRegressionHandoff(null)).toEqual({context:null,warning:null});expect(getAnalysisHandoff()).toBeNull()});
test('malformed handoff returns an inline-ready fallback instead of throwing',()=>{expect(()=>normalizeDoeRegressionHandoff({sourceTool:'doe',destination:'multiregression',response:null,factorDefinitions:'bad'})).not.toThrow();expect(normalizeDoeRegressionHandoff({sourceTool:'doe',destination:'multiregression'}).warning).toMatch(/incomplete/)});
test('refresh-equivalent reads retain consumed handoff context',()=>{createAnalysisHandoff(base);expect(consumeAnalysisHandoff('multiregression').response).toBe('Yield');expect(getAnalysisHandoff()).toEqual(expect.objectContaining({status:'consumed',response:'Yield'}));expect(normalizeDoeRegressionHandoff(getAnalysisHandoff()).context.response).toBe('Yield')});
test('unsupported terms are dropped with a safe warning',()=>{const result=normalizeDoeRegressionHandoff({...base,interactions:[['Temperature'],['Temperature','Missing']],polynomialTerms:[{name:'Missing',degree:3}]});expect(result.context.interactions).toEqual([]);expect(result.context.polynomialTerms).toEqual([]);expect(result.warning).toMatch(/could not be transferred/)});
test('handoff persistence preserves source analysis and version provenance',()=>{createAnalysisHandoff(base);const stored=getAnalysisHandoff(),normalized=normalizeDoeRegressionHandoff(stored).context;expect(normalized).toEqual(expect.objectContaining({sourceAnalysisId:'doe-123',projectId:'project-1',datasetId:'dataset-1',datasetVersion:3,datasetVersionId:'version-3'}));expect(normalized.createdAt).toBeTruthy()});
