import{isSupabaseConfigured,supabase}from'../lib/supabase';import{assertLeanScope}from'../foundation/leanRecords';
const requireContext=context=>{if(!isSupabaseConfigured||!supabase)throw new Error('Cloud persistence is not configured.');assertLeanScope(null,context)};
const check=({data,error})=>{if(error)throw new Error(error.message||'Lean persistence failed.');return data};
const toApp=row=>Object.fromEntries(Object.entries(row||{}).map(([key,value])=>[key.replace(/_([a-z])/g,(_,letter)=>letter.toUpperCase()),value]));
const toDb=record=>({id:record.id,organization_id:record.organizationId,project_id:record.projectId,record_type:record.type,title:record.title,status:record.status,revision:record.revision,prior_revision_id:record.priorRevisionId,is_current:record.isCurrent,owner_id:record.ownerId,created_by:record.createdBy,updated_by:record.updatedBy,created_at:record.createdAt,updated_at:record.updatedAt,effective_at:record.effectiveAt,change_summary:record.changeSummary,payload:record.payload,metadata:record.metadata});
export async function loadLeanRecords(context,type){requireContext(context);let query=supabase.from('lean_records').select('*').eq('organization_id',context.organizationId).eq('project_id',context.projectId).eq('is_current',true);if(type)query=query.eq('record_type',type);return check(await query.order('updated_at',{ascending:false})).map(row=>({...toApp(row),type:row.record_type}))}
export async function createPersistedLeanRecord(record,context){requireContext(context);assertLeanScope(record,context);if(record.createdBy!==context.userId)throw new Error('Lean record creator must match authenticated user.');return{...toApp(check(await supabase.from('lean_records').insert(toDb(record)).select('*').single())),type:record.type}}
export async function updatePersistedLeanRecord(prior,current,revision,context){requireContext(context);assertLeanScope(prior,context);assertLeanScope(current,context);if(prior.id!==current.id||current.revision!==prior.revision+1||!revision)throw new Error('Lean revision chain is invalid.');check(await supabase.from('lean_record_revisions').insert({id:revision.id,organization_id:revision.organizationId,project_id:revision.projectId,record_id:revision.recordId,revision:revision.revision,prior_revision:revision.priorRevision,snapshot:revision.snapshot,changes:revision.changes,change_summary:revision.changeSummary,created_by:revision.createdBy,created_at:revision.createdAt}));return{...toApp(check(await supabase.from('lean_records').update(toDb(current)).eq('id',prior.id).eq('organization_id',context.organizationId).eq('project_id',context.projectId).eq('revision',prior.revision).select('*').single())),type:current.type}}
export async function loadLeanRevisionHistory(record,context){requireContext(context);assertLeanScope(record,context);return check(await supabase.from('lean_record_revisions').select('*').eq('organization_id',context.organizationId).eq('project_id',context.projectId).eq('record_id',record.id).order('revision',{ascending:false})).map(toApp)}
export async function archivePersistedLeanRecord(record,context){requireContext(context);assertLeanScope(record,context);return{...toApp(check(await supabase.from('lean_records').update({is_current:false,status:'Archived',updated_by:context.userId}).eq('id',record.id).eq('organization_id',context.organizationId).eq('project_id',context.projectId).select('*').single())),type:record.type}}
export async function persistLeanLink(link,context){requireContext(context);assertLeanScope(link,context);return check(await supabase.from('object_links').upsert({organization_id:context.organizationId,project_id:context.projectId,created_by:context.userId,from_type:link.fromType,from_id:link.fromId,to_type:link.toType,to_id:link.toId,relationship:link.relationship,metadata:link.metadata},{onConflict:'organization_id,project_id,from_type,from_id,to_type,to_id,relationship'}).select('*').single())}
export async function loadLeanConnectivity(context){requireContext(context);const[links,findings]=await Promise.all([supabase.from('object_links').select('*').eq('organization_id',context.organizationId).eq('project_id',context.projectId),supabase.from('findings').select('*').eq('organization_id',context.organizationId).eq('project_id',context.projectId).eq('suite','operational-excellence')]);return{links:check(links).map(toApp),findings:check(findings).map(toApp)}}
export async function updatePersistedLeanLink(link,relationship,context){requireContext(context);assertLeanScope(link,context);return toApp(check(await supabase.from('object_links').update({relationship}).eq('id',link.id).eq('organization_id',context.organizationId).eq('project_id',context.projectId).select('*').single()))}
export async function removePersistedLeanLink(link,context){requireContext(context);assertLeanScope(link,context);check(await supabase.from('object_links').delete().eq('id',link.id).eq('organization_id',context.organizationId).eq('project_id',context.projectId));return link.id}
export async function createPersistedLeanFinding(input,context){requireContext(context);if(input.organizationId!==context.organizationId||input.projectId!==context.projectId)throw new Error('Finding scope mismatch.');return toApp(check(await supabase.from('findings').insert({organization_id:context.organizationId,project_id:context.projectId,created_by:context.userId,finding_type:input.findingType,title:input.title,statement:input.statement,severity:input.severity,status:'active',source_type:input.sourceArtifactType,source_id:input.sourceArtifactId,suite:'operational-excellence',methodology:'lean-enterprise',lifecycle_phase:'Improve',version:1,metadata:{sourceRevision:input.sourceRevision,sourceElementId:input.sourceElementId,process:input.process,metric:input.metric,observedValue:input.observedValue,threshold:input.threshold,rule:input.rule,evidence:input.evidence}}).select('*').single()))}
