import{isSupabaseConfigured,supabase}from'../lib/supabase';
const TABLES={requirement:'product_requirements',ctq:'product_ctqs',verification:'product_verifications'};
const requireContext=context=>{if(!isSupabaseConfigured||!supabase)throw new Error('Cloud persistence is not configured.');if(!context?.userId)throw new Error('Authenticated user is required.');if(!context.organizationId||!context.projectId)throw new Error('Select an organization-scoped project before editing product-development records.')};
const check=({data,error})=>{if(error)throw new Error(error.message||'Product-development persistence failed.');return data};
const camelToSnake=value=>value.replace(/[A-Z]/g,letter=>`_${letter.toLowerCase()}`);
const toDb=record=>Object.fromEntries(Object.entries(record).filter(([key])=>!['schemaVersion','ctqIds','evidenceLinks'].includes(key)).map(([key,value])=>[camelToSnake(key),value]));
const toApp=row=>Object.fromEntries(Object.entries(row||{}).map(([key,value])=>[key.replace(/_([a-z])/g,(_,letter)=>letter.toUpperCase()),value]));
export async function loadProductDevelopmentRecords(context){requireContext(context);const query=table=>supabase.from(table).select('*').eq('organization_id',context.organizationId).eq('project_id',context.projectId).is('archived_at',null);const[requirements,ctqs,verifications,revisions,links,findings]=await Promise.all([query(TABLES.requirement),query(TABLES.ctq),query(TABLES.verification),supabase.from('product_record_revisions').select('*').eq('organization_id',context.organizationId).eq('project_id',context.projectId),supabase.from('object_links').select('*').eq('organization_id',context.organizationId).eq('project_id',context.projectId),supabase.from('findings').select('*').eq('organization_id',context.organizationId).eq('project_id',context.projectId).eq('source_type','product_verification')]);return{requirements:check(requirements).map(toApp),ctqs:check(ctqs).map(toApp),verifications:check(verifications).map(row=>({...toApp(row),evidenceLinks:check(links).filter(link=>link.from_type==='verification'&&link.from_id===row.id&&link.relationship==='evidence').map(link=>({id:link.id,type:link.to_type,objectId:link.to_id,title:link.metadata?.title||link.to_id,date:link.created_at,owner:link.metadata?.owner||''}))})),revisions:check(revisions).map(toApp),links:check(links).map(toApp),findings:check(findings).map(row=>({...toApp(row),verificationId:row.metadata?.verificationId||row.source_id}))}}
export async function createPersistedProductRecord(type,record,context){requireContext(context);if(record.organizationId!==context.organizationId||record.projectId!==context.projectId||record.createdBy!==context.userId)throw new Error('Record scope does not match the authenticated project context.');return toApp(check(await supabase.from(TABLES[type]).insert(toDb(record)).select('*').single()))}
export async function updatePersistedProductRecord(type,prior,next,revision,context){requireContext(context);if(prior.id!==next.id||next.organizationId!==context.organizationId||next.projectId!==context.projectId)throw new Error('Record update scope mismatch.');if(revision)check(await supabase.from('product_record_revisions').insert(toDb(revision)));return toApp(check(await supabase.from(TABLES[type]).update(toDb(next)).eq('id',prior.id).eq('organization_id',context.organizationId).eq('project_id',context.projectId).select('*').single()))}
export async function archivePersistedProductRecord(type,record,context){requireContext(context);return toApp(check(await supabase.from(TABLES[type]).update({archived_at:new Date().toISOString()}).eq('id',record.id).eq('organization_id',context.organizationId).eq('project_id',context.projectId).select('*').single()))}
export async function attachPersistedEvidence(verification,evidence,context){requireContext(context);if(evidence.organizationId&&evidence.organizationId!==context.organizationId)throw new Error('Evidence organization scope mismatch.');if(evidence.projectId&&evidence.projectId!==context.projectId)throw new Error('Evidence project scope mismatch.');return check(await supabase.from('object_links').upsert({organization_id:context.organizationId,project_id:context.projectId,created_by:context.userId,from_type:'verification',from_id:verification.id,to_type:evidence.type,to_id:evidence.objectId,relationship:'evidence',metadata:{title:evidence.title||evidence.objectId,owner:evidence.owner||context.userId}},{onConflict:'organization_id,project_id,from_type,from_id,to_type,to_id,relationship'}).select('*').single())}
export async function createPersistedProductFinding(finding,context){requireContext(context);return toApp(check(await supabase.from('findings').insert({organization_id:context.organizationId,project_id:context.projectId,created_by:context.userId,analysis_id:finding.analysisId||null,finding_type:finding.findingType||finding.type,statement:finding.statement,severity:finding.severity||'warning',status:'active',source_type:'product_verification',source_id:finding.verificationId,suite:'operational-excellence',methodology:'product-development',lifecycle_phase:'verification',metadata:finding.evidence||{}}).select('*').single()))}
export function savedEvidencePath(evidence){if(evidence.type==='analysis')return`/projects/${evidence.projectId||''}?openResult=${encodeURIComponent(evidence.objectId)}`;if(evidence.type==='report')return'/report';if(evidence.type==='document')return`/documents/${encodeURIComponent(evidence.objectId)}`;return evidence.url||null}
