const{admin,stripe,json,epoch,required}=require('../_lib/server');
const{eventDisposition}=require('../_lib/idempotency');
exports.config={api:{bodyParser:false}};
const rawBody=req=>new Promise((resolve,reject)=>{const chunks=[];req.on('data',chunk=>chunks.push(Buffer.from(chunk)));req.on('end',()=>resolve(Buffer.concat(chunks)));req.on('error',reject)});
const accessState=subscription=>{
 if(subscription.status==='trialing')return'trial';
 if(['active','past_due'].includes(subscription.status))return'active';
 if(subscription.status==='canceled'&&subscription.current_period_end*1000>Date.now())return'active';
 return'expired';
};
async function findCatalogPrice(db,stripePriceId){return db.from('subscription_prices').select('id,plan_id,is_founding,grandfather_behavior').or(`stripe_price_id.eq.${stripePriceId},provider_price_id.eq.${stripePriceId}`).maybeSingle()}
async function reconcileSubscription(db,client,subscription,eventId,checkoutMetadata={}){
 const firstItem=subscription.items?.data?.[0],stripePriceId=firstItem?.price?.id;const{data:catalogPrice}=stripePriceId?await findCatalogPrice(db,stripePriceId):{data:null};
 const metadata={...checkoutMetadata,...subscription.metadata};const organizationId=metadata.organization_id;if(!organizationId)throw new Error('stripe-subscription-missing-organization');
 const row={organization_id:organizationId,plan_id:metadata.plan_id||catalogPrice?.plan_id||null,price_id:metadata.price_id||catalogPrice?.id||null,status:subscription.status,provider:'stripe',provider_customer_id:String(subscription.customer),provider_subscription_id:subscription.id,stripe_customer_id:String(subscription.customer),stripe_subscription_id:subscription.id,seat_quantity:firstItem?.quantity||1,current_period_start:epoch(subscription.current_period_start),current_period_end:epoch(subscription.current_period_end),trial_start:epoch(subscription.trial_start),trial_end:epoch(subscription.trial_end),trial_ends_at:epoch(subscription.trial_end),cancel_at_period_end:Boolean(subscription.cancel_at_period_end),cancel_at:epoch(subscription.cancel_at),ended_at:epoch(subscription.ended_at),grandfathered_price_id:catalogPrice?.is_founding&&catalogPrice?.grandfather_behavior==='while_continuously_subscribed'?catalogPrice.id:null,metadata:{...metadata,stripe_status:subscription.status,last_event_id:eventId}};
 const{data:stored,error}=await db.from('subscriptions').upsert(row,{onConflict:'stripe_subscription_id'}).select().single();if(error)throw error;
 for(const item of subscription.items?.data||[]){const{data:itemPrice}=await findCatalogPrice(db,item.price.id);const suiteId=item.metadata?.suite_key||metadata.suite_key||null;const{data:storedItem,error:itemError}=await db.from('subscription_items').upsert({subscription_id:stored.id,price_id:itemPrice?.id||null,stripe_subscription_item_id:item.id,suite_id:suiteId,quantity:item.quantity||1,status:'active',metadata:item.metadata||{}},{onConflict:'subscription_id,stripe_subscription_item_id'}).select().single();if(itemError)throw itemError;
  if(suiteId){const{data:previous}=await db.from('suite_entitlements').select('id,status').eq('organization_id',organizationId).eq('suite_id',suiteId).maybeSingle();const nextState=accessState(subscription),endsAt=subscription.status==='past_due'?null:['active','trial'].includes(nextState)?row.current_period_end:row.ended_at||row.current_period_end;
   const{data:entitlement,error:entitlementError}=await db.from('suite_entitlements').upsert({organization_id:organizationId,suite_id:suiteId,subscription_id:stored.id,subscription_item_id:storedItem.id,status:nextState,source:'stripe-subscription',starts_at:row.current_period_start,ends_at:endsAt,metadata:{stripe_subscription_id:subscription.id,stripe_status:subscription.status,grace_state:subscription.status==='past_due'}},{onConflict:'organization_id,suite_id'}).select().single();if(entitlementError)throw entitlementError;
   if(previous?.status!==nextState)await db.from('entitlement_history').insert({organization_id:organizationId,suite_id:suiteId,entitlement_id:entitlement.id,subscription_id:stored.id,previous_state:previous?.status||'locked',next_state:nextState,reason:`stripe-subscription-${subscription.status}`,actor_type:'stripe-webhook',stripe_event_id:eventId});
  }
 }
 return stored;
}
async function subscriptionFromInvoice(client,invoice){const id=typeof invoice.subscription==='string'?invoice.subscription:invoice.subscription?.id||invoice.parent?.subscription_details?.subscription;if(!id)return null;return client.subscriptions.retrieve(id,{expand:['items.data.price']})}
module.exports=async(req,res)=>{if(req.method!=='POST')return json(res,405,{error:'Method not allowed'});let event;try{const body=await rawBody(req);event=stripe().webhooks.constructEvent(body,req.headers['stripe-signature'],required('STRIPE_WEBHOOK_SECRET'))}catch(error){console.error('Stripe webhook signature rejected',{message:error.message});return json(res,400,{error:'Invalid webhook signature'})}
 const db=admin();const{data:existing}=await db.from('billing_events').select('id,status,attempt_count').eq('stripe_event_id',event.id).maybeSingle();if(eventDisposition(existing)==='duplicate')return json(res,200,{received:true,duplicate:true});
 let eventRecord=existing;if(existing){const{data}=await db.from('billing_events').update({status:'processing',attempt_count:(existing.attempt_count||1)+1,last_error:null,updated_at:new Date().toISOString()}).eq('id',existing.id).select().single();eventRecord=data}else{const{data,error}=await db.from('billing_events').insert({stripe_event_id:event.id,event_type:event.type,status:'processing',payload:{livemode:event.livemode,api_version:event.api_version,object_id:event.data?.object?.id}}).select().single();if(error?.code==='23505')return json(res,200,{received:true,duplicate:true});if(error)throw error;eventRecord=data}
 try{const client=stripe();let organizationId=null,handled=true;
  if(event.type==='checkout.session.completed'){const session=event.data.object;organizationId=session.metadata?.organization_id||session.client_reference_id;if(session.subscription){const subscription=await client.subscriptions.retrieve(String(session.subscription),{expand:['items.data.price']});await reconcileSubscription(db,client,subscription,event.id,session.metadata)}}
  else if(['customer.subscription.created','customer.subscription.updated','customer.subscription.deleted'].includes(event.type)){const subscription=event.data.object;organizationId=subscription.metadata?.organization_id;await reconcileSubscription(db,client,subscription,event.id)}
  else if(['invoice.paid','invoice.payment_failed'].includes(event.type)){const subscription=await subscriptionFromInvoice(client,event.data.object);if(subscription){organizationId=subscription.metadata?.organization_id;await reconcileSubscription(db,client,subscription,event.id)}else handled=false}
  else handled=false;
  await db.from('billing_events').update({organization_id:organizationId,status:handled?'processed':'ignored',processed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',eventRecord.id);return json(res,200,{received:true,handled});
 }catch(error){console.error('Stripe webhook processing failed',{eventId:event.id,type:event.type,message:error.message});await db.from('billing_events').update({status:'failed',last_error:String(error.message||'processing-failed').slice(0,500),updated_at:new Date().toISOString()}).eq('id',eventRecord.id);return json(res,500,{error:'Webhook processing failed'})}
};
