import React,{useState}from'react';
import{Link,Navigate,useParams}from'react-router-dom';
import{SUITES,getSuite,SUITE_STATES}from'../config/suites';
import{useEntitlements}from'../context/EntitlementContext';
import{useBilling}from'../context/BillingContext';
import{useAuth}from'../context/AuthContext';
import{registerSuiteInterest}from'../services/suiteInterestService';
import'./Suites.css';
import'./SuiteOverview.css';
const statusLabel=status=>status===SUITE_STATES.COMING_SOON?'Coming Soon':status===SUITE_STATES.TRIAL?'Trial':status===SUITE_STATES.ACTIVE?'Active':status===SUITE_STATES.EXPIRED?'Trial Ended':'Not included in your plan';
function Waitlist({suite,user}){const[email,setEmail]=useState(user?.email||''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const submit=async event=>{event.preventDefault();setBusy(true);setNotice('');try{const result=await registerSuiteInterest({email,suiteKey:suite.id,source:user?'signed-in-suite-overview':'public-suite-overview'});setNotice(result.message)}catch(error){setNotice(error.message)}finally{setBusy(false)}};return <form className="suite-waitlist" onSubmit={submit}>{!user&&<label>Email address<input type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="you@company.com" required/></label>}<button className="btn-primary" disabled={busy}>{busy?'Adding you…':'Notify Me'}</button>{notice&&<small role="status">{notice}</small>}</form>}
function PublicOverview({suite}){return <div className="suite-overview"><header><span>ACTIVE PROFESSIONAL SUITE</span><h1>{suite.name}</h1><p>{suite.description}</p><div><Link className="btn-primary" to={`/start?suite=${suite.id}`}>Start Free Trial</Link><Link className="btn-secondary" to="/pricing">View Pricing</Link></div></header><section className="suite-overview-audience"><span>WHO IT IS FOR</span><h2>{suite.audience}</h2></section><div className="suite-overview-grid">{[['Major workflows',suite.workflows],['Tools and capabilities',suite.tools],['Documents and templates',suite.documents],['Benefits',suite.benefits],['Example outputs',suite.outputs]].map(([title,items])=><article key={title}><h3>{title}</h3><ul>{items.map(item=><li key={item}>{item}</li>)}</ul></article>)}</div><section className="suite-overview-price"><div><span>FOUNDING MEMBER</span><h2>$9.99 <small>/ month</small></h2><p>One professional suite plus the core Aureqin platform. Regular future price: $19.99/month.</p></div><Link className="btn-primary" to={`/start?suite=${suite.id}`}>Start Free Trial</Link></section><Link className="suite-return" to="/suites">← Return to Suites</Link></div>}
export function SuiteRoute(){const{suiteId}=useParams(),suite=getSuite(suiteId),{user}=useAuth(),{canAccess,statusFor,entitlementFor,refresh}=useEntitlements(),{data,checkout,startTrial}=useBilling();const[busy,setBusy]=useState(''),[notice,setNotice]=useState('');if(!suite)return <Navigate to="/suites" replace/>;const status=statusFor(suiteId),entitlement=entitlementFor(suiteId),purchasable=suite.status===SUITE_STATES.ACTIVE,paying=Boolean(data?.current&&['active','trialing','past_due'].includes(data.current.status));if(user&&canAccess(suiteId)&&suite.entryPath)return <Navigate to={suite.entryPath} replace/>;if(!user&&purchasable)return <PublicOverview suite={suite}/>;const run=async(label,action)=>{setBusy(label);setNotice('');try{await action();await refresh()}catch(error){setNotice(error.message)}finally{setBusy('')}};return <div className={`suite-locked status-${status}`}><article><div className="suite-lock-icon" aria-hidden="true">{canAccess(suiteId)?'●':'🔒'}</div><span>{statusLabel(status).toUpperCase()}</span><h1>{suite.name}</h1><p>{suite.description}</p>{status===SUITE_STATES.EXPIRED?<strong>Your trial of {suite.name} has ended. Your projects, documents, datasets, analyses, reports, and artifacts remain preserved.</strong>:<strong>{status===SUITE_STATES.COMING_SOON?'This professional suite is planned for a future Aureqin release.':canAccess(suiteId)?'Your organization has access. The suite workspace is being prepared.':'This suite is not currently included for this organization.'}</strong>}{status===SUITE_STATES.TRIAL&&<small>Trial Active · {entitlement?.daysRemaining} days remaining · Ends {entitlement?.endsAt?new Date(entitlement.endsAt).toLocaleDateString():'soon'}</small>}{notice&&<small className="suite-action-notice">{notice}</small>}{suite.status===SUITE_STATES.COMING_SOON&&<Waitlist suite={suite} user={user}/>}<div>{purchasable&&user&&!canAccess(suiteId)&&<>{paying&&<button className="btn-secondary" disabled={Boolean(busy)} onClick={()=>run('trial',()=>startTrial(suiteId))}>{busy==='trial'?'Starting…':'Start 14-Day Trial'}</button>}<button className="btn-primary" disabled={Boolean(busy)} onClick={()=>run('checkout',()=>checkout(suiteId))}>{busy==='checkout'?'Opening…':'Add Suite'}</button></>}<Link className="btn-secondary" to={user?'/account/billing':'/pricing'}>{user?'Billing & Plans':'View Pricing'}</Link><Link className="btn-secondary" to="/suites">Return to Suites</Link></div></article></div>}
export default function Suites(){const{user}=useAuth(),{canAccess,statusFor,entitlementFor}=useEntitlements();return <div className="suites-page"><header><span>AUREQIN SUITES</span><h1>The productivity platform for professionals.</h1><p>Perform · Optimize · Transform</p></header><div className="suite-grid">{SUITES.map(suite=>{const available=Boolean(user&&canAccess(suite.id)),status=user?statusFor(suite.id):suite.status,entitlement=entitlementFor(suite.id);return <article key={suite.id} className={`${available?'available':'locked'} status-${status}`}><div className="suite-card-status"><span aria-hidden="true">{available?'●':'🔒'}</span>{statusLabel(status)}</div><h2>{suite.name}</h2><p>{suite.description}</p>{status===SUITE_STATES.TRIAL&&<small>{entitlement?.daysRemaining} days remaining</small>}{status===SUITE_STATES.EXPIRED&&<small>Saved work preserved</small>}<Link className={available?'btn-primary':'btn-secondary'} to={`/suites/${suite.id}`}>{available?'Open Suite':!user&&suite.status===SUITE_STATES.ACTIVE?'Explore Suite':'View Suite'}</Link></article>})}</div></div>}
