import {ANALYTICS_CATALOG} from './analyticsCatalog';
import {analyticsSearchEntries,methodDeepLink,resolveMethodContext,searchAnalyticsMethods} from './analyticsExposure';
import {GUIDED_HYPOTHESIS_CHOICES,HYPOTHESIS_METHOD_CONTEXT,TESTS} from '../pages/HypothesisTesting';

test('every catalog method maps to a safe workspace deep link',()=>{const entries=analyticsSearchEntries();expect(entries).toHaveLength(ANALYTICS_CATALOG.length);entries.forEach(entry=>{expect(entry.path).toMatch(/^\/(hypothesis|doe|tool\/[^?]+)\?method=/);expect(entry.validationStatus).toBeTruthy()})});
test.each([['Mann Whitney','mann-whitney','/hypothesis'],['Fisher exact','fisher-exact','/hypothesis'],['Tukey','one-way-anova','/tool/anova'],['Weibull','distribution-analysis','/tool/distribution-analysis'],['fractional factorial','fractional-factorial-doe','/doe']])('%s finds its workspace',(query,id,route)=>{const result=searchAnalyticsMethods(query);expect(result.some(method=>method.id===id&&method.route===route)).toBe(true)});
test('method context rejects stale cross-workspace values and keeps direct routes valid',()=>{expect(resolveMethodContext('/hypothesis','mann-whitney')).toEqual(expect.objectContaining({id:'mann-whitney'}));expect(resolveMethodContext('/tool/anova','mann-whitney')).toBeNull();expect(resolveMethodContext('/hypothesis','stale-method')).toBeNull()});
test('hypothesis direct and guided selections map to exposed controls',()=>{const ids=new Set(TESTS.map(test=>test.id));Object.values(HYPOTHESIS_METHOD_CONTEXT).forEach(id=>expect(ids.has(id)).toBe(true));GUIDED_HYPOTHESIS_CHOICES.forEach(choice=>expect(ids.has(choice.method)).toBe(true));expect(HYPOTHESIS_METHOD_CONTEXT['sign-test']).toBe('sign');expect(HYPOTHESIS_METHOD_CONTEXT['variance-inference']).toBe('1variance')});
test('deep links preserve validation status rather than promoting UI-complete methods',()=>{const method=ANALYTICS_CATALOG.find(item=>item.id==='sign-test');expect(methodDeepLink(method)).toBe('/hypothesis?method=sign-test');expect(method.validationStatus).toBe('UNVALIDATED')});
test.each([['response surface','response-surface'],['RSM','response-surface'],['central composite','central-composite'],['CCD','central-composite'],['Box-Behnken','box-behnken'],['contour plot','response-surface']])('%s resolves to DOE method context',(query,id)=>{const result=searchAnalyticsMethods(query);expect(result).toEqual(expect.arrayContaining([expect.objectContaining({id,route:'/doe'})]));expect(methodDeepLink(result.find(item=>item.id===id))).toBe(`/doe?method=${id}`)});
