const text=(id,label,placeholder='',options={})=>({id,label,type:'text',placeholder,...options});
const narrative=(id,label,placeholder,options={})=>({id,label,type:'textarea',placeholder,...options});
const table=(id,label,columns,help)=>({id,label,type:'table',columns,help,span:2});
const choice=(key,label,options)=>({key,label,type:'select',options});
export const CONTROL_TEMPLATES=[
 {id:'control-plan',name:'Control Plan',phase:'Control',icon:'▣',desc:'Define controls, ownership, specifications, and reactions that sustain improved performance.',sections:[{id:'control-context',title:'Control Strategy',guidance:'Connect critical characteristics to reliable controls and accountable ownership.',cols:2,fields:[text('process','Process','Controlled process'),text('planOwner','Plan Owner','Accountable owner'),narrative('objective','Control Objective','Describe the performance condition this plan sustains.',{span:2})]},{id:'controls',title:'Control Plan',guidance:'Every control requires a frequency, owner, specification, and reaction.',cols:1,fields:[table('controlRows','Process controls',[{key:'characteristic',label:'Characteristic'},{key:'specification',label:'Specification'},{key:'method',label:'Control Method'},{key:'frequency',label:'Frequency'},{key:'owner',label:'Owner'},{key:'reaction',label:'Reaction Plan',multiline:true}],'Maintain one row per critical control.')] }]},
 {id:'reaction-plan',name:'Reaction Plan',phase:'Control',icon:'⚑',desc:'Standardize immediate containment, escalation, correction, and verification actions.',sections:[{id:'reactions',title:'Reaction Matrix',guidance:'Make triggers unambiguous and assign named owners for containment and escalation.',cols:1,fields:[table('reactionRows','Reaction scenarios',[{key:'trigger',label:'Trigger'},{key:'containment',label:'Immediate Containment',multiline:true},{key:'escalation',label:'Escalation'},{key:'owner',label:'Owner'},{key:'correction',label:'Corrective Action',multiline:true},{key:'verification',label:'Verification'}],'Test reactions through tabletop review.')] }]},
 {id:'monitoring-plan',name:'Monitoring Plan',phase:'Control',icon:'◴',desc:'Define ongoing indicators, review cadence, thresholds, and governance.',sections:[{id:'monitoring',title:'Monitoring Schedule',guidance:'Use indicators that detect deterioration early enough for effective response.',cols:1,fields:[table('monitoringRows','Monitoring indicators',[{key:'metric',label:'Metric'},{key:'source',label:'Source'},{key:'frequency',label:'Frequency'},{key:'threshold',label:'Threshold'},{key:'owner',label:'Owner'},{key:'review',label:'Review Forum'},choice('status','Status',['Active','At Risk','Paused'])],'Link monitoring indicators to verified project datasets and analyses.')] }]},
 {id:'audit-checklist',name:'Audit Checklist',phase:'Control',icon:'☑',desc:'Create repeatable conformance checks with evidence and corrective ownership.',sections:[{id:'audit-context',title:'Audit Context',guidance:'Define scope, cadence, auditor, and evidence expectations.',cols:2,fields:[text('scope','Audit Scope','Process or location'),text('auditor','Auditor','Responsible reviewer'),text('cadence','Cadence','Weekly, monthly, quarterly'),text('standard','Standard','Procedure or requirement')]},{id:'checklist',title:'Checklist',guidance:'Each check should be observable and supported by evidence.',cols:1,fields:[table('auditRows','Audit checks',[{key:'requirement',label:'Requirement'},{key:'evidence',label:'Expected Evidence'},{key:'result',label:'Result'},{key:'finding',label:'Finding',multiline:true},{key:'owner',label:'Corrective Owner'},{key:'dueDate',label:'Due Date',type:'date'}],'Record objective evidence for every audit item.')] }]},
 {id:'lessons-learned',name:'Lessons Learned',phase:'Control',icon:'✦',desc:'Capture reusable insight from project delivery, adoption, analysis, and outcomes.',sections:[{id:'summary',title:'Executive Reflection',guidance:'Summarize what future teams should repeat, avoid, or change.',cols:1,fields:[narrative('summary','Lessons Summary','Describe the most important transferable learning.')]},{id:'lessons',title:'Lessons Register',guidance:'Make each lesson actionable and identify where it should be reused.',cols:1,fields:[table('lessonRows','Lessons',[{key:'category',label:'Category'},{key:'observation',label:'Observation',multiline:true},{key:'impact',label:'Impact'},{key:'recommendation',label:'Recommendation',multiline:true},{key:'owner',label:'Knowledge Owner'}],'Capture both successful practices and preventable issues.')] }]},
 {id:'project-closure',name:'Project Closure',phase:'Control',icon:'◇',desc:'Confirm deliverables, ownership transfer, outstanding actions, and formal closure.',sections:[{id:'closure-summary',title:'Closure Summary',guidance:'Confirm that objectives, deliverables, benefits, and operational ownership are understood.',cols:1,fields:[narrative('outcomes','Project Outcomes','Summarize achieved results against the charter.'),narrative('handoff','Operational Handoff','Document process ownership, controls, training, and support.'),narrative('openItems','Outstanding Items','List remaining actions, owners, and dates.')]},{id:'approval',title:'Closure Approval',guidance:'Capture an accountable closure decision.',cols:2,fields:[text('sponsor','Sponsor','Approver'),text('closureDate','Closure Date','',{type:'date'}),text('status','Closure Status','Approved, conditional, pending'),narrative('approvalNotes','Approval Notes','Conditions or formal comments.',{span:2})]}]}
];
