const text = (id, label, placeholder = '', options = {}) => ({ id, label, type: 'text', placeholder, ...options });
const narrative = (id, label, placeholder, options = {}) => ({ id, label, type: 'textarea', placeholder, ...options });
const table = (id, label, columns, help) => ({ id, label, type: 'table', columns, help, span: 2 });
const option = (key, label, options) => ({ key, label, type: 'select', options });

export const DEFINE_TEMPLATES = [
  { id:'charter', name:'Project Charter', phase:'Define', discipline:'Lean Six Sigma', icon:'📋', desc:'Align leaders on the case for change, scope, goals, ownership, and authorization.', sections:[] },
  { id:'sipoc', name:'SIPOC', phase:'Define', discipline:'Lean Six Sigma', icon:'↔', desc:'Define the high-level process and its supplier-to-customer relationships.', sections:[
    { id:'project-information', title:'Project Information', guidance:'Establish the process boundary and accountable ownership before mapping details.', cols:2, fields:[text('processName','Process Name','Name the process',{span:2}),text('processOwner','Process Owner','Accountable owner'),text('startPoint','Start Point','Trigger that begins the process'),text('endPoint','End Point','Event that completes the process'),narrative('objective','Objective','Explain what this SIPOC must clarify.',{span:2}),narrative('scope','Scope','Define included products, locations, customers, and boundaries.',{span:2})]},
    { id:'sipoc-map', title:'SIPOC Map', guidance:'Keep entries high-level. Use five to seven major process steps and connect each row across the value chain.', cols:1, fields:[table('sipocRows','Supplier-to-customer map',[{key:'supplier',label:'Supplier',multiline:true},{key:'input',label:'Input',multiline:true},{key:'process',label:'Process',multiline:true},{key:'output',label:'Output',multiline:true},{key:'customer',label:'Customer',multiline:true}],'Add unlimited relationships, drag rows to reorder, and expand any cell for focused editing.')]}
  ]},
  { id:'voc', name:'Voice of the Customer (VOC)', phase:'Define', discipline:'Lean Six Sigma', icon:'◉', desc:'Translate customer evidence into prioritized needs and measurable CTQ connections.', sections:[
    { id:'voc-context', title:'VOC Context', guidance:'Document where customer evidence came from and how it represents the target population.', cols:2, fields:[text('researchOwner','Research Owner','Name or team'),text('collectionPeriod','Collection Period','Date range'),narrative('customerSegments','Customer Segments','Describe represented customer groups.'),narrative('sources','Evidence Sources','Interviews, surveys, complaints, observation, or support data.')]},
    { id:'customer-voice', title:'Customer Requirements', guidance:'Record the customer’s language first, then assess priority and criticality before translating it into a CTQ.', cols:1, fields:[table('vocRows','Voice of customer register',[{key:'customer',label:'Customer'},{key:'requirement',label:'Requirement',multiline:true},{key:'painPoint',label:'Pain Point',multiline:true},option('priority','Priority',['High','Medium','Low']),option('criticality','Criticality',['Critical','Important','Standard']),{key:'ctqLink',label:'CTQ Link'},{key:'notes',label:'Notes',multiline:true}],'Maintain one testable customer requirement per row.')]}
  ]},
  { id:'ctq-tree', name:'CTQ Tree', phase:'Define', discipline:'Lean Six Sigma', icon:'⌘', desc:'Translate broad customer needs into drivers, measurable CTQs, and specifications.', sections:[
    { id:'ctq-context', title:'Tree Context', guidance:'Anchor the tree in a defined customer group and evidence source.', cols:2, fields:[text('customerSegment','Customer Segment','Who expressed the need?'),text('treeOwner','Tree Owner','Accountable person'),narrative('evidence','VOC Evidence','Summarize supporting research and observations.',{span:2})]},
    { id:'ctq-structure', title:'CTQ Structure', guidance:'Each branch should trace from a customer need through a driver to a measurable CTQ and an unambiguous specification.', cols:1, fields:[{id:'ctqTree',label:'Need → Driver → CTQ → Specification',type:'tree',span:2,help:'Add unlimited branches and collapse completed paths.'}]}
  ]},
  { id:'business-case', name:'Business Case', phase:'Define', discipline:'Project Management', icon:'◆', desc:'Present a decision-ready case for investment, alignment, benefits, and measurable success.', sections:[
    {id:'executive-summary',title:'Executive Summary',guidance:'Give decision-makers the issue, proposed response, value, and requested decision in concise language.',cols:1,fields:[narrative('executiveSummary','Executive Summary','Summarize the opportunity, recommendation, value, and decision requested.')]},
    {id:'case-for-change',title:'Case for Change',guidance:'Contrast the evidence-based current state with the intended future state.',cols:1,fields:[narrative('problemStatement','Problem Statement','Define the gap, where it occurs, magnitude, and consequence.'),narrative('currentState','Current State','Describe baseline performance, cost, customer impact, and constraints.'),narrative('futureState','Future State','Describe the intended operating condition and measurable outcome.')]},
    {id:'value',title:'Value and Alignment',guidance:'Separate financial impact from strategic and operational benefits.',cols:1,fields:[narrative('financialImpact','Financial Impact','Quantify investment, hard savings, avoidance, revenue, and timing.'),narrative('strategicAlignment','Strategic Alignment','Connect the proposal to enterprise objectives and priorities.'),narrative('benefits','Benefits','List customer, quality, delivery, workforce, compliance, and capability benefits.')]},
    {id:'assurance',title:'Risk and Success',guidance:'Show how value will be protected and how success will be verified.',cols:1,fields:[narrative('risks','Risks','Describe material risks, assumptions, mitigations, and owners.'),narrative('successCriteria','Success Criteria','Define measurable acceptance criteria, owners, and validation timing.')]}
  ]},
  { id:'stakeholder-register', name:'Stakeholder Register', phase:'Define', discipline:'Project Management', icon:'◎', desc:'Map influence, interest, support, ownership, and communication commitments.', sections:[
    {id:'stakeholder-context',title:'Engagement Strategy',guidance:'Set the purpose and ownership of stakeholder engagement.',cols:2,fields:[text('engagementOwner','Engagement Lead','Accountable person'),text('reviewCadence','Register Review Cadence','Weekly, monthly, gate review'),narrative('engagementObjective','Engagement Objective','Describe the adoption, decision, and communication outcomes required.',{span:2})]},
    {id:'stakeholders',title:'Stakeholder Register',guidance:'Prioritize high-influence and low-support stakeholders for deliberate engagement.',cols:1,fields:[table('stakeholderRows','Stakeholders',[{key:'name',label:'Name'},{key:'role',label:'Role'},{key:'department',label:'Department'},option('influence','Influence',['High','Medium','Low']),option('interest','Interest',['High','Medium','Low']),option('supportLevel','Support Level',['Leading','Supportive','Neutral','Resistant','Unaware']),{key:'communicationFrequency',label:'Communication Frequency'},{key:'owner',label:'Owner'},{key:'notes',label:'Notes',multiline:true}],'Maintain current engagement assessments and clear relationship ownership.')]}
  ]}
];

export const DEFINE_TEMPLATE_IDS = DEFINE_TEMPLATES.map(template => template.id);
