const text=(id,label,placeholder='',options={})=>({id,label,type:'text',placeholder,...options});
const narrative=(id,label,placeholder,options={})=>({id,label,type:'textarea',placeholder,...options});
const select=(id,label,options,extra={})=>({id,label,type:'select',options,...extra});
const choice=(key,label,options)=>({key,label,type:'select',options});
const table=(id,label,columns,help,extra={})=>({id,label,type:'table',columns,help,span:2,...extra});

export const MEASURE_TEMPLATES=[
 {id:'data-collection-plan',name:'Data Collection Plan',phase:'Measure',icon:'▦',desc:'Define what data will be collected, how, when, and by whom.',sections:[
  {id:'plan-context',title:'Collection Strategy',guidance:'Anchor collection activities to the project question and intended decisions.',cols:2,fields:[narrative('objective','Collection Objective','Describe the decision this data must support.',{span:2}),text('planOwner','Plan Owner','Accountable owner'),text('reviewCadence','Review Cadence','Daily, weekly, gate review')]},
  {id:'collection-items',title:'Collection Plan',guidance:'Every metric needs a testable definition, traceable source, feasible sample, and accountable owner.',cols:1,fields:[table('collectionRows','Data collection items',[{key:'metric',label:'Metric'},{key:'operationalDefinition',label:'Operational Definition',multiline:true},{key:'unit',label:'Unit of Measure'},{key:'method',label:'Collection Method'},{key:'source',label:'Data Source'},{key:'frequency',label:'Sampling Frequency'},{key:'sampleSize',label:'Sample Size',type:'number'},{key:'owner',label:'Responsible Owner'},{key:'start',label:'Collection Start',type:'date'},{key:'end',label:'Collection End',type:'date'},{key:'notes',label:'Notes',multiline:true}],'Use one row for each metric and validate the plan with data collectors.')]}
 ]},
 {id:'process-map',name:'Process Map',phase:'Measure',icon:'⇢',desc:'Build an ordered process flow with activities, decisions, inputs, outputs, and ownership.',sections:[
  {id:'map-context',title:'Map Context',guidance:'Set clear boundaries and the level of detail needed for analysis.',cols:2,fields:[text('processName','Process Name','Name the process'),text('processOwner','Process Owner','Accountable owner'),text('startPoint','Start Point','Trigger'),text('endPoint','End Point','Completion event'),narrative('mapObjective','Mapping Objective','What should this map reveal?',{span:2})]},
  {id:'process-flow',title:'Interactive Process Flow',guidance:'Sequence activities and decisions in actual operating order. Make connectors explicit.',cols:1,fields:[{id:'processNodes',label:'Process builder',type:'flow',mode:'process',span:2}]}
 ]},
 {id:'swimlane-process-map',name:'Swimlane Process Map',phase:'Measure',icon:'☷',desc:'Visualize work, decisions, roles, departments, and cross-functional handoffs.',sections:[
  {id:'lane-context',title:'Swimlane Context',guidance:'Identify the end-to-end process and functions participating in it.',cols:2,fields:[text('processName','Process Name','Name the process'),text('mapOwner','Map Owner','Facilitator'),narrative('departments','Departments and Roles','List functions represented in the map.',{span:2})]},
  {id:'lane-flow',title:'Swimlane Flow',guidance:'Use one row per step and identify every handoff and decision point.',cols:1,fields:[{id:'swimlaneNodes',label:'Swimlane editor',type:'flow',mode:'swimlane',span:2}]}
 ]},
 {id:'value-stream-map',name:'Value Stream Map',phase:'Measure',icon:'≋',desc:'Quantify material and information flow, delay, capacity, and value-added performance.',sections:[
  {id:'vsm-context',title:'Value Stream Context',guidance:'Define product family, customer demand, available time, and map boundaries.',cols:2,fields:[text('productFamily','Product or Service Family','Family being mapped'),text('demand','Customer Demand','Units per period'),text('availableTime','Available Time','Minutes per period'),text('vsmOwner','Map Owner','Facilitator')]},
  {id:'vsm-flow',title:'Current-State Flow',guidance:'Capture actual observed times and distinguish value-added from non-value-added activity.',cols:1,fields:[table('vsmRows','Value stream steps',[{key:'step',label:'Process Step'},{key:'cycleTime',label:'Cycle Time',type:'number'},{key:'changeoverTime',label:'Changeover Time',type:'number'},{key:'waitTime',label:'Wait Time',type:'number'},{key:'inventory',label:'Inventory',type:'number'},{key:'operators',label:'Operators',type:'number'},{key:'uptime',label:'Uptime %',type:'number'},choice('classification','VA / NVA',['VA','NVA','Business Necessary'])],'Enter consistent time units for meaningful totals.',{summaries:[{label:'Total Cycle Time',key:'cycleTime',operation:'sum'},{label:'Total Changeover',key:'changeoverTime',operation:'sum'},{label:'Total Wait',key:'waitTime',operation:'sum'},{label:'Total Inventory',key:'inventory',operation:'sum'},{label:'Average Uptime',key:'uptime',operation:'average'}]})]}
 ]},
 {id:'msa-workspace',name:'Measurement System Analysis (MSA)',phase:'Measure',icon:'⌖',desc:'Plan, document, and reference measurement-system studies without changing statistical calculations.',sections:[
  {id:'study-information',title:'Study Information',guidance:'Document the measurement system, characteristic, ownership, and study purpose.',cols:2,fields:[text('studyName','Study Name','MSA study title'),select('studyType','Study Type',['Gauge R&R','Attribute Agreement','Bias','Linearity','Stability']),text('characteristic','Measured Characteristic','Metric or feature'),text('instrument','Instrument or Gauge','Asset or method'),text('studyOwner','Study Owner','Accountable analyst'),text('studyDate','Study Date','', {type:'date'}),narrative('studyObjective','Study Objective','Define the question and acceptance decision.',{span:2})]},
  {id:'study-design',title:'Study Design',guidance:'Record the design and reference the project dataset used by the existing statistical tool.',cols:2,fields:[text('parts','Parts or Samples','Count and selection'),text('appraisers','Appraisers','Names or count'),text('trials','Trials','Replicates'),text('referenceStandard','Reference Standard','Master or standard'),narrative('procedure','Study Procedure','Explain randomization, blinding, environment, and collection rules.',{span:2})]},
  {id:'study-results',title:'Results and Decision',guidance:'Reference completed analyses and document conclusions; calculations remain in the statistical tools.',cols:1,fields:[narrative('resultsSummary','Results Summary','Summarize Gauge R&R, agreement, bias, linearity, or stability evidence.'),narrative('acceptanceDecision','Acceptance Decision','State criteria, decision, limitations, and actions.'),narrative('recommendations','Recommendations','Document corrective actions and follow-up studies.')]}
 ]},
 {id:'sampling-plan',name:'Sampling Plan',phase:'Measure',icon:'◌',desc:'Define a defensible sampling method, precision target, frequency, and ownership.',sections:[
  {id:'sampling-design',title:'Sampling Design',guidance:'Match the sampling method and precision to the population and intended inference.',cols:2,fields:[text('population','Population','Define population and frame',{span:2}),select('samplingMethod','Sampling Method',['Simple Random','Systematic','Stratified','Cluster','Judgment','Convenience']),text('confidenceLevel','Confidence Level','e.g. 95%'),text('marginOfError','Margin of Error','e.g. ±3%'),text('sampleSize','Sample Size','Required observations'),text('frequency','Frequency','Per shift, weekly, monthly'),text('owner','Owner','Responsible person'),narrative('notes','Notes','Assumptions, strata, exclusions, replacement, and nonresponse rules.',{span:2})]}
 ]},
 {id:'operational-definitions',name:'Operational Definitions',phase:'Measure',icon:'≜',desc:'Create observable, repeatable definitions for every project measure.',sections:[
  {id:'definition-register',title:'Definition Register',guidance:'A different trained observer should reach the same result using each definition.',cols:1,fields:[table('definitionRows','Operational definitions',[{key:'metric',label:'Metric'},{key:'definition',label:'Definition',multiline:true},{key:'formula',label:'Formula'},{key:'unit',label:'Unit'},{key:'collectionRules',label:'Collection Rules',multiline:true},{key:'exceptions',label:'Exceptions',multiline:true},{key:'owner',label:'Owner'}],'Test definitions with collectors before baseline collection.')]}
 ]},
 {id:'baseline-metrics',name:'Baseline Metrics',phase:'Measure',icon:'◫',desc:'Establish the verified starting performance for project KPIs.',sections:[
  {id:'baseline-context',title:'Baseline Context',guidance:'Define the observation window, source, and validation owner.',cols:2,fields:[text('baselinePeriod','Baseline Period','Date range'),text('validationOwner','Validation Owner','Process or finance owner'),narrative('baselineNotes','Baseline Notes','Data exclusions, transformations, and known limitations.',{span:2})]},
  {id:'kpi-baseline',title:'KPI Baseline',guidance:'Use consistent units and link each KPI to a verified dataset or analysis.',cols:1,fields:[table('baselineRows','Baseline KPIs',[{key:'metric',label:'Metric'},{key:'current',label:'Current',type:'number'},{key:'target',label:'Target',type:'number'},{key:'specification',label:'Specification'},{key:'baselineDate',label:'Baseline Date',type:'date'},{key:'owner',label:'Owner'},choice('trend','Trend',['Improving','Stable','Declining','Unknown']),choice('status','Status',['On Track','At Risk','Off Track','Not Rated'])],'Review baseline values at the Measure gate.')]}
 ]},
 {id:'process-capability-study',name:'Process Capability Study',phase:'Measure',icon:'Cpk',desc:'Document specifications and reference completed capability analyses as reusable project evidence.',sections:[
  {id:'capability-context',title:'Study Context',guidance:'Confirm process stability, distribution assumptions, and the analysis dataset.',cols:2,fields:[text('characteristic','Characteristic','Measured output'),text('studyOwner','Study Owner','Analyst'),text('lsl','Lower Specification Limit','LSL'),text('usl','Upper Specification Limit','USL'),text('target','Target','Nominal target'),text('studyPeriod','Study Period','Date range')]},
  {id:'capability-results',title:'Capability Results',guidance:'Record reported indices from the completed capability analysis; do not recalculate them here.',cols:2,fields:[text('cp','Cp','Reported Cp'),text('cpk','Cpk','Reported Cpk'),text('pp','Pp','Reported Pp'),text('ppk','Ppk','Reported Ppk'),narrative('comments','Comments','Stability, distribution, subgrouping, and limitation notes.',{span:2}),narrative('recommendations','Recommendations','Actions based on capability evidence.',{span:2})]}
 ]},
 {id:'measurement-plan',name:'Measurement Plan',phase:'Measure',icon:'✓',desc:'Define how critical characteristics will be measured and how teams will react.',sections:[
  {id:'measurement-context',title:'Plan Governance',guidance:'Set plan ownership, review cadence, and instrument-control expectations.',cols:2,fields:[text('planOwner','Plan Owner','Accountable owner'),text('reviewCadence','Review Cadence','Monthly, quarterly'),narrative('governance','Measurement Governance','Calibration, data integrity, access, retention, and approval rules.',{span:2})]},
  {id:'measurement-items',title:'Measurement Plan',guidance:'Each characteristic requires a repeatable method and a clear reaction to unacceptable results.',cols:1,fields:[table('measurementRows','Measurement items',[{key:'characteristic',label:'Characteristic'},{key:'method',label:'Method',multiline:true},{key:'instrument',label:'Instrument'},{key:'frequency',label:'Frequency'},{key:'sampleSize',label:'Sample Size',type:'number'},{key:'responsiblePerson',label:'Responsible Person'},{key:'reactionPlan',label:'Reaction Plan',multiline:true}],'Align reaction plans with process ownership and escalation rules.')]}
 ]}
];

export const MEASURE_TEMPLATE_IDS=MEASURE_TEMPLATES.map(template=>template.id);
