const slug=name=>name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const narrative=(id,label,placeholder)=>({id,label,type:'textarea',placeholder,span:2});
const table=(id,label,columns,help)=>({id,label,type:'table',columns,help,span:2});
const choice=(key,label,options)=>({key,label,type:'select',options});
const lifecycle={
 Initiation:['Benefits Management Plan','Assumption Log'],
 // PMBOK 8th Edition additions (Project Governance Framework, Value Realization Plan, AI and
 // Automation Impact Assessment, Sustainability Impact Assessment) are inserted right after
 // Project Management Plan rather than appended at the end of this array, so 'Change Management
 // Plan' stays the last Planning-stage document — defineSequence.pm.test.js asserts
 // change-management-plan -> issue-log as adjacent sequence neighbors across the Planning ->
 // Execution boundary, and appending here would have inserted between them instead. Their
 // Performance Domain clusters (Governance, Value Delivery, AI Impact Assessment, Sustainability)
 // are assigned in navigation.js PM_GROUPS; this array only controls which Focus Area (Process
 // Group) stage a document belongs to, unchanged by the PMBOK 8 taxonomy update.
 Planning:['Project Management Plan','Project Governance Framework','Value Realization Plan','AI and Automation Impact Assessment','Sustainability Impact Assessment','Scope Management Plan','Scope Statement','WBS','WBS Dictionary','Requirements Management Plan','Requirements Traceability Matrix','Schedule Management Plan','Schedule Baseline','Cost Management Plan','Cost Baseline','Resource Management Plan','Resource Calendar','Communications Management Plan','Stakeholder Engagement Plan','Risk Management Plan','Risk Register','Risk Report','Procurement Management Plan','Quality Management Plan','Configuration Management Plan','Change Management Plan'],
 Execution:['Issue Log','Decision Log','Action Item Log','RAID Log','Change Request','Procurement Documents','Vendor Evaluation','Lessons Learned Register','Team Performance Reviews'],
 // Benefits Tracking Register is inserted right after Status Report rather than appended at the
 // end, so 'KPI Dashboard' stays the last Monitoring & Controlling document —
 // defineSequence.pm.test.js asserts kpi-dashboard -> final-project-report as adjacent sequence
 // neighbors across the Monitoring & Controlling -> Closing boundary.
 'Monitoring & Controlling':['Status Report','Benefits Tracking Register','Executive Dashboard','Variance Report','EVM Dashboard','Milestone Report','Change Log','Quality Audit','Risk Review','KPI Dashboard'],
 Closing:['Final Project Report','Lessons Learned Report','Project Closure Report','Transition Plan','Acceptance Signoff','Benefits Realization Review','Archive Checklist']
};
const logColumns=[{key:'item',label:'Item',multiline:true},{key:'owner',label:'Owner'},{key:'dueDate',label:'Due Date',type:'date'},choice('status','Status',['Not Started','In Progress','Blocked','Complete']),{key:'notes',label:'Notes',multiline:true}];
function generic(name,group){return{id:slug(name),name,phase:group,pmpLifecycle:group,documentType:name.includes('Plan')?'Plan':name.includes('Report')?'Report':name.includes('Log')||name.includes('Register')?'Register':'Project Document',icon:'◇',desc:`Create and maintain the project ${name.toLowerCase()} as a governed, project-connected workspace.`,sections:[{id:'overview',title:'Purpose and Governance',guidance:`Define the purpose, ownership, approval, and operating expectations for the ${name}.`,cols:2,fields:[narrative('purpose','Purpose and Objectives',`Describe what the ${name.toLowerCase()} governs and the decisions it supports.`),narrative('approach','Approach and Governance','Roles, cadence, standards, approvals, escalation, and change control.')]},{id:'register',title:'Managed Items',guidance:'Maintain structured, accountable records and current status.',cols:1,fields:[table('items',name,logColumns,'Add unlimited records and keep ownership, dates, status, and evidence current.')]},{id:'review',title:'Review and Approval',guidance:'Document decisions, exceptions, and approval conditions.',cols:1,fields:[narrative('reviewNotes','Review Notes','Key decisions, exceptions, approvals, and next review actions.')]}]};}
const overrides={
 'Benefits Management Plan':{sections:[{id:'benefits',title:'Benefits Profile',guidance:'Define measurable benefits, ownership, timing, and verification.',cols:1,fields:[table('benefitRows','Benefits',[{key:'benefit',label:'Benefit',multiline:true},{key:'metric',label:'Metric'},{key:'baseline',label:'Baseline'},{key:'target',label:'Target'},{key:'owner',label:'Benefit Owner'},{key:'realizationDate',label:'Realization Date',type:'date'},choice('status','Status',['Planned','Tracking','Realized','At Risk'])],'Connect every benefit to a measurable outcome.')],example:'"Reduce onboarding time" measured by "days from signup to first order", baseline 14 days, target 5 days, owned by the Customer Success lead, realized by Q3 — not just "improve onboarding."'}]},
 'Assumption Log':{sections:[{id:'assumptions',title:'Assumption Log',guidance:'Validate assumptions early and track their effect on project decisions.',cols:1,fields:[table('assumptionRows','Assumptions',[{key:'assumption',label:'Assumption',multiline:true},{key:'basis',label:'Basis',multiline:true},{key:'owner',label:'Owner'},{key:'validationDate',label:'Validation Date',type:'date'},choice('status','Status',['Open','Validated','Invalidated']),{key:'impact',label:'Impact',multiline:true}],'Escalate invalidated assumptions that affect baselines.')] }]},
 'WBS':{sections:[{id:'wbs',title:'Work Breakdown Structure',guidance:'Decompose scope hierarchically into manageable work packages.',cols:1,fields:[table('wbsRows','WBS hierarchy',[{key:'wbsId',label:'WBS ID'},{key:'level',label:'Level',type:'number'},{key:'parentId',label:'Parent WBS ID'},{key:'workPackage',label:'Deliverable / Work Package',multiline:true},{key:'owner',label:'Owner'},{key:'acceptance',label:'Acceptance Criteria',multiline:true}],'Use parent IDs and levels to preserve hierarchy.')],example:'"1.2.3 — Assemble prototype housing," owned by the mechanical lead, with acceptance criteria "Passes 1.2m drop test" — not a vague line like "Build stuff."'}]},
 'Requirements Traceability Matrix':{sections:[{id:'requirements',title:'Requirements Traceability Matrix',guidance:'Trace every approved requirement from source through validation and acceptance.',cols:1,fields:[table('requirementRows','Requirements',[{key:'requirementId',label:'Requirement ID'},{key:'requirement',label:'Requirement',multiline:true},{key:'source',label:'Source'},{key:'owner',label:'Owner'},choice('status','Status',['Proposed','Approved','Implemented','Verified','Rejected']),{key:'test',label:'Test / Verification',multiline:true},{key:'acceptance',label:'Acceptance Evidence',multiline:true}],'Maintain stable IDs through the project lifecycle.')] }]},
 'Schedule Baseline':{sections:[{id:'schedule',title:'Schedule Baseline',guidance:'Preserve approved dates and dependencies for performance comparison.',cols:1,fields:[table('scheduleRows','Baseline milestones',[{key:'milestone',label:'Milestone'},{key:'start',label:'Start',type:'date'},{key:'finish',label:'Finish',type:'date'},{key:'duration',label:'Duration'},{key:'dependencies',label:'Dependencies'},{key:'owner',label:'Owner'},choice('status','Status',['Not Started','In Progress','Complete','Delayed'])],'Changes should follow approved change control.')] }]},
 'Risk Register':{sections:[{id:'risks',title:'Risk Register',guidance:'Assess exposure consistently and maintain response ownership.',cols:1,fields:[table('riskRows','Project risks',[{key:'riskId',label:'Risk ID'},{key:'risk',label:'Risk',multiline:true},{key:'probability',label:'Probability',type:'number'},{key:'impact',label:'Impact',type:'number'},{key:'exposure',label:'Exposure',type:'number'},{key:'owner',label:'Owner'},{key:'response',label:'Response',multiline:true},choice('status','Status',['Open','Monitoring','Triggered','Closed'])],'Exposure may be recorded as probability × impact using the project scoring convention.')],example:'"Key vendor may miss the material delivery date," probability 3, impact 4, response "Qualify a backup vendor by end of month," owned by Procurement — not just "vendor risk."'}]},
  'EVM Dashboard':{calculate:values=>{const pv=Number(values.pv)||0,ev=Number(values.ev)||0,ac=Number(values.ac)||0,bac=Number(values.bac)||0,cpi=ac?ev/ac:0,spi=pv?ev/pv:0,eac=cpi?bac/cpi:0;return{CPI:cpi.toFixed(2),SPI:spi.toFixed(2),CV:(ev-ac).toFixed(2),SV:(ev-pv).toFixed(2),EAC:eac.toFixed(2),ETC:(eac-ac).toFixed(2),VAC:(bac-eac).toFixed(2)};},sections:[{id:'evm-inputs',title:'EVM Inputs',guidance:'Use values from the approved cost and schedule baselines.',cols:2,fields:[{id:'pv',label:'Planned Value (PV)',type:'text'},{id:'ev',label:'Earned Value (EV)',type:'text'},{id:'ac',label:'Actual Cost (AC)',type:'text'},{id:'bac',label:'Budget at Completion (BAC)',type:'text'}]},{id:'forecast',title:'Calculated Performance and Interpretation',guidance:'Review calculated indicators, then explain drivers, forecast confidence, and corrective action.',cols:2,fields:[{id:'CPI',label:'Cost Performance Index (CPI)',type:'text'},{id:'SPI',label:'Schedule Performance Index (SPI)',type:'text'},{id:'CV',label:'Cost Variance (CV)',type:'text'},{id:'SV',label:'Schedule Variance (SV)',type:'text'},{id:'EAC',label:'Estimate at Completion (EAC)',type:'text'},{id:'ETC',label:'Estimate to Complete (ETC)',type:'text'},{id:'VAC',label:'Variance at Completion (VAC)',type:'text'},narrative('interpretation','Interpretation','Explain CPI, SPI, variances, forecast, and management action.')]}]},
 // PMBOK 8 upgrade: previously a generic register (a single freeform "Managed Items" table).
 // Replaced with the specific decision-record fields PMBOK 8's Governance domain expects, while
 // keeping the same overview/register/review three-section shape every other generic document
 // uses, so this remains structurally consistent with the rest of the catalog.
 'Decision Log':{sections:[
  {id:'overview',title:'Purpose and Governance',guidance:'Define the purpose, ownership, approval, and operating expectations for the Decision Log.',cols:2,fields:[narrative('purpose','Purpose and Objectives','Describe what the decision log governs and the decisions it supports.'),narrative('approach','Approach and Governance','Roles, cadence, standards, approvals, escalation, and change control.')]},
  {id:'register',title:'Decisions',guidance:'Record every material project decision with enough context to audit it later.',cols:1,fields:[table('decisionRows','Decisions',[{key:'decisionId',label:'Decision ID'},{key:'decision',label:'Decision Statement',multiline:true},{key:'rationale',label:'Rationale',multiline:true},choice('authorityLevel','Authority Level',['Team','Project Manager','Sponsor','Steering Committee','Governance Board']),{key:'alternatives',label:'Alternatives Considered',multiline:true},{key:'date',label:'Date',type:'date'},{key:'owner',label:'Owner'},{key:'impact',label:'Impact Assessment',multiline:true}],'Capture the decision, why it was made, what else was considered, and its downstream impact.')]},
  {id:'review',title:'Review and Approval',guidance:'Document decisions, exceptions, and approval conditions.',cols:1,fields:[narrative('reviewNotes','Review Notes','Key decisions, exceptions, approvals, and next review actions.')]},
 ]},
 // New PMBOK 8 artifact — Governance domain (replaces Integration Management as the home for
 // project-level authority and decision structure).
 'Project Governance Framework':{sections:[
  {id:'structure',title:'Governance Structure',guidance:'Define who governs this project and how authority flows from sponsor to delivery team.',cols:2,fields:[narrative('governanceStructure','Governance Structure','Describe governance bodies, membership, and how they relate to each other.'),narrative('sponsorResponsibilities','Sponsor Responsibilities','What the executive sponsor owns, decides, and is accountable for.')]},
  {id:'authority',title:'Decision Authority',guidance:"Make explicit who can decide what, and where decisions escalate when a role's authority is exceeded.",cols:1,fields:[table('decisionAuthorityRows','Decision Authority Matrix',[{key:'decisionType',label:'Decision Type',multiline:true},{key:'role',label:'Role / Body'},choice('authorityLevel','Authority Level',['Recommend','Approve','Escalate','Inform']),{key:'threshold',label:'Threshold / Trigger',multiline:true}],'List every recurring decision type and who holds authority over it.'),narrative('escalationPath','Escalation Path',"Describe the escalation chain when a decision exceeds a role's authority or a conflict cannot be resolved.")]},
  {id:'operating-rhythm',title:'Operating Rhythm',guidance:'Define how often governance bodies meet, who reports what to whom, and who sits on them.',cols:1,fields:[narrative('reportingCadence','Reporting Cadence','Who reports what, to whom, and how often.'),table('steeringCommitteeRows','Steering Committee',[{key:'name',label:'Name'},{key:'role',label:'Role'},{key:'organization',label:'Organization / Function'}],'Record every voting and advisory member of the steering committee.')]},
 ]},
 // New PMBOK 8 artifact — Value Delivery (woven through the lifecycle rather than confined to one
 // domain; this plan is the source of truth Benefits Tracking Register reports against).
 'Value Realization Plan':{sections:[
  {id:'overview',title:'Purpose and Governance',guidance:'Define the purpose, ownership, approval, and operating expectations for the Value Realization Plan.',cols:2,fields:[narrative('purpose','Purpose and Objectives','Describe what the value realization plan governs and the decisions it supports.'),narrative('approach','Approach and Governance','Roles, cadence, standards, approvals, escalation, and change control.')]},
  {id:'value',title:'Value Drivers and Targets',guidance:'Connect every value driver to a measurable target, an owner, and a review cadence.',cols:1,fields:[table('valueRows','Value Drivers',[{key:'valueDriver',label:'Value Driver',multiline:true},{key:'successMetric',label:'Success Metric'},{key:'measurementApproach',label:'Measurement Approach',multiline:true},{key:'baseline',label:'Baseline'},{key:'target',label:'Target'},{key:'realizationTimeline',label:'Realization Timeline'},{key:'owner',label:'Owner'},{key:'reviewCadence',label:'Review Cadence'}],'Add every value driver this project is expected to deliver.')]},
  {id:'review',title:'Review and Approval',guidance:'Document decisions, exceptions, and approval conditions.',cols:1,fields:[narrative('reviewNotes','Review Notes','Key decisions, exceptions, approvals, and next review actions.')]},
 ]},
 // New PMBOK 8 artifact — Value Delivery. Reports against Value Realization Plan's baselines/targets
 // on an ongoing (Monitoring & Controlling) cadence, mirroring how EVM Dashboard/KPI Dashboard track
 // against their own baselines in the same stage.
 'Benefits Tracking Register':{sections:[
  {id:'overview',title:'Purpose and Governance',guidance:'Define the purpose, ownership, approval, and operating expectations for the Benefits Tracking Register.',cols:2,fields:[narrative('purpose','Purpose and Objectives','Describe what the benefits tracking register governs and the decisions it supports.'),narrative('approach','Approach and Governance','Roles, cadence, standards, approvals, escalation, and change control.')]},
  {id:'benefits',title:'Benefits Tracking',guidance:'Track every benefit from baseline through realization, and flag variance as it happens.',cols:1,fields:[table('benefitRows','Benefits',[{key:'benefitId',label:'Benefit ID'},{key:'benefitDescription',label:'Benefit Description',multiline:true},{key:'metric',label:'Metric'},{key:'baselineValue',label:'Baseline Value'},{key:'targetValue',label:'Target Value'},{key:'currentValue',label:'Current Value'},{key:'variance',label:'Variance'},{key:'owner',label:'Owner'},{key:'realizationDate',label:'Realization Date',type:'date'},choice('status','Status',['Planned','Tracking','Realized','At Risk'])],'Update current value and variance each reporting cycle.')]},
  {id:'review',title:'Review and Approval',guidance:'Document decisions, exceptions, and approval conditions.',cols:1,fields:[narrative('reviewNotes','Review Notes','Key decisions, exceptions, approvals, and next review actions.')]},
 ]},
 // New PMBOK 8 artifact — AI Impact Assessment, a domain PMBOK 8 introduces to make AI/automation
 // use, its risks, and required human oversight an explicit, planned part of the project record.
 'AI and Automation Impact Assessment':{sections:[
  {id:'landscape',title:'AI and Automation Landscape',guidance:'Inventory every AI tool or automation this project uses or is considering, and where the opportunity is.',cols:1,fields:[table('aiToolRows','AI Tools In Use or Considered',[{key:'tool',label:'Tool / System',multiline:true},{key:'purpose',label:'Purpose'},choice('status','Status',['In Use','Considered','Rejected']),choice('riskLevel','Risk Level',['Low','Medium','High'])],'List every AI or automation tool touching this project, in use or under consideration.'),narrative('automationOpportunities','Automation Opportunities Identified','Where automation could reduce effort, risk, or cycle time on this project.')]},
  {id:'risk-governance',title:'Risk and Governance',guidance:"Assess the risks, ethics, and oversight this project's AI use requires.",cols:2,fields:[narrative('aiRisks','Risks of AI Use on This Project','Accuracy, bias, security, IP, vendor, and dependency risks specific to this project.'),narrative('ethicalConsiderations','Ethical Considerations','Fairness, transparency, consent, and impact on people affected by AI-driven decisions.'),narrative('dataGovernanceRequirements','Data Governance Requirements','What data feeds these tools, and what governance, privacy, or retention rules apply.'),narrative('humanOversightPlan','Human Oversight Plan','How humans review, validate, and can override AI-generated outputs.')]},
  {id:'judgment',title:'Human Judgment',guidance:'Name the decision points that must stay with a human regardless of AI capability.',cols:1,fields:[narrative('humanJudgmentDecisionPoints','Decision Points Requiring Human Judgment','Decisions that must never be delegated to an AI system on this project, and why.')]},
 ]},
 // New PMBOK 8 artifact — Sustainability, a principle PMBOK 8 elevates to require an explicit,
 // planned assessment of environmental, social, and economic impact rather than leaving it implicit.
 'Sustainability Impact Assessment':{sections:[
  {id:'impact',title:'Sustainability Impact',guidance:"Assess this project's environmental, social, and economic sustainability footprint.",cols:1,fields:[narrative('environmentalImpact','Environmental Impact Considerations',"Resource use, emissions, waste, and environmental footprint of this project's work and deliverables."),narrative('socialImpact','Social Impact Considerations','Effects on workers, communities, customers, and other people touched by this project.'),narrative('economicSustainability','Economic Sustainability Factors','Long-term cost, viability, and economic resilience of the delivered outcome.')]},
  {id:'goals',title:'Goals and Mitigation',guidance:'Set sustainability goals for this project and track the actions that get you there.',cols:1,fields:[narrative('sustainabilityGoals','Sustainability Goals for This Project','Specific, measurable sustainability goals this project commits to.'),table('mitigationActionRows','Mitigation Actions',[{key:'action',label:'Action',multiline:true},{key:'owner',label:'Owner'},{key:'targetDate',label:'Target Date',type:'date'},choice('status','Status',['Not Started','In Progress','Complete'])],'Track every action taken to mitigate a sustainability risk or impact.')]},
  {id:'reporting',title:'Reporting',guidance:'Define what sustainability reporting this project must produce and to whom.',cols:1,fields:[narrative('reportingRequirements','Reporting Requirements','What sustainability reporting is required, its frequency, and the audience.')]},
 ]},
};
export const PMP_TEMPLATES=Object.entries(lifecycle).flatMap(([group,names])=>names.map(name=>({...generic(name,group),...(overrides[name]||{}),pmpLifecycle:group})));
export const PMP_LIFECYCLE=lifecycle;
