const slug=name=>name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
const narrative=(id,label,placeholder)=>({id,label,type:'textarea',placeholder,span:2});
const table=(id,label,columns,help)=>({id,label,type:'table',columns,help,span:2});
const choice=(key,label,options)=>({key,label,type:'select',options});
const lifecycle={
 Initiation:['Benefits Management Plan','Assumption Log'],
 Planning:['Project Management Plan','Scope Management Plan','Scope Statement','WBS','WBS Dictionary','Requirements Management Plan','Requirements Traceability Matrix','Schedule Management Plan','Schedule Baseline','Cost Management Plan','Cost Baseline','Resource Management Plan','Resource Calendar','Communications Management Plan','Stakeholder Engagement Plan','Risk Management Plan','Risk Register','Risk Report','Procurement Management Plan','Quality Management Plan','Configuration Management Plan','Change Management Plan'],
 Execution:['Issue Log','Decision Log','Action Item Log','RAID Log','Change Request','Procurement Documents','Vendor Evaluation','Lessons Learned Register','Team Performance Reviews'],
 'Monitoring & Controlling':['Status Report','Executive Dashboard','Variance Report','EVM Dashboard','Milestone Report','Change Log','Quality Audit','Risk Review','KPI Dashboard'],
 Closing:['Final Project Report','Lessons Learned Report','Project Closure Report','Transition Plan','Acceptance Signoff','Benefits Realization Review','Archive Checklist']
};
const logColumns=[{key:'item',label:'Item',multiline:true},{key:'owner',label:'Owner'},{key:'dueDate',label:'Due Date',type:'date'},choice('status','Status',['Not Started','In Progress','Blocked','Complete']),{key:'notes',label:'Notes',multiline:true}];
function generic(name,group){return{id:slug(name),name,phase:group,pmpLifecycle:group,documentType:name.includes('Plan')?'Plan':name.includes('Report')?'Report':name.includes('Log')||name.includes('Register')?'Register':'Project Document',icon:'◇',desc:`Create and maintain the project ${name.toLowerCase()} as a governed, project-connected workspace.`,sections:[{id:'overview',title:'Purpose and Governance',guidance:`Define the purpose, ownership, approval, and operating expectations for the ${name}.`,cols:2,fields:[narrative('purpose','Purpose and Objectives',`Describe what the ${name.toLowerCase()} governs and the decisions it supports.`),narrative('approach','Approach and Governance','Roles, cadence, standards, approvals, escalation, and change control.')]},{id:'register',title:'Managed Items',guidance:'Maintain structured, accountable records and current status.',cols:1,fields:[table('items',name,logColumns,'Add unlimited records and keep ownership, dates, status, and evidence current.')]},{id:'review',title:'Review and Approval',guidance:'Document decisions, exceptions, and approval conditions.',cols:1,fields:[narrative('reviewNotes','Review Notes','Key decisions, exceptions, approvals, and next review actions.')]}]};}
const overrides={
 'Benefits Management Plan':{sections:[{id:'benefits',title:'Benefits Profile',guidance:'Define measurable benefits, ownership, timing, and verification.',cols:1,fields:[table('benefitRows','Benefits',[{key:'benefit',label:'Benefit',multiline:true},{key:'metric',label:'Metric'},{key:'baseline',label:'Baseline'},{key:'target',label:'Target'},{key:'owner',label:'Benefit Owner'},{key:'realizationDate',label:'Realization Date',type:'date'},choice('status','Status',['Planned','Tracking','Realized','At Risk'])],'Connect every benefit to a measurable outcome.')] }]},
 'Assumption Log':{sections:[{id:'assumptions',title:'Assumption Log',guidance:'Validate assumptions early and track their effect on project decisions.',cols:1,fields:[table('assumptionRows','Assumptions',[{key:'assumption',label:'Assumption',multiline:true},{key:'basis',label:'Basis',multiline:true},{key:'owner',label:'Owner'},{key:'validationDate',label:'Validation Date',type:'date'},choice('status','Status',['Open','Validated','Invalidated']),{key:'impact',label:'Impact',multiline:true}],'Escalate invalidated assumptions that affect baselines.')] }]},
 'WBS':{sections:[{id:'wbs',title:'Work Breakdown Structure',guidance:'Decompose scope hierarchically into manageable work packages.',cols:1,fields:[table('wbsRows','WBS hierarchy',[{key:'wbsId',label:'WBS ID'},{key:'level',label:'Level',type:'number'},{key:'parentId',label:'Parent WBS ID'},{key:'workPackage',label:'Deliverable / Work Package',multiline:true},{key:'owner',label:'Owner'},{key:'acceptance',label:'Acceptance Criteria',multiline:true}],'Use parent IDs and levels to preserve hierarchy.')] }]},
 'Requirements Traceability Matrix':{sections:[{id:'requirements',title:'Requirements Traceability Matrix',guidance:'Trace every approved requirement from source through validation and acceptance.',cols:1,fields:[table('requirementRows','Requirements',[{key:'requirementId',label:'Requirement ID'},{key:'requirement',label:'Requirement',multiline:true},{key:'source',label:'Source'},{key:'owner',label:'Owner'},choice('status','Status',['Proposed','Approved','Implemented','Verified','Rejected']),{key:'test',label:'Test / Verification',multiline:true},{key:'acceptance',label:'Acceptance Evidence',multiline:true}],'Maintain stable IDs through the project lifecycle.')] }]},
 'Schedule Baseline':{sections:[{id:'schedule',title:'Schedule Baseline',guidance:'Preserve approved dates and dependencies for performance comparison.',cols:1,fields:[table('scheduleRows','Baseline milestones',[{key:'milestone',label:'Milestone'},{key:'start',label:'Start',type:'date'},{key:'finish',label:'Finish',type:'date'},{key:'duration',label:'Duration'},{key:'dependencies',label:'Dependencies'},{key:'owner',label:'Owner'},choice('status','Status',['Not Started','In Progress','Complete','Delayed'])],'Changes should follow approved change control.')] }]},
 'Risk Register':{sections:[{id:'risks',title:'Risk Register',guidance:'Assess exposure consistently and maintain response ownership.',cols:1,fields:[table('riskRows','Project risks',[{key:'riskId',label:'Risk ID'},{key:'risk',label:'Risk',multiline:true},{key:'probability',label:'Probability',type:'number'},{key:'impact',label:'Impact',type:'number'},{key:'exposure',label:'Exposure',type:'number'},{key:'owner',label:'Owner'},{key:'response',label:'Response',multiline:true},choice('status','Status',['Open','Monitoring','Triggered','Closed'])],'Exposure may be recorded as probability × impact using the project scoring convention.')] }]},
 'EVM Dashboard':{calculate:values=>{const pv=Number(values.pv)||0,ev=Number(values.ev)||0,ac=Number(values.ac)||0,bac=Number(values.bac)||0,cpi=ac?ev/ac:0,spi=pv?ev/pv:0,eac=cpi?bac/cpi:0;return{CPI:cpi.toFixed(2),SPI:spi.toFixed(2),CV:(ev-ac).toFixed(2),SV:(ev-pv).toFixed(2),EAC:eac.toFixed(2),ETC:(eac-ac).toFixed(2),VAC:(bac-eac).toFixed(2)};},sections:[{id:'evm-inputs',title:'EVM Inputs',guidance:'Use values from the approved cost and schedule baselines.',cols:2,fields:[{id:'pv',label:'Planned Value (PV)',type:'text'},{id:'ev',label:'Earned Value (EV)',type:'text'},{id:'ac',label:'Actual Cost (AC)',type:'text'},{id:'bac',label:'Budget at Completion (BAC)',type:'text'}]},{id:'forecast',title:'Calculated Performance and Interpretation',guidance:'Review calculated indicators, then explain drivers, forecast confidence, and corrective action.',cols:2,fields:[{id:'CPI',label:'Cost Performance Index (CPI)',type:'text'},{id:'SPI',label:'Schedule Performance Index (SPI)',type:'text'},{id:'CV',label:'Cost Variance (CV)',type:'text'},{id:'SV',label:'Schedule Variance (SV)',type:'text'},{id:'EAC',label:'Estimate at Completion (EAC)',type:'text'},{id:'ETC',label:'Estimate to Complete (ETC)',type:'text'},{id:'VAC',label:'Variance at Completion (VAC)',type:'text'},narrative('interpretation','Interpretation','Explain CPI, SPI, variances, forecast, and management action.')]}]}
};
export const PMP_TEMPLATES=Object.entries(lifecycle).flatMap(([group,names])=>names.map(name=>({...generic(name,group),...(overrides[name]||{}),pmpLifecycle:group})));
export const PMP_LIFECYCLE=lifecycle;
