export const SUITE_STATES={ACTIVE:'active',TRIAL:'trial',LOCKED:'locked',COMING_SOON:'coming_soon',EXPIRED:'expired'};
export const SUITES=[
 {id:'operational-excellence',name:'Operational Excellence',status:SUITE_STATES.ACTIVE,description:'Lean Six Sigma, DMAIC, quality workspaces, datasets, evidence, and statistical analysis.',entryPath:'/projects',methodologies:['lean-six-sigma','dmaic'],audience:'Quality engineers, Lean Six Sigma professionals, and operations leaders.',workflows:['DMAIC project execution','Connected data and analysis','Evidence-based reporting'],tools:['Control charts','Capability analysis','ANOVA and regression','MSA and DOE'],documents:['Project Charter','SIPOC and VOC','Measure workspaces','FMEA and Control Plan'],benefits:['Keep every analysis connected to its project','Reuse evidence in documents and reports','Move from baseline to sustained control'],outputs:['Executive DMAIC report','Capability study','Evidence library','Project Binder']},
 {id:'project-management',name:'Project Management',status:SUITE_STATES.ACTIVE,description:'Professional project initiation, planning, execution, monitoring, and closeout.',entryPath:'/templates',methodologies:['pmp','hybrid'],audience:'Project managers, PMO leaders, sponsors, and delivery teams.',workflows:['Initiation through closeout','Risk and stakeholder management','Executive status reporting'],tools:['Project dashboard','Dataset and analysis references','Report Builder','Project Binder'],documents:['Business Case and Charter','Risk and stakeholder registers','Plans and status reports','Closure documentation'],benefits:['Maintain one source of truth','Connect evidence to decisions','Preserve governance and approvals'],outputs:['Executive status report','Project management plan','Decision and risk history','Closure package']},
 {id:'supply-chain',name:'Supply Chain',status:SUITE_STATES.COMING_SOON,description:'Reserved for connected planning, sourcing, logistics, and supplier performance.'},
 {id:'healthcare',name:'Healthcare',status:SUITE_STATES.COMING_SOON,description:'Reserved for healthcare quality, safety, and operational improvement.'},
 {id:'manufacturing',name:'Manufacturing',status:SUITE_STATES.COMING_SOON,description:'Reserved for production performance and manufacturing excellence.'},
 {id:'technology',name:'Technology',status:SUITE_STATES.COMING_SOON,description:'Reserved for technology delivery, reliability, and transformation.'},
 {id:'financial-services',name:'Financial Services',status:SUITE_STATES.COMING_SOON,description:'Reserved for financial operations, controls, and transformation.'},
 {id:'construction',name:'Construction',status:SUITE_STATES.LOCKED,description:'Reserved for construction delivery, controls, and field operations.'}
];
export const getSuite=id=>SUITES.find(suite=>suite.id===id);
