import {createDecisionRule} from '../foundation/guidance';

const recommendation=(id,priority,when,methodId,explanation,nextSteps=[])=>createDecisionRule({id:`wave3-${id}`,version:'1.0.0',priority,when,recommendation:{methodId},explanation,nextSteps});

export const WAVE3_DECISION_RULES=Object.freeze([
 recommendation('paired-two-groups',100,context=>context.responseType==='continuous'&&context.groupCount===2&&context.structure==='paired','paired-t','Use paired inference when the same subjects or matched units supply both measurements.',['Review the distribution and outliers of paired differences.','Use Wilcoxon signed-rank or the sign test when paired-difference assumptions are not defensible.']),
 recommendation('independent-two-groups',95,context=>context.responseType==='continuous'&&context.groupCount===2&&context.structure!=='paired','welch-two-sample-t','Welch inference is the default for two independent means because it does not require equal group variances.',['Review independence, group distributions, outliers, and sample sizes.','Use Mann-Whitney when an ordinal/shift interpretation is appropriate and parametric assumptions are not defensible.']),
 recommendation('independent-multiple-groups',90,context=>context.responseType==='continuous'&&context.groupCount>=3&&context.structure!=='repeated','one-way-anova','One-way ANOVA evaluates whether at least one independent group mean differs.',['Use Tukey HSD after an equal-variance ANOVA.','Use Games-Howell when variance equality is not supported.','Use Kruskal-Wallis with multiplicity-adjusted Dunn comparisons for an appropriate rank-based alternative.']),
 recommendation('repeated-multiple-groups',90,context=>context.responseType==='continuous'&&context.groupCount>=3&&context.structure==='repeated','repeated-measures-anova','Repeated-measures ANOVA preserves within-subject dependence.',['Map a subject identifier and ordered condition.','Review sphericity and use a supported correction or Friedman alternative when needed.']),
 recommendation('categorical-association',90,context=>context.responseType==='categorical'&&context.predictorType==='categorical','chi-square','A contingency analysis evaluates association between categorical variables.',['Use Fisher exact for a sparse 2×2 table.','Review standardized residuals to identify cells contributing to association.']),
 recommendation('continuous-relationship',80,context=>context.responseType==='continuous'&&context.predictorType==='continuous'&&!context.binaryResponse,'linear-regression','Linear regression estimates the conditional relationship and supports prediction with diagnostics.',['Review residuals, leverage, Cook’s distance, and multicollinearity.','Do not remove influential observations automatically.']),
 recommendation('binary-model',85,context=>context.binaryResponse===true,'logistic-regression','Binary logistic regression models outcome probability and odds.',['Verify both outcome classes have adequate observations.','Review convergence and separation diagnostics before interpreting odds ratios.']),
 recommendation('doe',100,context=>context.experimental===true,'full-factorial-doe','A designed experiment estimates causal factor effects when randomization, execution, and model assumptions are credible.',['Select a full or explicitly aliased fractional design.','Randomize with a recorded seed.','Complete optimization with a confirmation run.']),
]);
