import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import './DocumentReport.css';
// eslint-disable-next-line import/no-webpack-loader-syntax
import documentReportCss from '!!raw-loader!./DocumentReport.css';
// eslint-disable-next-line import/no-webpack-loader-syntax
import wbsTreeDiagramCss from '!!raw-loader!./WBSTreeDiagram.css';
// eslint-disable-next-line import/no-webpack-loader-syntax
import ctqTreeDiagramCss from '!!raw-loader!./CTQTreeDiagram.css';

const text=value=>String(value??'').replace(/<[^>]*>/g,'').trim();

function ReportTable({field,rows}){
  if(!rows.length)return <p className="dr-empty">No entries recorded.</p>;
  return <div className="dr-table-scroll"><table><thead><tr>{field.columns.map(column=><th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.id||index}>{field.columns.map(column=><td key={column.key}>{text(row[column.key])||'—'}</td>)}</tr>)}</tbody></table></div>;
}

function ReportFlow({nodes}){
  if(!nodes.length)return <p className="dr-empty">No process steps recorded.</p>;
  return <ol className="dr-flow">{nodes.map(node=><li key={node.id}><strong>{node.kind}: {text(node.step)||'Untitled step'}</strong>{text(node.owner)&&<span> · Owner: {text(node.owner)}</span>}{text(node.department)&&<span> · {text(node.department)}</span>}{(text(node.input)||text(node.output))&&<span> · {text(node.input)&&`In: ${text(node.input)}`}{text(node.input)&&text(node.output)&&' · '}{text(node.output)&&`Out: ${text(node.output)}`}</span>}</li>)}</ol>;
}

function ReportField({field,value}){
  if(field.type==='table')return <div className="dr-field wide"><h4>{field.label}</h4><ReportTable field={field} rows={Array.isArray(value)?value:[]}/></div>;
  if(field.type==='flow')return <div className="dr-field wide"><h4>{field.label}</h4><ReportFlow nodes={Array.isArray(value)?value:[]}/></div>;
  if(field.type==='tree'){
    const branches=Array.isArray(value)?value:[];
    return <div className="dr-field wide"><h4>{field.label}</h4>{branches.length?<ol className="dr-flow">{branches.map(branch=><li key={branch.id}>{[branch.need,branch.driver,branch.ctq,branch.specification].filter(Boolean).join(' → ')||'Untitled branch'}</li>)}</ol>:<p className="dr-empty">No branches recorded.</p>}</div>;
  }
  return <div className={`dr-field ${field.span?'wide':''}`}><h4>{field.label}</h4><p>{text(value)||'—'}</p></div>;
}

// The full multi-section, print-quality rendering of a DocumentWorkspace record: every section's
// every field, not just whichever section happens to be the active one on screen — and, when
// given a diagram, that diagram too. Deliberately a pure function of its props (no DOM
// visibility, no ref, no browser event dependency): this is the single source of truth for what
// "the document" looks like as output, callable directly (see renderReportDocument below) by
// anything that needs it — Print, Export PDF, or any other future consumer — without depending on
// a hidden node's on-screen visibility state.
export default function DocumentReport({template,project,record,phase,diagram}){
  const today=new Date().toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'});
  return <div className="dr-report">
    <header className="dr-header"><div><span>{phase}</span><h1>{template.name}</h1><p>{project.name}</p></div><div className="dr-meta"><span>Generated {today}</span><span>Doc: SSP-{template.id.slice(0,8).toUpperCase()}</span></div></header>
    {diagram&&<div className="dr-diagram">{diagram}</div>}
    {template.sections.map(section=><section key={section.id||section.title} className="dr-section"><h2>{section.title}</h2><div className="dr-grid">{section.fields.map(field=><ReportField key={field.id} field={field} value={record.values[field.id]}/>)}</div></section>)}
    <footer className="dr-footer"><span>Generated by Aureqin</span><span>Confidential — Internal Use Only</span></footer>
  </div>;
}

const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));

// The exact source text of every stylesheet the report/diagram components author (.dr-*, .wbs-*,
// .ctq-*), imported at build time via raw-loader rather than read back off `document.styleSheets`
// at call time. Reading live stylesheets was the actual cause of the blank-print-page bug: in a
// CRA dev build, style-loader's injected <style> tags can have CSSStyleSheet.cssRules that are
// empty or throw when read before the sheet has fully attached, so collectDocumentCss() was
// silently returning near-nothing even though the CSS itself was loaded and working for the live
// app. Importing the .css files' own text guarantees the isolated print/export document gets the
// real rules regardless of that runtime timing — and it's still exactly one place these styles are
// authored: this file only re-exports the same .css files already imported above for the live app.
export function collectDocumentCss(){
  return [documentReportCss,wbsTreeDiagramCss,ctqTreeDiagramCss].join('\n');
}

// Renders the full report to a standalone HTML document string — a pure function of
// (template, project, record, phase, diagram) with no dependency on any component being mounted,
// visible, or in any particular state. Callers (Print, Export PDF) each hand this string to their
// own isolated rendering target (an iframe, an off-screen container) rather than toggling
// visibility on a node shared with the live editor, so there's never ambiguity about which DOM
// tree is actually being printed or captured.
export function renderReportDocument({template,project,record,phase,diagram}){
  const markup=renderToStaticMarkup(<DocumentReport template={template} project={project} record={record} phase={phase} diagram={diagram}/>);
  const css=collectDocumentCss();
  const title=escapeHtml(`${template.name} — ${project.name}`);
  return `<!doctype html><html><head><meta charset="utf-8"><title>${title}</title><style>${css}\nbody{margin:0;background:#fff}@page{margin:12mm}</style></head><body>${markup}</body></html>`;
}
