import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import SavedAnalysisResult,{hasSavedResult} from './SavedAnalysisResult';
import {analysesWithProjectPlacements,buildProjectReviewModel,compactAnalysisSummary,openResultSearch,placementDraftForAnalysis,reportItemForAnalysis,routeFor} from './ProjectBinder';
import {connectAnalysisToProject,createProjectPlacement} from '../foundation/projectPlacement';

const saved=(toolId='regression')=>({id:`${toolId}-canonical`,projectId:'project-1',toolId,title:`Saved ${toolId}`,phase:toolId==='doe'?'Improve':'Analyze',createdAt:'2026-08-10T00:00:00.000Z',datasetIds:['dataset-1'],datasetVersionIds:['version-7'],variableMapping:{response:'Yield',predictor:'Temperature'},inputConfiguration:{alpha:.05},result:{coefficients:[{term:'Temperature',estimate:2.4}],diagnostics:{rSquared:.91}},interpretation:'Persisted interpretation'});

test.each(['regression','control-chart','capability','anova','doe'])('%s saved artifact uses canonical placement and report identity',toolId=>{const analysis=saved(toolId),draft=placementDraftForAnalysis('project-1',analysis,false);expect(draft.artifactId).toBe(analysis.id);expect(draft.analysis).toBe(analysis);expect(draft.includeReport).toBe(false);expect(draft.reportItem.provenance.analysisId).toBe(analysis.id);expect(draft.reportItem.structuredOutput).toBe(analysis.result)});
test('Project Binder routes a placed Lean artifact to its canonical saved editor',()=>{expect(routeFor('project-1',{kind:'artifact',sourceId:'lean canonical/id',toolId:'lean-enterprise'})).toBe('/tool/lean-enterprise?openLean=lean%20canonical%2Fid')});
test('Open Result renders persisted payload without a tool route or recalculation',()=>{const analysis=saved(),markup=renderToStaticMarkup(<SavedAnalysisResult analysis={analysis} onClose={()=>{}}/>);expect(markup).toContain('Read-only canonical result');expect(markup).toContain('regression-canonical');expect(markup).toContain('Temperature');expect(markup).not.toContain('/tool/regression')});
test('Open Result restores the exact saved manual analysis input',()=>{const analysis={...saved('hypothesis'),inputConfiguration:{testId:'1t',mu0:10,manualInputs:{manualD1:'10.1, 10.4\n10.7'}}},markup=renderToStaticMarkup(<SavedAnalysisResult analysis={analysis} onClose={()=>{}}/>);expect(markup).toContain('10.1, 10.4');expect(markup).toContain('10.7');expect(markup).toContain('Mu0');});
test('legacy incomplete result shows an explicit limitation',()=>{const analysis={id:'legacy-1',toolId:'anova',title:'Legacy ANOVA'},markup=renderToStaticMarkup(<SavedAnalysisResult analysis={analysis} onClose={()=>{}}/>);expect(hasSavedResult(analysis)).toBe(false);expect(markup).toContain('Full saved-result rendering is unavailable');expect(markup).toContain('will not reconstruct it from the current worksheet')});
test('report payload is additive and leaves canonical result unchanged',()=>{const analysis=saved(),before=JSON.stringify(analysis),item=reportItemForAnalysis(analysis);expect(item.structuredOutput).toBe(analysis.result);expect(item.phase).toBe('Analyze');expect(JSON.stringify(analysis)).toBe(before)});
test('OE corrective actions appear as concise Binder action entries with a stable reopen route',()=>{const project={id:'project-1',suite:'operational-excellence'},action={id:'ca-1',title:'Eliminate seal leak',status:'Action in Progress',lifecycle_phase:'Improve',content:{item_type:'oe-corrective-action',problemStatement:'Leak rate exceeds threshold',actionDescription:'Lock torque settings'}};const model=buildProjectReviewModel(project,{correctiveActions:[action]});const item=model.items.find(entry=>entry.sourceId==='ca-1');expect(item.kind).toBe('corrective-action');expect(item.stage).toBe('Decisions / Actions');expect(routeFor('project-1',item)).toBe('/projects/project-1?tab=corrective-actions&correctiveAction=ca-1')});
test('Binder model uses native PM lifecycle and does not invent DMAIC stages',()=>{const model=buildProjectReviewModel({id:'pm-1',suiteId:'project-management',methodology:'project-management',currentPhase:'Planning'},{documents:[{id:'pm-plan',title:'PM Plan',phase:'Planning',values:{summary:'Approved plan'}}],analyses:[],evidence:[],artifacts:[],datasets:[]});expect(model.narrativeContract.sequence).toEqual(['Initiation','Planning','Execution','Monitoring & Controlling','Closing']);expect(model.items[0].phase).toBe('Planning');expect(model.narrativeContract.sequence).not.toContain('Define')});
test('Binder groups saved documents, analyses, and tool outputs by their canonical DMAIC phase',()=>{const model=buildProjectReviewModel({id:'oe-1',suiteId:'operational-excellence'},{documents:[{id:'document-control-plan',templateId:'control-plan',title:'Control Plan'}],analyses:[{id:'analysis-capability',toolId:'capability',title:'Capability'}],artifacts:[{id:'tool-doe-output',toolId:'doe',title:'DOE Output'}]});expect(model.items.map(item=>[item.id,item.phase])).toEqual(expect.arrayContaining([['document-control-plan','Control'],['analysis-capability','Measure'],['tool-doe-output','Improve']]))});
test('project placement connects one canonical hypothesis analysis to Binder without duplicating the report identity',()=>{const initial={id:'analysis-1t',projectId:'',toolId:'hypothesis',title:'1-Sample t-Test',result:{t:2.4,p:.03}},connected=connectAnalysisToProject(initial,{projectId:'project-1',organizationId:'org-1'}),placement=createProjectPlacement({projectId:'project-1',artifactId:connected.id,location:{suite:'Operational Excellence',suiteId:'operational-excellence',phase:'Analyze',phaseId:'analyze',workflowCluster:'Hypothesis & Comparison',workflowClusterId:'hypothesis-comparison'},reportIncluded:true}),analyses=analysesWithProjectPlacements([connected],[placement],'project-1'),documents=['hypothesis-plan','fishbone-workspace','five-whys'].map(templateId=>({id:`document-${templateId}`,templateId,title:templateId,phase:'Analyze'})),model=buildProjectReviewModel({id:'project-1',suiteId:'operational-excellence'},{documents,analyses});expect(connected.id).toBe(initial.id);expect(analyses).toHaveLength(1);expect(model.items.filter(item=>item.sourceId===initial.id)).toHaveLength(1);expect(model.items.find(item=>item.sourceId===initial.id)).toEqual(expect.objectContaining({kind:'analysis',phase:'Analyze',workflowCluster:'Hypothesis & Comparison'}));expect(model.items.filter(item=>item.phase==='Analyze')).toHaveLength(4);expect(reportItemForAnalysis(analyses[0]).provenance.analysisId).toBe(initial.id)});
test('Binder uses a compact statistical summary and a stable canonical open-result query',()=>{const analysis={id:'analysis-1t',title:'1-Sample t-Test',result:{pValue:.0019},interpretation:'A deliberately long interpretation that belongs in the full report, not the Binder summary.'};expect(compactAnalysisSummary(analysis)).toBe('1-Sample t-Test · Statistically significant · p = 0.0019');expect(compactAnalysisSummary(analysis)).not.toContain('deliberately long');expect(openResultSearch(analysis.id)).toEqual({openResult:'analysis-1t'})});
