import React,{useEffect,useState} from 'react';
import {useAuth} from '../context/AuthContext';
import {useInteractions} from '../context/InteractionContext';
import {pmRepository} from '../repositories/pmRepository';
import AssetUploadModal from './AssetUploadModal';
import LinkedAssetsList from './LinkedAssetsList';
import './ProjectActions.css';

const EMPTY={title:'',description:'',owner:'',dueDate:'',priority:'Medium',status:'Not Started'};
const PRIORITIES=['Low','Medium','High','Critical'];
const STATUSES=['Not Started','In Progress','Blocked','Complete'];
const detail=action=>({...EMPTY,...(action.content||{}),title:action.title||'',priority:action.priority||'Medium',status:action.status||'Not Started',dueDate:action.content?.due_date||action.content?.dueDate||''});
export const isActionOverdue=(action,now=new Date())=>{const{dueDate,status}=detail(action);if(!dueDate||status==='Complete')return false;const due=new Date(`${dueDate}T23:59:59.999`);return !Number.isNaN(due.getTime())&&due<now};
const errorMessage=error=>{const raw=error?.message||'';if(raw.includes('pm-update-conflict'))return'This action changed since you opened it. Reload Actions, review the latest version, and try again.';if(raw.includes('pm-actions-not-found'))return'This action no longer exists. Reload Actions to refresh the list.';return raw||'Project actions could not be loaded.'};

export default function ProjectActions({project}){
  const{user,profile}=useAuth();
  const{confirm,toast}=useInteractions();
  const[actions,setActions]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editor,setEditor]=useState(null),[saving,setSaving]=useState(false),[deletingId,setDeletingId]=useState(''),[attachTarget,setAttachTarget]=useState(null);
  const load=async()=>{setLoading(true);setError('');try{setActions(await pmRepository.actions.list(project.id))}catch(nextError){setError(errorMessage(nextError))}finally{setLoading(false)}};
  useEffect(()=>{let active=true;setLoading(true);setError('');pmRepository.actions.list(project.id).then(rows=>{if(active)setActions(rows)}).catch(nextError=>{if(active)setError(errorMessage(nextError))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[project.id]);

  const beginCreate=()=>setEditor({record:null,values:{...EMPTY}});
  const beginEdit=action=>setEditor({record:action,values:detail(action)});
  const change=(field,value)=>setEditor(current=>({...current,values:{...current.values,[field]:value}}));
  const reload=()=>{setEditor(null);load()};
  const save=async event=>{event.preventDefault();if(!editor||saving)return;setSaving(true);setError('');const values=editor.values,content={description:values.description.trim(),owner:values.owner.trim(),due_date:values.dueDate};try{let saved;if(editor.record){const{created_by,content:previousContent,...existing}=editor.record;saved=await pmRepository.actions.update({...existing,project_id:project.id,organization_id:project.organizationId||profile?.default_organization_id,title:values.title.trim(),priority:values.priority,status:values.status,methodology:project.methodology||'pmp',lifecycle_phase:existing.lifecycle_phase||project.currentPhase||'Planning',content});setActions(current=>current.map(action=>action.id===saved.id?saved:action))}else{saved=await pmRepository.actions.create({project_id:project.id,organization_id:project.organizationId||profile?.default_organization_id,created_by:user?.id,title:values.title.trim(),priority:values.priority,status:values.status,methodology:project.methodology||'pmp',lifecycle_phase:project.currentPhase||'Planning',content});setActions(current=>[saved,...current])}setEditor(null);toast(editor.record?'Action updated.':'Action created.')}catch(nextError){setError(errorMessage(nextError))}finally{setSaving(false)}};
  const remove=async action=>{if(!await confirm({title:'Delete action?',message:`“${action.title}” will be permanently removed from this project.`,confirmLabel:'Delete Action',destructive:true}))return;setDeletingId(action.id);setError('');try{await pmRepository.actions.remove(action.id);setActions(current=>current.filter(item=>item.id!==action.id));toast('Action deleted.')}catch(nextError){setError(errorMessage(nextError))}finally{setDeletingId('')}};

  return <section className="pm-actions" aria-labelledby="pm-actions-title">
    <header><div><span>PROJECT MANAGEMENT</span><h2 id="pm-actions-title">Action Items</h2><p>Track accountable work, deadlines, priority, and delivery status.</p></div><button type="button" className="btn-primary" onClick={beginCreate}>+ Add Action</button></header>
    {error&&<div className="pm-action-error" role="alert"><span>{error}</span><button type="button" onClick={reload}>Reload Actions</button></div>}
    {loading?<div className="pm-action-state" role="status">Loading project actions…</div>:actions.length?<div className="pm-action-list">{actions.map(action=>{const values=detail(action),overdue=isActionOverdue(action);return <article key={action.id} className={overdue?'overdue':''}><header><div><span className={`pm-action-priority priority-${values.priority.toLowerCase()}`}>{values.priority} priority</span><h3>{values.title}</h3></div><span className={`pm-action-status status-${values.status.toLowerCase().replace(/\s+/g,'-')}`}>{values.status}</span></header><p>{values.description||'No description provided.'}</p><dl><div><dt>Owner</dt><dd>{values.owner||'Unassigned'}</dd></div><div><dt>Due date</dt><dd>{values.dueDate?new Date(`${values.dueDate}T00:00:00`).toLocaleDateString():'Not scheduled'}{overdue&&<strong>Overdue</strong>}</dd></div></dl><LinkedAssetsList project={project} artifactType="action" artifactId={action.id} /><footer><button type="button" aria-label={`Attach file to ${values.title}`} onClick={()=>setAttachTarget(action)}>📎 Attach</button><button type="button" onClick={()=>beginEdit(action)}>Edit</button><button type="button" className="danger" disabled={deletingId===action.id} onClick={()=>remove(action)}>{deletingId===action.id?'Deleting…':'Delete'}</button></footer></article>})}</div>:<div className="pm-action-empty"><div>◇</div><h3>No action items yet</h3><p>Add the first action to establish ownership, priority, and a delivery date.</p><button type="button" className="btn-primary" onClick={beginCreate}>Add First Action</button></div>}
    {editor&&<div className="pm-action-editor" role="dialog" aria-modal="true" aria-labelledby="pm-action-editor-title"><button type="button" className="pm-action-backdrop" aria-label="Close action editor" onClick={()=>!saving&&setEditor(null)}/><form onSubmit={save}><header><div><span>{editor.record?'EDIT ACTION':'NEW ACTION'}</span><h2 id="pm-action-editor-title">{editor.record?'Update action item':'Add action item'}</h2></div><button type="button" aria-label="Close action editor" onClick={()=>setEditor(null)} disabled={saving}>×</button></header><label>Title<input required value={editor.values.title} onChange={event=>change('title',event.target.value)}/></label><label>Owner<input value={editor.values.owner} onChange={event=>change('owner',event.target.value)}/></label><label className="wide">Description<textarea rows="3" value={editor.values.description} onChange={event=>change('description',event.target.value)}/></label><label>Due date<input type="date" value={editor.values.dueDate} onChange={event=>change('dueDate',event.target.value)}/></label><label>Priority<select value={editor.values.priority} onChange={event=>change('priority',event.target.value)}>{PRIORITIES.map(value=><option key={value}>{value}</option>)}</select></label><label>Status<select value={editor.values.status} onChange={event=>change('status',event.target.value)}>{STATUSES.map(value=><option key={value}>{value}</option>)}</select></label><footer><button type="button" className="btn-secondary" disabled={saving} onClick={()=>setEditor(null)}>Cancel</button><button type="submit" className="btn-primary" disabled={saving}>{saving?'Saving…':editor.record?'Save Changes':'Create Action'}</button></footer></form></div>}
    {attachTarget&&<AssetUploadModal project={project} defaultLink={{artifactType:'action',artifactId:attachTarget.id,artifactLabel:attachTarget.title}} onClose={()=>setAttachTarget(null)} onUploaded={()=>setAttachTarget(null)} />}
  </section>;
}
