import React,{useEffect,useState} from 'react';
import {useAuth} from '../context/AuthContext';
import {useInteractions} from '../context/InteractionContext';
import {pmRepository} from '../repositories/pmRepository';
import './ProjectIssues.css';

const EMPTY={title:'',description:'',owner:'',priority:'Medium',status:'Open',dateIdentified:'',targetResolutionDate:'',resolution:''};
const PRIORITIES=['Low','Medium','High','Critical'];
const STATUSES=['Open','In Progress','Blocked','Resolved','Closed'];
const today=()=>{const now=new Date(),offset=now.getTimezoneOffset()*60000;return new Date(now-offset).toISOString().slice(0,10)};
const detail=issue=>({...EMPTY,...(issue.content||{}),title:issue.title||'',priority:issue.priority||'Medium',status:issue.status||'Open',dateIdentified:issue.content?.date_identified||issue.content?.dateIdentified||'',targetResolutionDate:issue.content?.target_resolution_date||issue.content?.targetResolutionDate||'',resolution:issue.content?.resolution||issue.content?.corrective_action||''});
export const isIssueOverdue=(issue,now=new Date())=>{const{targetResolutionDate,status}=detail(issue);if(!targetResolutionDate||['Resolved','Closed'].includes(status))return false;const target=new Date(`${targetResolutionDate}T23:59:59.999`);return !Number.isNaN(target.getTime())&&target<now};
const errorMessage=error=>{const raw=error?.message||'';if(raw.includes('pm-update-conflict'))return'This issue changed since you opened it. Reload Issues, review the latest version, and try again.';return raw||'Project issues could not be loaded.'};

export default function ProjectIssues({project}){
  const{user,profile}=useAuth();
  const{confirm,toast}=useInteractions();
  const[issues,setIssues]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editor,setEditor]=useState(null),[saving,setSaving]=useState(false),[deletingId,setDeletingId]=useState('');
  const load=async()=>{setLoading(true);setError('');try{setIssues(await pmRepository.issues.list(project.id))}catch(nextError){setError(errorMessage(nextError))}finally{setLoading(false)}};
  useEffect(()=>{let active=true;setLoading(true);setError('');pmRepository.issues.list(project.id).then(rows=>{if(active)setIssues(rows)}).catch(nextError=>{if(active)setError(errorMessage(nextError))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[project.id]);

  const beginCreate=()=>setEditor({record:null,values:{...EMPTY,dateIdentified:today()}});
  const beginEdit=issue=>setEditor({record:issue,values:detail(issue)});
  const change=(field,value)=>setEditor(current=>({...current,values:{...current.values,[field]:value}}));
  const reload=()=>{setEditor(null);load()};
  const save=async event=>{event.preventDefault();if(!editor||saving)return;setSaving(true);setError('');const values=editor.values,content={description:values.description.trim(),owner:values.owner.trim(),date_identified:values.dateIdentified,target_resolution_date:values.targetResolutionDate,resolution:values.resolution.trim()};try{let saved;if(editor.record){const{created_by,content:previousContent,...existing}=editor.record;saved=await pmRepository.issues.update({...existing,project_id:project.id,organization_id:project.organizationId||profile?.default_organization_id,title:values.title.trim(),priority:values.priority,status:values.status,methodology:project.methodology||'pmp',lifecycle_phase:existing.lifecycle_phase||project.currentPhase||'Execution',content});setIssues(current=>current.map(issue=>issue.id===saved.id?saved:issue))}else{saved=await pmRepository.issues.create({project_id:project.id,organization_id:project.organizationId||profile?.default_organization_id,created_by:user?.id,title:values.title.trim(),priority:values.priority,status:values.status,methodology:project.methodology||'pmp',lifecycle_phase:project.currentPhase||'Execution',content});setIssues(current=>[saved,...current])}setEditor(null);toast(editor.record?'Issue updated.':'Issue created.')}catch(nextError){setError(errorMessage(nextError))}finally{setSaving(false)}};
  const remove=async issue=>{if(!await confirm({title:'Delete issue?',message:`“${issue.title}” will be permanently removed from this project.`,confirmLabel:'Delete Issue',destructive:true}))return;setDeletingId(issue.id);setError('');try{await pmRepository.issues.remove(issue.id);setIssues(current=>current.filter(item=>item.id!==issue.id));toast('Issue deleted.')}catch(nextError){setError(errorMessage(nextError))}finally{setDeletingId('')}};

  return <section className="pm-issues" aria-labelledby="pm-issues-title">
    <header><div><span>PROJECT MANAGEMENT</span><h2 id="pm-issues-title">Project Issues</h2><p>Track active problems, accountable resolution, and corrective action.</p></div><button type="button" className="btn-primary" onClick={beginCreate}>+ Add Issue</button></header>
    {error&&<div className="pm-issue-error" role="alert"><span>{error}</span><button type="button" onClick={reload}>Reload Issues</button></div>}
    {loading?<div className="pm-issue-state" role="status">Loading project issues…</div>:issues.length?<div className="pm-issue-list">{issues.map(issue=>{const values=detail(issue),overdue=isIssueOverdue(issue);return <article key={issue.id} className={overdue?'overdue':''}><header><div><span className={`pm-issue-priority priority-${values.priority.toLowerCase()}`}>{values.priority} priority</span><h3>{values.title}</h3></div><span className={`pm-issue-status status-${values.status.toLowerCase().replace(/\s+/g,'-')}`}>{values.status}</span></header><p>{values.description||'No description provided.'}</p><dl><div><dt>Owner</dt><dd>{values.owner||'Unassigned'}</dd></div><div><dt>Identified</dt><dd>{values.dateIdentified?new Date(`${values.dateIdentified}T00:00:00`).toLocaleDateString():'Not recorded'}</dd></div><div><dt>Target resolution</dt><dd>{values.targetResolutionDate?new Date(`${values.targetResolutionDate}T00:00:00`).toLocaleDateString():'Not scheduled'}{overdue&&<strong>Overdue</strong>}</dd></div><div><dt>Resolution / corrective action</dt><dd>{values.resolution||'Not documented'}</dd></div></dl><footer><button type="button" onClick={()=>beginEdit(issue)}>Edit</button><button type="button" className="danger" disabled={deletingId===issue.id} onClick={()=>remove(issue)}>{deletingId===issue.id?'Deleting…':'Delete'}</button></footer></article>})}</div>:<div className="pm-issue-empty"><div>◇</div><h3>No project issues yet</h3><p>Add the first issue to establish ownership, priority, and a resolution target.</p><button type="button" className="btn-primary" onClick={beginCreate}>Add First Issue</button></div>}
    {editor&&<div className="pm-issue-editor" role="dialog" aria-modal="true" aria-labelledby="pm-issue-editor-title"><button type="button" className="pm-issue-backdrop" aria-label="Close issue editor" onClick={()=>!saving&&setEditor(null)}/><form onSubmit={save}><header><div><span>{editor.record?'EDIT ISSUE':'NEW ISSUE'}</span><h2 id="pm-issue-editor-title">{editor.record?'Update project issue':'Add project issue'}</h2></div><button type="button" aria-label="Close issue editor" onClick={()=>setEditor(null)} disabled={saving}>×</button></header><label>Title<input required value={editor.values.title} onChange={event=>change('title',event.target.value)}/></label><label>Owner<input value={editor.values.owner} onChange={event=>change('owner',event.target.value)}/></label><label className="wide">Description<textarea rows="3" value={editor.values.description} onChange={event=>change('description',event.target.value)}/></label><label>Priority<select value={editor.values.priority} onChange={event=>change('priority',event.target.value)}>{PRIORITIES.map(value=><option key={value}>{value}</option>)}</select></label><label>Status<select value={editor.values.status} onChange={event=>change('status',event.target.value)}>{STATUSES.map(value=><option key={value}>{value}</option>)}</select></label><label>Date identified<input type="date" value={editor.values.dateIdentified} onChange={event=>change('dateIdentified',event.target.value)}/></label><label>Target resolution date<input type="date" value={editor.values.targetResolutionDate} onChange={event=>change('targetResolutionDate',event.target.value)}/></label><label className="wide">Resolution / corrective action<textarea rows="3" value={editor.values.resolution} onChange={event=>change('resolution',event.target.value)}/></label><footer><button type="button" className="btn-secondary" disabled={saving} onClick={()=>setEditor(null)}>Cancel</button><button type="submit" className="btn-primary" disabled={saving}>{saving?'Saving…':editor.record?'Save Changes':'Create Issue'}</button></footer></form></div>}
  </section>;
}
