import React,{useEffect,useState} from 'react';
import {useAuth} from '../context/AuthContext';
import {useInteractions} from '../context/InteractionContext';
import {pmRepository} from '../repositories/pmRepository';
import './ProjectApprovals.css';

const EMPTY={title:'',description:'',approver:'',dueDate:'',priority:'Medium',status:'Pending',decisionNotes:''};
const PRIORITIES=['Low','Medium','High','Critical'];
const STATUSES=['Pending','Approved','Rejected','Withdrawn'];
const detail=entry=>({...EMPTY,...(entry.content||{}),title:entry.title||'',priority:entry.priority||'Medium',status:entry.status||'Pending',approver:entry.content?.approver||'',dueDate:entry.content?.due_date||entry.content?.dueDate||'',decisionNotes:entry.content?.decision_notes||entry.content?.decisionNotes||''});
export const isApprovalOverdue=(entry,now=new Date())=>{const{dueDate,status}=detail(entry);if(!dueDate||status!=='Pending')return false;const due=new Date(`${dueDate}T23:59:59.999`);return !Number.isNaN(due.getTime())&&due<now};
const toContent=values=>({description:values.description.trim(),approver:values.approver.trim(),due_date:values.dueDate,decision_notes:values.decisionNotes.trim()});
const errorMessage=error=>{const raw=error?.message||'';if(raw.includes('pm-update-conflict'))return'This approval changed since you opened it. Reload Approvals, review the latest version, and try again.';return raw||'Project approvals could not be loaded.'};

export default function ProjectApprovals({project}){
  const{user,profile}=useAuth();
  const{confirm,toast}=useInteractions();
  const[approvals,setApprovals]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editor,setEditor]=useState(null),[saving,setSaving]=useState(false),[deletingId,setDeletingId]=useState(''),[decidingId,setDecidingId]=useState('');
  const load=async()=>{setLoading(true);setError('');try{setApprovals(await pmRepository.approvals.list(project.id))}catch(nextError){setError(errorMessage(nextError))}finally{setLoading(false)}};
  useEffect(()=>{let active=true;setLoading(true);setError('');pmRepository.approvals.list(project.id).then(rows=>{if(active)setApprovals(rows)}).catch(nextError=>{if(active)setError(errorMessage(nextError))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[project.id]);

  const beginCreate=()=>setEditor({record:null,values:{...EMPTY}});
  const beginEdit=entry=>setEditor({record:entry,values:detail(entry)});
  const change=(field,value)=>setEditor(current=>({...current,values:{...current.values,[field]:value}}));
  const reload=()=>{setEditor(null);load()};
  const save=async event=>{event.preventDefault();if(!editor||saving)return;setSaving(true);setError('');const values=editor.values,content=toContent(values);try{let saved;if(editor.record){const{created_by,content:previousContent,...existing}=editor.record;saved=await pmRepository.approvals.update({...existing,project_id:project.id,organization_id:project.organizationId||profile?.default_organization_id,title:values.title.trim(),priority:values.priority,status:values.status,methodology:project.methodology||'pmp',lifecycle_phase:existing.lifecycle_phase||project.currentPhase||'Planning',content});setApprovals(current=>current.map(entry=>entry.id===saved.id?saved:entry))}else{saved=await pmRepository.approvals.create({project_id:project.id,organization_id:project.organizationId||profile?.default_organization_id,created_by:user?.id,title:values.title.trim(),priority:values.priority,status:values.status,methodology:project.methodology||'pmp',lifecycle_phase:project.currentPhase||'Planning',content});setApprovals(current=>[saved,...current])}setEditor(null);toast(editor.record?'Approval updated.':'Approval created.')}catch(nextError){setError(errorMessage(nextError))}finally{setSaving(false)}};
  const remove=async entry=>{if(!await confirm({title:'Delete approval?',message:`“${entry.title}” will be permanently removed from this project.`,confirmLabel:'Delete Approval',destructive:true}))return;setDeletingId(entry.id);setError('');try{await pmRepository.approvals.remove(entry.id);setApprovals(current=>current.filter(item=>item.id!==entry.id));toast('Approval deleted.')}catch(nextError){setError(errorMessage(nextError))}finally{setDeletingId('')}};
  const decide=async(entry,status)=>{if(!await confirm({title:`${status} this request?`,message:`“${entry.title}” will be marked ${status.toLowerCase()}.`,confirmLabel:status,destructive:status==='Rejected'}))return;setDecidingId(entry.id);setError('');try{const{created_by,content:previousContent,...existing}=entry,values=detail(entry);const saved=await pmRepository.approvals.update({...existing,project_id:project.id,organization_id:project.organizationId||profile?.default_organization_id,status,content:toContent(values)});setApprovals(current=>current.map(item=>item.id===saved.id?saved:item));toast(`Approval ${status.toLowerCase()}.`)}catch(nextError){setError(errorMessage(nextError))}finally{setDecidingId('')}};

  return <section className="pm-approvals" aria-labelledby="pm-approvals-title">
    <header><div><span>PROJECT MANAGEMENT</span><h2 id="pm-approvals-title">Project Approvals</h2><p>Track approval requests, accountable approvers, and decision outcomes.</p></div><button type="button" className="btn-primary" onClick={beginCreate}>+ Add Approval</button></header>
    {error&&<div className="pm-approval-error" role="alert"><span>{error}</span><button type="button" onClick={reload}>Reload Approvals</button></div>}
    {loading?<div className="pm-approval-state" role="status">Loading project approvals…</div>:approvals.length?<div className="pm-approval-list">{approvals.map(entry=>{const values=detail(entry),overdue=isApprovalOverdue(entry);return <article key={entry.id} className={overdue?'overdue':''}><header><div><span className={`pm-approval-priority priority-${values.priority.toLowerCase()}`}>{values.priority} priority</span><h3>{values.title}</h3></div><span className={`pm-approval-status status-${values.status.toLowerCase()}`}>{values.status}</span></header><p>{values.description||'No description provided.'}</p><dl><div><dt>Approver</dt><dd>{values.approver||'Unassigned'}</dd></div><div><dt>Due date</dt><dd>{values.dueDate?new Date(`${values.dueDate}T00:00:00`).toLocaleDateString():'Not scheduled'}{overdue&&<strong>Overdue</strong>}</dd></div><div><dt>Decision notes</dt><dd>{values.decisionNotes||'Not documented'}</dd></div></dl><footer>{values.status==='Pending'&&<><button type="button" className="approve" disabled={decidingId===entry.id} onClick={()=>decide(entry,'Approved')}>Approve</button><button type="button" className="reject" disabled={decidingId===entry.id} onClick={()=>decide(entry,'Rejected')}>Reject</button></>}<button type="button" onClick={()=>beginEdit(entry)}>Edit</button><button type="button" className="danger" disabled={deletingId===entry.id} onClick={()=>remove(entry)}>{deletingId===entry.id?'Deleting…':'Delete'}</button></footer></article>})}</div>:<div className="pm-approval-empty"><div>◇</div><h3>No project approvals yet</h3><p>Add the first approval request to establish an accountable approver and due date.</p><button type="button" className="btn-primary" onClick={beginCreate}>Add First Approval</button></div>}
    {editor&&<div className="pm-approval-editor" role="dialog" aria-modal="true" aria-labelledby="pm-approval-editor-title"><button type="button" className="pm-approval-backdrop" aria-label="Close approval editor" onClick={()=>!saving&&setEditor(null)}/><form onSubmit={save}><header><div><span>{editor.record?'EDIT APPROVAL':'NEW APPROVAL'}</span><h2 id="pm-approval-editor-title">{editor.record?'Update approval request':'Add approval request'}</h2></div><button type="button" aria-label="Close approval editor" onClick={()=>setEditor(null)} disabled={saving}>×</button></header><label>Title<input required value={editor.values.title} onChange={event=>change('title',event.target.value)}/></label><label>Approver<input value={editor.values.approver} onChange={event=>change('approver',event.target.value)}/></label><label className="wide">Description<textarea rows="3" value={editor.values.description} onChange={event=>change('description',event.target.value)}/></label><label>Due date<input type="date" value={editor.values.dueDate} onChange={event=>change('dueDate',event.target.value)}/></label><label>Priority<select value={editor.values.priority} onChange={event=>change('priority',event.target.value)}>{PRIORITIES.map(value=><option key={value}>{value}</option>)}</select></label><label>Status<select value={editor.values.status} onChange={event=>change('status',event.target.value)}>{STATUSES.map(value=><option key={value}>{value}</option>)}</select></label><label className="wide">Decision notes<textarea rows="3" value={editor.values.decisionNotes} onChange={event=>change('decisionNotes',event.target.value)}/></label><footer><button type="button" className="btn-secondary" disabled={saving} onClick={()=>setEditor(null)}>Cancel</button><button type="submit" className="btn-primary" disabled={saving}>{saving?'Saving…':editor.record?'Save Changes':'Create Approval'}</button></footer></form></div>}
  </section>;
}
