import React,{useEffect,useState} from 'react';
import {useAuth} from '../context/AuthContext';
import {useInteractions} from '../context/InteractionContext';
import {pmRepository} from '../repositories/pmRepository';
import './ProjectDecisions.css';

const EMPTY={title:'',description:'',decisionMaker:'',priority:'Medium',status:'Proposed',dateRaised:'',targetDecisionDate:'',decision:''};
const PRIORITIES=['Low','Medium','High','Critical'];
const STATUSES=['Proposed','Decided','Deferred','Superseded'];
const today=()=>{const now=new Date(),offset=now.getTimezoneOffset()*60000;return new Date(now-offset).toISOString().slice(0,10)};
const detail=entry=>({...EMPTY,...(entry.content||{}),title:entry.title||'',priority:entry.priority||'Medium',status:entry.status||'Proposed',dateRaised:entry.content?.date_raised||entry.content?.dateRaised||'',targetDecisionDate:entry.content?.target_decision_date||entry.content?.targetDecisionDate||'',decision:entry.content?.decision||''});
export const isDecisionOverdue=(entry,now=new Date())=>{const{targetDecisionDate,status}=detail(entry);if(!targetDecisionDate||status!=='Proposed')return false;const target=new Date(`${targetDecisionDate}T23:59:59.999`);return !Number.isNaN(target.getTime())&&target<now};
const errorMessage=error=>{const raw=error?.message||'';if(raw.includes('pm-update-conflict'))return'This decision changed since you opened it. Reload Decisions, review the latest version, and try again.';return raw||'Project decisions could not be loaded.'};

export default function ProjectDecisions({project}){
  const{user,profile}=useAuth();
  const{confirm,toast}=useInteractions();
  const[decisions,setDecisions]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[editor,setEditor]=useState(null),[saving,setSaving]=useState(false),[deletingId,setDeletingId]=useState('');
  const load=async()=>{setLoading(true);setError('');try{setDecisions(await pmRepository.decisions.list(project.id))}catch(nextError){setError(errorMessage(nextError))}finally{setLoading(false)}};
  useEffect(()=>{let active=true;setLoading(true);setError('');pmRepository.decisions.list(project.id).then(rows=>{if(active)setDecisions(rows)}).catch(nextError=>{if(active)setError(errorMessage(nextError))}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[project.id]);

  const beginCreate=()=>setEditor({record:null,values:{...EMPTY,dateRaised:today()}});
  const beginEdit=entry=>setEditor({record:entry,values:detail(entry)});
  const change=(field,value)=>setEditor(current=>({...current,values:{...current.values,[field]:value}}));
  const reload=()=>{setEditor(null);load()};
  const save=async event=>{event.preventDefault();if(!editor||saving)return;setSaving(true);setError('');const values=editor.values,content={description:values.description.trim(),decision_maker:values.decisionMaker.trim(),date_raised:values.dateRaised,target_decision_date:values.targetDecisionDate,decision:values.decision.trim()};try{let saved;if(editor.record){const{created_by,content:previousContent,...existing}=editor.record;saved=await pmRepository.decisions.update({...existing,project_id:project.id,organization_id:project.organizationId||profile?.default_organization_id,title:values.title.trim(),priority:values.priority,status:values.status,methodology:project.methodology||'pmp',lifecycle_phase:existing.lifecycle_phase||project.currentPhase||'Execution',content});setDecisions(current=>current.map(entry=>entry.id===saved.id?saved:entry))}else{saved=await pmRepository.decisions.create({project_id:project.id,organization_id:project.organizationId||profile?.default_organization_id,created_by:user?.id,title:values.title.trim(),priority:values.priority,status:values.status,methodology:project.methodology||'pmp',lifecycle_phase:project.currentPhase||'Execution',content});setDecisions(current=>[saved,...current])}setEditor(null);toast(editor.record?'Decision updated.':'Decision created.')}catch(nextError){setError(errorMessage(nextError))}finally{setSaving(false)}};
  const remove=async entry=>{if(!await confirm({title:'Delete decision?',message:`“${entry.title}” will be permanently removed from this project.`,confirmLabel:'Delete Decision',destructive:true}))return;setDeletingId(entry.id);setError('');try{await pmRepository.decisions.remove(entry.id);setDecisions(current=>current.filter(item=>item.id!==entry.id));toast('Decision deleted.')}catch(nextError){setError(errorMessage(nextError))}finally{setDeletingId('')}};

  return <section className="pm-decisions" aria-labelledby="pm-decisions-title">
    <header><div><span>PROJECT MANAGEMENT</span><h2 id="pm-decisions-title">Project Decisions</h2><p>Maintain an accountable record of decisions, owners, and rationale.</p></div><button type="button" className="btn-primary" onClick={beginCreate}>+ Add Decision</button></header>
    {error&&<div className="pm-decision-error" role="alert"><span>{error}</span><button type="button" onClick={reload}>Reload Decisions</button></div>}
    {loading?<div className="pm-decision-state" role="status">Loading project decisions…</div>:decisions.length?<div className="pm-decision-list">{decisions.map(entry=>{const values=detail(entry),overdue=isDecisionOverdue(entry);return <article key={entry.id} className={overdue?'overdue':''}><header><div><span className={`pm-decision-priority priority-${values.priority.toLowerCase()}`}>{values.priority} priority</span><h3>{values.title}</h3></div><span className={`pm-decision-status status-${values.status.toLowerCase()}`}>{values.status}</span></header><p>{values.description||'No description provided.'}</p><dl><div><dt>Decision maker</dt><dd>{values.decisionMaker||'Unassigned'}</dd></div><div><dt>Raised</dt><dd>{values.dateRaised?new Date(`${values.dateRaised}T00:00:00`).toLocaleDateString():'Not recorded'}</dd></div><div><dt>Target decision date</dt><dd>{values.targetDecisionDate?new Date(`${values.targetDecisionDate}T00:00:00`).toLocaleDateString():'Not scheduled'}{overdue&&<strong>Overdue</strong>}</dd></div><div><dt>Decision</dt><dd>{values.decision||'Not yet decided'}</dd></div></dl><footer><button type="button" onClick={()=>beginEdit(entry)}>Edit</button><button type="button" className="danger" disabled={deletingId===entry.id} onClick={()=>remove(entry)}>{deletingId===entry.id?'Deleting…':'Delete'}</button></footer></article>})}</div>:<div className="pm-decision-empty"><div>◇</div><h3>No project decisions yet</h3><p>Add the first decision to establish ownership, rationale, and a decision target.</p><button type="button" className="btn-primary" onClick={beginCreate}>Add First Decision</button></div>}
    {editor&&<div className="pm-decision-editor" role="dialog" aria-modal="true" aria-labelledby="pm-decision-editor-title"><button type="button" className="pm-decision-backdrop" aria-label="Close decision editor" onClick={()=>!saving&&setEditor(null)}/><form onSubmit={save}><header><div><span>{editor.record?'EDIT DECISION':'NEW DECISION'}</span><h2 id="pm-decision-editor-title">{editor.record?'Update project decision':'Add project decision'}</h2></div><button type="button" aria-label="Close decision editor" onClick={()=>setEditor(null)} disabled={saving}>×</button></header><label>Title<input required value={editor.values.title} onChange={event=>change('title',event.target.value)}/></label><label>Decision maker<input value={editor.values.decisionMaker} onChange={event=>change('decisionMaker',event.target.value)}/></label><label className="wide">Description<textarea rows="3" value={editor.values.description} onChange={event=>change('description',event.target.value)}/></label><label>Priority<select value={editor.values.priority} onChange={event=>change('priority',event.target.value)}>{PRIORITIES.map(value=><option key={value}>{value}</option>)}</select></label><label>Status<select value={editor.values.status} onChange={event=>change('status',event.target.value)}>{STATUSES.map(value=><option key={value}>{value}</option>)}</select></label><label>Date raised<input type="date" value={editor.values.dateRaised} onChange={event=>change('dateRaised',event.target.value)}/></label><label>Target decision date<input type="date" value={editor.values.targetDecisionDate} onChange={event=>change('targetDecisionDate',event.target.value)}/></label><label className="wide">Decision<textarea rows="3" value={editor.values.decision} onChange={event=>change('decision',event.target.value)}/></label><footer><button type="button" className="btn-secondary" disabled={saving} onClick={()=>setEditor(null)}>Cancel</button><button type="submit" className="btn-primary" disabled={saving}>{saving?'Saving…':editor.record?'Save Changes':'Create Decision'}</button></footer></form></div>}
  </section>;
}
