import React from 'react';
import './SavedAnalysisResult.css';

const present=value=>value!==undefined&&value!==null&&value!=='';
const label=value=>String(value||'').replace(/([a-z])([A-Z])/g,'$1 $2').replace(/[-_]/g,' ').replace(/^./,letter=>letter.toUpperCase());
const date=value=>{if(!value)return'Not recorded';const parsed=new Date(value);return Number.isNaN(parsed.getTime())?String(value):parsed.toLocaleString()};
function Value({value}){if(!present(value))return <span className="saved-result-empty">Not recorded</span>;if(typeof value==='boolean')return <span>{value?'Yes':'No'}</span>;if(typeof value!=='object')return <span>{String(value)}</span>;if(Array.isArray(value))return value.length?<div className="saved-result-list">{value.map((item,index)=><div key={index}><Value value={item}/></div>)}</div>:<span className="saved-result-empty">None recorded</span>;return <dl className="saved-result-fields">{Object.entries(value).map(([key,item])=><div key={key}><dt>{label(key)}</dt><dd><Value value={item}/></dd></div>)}</dl>}
export const hasSavedResult=analysis=>Boolean(analysis&&present(analysis.result||analysis.statsSummary||analysis.structuredOutput));
export default function SavedAnalysisResult({analysis,onClose}){const result=analysis?.result||analysis?.structuredOutput||analysis?.statsSummary;const incomplete=analysis?.provenanceStatus==='legacy-incomplete';return <div className="saved-result-backdrop" role="presentation" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="saved-result" role="dialog" aria-modal="true" aria-labelledby="saved-result-title"><header><div><span>SAVED ANALYSIS RESULT</span><h2 id="saved-result-title">{analysis?.title||analysis?.name||'Analysis result'}</h2><p>Read-only canonical result · {analysis?.id}</p></div><button onClick={onClose} aria-label="Close">×</button></header>{incomplete&&<div className="saved-result-limitation"><strong>Legacy analysis — incomplete provenance</strong><p>The original dataset version or variable mapping cannot be proven. Aureqin preserves this record without reconstructing or inventing provenance.</p></div>}<div className="saved-result-summary"><div><small>Method</small><strong>{analysis?.method||analysis?.toolId||analysis?.toolType||'Not recorded'}</strong></div><div><small>Dataset / version</small><strong>{(analysis?.datasetIds||[]).join(', ')||'Not recorded'}{present(analysis?.datasetVersion)?` · v${analysis.datasetVersion}`:''}</strong></div><div><small>Created / executed</small><strong>{date(analysis?.executedAt||analysis?.createdAt)}</strong></div></div>{analysis?.variableMapping&&<section><h3>Variable mapping</h3><Value value={analysis.variableMapping}/></section>}{analysis?.inputConfiguration&&Object.keys(analysis.inputConfiguration).length>0&&<section><h3>Analysis configuration</h3><Value value={analysis.inputConfiguration}/></section>}<section><h3>Saved result</h3>{hasSavedResult(analysis)?<Value value={result}/>:<div className="saved-result-limitation"><strong>Full saved-result rendering is unavailable for this legacy analysis.</strong><p>The canonical record does not contain a persisted result payload. Aureqin will not reconstruct it from the current worksheet or open a blank analysis.</p></div>}</section>{present(analysis?.interpretation)&&<section><h3>Interpretation</h3><p>{String(analysis.interpretation)}</p></section>}{present(analysis?.diagnostics)&&<section><h3>Diagnostics</h3><Value value={analysis.diagnostics}/></section>}<section><h3>Provenance</h3><Value value={analysis?.reproducibility||{analysisId:analysis?.id,organizationId:analysis?.organizationId,createdBy:analysis?.createdBy,datasetVersionIds:analysis?.datasetVersionIds,methodVersion:analysis?.methodVersion,validationStatus:analysis?.validationStatus,updatedAt:analysis?.updatedAt}}/></section><footer><button className="btn-primary" onClick={onClose}>Close Result</button></footer></section></div>}
