import { approximateCpkInterval, lognormalCapability, normalCapability } from './capabilityEngine';

describe('process capability engine',()=>{
 test('reproduces the NIST two-sided Cp/Cpk example and distinguishes performance',()=>{const values=[12,14,16,18,20,14,16,18];const r=normalCapability({values,lsl:8,usl:20});expect(r.indices.cp).not.toBeNull();expect(r.indices.cpk).toBeLessThanOrEqual(r.indices.cp);expect(r.indices.pp).toBe(r.indices.cp);expect(r.indices.ppk).toBe(r.indices.cpk)});
 test('supports exact NIST parameter example through equivalent data moments',()=>{const values=[14,18];const r=normalCapability({values,lsl:8,usl:20});expect(r.mean).toBe(16);expect(r.overallSigma).toBeCloseTo(2.828427);expect(r.indices.cpu).toBeCloseTo(.471405)});
 test('supports one-sided specifications and target Cpm',()=>{const lower=normalCapability({values:[9,10,11,10,10.5],lsl:8}),upper=normalCapability({values:[9,10,11,10,10.5],usl:12}),target=normalCapability({values:[9,10,11,10,10.5],lsl:8,usl:12,target:10});expect(lower.indices.cpk).toBe(lower.indices.cpl);expect(upper.indices.cpk).toBe(upper.indices.cpu);expect(target.indices.cpm).not.toBeNull()});
 test('uses pooled within subgroup sigma separately from overall sigma',()=>{const subgroups=[[1,2,3],[5,6,7],[9,10,11]],values=subgroups.flat(),r=normalCapability({values,lsl:0,usl:12,subgroups});expect(r.withinSigma).toBeCloseTo(1);expect(r.overallSigma).toBeGreaterThan(r.withinSigma);expect(r.indices.cp).toBeLessThanOrEqual(2)});
 test('warns for unstable processes and inadequate measurement systems',()=>{const r=normalCapability({values:[1,2,3,4,5],lsl:0,usl:6,stabilityEvidence:{id:'spc1',stable:false},msaEvidence:{id:'msa1',adequate:false}});expect(r.warnings.join(' ')).toMatch(/unstable/);expect(r.warnings.join(' ')).toMatch(/measurement-system/)});
 test('separates observed and expected nonconformance',()=>{const r=normalCapability({values:[1,2,3,4,5],lsl:0,usl:6});expect(r.observedNonconformance.totalCount).toBe(0);expect(r.expectedNonconformance.totalPpm).toBeGreaterThan(0)});
 test('provides a guarded lognormal path and approximate Cpk interval',()=>{const r=lognormalCapability({values:[1,1.2,1.5,2,3,4],lsl:.5,usl:6});expect(r.distribution.name).toBe('lognormal');expect(r.warning).toMatch(/fit review/);expect(approximateCpkInterval(1.33,50)).toHaveLength(2);expect(approximateCpkInterval(1.33,10)).toBeNull()});
 test('rejects invalid specifications, zero variation, and invalid lognormal data',()=>{expect(()=>normalCapability({values:[1,2],lsl:3,usl:2})).toThrow('invalid');expect(()=>normalCapability({values:[2,2,2],lsl:1,usl:3})).toThrow('zero-variance');expect(()=>lognormalCapability({values:[0,1,2],usl:3})).toThrow('positive')});
});
