import {doeFullFactorialAnalysis} from './statTests';

export const DOE_ENGINE_VERSION='1.0.0';
const product=(row,names)=>names.reduce((value,name)=>value*row.factorCodes[name],1);
const seededRandom=seed=>{let state=(Number(seed)||1)>>>0;return()=>{state=(1664525*state+1013904223)>>>0;return state/4294967296}};
const shuffle=(items,seed)=>{const random=seededRandom(seed),copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
const symmetricDifference=(a,b)=>[...new Set([...a,...b].filter(value=>!(a.includes(value)&&b.includes(value))))].sort();

export function createDoeModel(input={}){const factors=(input.factors||[]).map((factor,index)=>({id:factor.id||`factor-${index+1}`,name:factor.name||`Factor ${index+1}`,type:factor.type||'continuous',low:factor.low??-1,high:factor.high??1,levels:factor.levels||[factor.low??-1,factor.high??1]}));if(factors.length<2)throw new Error('DOE requires at least two factors.');if(new Set(factors.map(factor=>factor.name)).size!==factors.length)throw new Error('Factor names must be unique.');return{schemaVersion:1,methodVersion:DOE_ENGINE_VERSION,designType:input.designType||'full-factorial-2-level',factors,responses:input.responses||[{name:input.response||'Response',goal:'maximize'}],blocks:Math.max(1,Number(input.blocks)||1),replicates:Math.max(1,Number(input.replicates)||1),centerPoints:Math.max(0,Number(input.centerPoints)||0),randomized:input.randomized!==false,randomSeed:Number(input.randomSeed)||20260809,generators:input.generators||{},modelTerms:input.modelTerms||[],runs:[],analysisResults:null,confirmationRuns:[]}}

export function generateFullFactorial(input){const model=createDoeModel({...input,designType:'full-factorial-2-level'}),k=model.factors.length,base=[];for(let index=0;index<2**k;index++){const factorCodes={},factorSettings={};model.factors.forEach((factor,position)=>{const code=(index>>position)&1?1:-1;factorCodes[factor.name]=code;factorSettings[factor.name]=code===-1?factor.low:factor.high});for(let replicate=1;replicate<=model.replicates;replicate++)base.push({standardOrder:base.length+1,replicate,factorCodes,factorSettings,isCenterPoint:false})}for(let i=0;i<model.centerPoints;i++){const factorCodes={},factorSettings={};model.factors.forEach(factor=>{factorCodes[factor.name]=0;factorSettings[factor.name]=typeof factor.low==='number'&&typeof factor.high==='number'?(factor.low+factor.high)/2:'Center'});base.push({standardOrder:base.length+1,replicate:i+1,factorCodes,factorSettings,isCenterPoint:true})}const ordered=model.randomized?shuffle(base,model.randomSeed):base;const runs=ordered.map((run,index)=>({...run,runOrder:index+1,block:index%model.blocks+1,responses:{}}));return{...model,runs,aliases:[],resolution:null}}

export function generateFractionalFactorial(input){const model=createDoeModel({...input,designType:'fractional-factorial-2-level'}),generatedNames=Object.keys(model.generators);if(!generatedNames.length&&model.factors.length<4)throw new Error('A default half-fraction requires at least four factors.');
 const generators=Object.keys(model.generators).length?model.generators:{[model.factors.at(-1).name]:model.factors.slice(0,-1).map(factor=>factor.name)};
 const generatedSet=new Set(Object.keys(generators)),independent=model.factors.filter(factor=>!generatedSet.has(factor.name));if(independent.length<2)throw new Error('Fractional factorial generators leave too few independent base factors.');Object.entries(generators).forEach(([target,sources])=>{if(!model.factors.some(factor=>factor.name===target)||!Array.isArray(sources)||!sources.length||sources.some(source=>!independent.some(factor=>factor.name===source)))throw new Error(`Generator ${target} must reference existing independent base factors.`)});const base=[];for(let index=0;index<2**independent.length;index++){const factorCodes={},factorSettings={};independent.forEach((factor,position)=>{factorCodes[factor.name]=(index>>position)&1?1:-1});Object.entries(generators).forEach(([target,sources])=>{factorCodes[target]=sources.reduce((value,source)=>value*factorCodes[source],1)});model.factors.forEach(factor=>{factorSettings[factor.name]=factorCodes[factor.name]===-1?factor.low:factor.high});for(let replicate=1;replicate<=model.replicates;replicate++)base.push({standardOrder:base.length+1,replicate,factorCodes,factorSettings,isCenterPoint:false})}const definingWords=Object.entries(generators).map(([target,sources])=>[target,...sources].sort()),resolution=Math.min(...definingWords.map(word=>word.length)),aliases=aliasStructure(model.factors.map(factor=>factor.name),definingWords),ordered=model.randomized?shuffle(base,model.randomSeed):base,runs=ordered.map((run,index)=>({...run,runOrder:index+1,block:index%model.blocks+1,responses:{}}));return{...model,generators,definingWords,resolution,aliases,runs,warnings:[`Resolution ${resolution} design: effects sharing an alias chain cannot be separated without additional assumptions or runs.`]}}

function aliasStructure(factorNames,definingWords){const terms=factorNames.map(name=>[name]);for(let i=0;i<factorNames.length;i++)for(let j=i+1;j<factorNames.length;j++)terms.push([factorNames[i],factorNames[j]]);return terms.map(term=>{const chain=[term,...definingWords.map(word=>symmetricDifference(term,word))].map(value=>value.length?value.join('×'):'I');return{term:term.join('×'),aliases:[...new Set(chain)].filter(value=>value!==term.join('×'))}})}

export function analyzeFactorial(model,responseName){if(!model?.runs?.length)throw new Error('Generate a DOE design before analysis.');const usable=model.runs.filter(run=>!run.isCenterPoint&&Number.isFinite(Number(run.responses?.[responseName]??run.response)));if(usable.length!==model.runs.filter(run=>!run.isCenterPoint).length)throw new Error(`Every non-center run needs a finite ${responseName} result before factorial analysis.`);const rows=usable.map(run=>({factorCodes:run.factorCodes,value:Number(run.responses?.[responseName]??run.response)})),factorNames=model.factors.map(factor=>factor.name),result=doeFullFactorialAnalysis(rows,factorNames);return{...result,method:'two-level-factorial-effects',methodVersion:DOE_ENGINE_VERSION,designType:model.designType,responseName,factorNames,aliases:model.aliases||[],resolution:model.resolution??null,provenance:{designSeed:model.randomSeed,runOrder:model.runs.map(run=>run.standardOrder),blocks:model.blocks,replicates:model.replicates},warnings:[...(!result.hasReplication?['The design has no pure-error replication; effect p-values are not available.']:[]),...(model.designType==='fractional-factorial-2-level'?['Aliased effects cannot be interpreted independently without subject-matter assumptions or follow-up runs.']:[])]}}

export function optimizeFactorial(model,analysis,goal={type:'maximize'}){if(!analysis?.effects)throw new Error('Optimization requires a completed factorial analysis.');const coefficients={Intercept:analysis.grandMean};analysis.effects.forEach(effect=>{coefficients[effect.term]=effect.effect/2});const candidates=[];for(let index=0;index<2**model.factors.length;index++){const factorCodes={};model.factors.forEach((factor,position)=>{factorCodes[factor.name]=(index>>position)&1?1:-1});let predicted=coefficients.Intercept;analysis.effects.forEach(effect=>{const names=effect.term.split(/\s*[×Ã—]\s*/);predicted+=(coefficients[effect.term]||0)*product({factorCodes},names)});candidates.push({factorCodes,factorSettings:Object.fromEntries(model.factors.map(factor=>[factor.name,factorCodes[factor.name]===-1?factor.low:factor.high])),predicted})}const target=Number(goal.target),scored=candidates.map(candidate=>({...candidate,score:goal.type==='minimize'?-candidate.predicted:goal.type==='target'?-Math.abs(candidate.predicted-target):candidate.predicted})).sort((a,b)=>b.score-a.score);return{method:'factorial-grid-optimization',methodVersion:DOE_ENGINE_VERSION,goal,recommended:scored[0],candidates:scored,warnings:['Optimization is model-based and remains subject to the fitted model, aliasing, residual, and extrapolation limitations. A confirmation run is required.']}}

export function recordConfirmationRun(model,optimization,input){if(!optimization?.recommended)throw new Error('A confirmation run requires recommended settings.');const observed=Number(input.observed);if(!Number.isFinite(observed))throw new Error('Enter a finite observed confirmation response.');const predicted=optimization.recommended.predicted,deviation=observed-predicted,percentDeviation=predicted===0?null:deviation/Math.abs(predicted)*100,record={id:input.id||`confirmation-${Date.now()}`,plannedAt:input.plannedAt||new Date().toISOString(),observedAt:input.observedAt||new Date().toISOString(),settings:optimization.recommended.factorSettings,predicted,observed,deviation,percentDeviation,responseName:input.responseName||model.responses[0]?.name||'Response',notes:input.notes||'',provenance:{designType:model.designType,randomSeed:model.randomSeed,methodVersion:DOE_ENGINE_VERSION}};return{...model,confirmationRuns:[...(model.confirmationRuns||[]),record]}}
