import {chiSquareCDF,fCDF,invNorm,normCDF,tCDF} from './statMath';
import {chiSquareIndependence,dunnsTest,fishersExact,friedmanTest,kendallTauTest,pearsonCorrelationTest,spearmanCorrelationTest,wilcoxonSignedRank} from './statTests';
import {oneSampleTTest,welchTwoSampleTTest} from './statisticalEngines';

export const INFERENCE_ENGINE_VERSION='1.0.0';
const finite=(values,label='Values')=>{if(!Array.isArray(values))throw new Error(`${label} must be an array.`);if(values.some(value=>!Number.isFinite(value)))throw new Error(`${label} contains missing or nonnumeric observations. Apply an explicit missing-data policy before analysis.`);return values};
const avg=values=>values.reduce((sum,value)=>sum+value,0)/values.length;
const variance=values=>{const center=avg(values);return values.reduce((sum,value)=>sum+(value-center)**2,0)/(values.length-1)};
const quantile=(cdf,p,low,high)=>{for(let i=0;i<100;i++){const mid=(low+high)/2;if(cdf(mid)<p)low=mid;else high=mid}return(low+high)/2};
const tCritical=(confidence,df)=>quantile(value=>tCDF(value,df),1-(1-confidence)/2,0,50);
const chiCritical=(p,df)=>quantile(value=>chiSquareCDF(value,df),p,0,Math.max(10,df+20*Math.sqrt(2*df)));
const fCritical=(p,df1,df2)=>quantile(value=>fCDF(value,df1,df2),p,0,1e5);
const logFactorial=n=>{let sum=0;for(let i=2;i<=n;i++)sum+=Math.log(i);return sum};
const logChoose=(n,k)=>k<0||k>n?-Infinity:logFactorial(n)-logFactorial(k)-logFactorial(n-k);
const binomialProbability=(x,n,p)=>Math.exp(logChoose(n,x)+x*Math.log(p)+(n-x)*Math.log(1-p));
const exactBinomialP=(x,n,p0)=>{const observed=binomialProbability(x,n,p0);let p=0;for(let i=0;i<=n;i++){const candidate=binomialProbability(i,n,p0);if(candidate<=observed*(1+1e-12))p+=candidate}return Math.min(1,p)};
const wilson=(x,n,confidence)=>{const p=x/n,z=invNorm(1-(1-confidence)/2),den=1+z*z/n,center=(p+z*z/(2*n))/den,half=z*Math.sqrt(p*(1-p)/n+z*z/(4*n*n))/den;return[Math.max(0,center-half),Math.min(1,center+half)]};
const rank=(values)=>{const order=values.map((value,index)=>({value,index})).sort((a,b)=>a.value-b.value),ranks=new Array(values.length),ties=[];for(let i=0;i<order.length;){let j=i;while(j+1<order.length&&order[j+1].value===order[i].value)j++;const value=(i+j+2)/2;for(let k=i;k<=j;k++)ranks[order[k].index]=value;if(j>i)ties.push(j-i+1);i=j+1}return{ranks,ties}};

export function oneSampleMean(input){const confidence=input.confidence??.95,result=oneSampleTTest({values:finite(input.values),mu0:input.mu0??0,confidenceLevel:confidence});return{...result,method:'one-sample-t',methodVersion:INFERENCE_ENGINE_VERSION,assumptions:['Independent observations','Approximately normal population or adequate sample size'],guidance:'Use the interval and effect magnitude with the p-value; statistical significance alone is not practical significance.'}}

export function pairedMean(input){const a=finite(input.a,'First paired measurement'),b=finite(input.b,'Second paired measurement');if(a.length!==b.length)throw new Error('Paired measurements must contain the same number of observations in matching subject order.');const differences=a.map((value,index)=>value-b[index]);const result=oneSampleTTest({values:differences,mu0:input.mu0??0,confidenceLevel:input.confidence??.95});return{...result,method:'paired-t',methodVersion:INFERENCE_ENGINE_VERSION,differences,meanDifference:result.mean,assumptions:['Correct subject pairing','Approximately normal paired differences']}}

export function independentMeans(input){const a=finite(input.a,'Group A'),b=finite(input.b,'Group B'),confidence=input.confidence??.95;if(input.pooled!==true)return{...welchTwoSampleTTest({a,b,confidenceLevel:confidence}),method:'welch-two-sample-t',methodVersion:INFERENCE_ENGINE_VERSION,varianceModel:'unequal (Welch)',guidance:'Welch is the default because it remains appropriate when group variances or sample sizes differ.'};if(a.length<2||b.length<2)throw new Error('Each independent group requires at least two observations.');const nA=a.length,nB=b.length,meanA=avg(a),meanB=avg(b),varianceA=variance(a),varianceB=variance(b),df=nA+nB-2,pooledVariance=((nA-1)*varianceA+(nB-1)*varianceB)/df;if(!(pooledVariance>0))throw new Error('Pooled inference is undefined when both groups have zero variance.');const standardError=Math.sqrt(pooledVariance*(1/nA+1/nB)),difference=meanA-meanB,statistic=difference/standardError,pValue=2*(1-tCDF(Math.abs(statistic),df)),critical=tCritical(confidence,df);return{method:'pooled-two-sample-t',methodVersion:INFERENCE_ENGINE_VERSION,nA,nB,meanA,meanB,varianceA,varianceB,pooledVariance,difference,standardError,statistic,df,pValue,confidenceInterval:[difference-critical*standardError,difference+critical*standardError],varianceModel:'equal (pooled)',guidance:'Use pooled inference only when the design and variance evidence support a common population variance.'}}

export function oneProportion(input){const x=Number(input.successes),n=Number(input.trials),p0=input.p0??.5,confidence=input.confidence??.95;if(!Number.isInteger(x)||!Number.isInteger(n)||n<=0||x<0||x>n)throw new Error('Successes and trials must be nonnegative integers with successes no greater than trials.');if(!(p0>0&&p0<1))throw new Error('The null proportion must be between 0 and 1.');const estimate=x/n,expected=[n*p0,n*(1-p0)],exact=Math.min(...expected)<5,pValue=exact?exactBinomialP(x,n,p0):2*(1-normCDF(Math.abs((estimate-p0)/Math.sqrt(p0*(1-p0)/n))));return{method:exact?'exact-binomial':'one-proportion-z',methodVersion:INFERENCE_ENGINE_VERSION,x,n,estimate,nullProportion:p0,statistic:exact?null:(estimate-p0)/Math.sqrt(p0*(1-p0)/n),pValue:Math.min(1,pValue),confidenceInterval:wilson(x,n,confidence),approximationValid:!exact,warnings:exact?['Expected successes or failures are below 5; Aureqin used an exact binomial test instead of a normal approximation.']:[]}}

export function twoProportions(input){const x1=Number(input.x1),n1=Number(input.n1),x2=Number(input.x2),n2=Number(input.n2),confidence=input.confidence??.95;if(![x1,n1,x2,n2].every(Number.isInteger)||n1<=0||n2<=0||x1<0||x2<0||x1>n1||x2>n2)throw new Error('Both groups require valid integer success and trial counts.');const p1=x1/n1,p2=x2/n2,difference=p1-p2,pooled=(x1+x2)/(n1+n2),expected=[n1*pooled,n1*(1-pooled),n2*pooled,n2*(1-pooled)],sparse=Math.min(...expected)<5,seUnpooled=Math.sqrt(p1*(1-p1)/n1+p2*(1-p2)/n2),z=invNorm(1-(1-confidence)/2);if(sparse){const fisher=fishersExact([[x1,n1-x1],[x2,n2-x2]]);return{method:'fisher-exact',methodVersion:INFERENCE_ENGINE_VERSION,p1,p2,difference,pValue:fisher.p,oddsRatio:fisher.oddsRatio,confidenceInterval:[difference-z*seUnpooled,difference+z*seUnpooled],approximationValid:false,warnings:['Sparse expected counts detected; Aureqin used Fisher exact inference for the hypothesis test. The displayed difference interval is a large-sample interval and should be interpreted cautiously.']}}const seNull=Math.sqrt(pooled*(1-pooled)*(1/n1+1/n2)),statistic=difference/seNull,pValue=2*(1-normCDF(Math.abs(statistic)));return{method:'two-proportion-z',methodVersion:INFERENCE_ENGINE_VERSION,p1,p2,difference,pooled,statistic,pValue,confidenceInterval:[difference-z*seUnpooled,difference+z*seUnpooled],approximationValid:true,warnings:[]}}

export function oneVariance(input){const values=finite(input.values);if(values.length<2)throw new Error('Variance inference requires at least two observations.');const confidence=input.confidence??.95,df=values.length-1,s2=variance(values),sigma0=input.sigma0??null,alpha=1-confidence,lower=df*s2/chiCritical(1-alpha/2,df),upper=df*s2/chiCritical(alpha/2,df),statistic=sigma0===null?null:df*s2/(sigma0*sigma0),pValue=statistic===null?null:Math.min(1,2*Math.min(chiSquareCDF(statistic,df),1-chiSquareCDF(statistic,df)));return{method:'one-variance-chi-square',methodVersion:INFERENCE_ENGINE_VERSION,n:values.length,variance:s2,standardDeviation:Math.sqrt(s2),df,statistic,pValue,varianceConfidenceInterval:[lower,upper],standardDeviationConfidenceInterval:[Math.sqrt(lower),Math.sqrt(upper)],warnings:['Chi-square variance inference is highly sensitive to nonnormality. Review the normality diagnostic before relying on this interval or test.']}}

export function twoVariances(input){const a=finite(input.a,'Group A'),b=finite(input.b,'Group B');if(a.length<2||b.length<2)throw new Error('Each group requires at least two observations for variance inference.');const va=variance(a),vb=variance(b);if(!(va>0&&vb>0))throw new Error('Variance-ratio inference requires positive variance in both groups.');const statistic=va/vb,df1=a.length-1,df2=b.length-1,pValue=Math.min(1,2*Math.min(fCDF(statistic,df1,df2),1-fCDF(statistic,df1,df2))),confidence=input.confidence??.95,alpha=1-confidence,lower=statistic/fCritical(1-alpha/2,df1,df2),upper=statistic/fCritical(alpha/2,df1,df2);return{method:'two-variance-f',methodVersion:INFERENCE_ENGINE_VERSION,varianceA:va,varianceB:vb,ratio:statistic,statistic,df1,df2,pValue,confidenceInterval:[lower,upper],warnings:['The F test is not robust to severe nonnormality. Prefer Brown-Forsythe/Levene for general equality-of-variance screening.']}}

export function categoricalAssociation(input){const table=input.table;if(!Array.isArray(table)||table.length<2||!Array.isArray(table[0])||table[0].length<2||table.some(row=>row.length!==table[0].length||row.some(value=>!Number.isInteger(value)||value<0)))throw new Error('A contingency table requires at least 2 rows and 2 columns of nonnegative integer counts.');const result=chiSquareIndependence(table),sparse=result.expected.some(row=>row.some(value=>value<5)),standardizedResiduals=table.map((row,i)=>row.map((observed,j)=>(observed-result.expected[i][j])/Math.sqrt(result.expected[i][j]))),contributors=[];standardizedResiduals.forEach((row,i)=>row.forEach((value,j)=>{if(Math.abs(value)>=2)contributors.push({row:i,column:j,residual:value,direction:value>0?'higher than expected':'lower than expected'})}));const fisher=table.length===2&&table[0].length===2&&sparse?fishersExact(table):null;return{...result,method:fisher?'fisher-exact-with-chi-square-context':'chi-square-independence',methodVersion:INFERENCE_ENGINE_VERSION,p:fisher?.p??result.p,chiSquarePValue:result.p,fisher,cramersV:Math.sqrt(result.chi2/(result.grandTotal*Math.min(result.rows-1,result.cols-1))),standardizedResiduals,contributors,warnings:[...(sparse?['One or more expected counts are below 5; asymptotic chi-square evidence may be unreliable.']:[]),'Association does not establish causation.']}}

export function goodnessOfFit(input){const observed=finite(input.observed,'Observed counts'),expected=input.expected?finite(input.expected,'Expected counts'):new Array(observed.length).fill(observed.reduce((a,b)=>a+b,0)/observed.length);if(observed.length<2||expected.length!==observed.length||observed.some(v=>v<0)||expected.some(v=>v<=0))throw new Error('Goodness-of-fit requires matching nonnegative observed and positive expected counts.');const observedTotal=observed.reduce((a,b)=>a+b,0),expectedTotal=expected.reduce((a,b)=>a+b,0),scaled=expected.map(value=>value*observedTotal/expectedTotal),statistic=observed.reduce((sum,value,index)=>sum+(value-scaled[index])**2/scaled[index],0),df=observed.length-1-(input.estimatedParameters||0);if(df<1)throw new Error('Goodness-of-fit has no residual degrees of freedom after estimated parameters.');return{method:'chi-square-goodness-of-fit',methodVersion:INFERENCE_ENGINE_VERSION,observed,expected:scaled,statistic,df,pValue:1-chiSquareCDF(statistic,df),standardizedResiduals:observed.map((value,index)=>(value-scaled[index])/Math.sqrt(scaled[index])),warnings:scaled.some(value=>value<5)?['Expected counts below 5 make the chi-square approximation unreliable.']:[]}}

export function mannWhitney(input){const a=finite(input.a,'Group A'),b=finite(input.b,'Group B');if(!a.length||!b.length)throw new Error('Mann-Whitney requires observations in both independent groups.');const combined=[...a,...b],ranked=rank(combined),rankA=ranked.ranks.slice(0,a.length).reduce((s,v)=>s+v,0),uA=rankA-a.length*(a.length+1)/2,uB=a.length*b.length-uA,U=Math.min(uA,uB),meanU=a.length*b.length/2,tieTerm=ranked.ties.reduce((s,t)=>s+t**3-t,0),varianceU=a.length*b.length/12*((combined.length+1)-tieTerm/(combined.length*(combined.length-1))),correction=U<meanU?.5:-.5,z=(U-meanU+correction)/Math.sqrt(varianceU),pValue=2*(1-normCDF(Math.abs(z)));return{method:'mann-whitney-u',methodVersion:INFERENCE_ENGINE_VERSION,nA:a.length,nB:b.length,uA,uB,U,z,pValue,ties:ranked.ties.length,warnings:[...(a.length*b.length<=200&&ranked.ties.length===0?['An exact small-sample distribution is not yet exposed; this result uses a continuity-corrected normal approximation.']:[])]}}

export function signedRank(input){const a=finite(input.a,'First paired measurement'),b=finite(input.b,'Second paired measurement');if(a.length!==b.length)throw new Error('Wilcoxon signed-rank requires matching paired lengths.');if(a.length<2)throw new Error('Wilcoxon signed-rank requires at least two pairs.');return{...wilcoxonSignedRank(a,b),method:'wilcoxon-signed-rank',methodVersion:INFERENCE_ENGINE_VERSION,warnings:['The current signed-rank p-value uses an asymptotic approximation; ties and zero differences are reported through the effective sample size.']}}

export function signTest(input){const a=finite(input.a,'First paired measurement'),b=finite(input.b,'Second paired measurement');if(a.length!==b.length)throw new Error('Sign test requires matching paired lengths.');const differences=a.map((v,i)=>v-b[i]),positive=differences.filter(v=>v>0).length,negative=differences.filter(v=>v<0).length,n=positive+negative;if(!n)throw new Error('All paired differences are zero; a sign test cannot be computed.');const x=Math.min(positive,negative),pValue=Math.min(1,2*Array.from({length:x+1},(_,i)=>binomialProbability(i,n,.5)).reduce((s,v)=>s+v,0));return{method:'exact-sign-test',methodVersion:INFERENCE_ENGINE_VERSION,n,positive,negative,zeros:differences.length-n,statistic:x,pValue}}

export function kruskalWallis(input){const groups=input.groups?.map((group,index)=>finite(group,`Group ${index+1}`));if(!groups||groups.length<2||groups.some(group=>!group.length))throw new Error('Kruskal-Wallis requires at least two nonempty independent groups.');const flat=groups.flat(),ranked=rank(flat),N=flat.length;let cursor=0;const rankSums=groups.map(group=>{const total=ranked.ranks.slice(cursor,cursor+group.length).reduce((s,v)=>s+v,0);cursor+=group.length;return total});let H=12/(N*(N+1))*rankSums.reduce((sum,value,index)=>sum+value*value/groups[index].length,0)-3*(N+1),tieCorrection=1-ranked.ties.reduce((sum,t)=>sum+t**3-t,0)/(N**3-N);H/=tieCorrection;const df=groups.length-1,pValue=1-chiSquareCDF(H,df),labels=input.labels||groups.map((_,index)=>`Group ${index+1}`);return{method:'kruskal-wallis',methodVersion:INFERENCE_ENGINE_VERSION,H,df,pValue,rankSums,tieCorrection,postHoc:pValue<(input.alpha??.05)?dunnsTest(groups,labels):null}}

export function repeatedRanks(input){const conditions=input.conditions?.map((condition,index)=>finite(condition,`Condition ${index+1}`));if(!conditions||conditions.length<3||conditions.some(condition=>condition.length!==conditions[0].length))throw new Error('Friedman requires at least three conditions with matching subject counts.');return{...friedmanTest(conditions),method:'friedman',methodVersion:INFERENCE_ENGINE_VERSION}}

export function correlation(input){const x=finite(input.x,'X'),y=finite(input.y,'Y');if(x.length!==y.length||x.length<3)throw new Error('Correlation requires at least three paired observations.');const selected=input.method||'pearson',result=selected==='spearman'?spearmanCorrelationTest(x,y):selected==='kendall'?kendallTauTest(x,y):pearsonCorrelationTest(x,y),coefficient=result.r??result.rho??result.tau,z=Math.atanh(Math.max(-.999999999,Math.min(.999999999,coefficient))),se=1/Math.sqrt(x.length-3),critical=invNorm(1-(1-(input.confidence??.95))/2),confidenceInterval=selected==='pearson'&&x.length>3?[Math.tanh(z-critical*se),Math.tanh(z+critical*se)]:null;return{...result,method:selected,methodVersion:INFERENCE_ENGINE_VERSION,coefficient,confidenceInterval,strength:Math.abs(coefficient)>=.7?'strong':Math.abs(coefficient)>=.4?'moderate':'weak',direction:coefficient>0?'positive':coefficient<0?'negative':'none',warnings:['Correlation does not imply causation.']}}
