import Papa from 'papaparse';
import { applyIntakeCleanup, createIntakeReview, defaultCleanupOptions } from './intakeReview';

const review = matrix => createIntakeReview({ matrix, source: 'test' });
test('clean Excel paste remains a fast path',()=>{const result=review([['Part','Operator','Measurement'],['1','A','10.12'],['1','B','10.08'],['2','A','12.41']]);expect(result).toMatchObject({headerRowIndex:0,rowCount:3,columnCount:3,requiresReview:false})});
test('detects title rows before probable headers',()=>expect(review([['Quarterly study'],[],['Part','Value'],['A','1'],['B','2']])).toMatchObject({headerRowIndex:2,requiresReview:true}));
test('detects blank rows and columns',()=>{const result=review([['A','','B'],['1','','2'],['','',''],['3','','4']]);expect(result.issues.map(issue=>issue.id)).toEqual(expect.arrayContaining(['blank-rows','blank-columns']))});
test('detects duplicate and missing headers',()=>{const result=review([['A','A',''],['1','2','3']]);expect(result.issues.map(issue=>issue.id)).toEqual(expect.arrayContaining(['duplicate-headers','missing-headers']))});
test('detects inconsistent rows',()=>expect(review([['A','B'],['1'],['2','3']]).issues.some(issue=>issue.id==='inconsistent-rows')).toBe(true));
test('recognizes numeric strings, currency, percentages and dates',()=>{const result=review([['Number','Currency','Percent','Date'],['1,250','$1,250.50','25%','2026-08-09'],['2,500','$9.00','50%','2026-08-10']]);expect(result.columns.map(column=>column.inferredType)).toEqual(['numeric','numeric','numeric','date']);expect(result.columns[1].currencyCount).toBe(2);expect(result.columns[2].percentageCount).toBe(2)});
test('flags mostly numeric mixed-type columns with row evidence',()=>{const rows=[['Cycle Time'],...Array.from({length:8},(_,index)=>[String(index+1)]),['unknown'],['machine down']];const issue=review(rows).issues.find(item=>item.id==='mixed-0');expect(issue.values.map(item=>item.value)).toEqual(['unknown','machine down'])});
test('recognizes standard missing tokens but never zero',()=>{const result=review([['Y'],['NA'],['N/A'],['null'],['0']]);expect(result.missingTokens).toEqual(expect.arrayContaining(['NA','N/A','null']));const cleaned=applyIntakeCleanup(result,defaultCleanupOptions(result));expect(cleaned.columns[0].data).toContain('0')});
test('Papa Parse preserves quoted CSV fields containing commas',()=>{const parsed=Papa.parse('Name,Note\nA,"one, two"',{header:false,skipEmptyLines:false});const result=applyIntakeCleanup(createIntakeReview({matrix:parsed.data,parserErrors:parsed.errors,source:'csv'}));expect(result.columns[1].data[0]).toBe('one, two')});
test('cleanup records operations and preserves the original representation',()=>{const source=[['Title'],['A','B'],[' 1 ','$2.00'],['NA','25%']];const intake=review(source);const options={...defaultCleanupOptions(intake),convertNumericText:true,parseCurrency:true,parsePercentages:true};const result=applyIntakeCleanup(intake,options);expect(result.sourceRepresentation.matrix).toEqual(source);expect(result.lineage.operations).toEqual(expect.arrayContaining(['Trim leading/trailing whitespace','Parse currency','Parse percentages']))});
test('malformed and large reasonable input cannot crash review',()=>{expect(()=>review([null,['A'],{bad:true}])).not.toThrow();const large=[['A','B'],...Array.from({length:5000},(_,index)=>[String(index),String(index*2)])];expect(review(large).rowCount).toBe(5000)});
