import{addVsmNode,capacityAnalysis,connectVsm,createVsm,dailyManagement,deleteVsmNode,editWorkElement,futureStateFrom,heijunka,kanbanDesign,moveVsmNode,moveWorkElement,oee,reorderWorkElement,smed,standardWork,taktTime,updateVsmConnection,updateVsmNode,vsmTimeline,xMatrix,yamazumi}from'./leanEnterpriseEngine';
const scope={userId:'u',organizationId:'o',projectId:'p'};
test('VSM nodes, semantic connections, future state and timeline survive reopening shapes',()=>{let map=createVsm({},scope);map=addVsmNode(map,{id:'p1',type:'Process',x:10,y:20,data:{cycleTime:5,waitingTime:40}});map=addVsmNode(map,{id:'p2',type:'Process',x:100,y:20,data:{cycleTime:7}});map=connectVsm(map,{fromId:'p1',toId:'p2',type:'Material Flow'});expect(vsmTimeline(map)).toMatchObject({processingTime:12,waitingTime:40,leadTime:52});expect(futureStateFrom(map)).toMatchObject({state:'future',parentMapId:map.id});expect(JSON.parse(JSON.stringify(map)).connections[0].type).toBe('Material Flow')});
test('takt/capacity distinguish metrics',()=>{const takt=taktTime({demand:100,scheduledMinutes:500,breakMinutes:20,plannedDowntimeMinutes:30});expect(takt.taktMinutesPerUnit).toBe(4.5);const result=capacityAnalysis([{id:'A',cycleTime:5,uptime:.9,availableTime:450,parallelResources:2,yield:.98,demand:100},{id:'B',cycleTime:4,uptime:1,availableTime:450,parallelResources:1,yield:1,demand:100}],4.5);expect(result.processes[0].effectiveCapacity).toBeCloseTo(158.76);expect(result.highestUtilization).toBe('B')});
test('Yamazumi reassigns work and calculates balance',()=>{let elements=[{id:'a',station:'S1',cycleTime:4},{id:'b',station:'S1',cycleTime:3},{id:'c',station:'S2',cycleTime:2}];elements=moveWorkElement(elements,'b','S2');expect(yamazumi(elements,5)).toMatchObject({theoreticalStations:2,bottleneckStation:'S2'})});
test('standard work, Kanban, Heijunka, OEE and SMED guard calculations',()=>{expect(standardWork([{duration:2,type:'Manual'},{duration:3,type:'Machine'}],4).aboveTakt).toBe(true);expect(kanbanDesign({demandRate:10,leadTime:2,containerQuantity:6,safetyFactor:.1}).requiredKanban).toBe(4);expect(heijunka({products:[{name:'A',demand:10,cycleTime:6},{name:'B',demand:10,cycleTime:6}],availableTime:100,pitch:10,changeoverTime:5}).feasible).toBe(false);expect(oee({plannedProductionTime:100,runTime:90,idealCycleTime:1,totalCount:80,goodCount:76}).oee).toBeCloseTo(.76);expect(smed([{id:'x',duration:10,futureDuration:5,classification:'Internal'}]).reduction).toBe(5)});
test('daily management and X-matrix preserve deterministic relationships',()=>{expect(dailyManagement([{target:5,actual:7,direction:'upper'}])[0].abnormality).toBe(true);expect(()=>xMatrix({breakthroughObjectives:[{id:'b'}],annualObjectives:[],initiatives:[],metrics:[],relationships:[{fromId:'b',toId:'missing',strength:9}]})).toThrow('existing endpoints')});
test('VSM authoring moves, edits and deletes nodes and reconnects semantic links',()=>{let map=createVsm({},scope);map=addVsmNode(map,{id:'a',type:'Process',x:0,y:0});map=addVsmNode(map,{id:'b',type:'Inventory',x:20,y:0});map=connectVsm(map,{id:'c',fromId:'a',toId:'b',type:'Material Flow'});map=moveVsmNode(map,'a',40,50);map=updateVsmNode(map,'a',{label:'Assembly',data:{cycleTime:6,wip:3}});map=updateVsmConnection(map,'c',{type:'Pull Movement',label:'FIFO'});expect(map.nodes[0]).toMatchObject({x:40,y:50,label:'Assembly',data:{cycleTime:6,wip:3}});expect(map.connections[0]).toMatchObject({type:'Pull Movement',label:'FIFO'});expect(deleteVsmNode(map,'b').connections).toHaveLength(0)});
test('Yamazumi elements support edit, reassignment and ordering without mutation',()=>{const original=[{id:'a',station:'S1',cycleTime:2,classification:'VA'},{id:'b',station:'S2',cycleTime:3,classification:'NVA'}],edited=editWorkElement(moveWorkElement(original,'b','S1'),'b',{cycleTime:4,classification:'VA'}),ordered=reorderWorkElement(edited,'b',0);expect(ordered[0]).toMatchObject({id:'b',station:'S1',cycleTime:4,classification:'VA'});expect(original[1].station).toBe('S2')});
