export const LEAN_ENGINE_VERSION='1.0.0';
const finite=(v,l)=>{const n=Number(v);if(!Number.isFinite(n))throw new Error(`${l} must be finite.`);return n};
const positive=(v,l)=>{const n=finite(v,l);if(!(n>0))throw new Error(`${l} must be positive.`);return n};
export const WASTES=Object.freeze(['Defects','Overproduction','Waiting','Non-utilized talent','Transportation','Inventory','Motion','Extra-processing']);
export const VSM_NODE_TYPES=Object.freeze(['Supplier','Customer','Production Control','Process','Shared Process','Work Cell','Inventory','Supermarket','FIFO Lane','Shipment','Operator','Kaizen Burst','Problem Indicator']);
export const VSM_CONNECTION_TYPES=Object.freeze(['Material Flow','Push Movement','Pull Movement','Manual Information','Electronic Information','Production Signal','Kanban Signal','Withdrawal Signal','Production Kanban','Withdrawal Kanban','Signal Kanban']);
const uid=p=>`${p}-${Date.now()}-${Math.random().toString(36).slice(2,7)}`;
export function createLeanArtifact(type,input={},scope={}){if(!scope.userId||!scope.organizationId||!scope.projectId)throw new Error('Authenticated organization/project scope is required.');return{schemaVersion:1,id:input.id||uid(type),type,organizationId:scope.organizationId,projectId:scope.projectId,createdBy:scope.userId,title:input.title||`Untitled ${type}`,revision:input.revision||1,status:input.status||'Draft',createdAt:input.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),history:input.history||[],...input}}
export function reviseLeanArtifact(artifact,updates,userId,reason){if(!userId)throw new Error('Authenticated user is required.');const changes={};Object.entries(updates).forEach(([k,v])=>{if(JSON.stringify(artifact[k])!==JSON.stringify(v))changes[k]={prior:artifact[k],next:v}});if(!Object.keys(changes).length)return artifact;return{...artifact,...updates,revision:artifact.revision+1,updatedAt:new Date().toISOString(),history:[...(artifact.history||[]),{revision:artifact.revision+1,changes,userId,reason:reason||'',at:new Date().toISOString()}]}}
export function createVsm(input={},scope){return createLeanArtifact('value-stream-map',{title:input.title||'Current-State VSM',state:input.state||'current',parentMapId:input.parentMapId||null,nodes:input.nodes||[],connections:input.connections||[],wastes:input.wastes||[],assumptions:input.assumptions||{}},scope)}
export function addVsmNode(map,node){if(!VSM_NODE_TYPES.includes(node.type))throw new Error('Unsupported VSM node type.');return{...map,nodes:[...map.nodes,{id:node.id||uid('node'),label:node.label||node.type,x:finite(node.x??80,'Node x'),y:finite(node.y??80,'Node y'),data:{cycleTime:0,changeoverTime:0,uptime:1,availableTime:0,operators:1,shifts:1,batchSize:1,scrapRate:0,wip:0,inventory:0,demand:0,yield:1,...node.data},...node}]}}
export function connectVsm(map,connection){if(!map.nodes.some(n=>n.id===connection.fromId)||!map.nodes.some(n=>n.id===connection.toId))throw new Error('VSM connection endpoints must exist.');if(!VSM_CONNECTION_TYPES.includes(connection.type))throw new Error('Unsupported VSM connection type.');return{...map,connections:[...map.connections,{id:connection.id||uid('connection'),label:connection.label||'',...connection}]}}
export function updateVsmNode(map,nodeId,updates){if(!map.nodes.some(node=>node.id===nodeId))throw new Error('VSM node does not exist.');return{...map,nodes:map.nodes.map(node=>node.id===nodeId?{...node,...updates,data:{...node.data,...(updates.data||{})}}:node)}}
export function moveVsmNode(map,nodeId,x,y){return updateVsmNode(map,nodeId,{x:finite(x,'Node x'),y:finite(y,'Node y')})}
export function deleteVsmNode(map,nodeId){return{...map,nodes:map.nodes.filter(node=>node.id!==nodeId),connections:map.connections.filter(link=>link.fromId!==nodeId&&link.toId!==nodeId)}}
export function updateVsmConnection(map,connectionId,updates){if(updates.type&&!VSM_CONNECTION_TYPES.includes(updates.type))throw new Error('Unsupported VSM connection type.');if(!map.connections.some(link=>link.id===connectionId))throw new Error('VSM connection does not exist.');if((updates.fromId&&!map.nodes.some(node=>node.id===updates.fromId))||(updates.toId&&!map.nodes.some(node=>node.id===updates.toId)))throw new Error('VSM connection endpoints must exist.');return{...map,connections:map.connections.map(link=>link.id===connectionId?{...link,...updates}:link)}}
export function vsmTimeline(map){const processes=map.nodes.filter(n=>['Process','Shared Process','Work Cell'].includes(n.type)),processing=processes.reduce((s,n)=>s+Number(n.data?.cycleTime||0),0),waiting=map.nodes.reduce((s,n)=>s+Number(n.data?.waitingTime||n.data?.inventoryWait||0),0),leadTime=processing+waiting;return{processingTime:processing,waitingTime:waiting,leadTime,processCycleEfficiency:leadTime?processing/leadTime:null,contributions:processes.map(n=>({id:n.id,label:n.label,processing:Number(n.data?.cycleTime||0),waiting:Number(n.data?.waitingTime||0)}))}}
export function futureStateFrom(current){return{...current,id:uid('vsm'),title:`${current.title} — Future State`,state:'future',parentMapId:current.id,revision:1,history:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),nodes:current.nodes.map(n=>({...n,data:{...n.data}})),connections:current.connections.map(c=>({...c}))}}
export function taktTime({demand,scheduledMinutes,breakMinutes=0,plannedDowntimeMinutes=0,period='shift'}){const d=positive(demand,'Customer demand'),available=positive(finite(scheduledMinutes,'Scheduled time')-finite(breakMinutes,'Break time')-finite(plannedDowntimeMinutes,'Planned downtime'),'Available production time');return{method:'takt-time',methodVersion:LEAN_ENGINE_VERSION,demand:d,period,availableMinutes:available,taktMinutesPerUnit:available/d,requiredUnitsPerMinute:d/available}}
export function capacityAnalysis(processes,takt){const rows=processes.map(p=>{const cycle=positive(p.cycleTime,'Cycle time'),uptime=finite(p.uptime??1,'Uptime'),available=positive(p.availableTime,'Available time'),parallel=positive(p.parallelResources??1,'Parallel resources'),yieldRate=finite(p.yield??1,'Yield'),capacity=available*uptime*parallel/cycle*yieldRate,demand=finite(p.demand,'Demand'),utilization=demand/capacity;return{...p,effectiveCapacity:capacity,utilization,capacityGap:capacity-demand,taktStatus:cycle>takt?'Above takt':cycle>=.9*takt?'Near takt':cycle<.6*takt?'Excess capacity':'Below takt'}}),highest=[...rows].sort((a,b)=>b.utilization-a.utilization)[0],lowest=[...rows].sort((a,b)=>a.effectiveCapacity-b.effectiveCapacity)[0],longest=[...rows].sort((a,b)=>b.cycleTime-a.cycleTime)[0];return{processes:rows,highestUtilization:highest?.id,lowestEffectiveCapacity:lowest?.id,longestCycle:longest?.id,constraintConclusion:highest?.id===lowest?.id?`Evidence identifies ${highest.id} as the leading constraint candidate.`:'Metrics disagree; observe actual queues, starvation and blocking before declaring the constraint.'}}
export function yamazumi(elements,takt){const stations=[...new Set(elements.map(e=>e.station))].map(station=>{const items=elements.filter(e=>e.station===station),load=items.reduce((s,e)=>s+finite(e.cycleTime,'Element time'),0);return{station,load,idleTime:Math.max(0,takt-load),aboveTakt:load>takt,elements:items}}),total=elements.reduce((s,e)=>s+Number(e.cycleTime),0),max=Math.max(...stations.map(s=>s.load));return{stations,takt,totalWork:total,maximumStationLoad:max,theoreticalStations:Math.ceil(total/takt),balanceEfficiency:total/(stations.length*max),balanceDelay:1-total/(stations.length*max),bottleneckStation:stations.find(s=>s.load===max)?.station}}
export const moveWorkElement=(elements,id,station)=>elements.map(e=>e.id===id?{...e,station}:e);
export const editWorkElement=(elements,id,updates)=>elements.map(element=>element.id===id?{...element,...updates}:element);
export const reorderWorkElement=(elements,id,index)=>{const source=elements.find(element=>element.id===id);if(!source)return elements;const rest=elements.filter(element=>element.id!==id),target=Math.max(0,Math.min(Number(index)||0,rest.length));return[...rest.slice(0,target),source,...rest.slice(target)]};
export function kanbanDesign({demandRate,leadTime,containerQuantity,safetyFactor=0,variabilityAllowance=0}){const raw=positive(demandRate,'Demand rate')*positive(leadTime,'Lead time')*(1+finite(safetyFactor,'Safety factor')+finite(variabilityAllowance,'Variability allowance'))/positive(containerQuantity,'Container quantity');return{rawKanban:raw,requiredKanban:Math.ceil(raw),rounding:'Rounded upward to the next whole Kanban.',maxWip:Math.ceil(raw)*Number(containerQuantity)}}
export function heijunka({products,availableTime,pitch,changeoverTime=0}){const demand=products.reduce((s,p)=>s+positive(p.demand,`${p.name} demand`),0),required=products.reduce((s,p)=>s+positive(p.demand,`${p.name} demand`)*positive(p.cycleTime,`${p.name} cycle time`),0),changeovers=Math.max(0,products.length-1)*finite(changeoverTime,'Changeover time'),feasible=required+changeovers<=positive(availableTime,'Available time'),slots=Math.floor(availableTime/positive(pitch,'Pitch')),pattern=Array.from({length:slots},(_,i)=>products[i%products.length].name);return{demand,productionTimeRequirement:required,changeoverTimeRequirement:changeovers,availableChangeoverWindow:availableTime-required,feasible,pattern,epei:products.length*Number(pitch),warning:feasible?null:'Leveling is infeasible with the entered capacity and changeover requirements.'}}
export function oee({plannedProductionTime,runTime,idealCycleTime,totalCount,goodCount,losses=[]}){const planned=positive(plannedProductionTime,'Planned production time'),run=finite(runTime,'Run time'),total=positive(totalCount,'Total count'),good=finite(goodCount,'Good count');if(run<0||run>planned||good<0||good>total)throw new Error('OEE times/counts are inconsistent.');const availability=run/planned,performance=Math.min(1,positive(idealCycleTime,'Ideal cycle time')*total/run),quality=good/total;return{availability,performance,quality,oee:availability*performance*quality,losses,lossSummary:Object.fromEntries(['Breakdowns','Setup/Adjustment','Minor Stops','Reduced Speed','Startup/Reduced Yield','Defects/Rework'].map(type=>[type,losses.filter(l=>l.category===type).reduce((s,l)=>s+Number(l.duration||l.count||0),0)]))}}
export function smed(elements){const current=elements.reduce((s,e)=>s+positive(e.duration,'Changeover duration'),0),future=elements.reduce((s,e)=>s+positive(e.futureDuration??e.duration,'Future duration'),0),internal=elements.filter(e=>e.classification==='Internal').reduce((s,e)=>s+Number(e.duration),0);return{currentTime:current,futureTime:future,reduction:current-future,reductionPercent:(current-future)/current,internalTime:internal,externalTime:current-internal,parallelOpportunities:elements.filter(e=>e.parallelCandidate).map(e=>e.id),timeline:elements.map((e,i)=>({...e,sequence:i+1}))}}
export function standardWork(elements,takt){let cursor=0;return{sequence:elements.map((e,i)=>{const start=cursor;cursor+=positive(e.duration,'Work duration');return{...e,sequence:i+1,start,end:cursor}}),cycleTime:cursor,takt,aboveTakt:cursor>takt,standardWip:elements.reduce((s,e)=>s+Number(e.standardWip||0),0)}}
export function abnormalityStatus(records){return records.map(r=>({...r,boardStatus:r.escalated?'Escalated':r.stopRequired?'Stopped':r.contained?'Attention':'Normal'}))}
export function dailyManagement(metrics){return metrics.map(m=>{const actual=finite(m.actual,'Actual'),target=finite(m.target,'Target'),miss=m.direction==='lower'?actual<target:actual>target;return{...m,gap:actual-target,abnormality:miss,status:miss?(m.escalated?'Escalated':'Attention'):'Normal'}})}
export function xMatrix(input){const ids=new Set([...input.breakthroughObjectives,...input.annualObjectives,...input.initiatives,...input.metrics].map(x=>x.id));input.relationships.forEach(r=>{if(!ids.has(r.fromId)||!ids.has(r.toId)||![1,3,9].includes(r.strength))throw new Error('X-Matrix relationships require existing endpoints and strength 1, 3, or 9.')});return{...input,relationshipCount:input.relationships.length,coverage:input.annualObjectives.map(o=>({id:o.id,initiatives:input.relationships.filter(r=>r.fromId===o.id||r.toId===o.id).length}))}}
export function leanFinding(condition,context){if(!condition?.triggered)return null;return{findingType:condition.type,sourceType:condition.sourceType,sourceId:condition.sourceId,projectId:context.projectId,organizationId:context.organizationId,process:condition.process,metric:condition.metric,threshold:condition.threshold,rule:condition.rule,evidence:condition.evidence||{},createdAt:new Date().toISOString(),status:'open'}}
