import { analyzePlackettBurman, fitMixtureModel, generateMixtureDesign, generatePlackettBurman, generateTaguchiDesign, monteCarloSimulation, readinessSummary, taguchiSignalToNoise, toleranceStack, tostMeans, verificationDecision } from './productDevelopmentEngine';

describe('Wave 5A screening and robust design',()=>{
 test('generates reproducible orthogonal Plackett-Burman screening and effects',()=>{const factors=['A','B','C','D'].map(name=>({name,low:0,high:1})),design=generatePlackettBurman({factors,runs:8,seed:7});expect(generatePlackettBurman({factors,runs:8,seed:7}).runs).toEqual(design.runs);for(const factor of factors)expect(design.runs.reduce((sum,row)=>sum+row.factorCodes[factor.name],0)).toBe(0);const responses=design.runs.map(run=>10+3*run.factorCodes.A-run.factorCodes.B),analysis=analyzePlackettBurman(design,responses);expect(analysis.effects[0]).toMatchObject({factor:'A',effect:6});expect(analysis.uncertainty).toBeNull()});
 test('guards Taguchi array constraints and reports response and S/N',()=>{const design=generateTaguchiDesign({array:'L9',factors:[{name:'A',levels:[1,2,3]},{name:'B',levels:[10,20,30]}],seed:3});expect(design.runs).toHaveLength(9);expect(()=>generateTaguchiDesign({array:'L4',factors:[{name:'A',levels:[1,2,3]}]})).toThrow('exactly 2');const sn=taguchiSignalToNoise([10,11,9],'nominal');expect(sn.meanResponse).toBe(10);expect(sn.standardDeviation).toBe(1)});
});

describe('Wave 5A mixture, simulation, and tolerance stack',()=>{
 test('generates constrained mixture points and fits Scheffe model',()=>{const design=generateMixtureDesign({components:['A','B','C'],type:'simplex-centroid'});expect(design.runs.every(run=>Math.abs(Object.values(run.proportions).reduce((a,b)=>a+b,0)-1)<1e-10)).toBe(true);const rows=design.runs.map(run=>({...run.proportions,response:2*run.proportions.A+3*run.proportions.B+4*run.proportions.C+run.proportions.A*run.proportions.B}));expect(fitMixtureModel(rows,['A','B','C'],'quadratic').rSquared).toBeCloseTo(1,8);expect(()=>fitMixtureModel([{A:.7,B:.7,response:1}],['A','B'],'linear')).toThrow('sums')});
 test('runs deterministic safe Monte Carlo with correlation validation',()=>{const input={inputs:[{name:'A',unit:'mm',distribution:'normal',parameters:{mean:10,sd:1}},{name:'B',unit:'mm',distribution:'fixed',parameters:{value:2}}],expression:'A+B',count:2000,seed:4,lsl:8,usl:16},a=monteCarloSimulation(input),b=monteCarloSimulation(input);expect(a.mean).toBe(b.mean);expect(a.completionStatus).toBe('complete');expect(a.sensitivity[0].input).toBe('A');expect(()=>monteCarloSimulation({...input,expression:'window.alert(1)'})).toThrow('unsafe');expect(()=>monteCarloSimulation({...input,correlation:[[1,.8],[0,1]]})).toThrow('dimensions')});
 test('keeps worst case, RSS, and Monte Carlo stack results distinct',()=>{const result=toleranceStack({contributors:[{name:'A',nominal:10,tolerance:1,direction:1,unit:'mm'},{name:'B',nominal:3,minusTolerance:.2,plusTolerance:.4,direction:-1,unit:'mm'}],count:1000,seed:2,lsl:5,usl:9});expect(result.nominalAssembly).toBe(7);expect(result.worstCase).toEqual(expect.objectContaining({minimum:5.6,maximum:8.2}));expect(result.rss.threeSigma).toBeGreaterThan(0);expect(result.monteCarlo.simulationCount).toBe(1000)});
});

describe('Wave 5A verification and comparison governance',()=>{
 test('TOST distinguishes equivalence from no detected difference',()=>{expect(tostMeans({groupA:[10,10.1,9.9,10],groupB:[10.05,10,10.1,9.95],margin:.5}).equivalent).toBe(true);expect(tostMeans({groupA:[10,14],groupB:[10,14],margin:.1}).equivalent).toBe(false)});
 test('requires evidence for PASS and summarizes readiness without inventing a gate',()=>{const record={id:'V1',requirementId:'R1',ctqId:'C1',result:'Pass',evidence:'report',rationale:'criterion met',linkedAnalysisId:'A1'};expect(verificationDecision(record).evidenceBacked).toBe(true);expect(()=>verificationDecision({...record,evidence:''})).toThrow('PASS requires');expect(readinessSummary({requirements:[{id:'R1',ctqIds:['C1']}],verifications:[record],risks:[],evidence:['A1']}).ready).toBe(true)});
});
