import { invNorm, normCDF } from './statMath';

export const PRODUCT_DEVELOPMENT_ENGINE_VERSION = '1.0.0';
const finite = (value, label) => { const number = Number(value); if (!Number.isFinite(number)) throw new Error(`${label} must be finite.`); return number; };
const mean = values => values.reduce((sum, value) => sum + value, 0) / values.length;
const variance = values => values.reduce((sum, value) => sum + (value - mean(values)) ** 2, 0) / (values.length - 1);
const seededRandom = seed => { let state = (Number(seed) || 1) >>> 0; return () => { state = (1664525 * state + 1013904223) >>> 0; return state / 4294967296; }; };
const shuffle = (items, seed) => { const random = seededRandom(seed), copy = [...items]; for (let i = copy.length - 1; i > 0; i -= 1) { const j = Math.floor(random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; };
const normalRandom = random => { const u1 = Math.max(random(), Number.EPSILON), u2 = random(); return Math.sqrt(-2 * Math.log(u1)) * Math.cos(2 * Math.PI * u2); };

const PB_ROWS = Object.freeze({
  4: [[1,1,1],[1,-1,-1],[-1,1,-1],[-1,-1,1]],
  8: Array.from({ length: 8 }, (_, row) => Array.from({ length: 7 }, (_, column) => { let bits = row & (column + 1), parity = 0; while (bits) { parity ^= bits & 1; bits >>= 1; } return parity ? -1 : 1; })),
  12: (() => { const first = [1,1,-1,1,1,1,-1,-1,-1,1,-1], rows = []; for (let shift = 0; shift < 11; shift += 1) rows.push([...first.slice(shift), ...first.slice(0, shift)]); rows.push(Array(11).fill(-1)); return rows; })(),
});

export function generatePlackettBurman({ factors = [], runs, seed = 20260810, randomize = true } = {}) {
  if (factors.length < 2) throw new Error('Plackett-Burman screening requires at least two factors.');
  if (new Set(factors.map(item => item.name)).size !== factors.length) throw new Error('Screening factor names must be unique.');
  const size = Number(runs) || [4,8,12].find(value => value - 1 >= factors.length);
  if (!PB_ROWS[size] || factors.length > size - 1) throw new Error('Supported Plackett-Burman sizes are 4, 8, and 12 runs with no more than N−1 factors.');
  const standard = PB_ROWS[size].map((codes, index) => ({ standardOrder: index + 1, factorCodes: Object.fromEntries(factors.map((factor, column) => [factor.name, codes[column]])), factorSettings: Object.fromEntries(factors.map((factor, column) => [factor.name, codes[column] < 0 ? factor.low : factor.high])) }));
  const ordered = randomize ? shuffle(standard, seed) : standard;
  return { method: 'plackett-burman-screening', methodVersion: PRODUCT_DEVELOPMENT_ENGINE_VERSION, designSize: size, factors, seed, randomized: randomize, runs: ordered.map((run, index) => ({ ...run, runOrder: index + 1 })), explanation: 'Screening estimates main effects efficiently but sacrifices interaction resolution. Main effects may be confounded with interactions.' };
}

export function analyzePlackettBurman(design, responses = []) {
  if (!design?.runs?.length || responses.length !== design.runs.length || responses.some(value => !Number.isFinite(Number(value)))) throw new Error('Enter one finite response for every screening run.');
  const values = responses.map(Number), overall = mean(values);
  const effects = design.factors.map(factor => { const high = [], low = []; design.runs.forEach((run, index) => (run.factorCodes[factor.name] > 0 ? high : low).push(values[index])); const effect = mean(high) - mean(low); return { factor: factor.name, effect, absoluteEffect: Math.abs(effect), coefficient: effect / 2 }; }).sort((a, b) => b.absoluteEffect - a.absoluteEffect);
  return { method: 'plackett-burman-main-effects', methodVersion: PRODUCT_DEVELOPMENT_ENGINE_VERSION, grandMean: overall, effects, uncertainty: null, warning: 'Without replication or designated error columns, pure-error ANOVA and effect p-values are not estimable. Confirm important factors in a higher-resolution design.' };
}

const TAGUCHI_ARRAYS = Object.freeze({
  L4: { levels: 2, columns: 3, rows: PB_ROWS[4] },
  L8: { levels: 2, columns: 7, rows: PB_ROWS[8] },
  L9: { levels: 3, columns: 4, rows: Array.from({ length: 9 }, (_, i) => [i % 3, Math.floor(i / 3) % 3, (i + Math.floor(i / 3)) % 3, (i + 2 * Math.floor(i / 3)) % 3]) },
});

export function generateTaguchiDesign({ array = 'L8', factors = [], seed = 20260810, randomize = true } = {}) {
  const definition = TAGUCHI_ARRAYS[array];
  if (!definition) throw new Error('Supported orthogonal arrays are L4, L8, and L9. L12/L16/L18 require additional independently verified array definitions.');
  if (!factors.length || factors.length > definition.columns) throw new Error(`${array} supports 1 to ${definition.columns} factors.`);
  factors.forEach(factor => { if (!Array.isArray(factor.levels) || factor.levels.length !== definition.levels) throw new Error(`${factor.name || 'Each factor'} must define exactly ${definition.levels} levels for ${array}.`); });
  const standard = definition.rows.map((row, index) => ({ standardOrder: index + 1, factorLevels: Object.fromEntries(factors.map((factor, column) => [factor.name, factor.levels[row[column] < 0 ? (row[column] + 1) / 2 : row[column]]])) }));
  const ordered = randomize ? shuffle(standard, seed) : standard;
  return { method: 'taguchi-orthogonal-array', methodVersion: PRODUCT_DEVELOPMENT_ENGINE_VERSION, array, factors, seed, randomized: randomize, runs: ordered.map((run, index) => ({ ...run, runOrder: index + 1 })), metadata: { runs: definition.rows.length, levels: definition.levels, availableColumns: definition.columns } };
}

export function taguchiSignalToNoise(replicates, objective = 'smaller') {
  const values = replicates.map(Number);
  if (!values.length || values.some(value => !Number.isFinite(value))) throw new Error('S/N calculation requires finite replicated responses.');
  let ratio;
  if (objective === 'smaller') ratio = -10 * Math.log10(mean(values.map(value => value ** 2)));
  else if (objective === 'larger') { if (values.some(value => value === 0)) throw new Error('Larger-is-better S/N is undefined for zero responses.'); ratio = -10 * Math.log10(mean(values.map(value => 1 / value ** 2))); }
  else if (objective === 'nominal') { const sampleVariance = variance(values); if (!(sampleVariance > 0)) throw new Error('Nominal-is-best S/N requires replicated variation greater than zero.'); ratio = 10 * Math.log10(mean(values) ** 2 / sampleVariance); }
  else throw new Error('S/N objective must be smaller, larger, or nominal.');
  return { objective, meanResponse: mean(values), standardDeviation: values.length > 1 ? Math.sqrt(variance(values)) : null, signalToNoise: ratio, warning: 'S/N ranks robustness only under its stated loss function; inspect response magnitude and variation separately.' };
}

export function generateMixtureDesign({ components = [], type = 'simplex-centroid', degree = 2, total = 1 } = {}) {
  if (components.length < 2 || components.length > 4 || new Set(components).size !== components.length) throw new Error('Mixture DOE requires 2 to 4 uniquely named components.');
  const target = finite(total, 'Mixture total'); if (!(target > 0)) throw new Error('Mixture total must be positive.');
  let points = components.map((_, i) => components.map((__, j) => i === j ? target : 0));
  if (type === 'simplex-centroid') for (let mask = 1; mask < 2 ** components.length; mask += 1) { const active = components.map((_, i) => (mask >> i) & 1).reduce((sum, value) => sum + value, 0); if (active > 1) points.push(components.map((_, i) => (mask >> i) & 1 ? target / active : 0)); }
  else if (type === 'simplex-lattice') { const m = Math.round(finite(degree, 'Lattice degree')); if (m < 1 || m > 6) throw new Error('Simplex-lattice degree must be from 1 to 6.'); points = []; const recurse = (remaining, index, row) => { if (index === components.length - 1) { points.push([...row, remaining].map(value => target * value / m)); return; } for (let value = 0; value <= remaining; value += 1) recurse(remaining - value, index + 1, [...row, value]); }; recurse(m, 0, []); }
  else throw new Error('Mixture design type must be simplex-centroid or simplex-lattice.');
  const unique = [...new Map(points.map(point => [point.map(value => value.toFixed(12)).join('|'), point])).values()];
  return { method: type, methodVersion: PRODUCT_DEVELOPMENT_ENGINE_VERSION, components, total: target, runs: unique.map((point, index) => ({ standardOrder: index + 1, proportions: Object.fromEntries(components.map((name, column) => [name, point[column]])) })), constraint: `${components.join(' + ')} = ${target}` };
}

function solveLinear(matrix, vector) { const a = matrix.map((row, i) => [...row, vector[i]]), n = a.length; for (let i = 0; i < n; i += 1) { let pivot = i; for (let j = i + 1; j < n; j += 1) if (Math.abs(a[j][i]) > Math.abs(a[pivot][i])) pivot = j; [a[i], a[pivot]] = [a[pivot], a[i]]; if (Math.abs(a[i][i]) < 1e-10) throw new Error('Mixture model is singular; add distinct design points or reduce model order.'); const divisor = a[i][i]; a[i] = a[i].map(value => value / divisor); for (let j = 0; j < n; j += 1) if (j !== i) { const factor = a[j][i]; a[j] = a[j].map((value, k) => value - factor * a[i][k]); } } return a.map(row => row[n]); }
export function fitMixtureModel(rows, components, order = 'quadratic', total = 1) {
  if (!rows.length || !components?.length) throw new Error('Mixture modeling requires design rows and component names.');
  const terms = components.map(name => ({ name, evaluate: row => Number(row[name]) })); if (order === 'quadratic') for (let i = 0; i < components.length; i += 1) for (let j = i + 1; j < components.length; j += 1) terms.push({ name: `${components[i]}:${components[j]}`, evaluate: row => Number(row[components[i]]) * Number(row[components[j]]) }); else if (order !== 'linear') throw new Error('Supported Scheffé models are linear and quadratic.');
  const x = rows.map((row, index) => { const sum = components.reduce((value, name) => value + finite(row[name], `${name} on row ${index + 1}`), 0); if (Math.abs(sum - total) > 1e-8) throw new Error(`Mixture row ${index + 1} sums to ${sum}, not ${total}.`); return terms.map(term => term.evaluate(row)); }), y = rows.map((row, index) => finite(row.response, `Response on row ${index + 1}`));
  if (rows.length < terms.length) throw new Error(`The ${order} Scheffé model needs at least ${terms.length} design points.`);
  const xtx = terms.map((_, i) => terms.map((__, j) => x.reduce((sum, row) => sum + row[i] * row[j], 0))), xty = terms.map((_, i) => x.reduce((sum, row, r) => sum + row[i] * y[r], 0)), coefficients = solveLinear(xtx, xty), predictions = x.map(row => row.reduce((sum, value, i) => sum + value * coefficients[i], 0)), residuals = y.map((value, i) => value - predictions[i]), sse = residuals.reduce((sum, value) => sum + value ** 2, 0), average = mean(y), sst = y.reduce((sum, value) => sum + (value - average) ** 2, 0);
  return { method: `${order}-scheffe-mixture-model`, methodVersion: PRODUCT_DEVELOPMENT_ENGINE_VERSION, terms: terms.map((term, i) => ({ term: term.name, coefficient: coefficients[i] })), rSquared: sst ? 1 - sse / sst : null, sse, predictions, residuals, warning: 'Scheffé mixture terms respect the fixed-sum constraint; process-variable terms are reserved by the data contract but not fitted in this version.' };
}

const OPERATORS = Object.freeze({ '+': { p: 1, f: (a,b) => a+b }, '-': { p: 1, f: (a,b) => a-b }, '*': { p: 2, f: (a,b) => a*b }, '/': { p: 2, f: (a,b) => a/b }, '^': { p: 3, f: (a,b) => a**b } });
function compileSafeExpression(expression, names) { const tokens = String(expression).match(/[A-Za-z_][A-Za-z0-9_]*|(?:\d+\.?\d*|\.\d+)(?:e[+-]?\d+)?|[()+\-*/^]/gi); if (!tokens || tokens.join('').toLowerCase() !== String(expression).replace(/\s+/g,'').toLowerCase()) throw new Error('Expression contains unsupported or unsafe syntax.'); const output=[], stack=[]; tokens.forEach(token => { if (Number.isFinite(Number(token))) output.push(Number(token)); else if (/^[A-Za-z_]/.test(token)) { if (!names.includes(token)) throw new Error(`Unknown response variable: ${token}.`); output.push({ name: token }); } else if (token === '(') stack.push(token); else if (token === ')') { while (stack.length && stack.at(-1) !== '(') output.push(stack.pop()); if (stack.pop() !== '(') throw new Error('Expression parentheses are unbalanced.'); } else { while (stack.length && OPERATORS[stack.at(-1)] && OPERATORS[stack.at(-1)].p >= OPERATORS[token].p) output.push(stack.pop()); stack.push(token); } }); while (stack.length) { const token = stack.pop(); if (token === '(') throw new Error('Expression parentheses are unbalanced.'); output.push(token); } return values => { const evaluation=[]; output.forEach(token => { if (typeof token === 'number') evaluation.push(token); else if (typeof token === 'object') evaluation.push(values[token.name]); else { const b=evaluation.pop(),a=evaluation.pop(); if (!Number.isFinite(a)||!Number.isFinite(b)) throw new Error('Expression could not be evaluated.'); evaluation.push(OPERATORS[token].f(a,b)); } }); if (evaluation.length!==1||!Number.isFinite(evaluation[0]))throw new Error('Expression returned a nonfinite result.'); return evaluation[0]; }; }

function validateCorrelation(matrix, size) { if (!matrix) return null; if (!Array.isArray(matrix)||matrix.length!==size||matrix.some(row=>!Array.isArray(row)||row.length!==size))throw new Error('Correlation matrix dimensions must match stochastic inputs.'); matrix.forEach((row,i)=>row.forEach((value,j)=>{const number=finite(value,'Correlation');if(Math.abs(number-(matrix[j]?.[i]))>1e-10)throw new Error('Correlation matrix must be symmetric.');if(i===j&&Math.abs(number-1)>1e-10)throw new Error('Correlation matrix diagonal must equal 1.')})); const lower=matrix.map(row=>row.map(()=>0));for(let i=0;i<size;i+=1)for(let j=0;j<=i;j+=1){let sum=matrix[i][j];for(let k=0;k<j;k+=1)sum-=lower[i][k]*lower[j][k];if(i===j){if(sum< -1e-10)throw new Error('Correlation matrix must be positive semidefinite.');lower[i][j]=Math.sqrt(Math.max(0,sum));}else lower[i][j]=lower[j][j]?sum/lower[j][j]:0;}return lower; }
function draw(input, random, z) { const distribution=input.distribution||'fixed',p=input.parameters||{};if(distribution==='fixed')return finite(p.value,'Fixed value');if(distribution==='normal'){const sd=finite(p.sd,'Normal SD');if(!(sd>0))throw new Error('Normal SD must be positive.');return finite(p.mean,'Normal mean')+sd*z}if(distribution==='lognormal'){const sdlog=finite(p.sdlog,'Lognormal sdlog');if(!(sdlog>0))throw new Error('Lognormal sdlog must be positive.');return Math.exp(finite(p.meanlog,'Lognormal meanlog')+sdlog*z)}if(distribution==='uniform'){const min=finite(p.min,'Uniform minimum'),max=finite(p.max,'Uniform maximum');if(!(max>min))throw new Error('Uniform maximum must exceed minimum.');return min+(max-min)*random()}if(distribution==='triangular'){const min=finite(p.min,'Triangular minimum'),mode=finite(p.mode,'Triangular mode'),max=finite(p.max,'Triangular maximum');if(!(min<=mode&&mode<=max&&max>min))throw new Error('Triangular parameters require min ≤ mode ≤ max.');const u=random(),f=(mode-min)/(max-min);return u<f?min+Math.sqrt(u*(max-min)*(mode-min)):max-Math.sqrt((1-u)*(max-min)*(max-mode))}if(distribution==='weibull'){const shape=finite(p.shape,'Weibull shape'),scale=finite(p.scale,'Weibull scale');if(!(shape>0&&scale>0))throw new Error('Weibull shape and scale must be positive.');return scale*(-Math.log(Math.max(1-random(),Number.EPSILON)))**(1/shape)}throw new Error(`Unsupported distribution: ${distribution}.`); }

export function monteCarloSimulation({ inputs = [], expression, count = 10000, seed = 20260810, lsl = null, usl = null, correlation = null, responseUnit = '' } = {}) {
  const n=Math.round(finite(count,'Simulation count'));if(n<100||n>200000)throw new Error('Simulation count must be between 100 and 200,000.');if(!inputs.length||new Set(inputs.map(item=>item.name)).size!==inputs.length)throw new Error('Monte Carlo inputs require unique names.');const units=[...new Set(inputs.map(item=>item.unit).filter(Boolean))];if(units.length>1)throw new Error('Inputs use different units; define explicit conversions before combining them.');const evaluate=compileSafeExpression(expression,inputs.map(item=>item.name)),random=seededRandom(seed),stochastic=inputs.filter(item=>item.distribution!=='fixed'),lower=validateCorrelation(correlation,stochastic.length),values=[],inputSamples=Object.fromEntries(inputs.map(item=>[item.name,[]]));for(let iteration=0;iteration<n;iteration+=1){const independent=stochastic.map(()=>normalRandom(random)),correlated=lower?lower.map(row=>row.reduce((sum,value,index)=>sum+value*independent[index],0)):independent;let cursor=0;const row={};inputs.forEach(input=>{const z=input.distribution==='fixed'?0:correlated[cursor++];row[input.name]=draw(input,random,z);inputSamples[input.name].push(row[input.name])});values.push(evaluate(row))}const sorted=[...values].sort((a,b)=>a-b),average=mean(values),sd=Math.sqrt(variance(values)),quantile=p=>sorted[Math.min(n-1,Math.max(0,Math.floor(p*(n-1))))],below=lsl===null?null:values.filter(value=>value<Number(lsl)).length/n,above=usl===null?null:values.filter(value=>value>Number(usl)).length/n,correlationWithResponse=inputs.map(input=>{const x=inputSamples[input.name],mx=mean(x),sx=Math.sqrt(variance(x)),cov=x.reduce((sum,value,index)=>sum+(value-mx)*(values[index]-average),0)/(n-1),r=sx&&sd?cov/(sx*sd):0;return{input:input.name,correlation:r,standardizedContribution:r*r}}).sort((a,b)=>b.standardizedContribution-a.standardizedContribution);return{method:'seeded-engineering-monte-carlo',methodVersion:PRODUCT_DEVELOPMENT_ENGINE_VERSION,seed,simulationCount:n,completionStatus:'complete',responseUnit,mean:average,standardDeviation:sd,percentiles:{p1:quantile(.01),p5:quantile(.05),p50:quantile(.5),p95:quantile(.95),p99:quantile(.99)},probabilityBelowLsl:below,probabilityAboveUsl:above,conformanceProbability:1-(below||0)-(above||0),monteCarloStandardErrorMean:sd/Math.sqrt(n),samples:values,sensitivity:correlationWithResponse,methodology:'Pearson input-response correlation; squared correlations are screening approximations, not causal variance decomposition.',provenance:{expression,inputs,correlationSpecified:Boolean(correlation)}}; }

export function toleranceStack({ contributors = [], lsl = null, usl = null, count = 20000, seed = 20260810 } = {}) { if(!contributors.length)throw new Error('Tolerance stack requires at least one contributor.');const units=[...new Set(contributors.map(item=>item.unit).filter(Boolean))];if(units.length>1)throw new Error('Tolerance contributors must share one engineering unit or provide explicit conversion.');const prepared=contributors.map((item,index)=>{const nominal=finite(item.nominal,`Nominal on contributor ${index+1}`),direction=finite(item.direction??1,`Direction on contributor ${index+1}`);if(![-1,1].includes(direction))throw new Error('Contributor direction must be +1 or -1.');const minus=Math.abs(finite(item.minusTolerance??item.tolerance,`Negative tolerance on contributor ${index+1}`)),plus=Math.abs(finite(item.plusTolerance??item.tolerance,`Positive tolerance on contributor ${index+1}`));return{...item,name:item.name||`Contributor ${index+1}`,nominal,direction,minus,plus}}),nominal=prepared.reduce((sum,item)=>sum+item.direction*item.nominal,0),minimum=prepared.reduce((sum,item)=>sum+item.direction*item.nominal-(item.direction>0?item.minus:item.plus),0),maximum=prepared.reduce((sum,item)=>sum+item.direction*item.nominal+(item.direction>0?item.plus:item.minus),0),rssSigma=Math.sqrt(prepared.reduce((sum,item)=>sum+(((item.minus+item.plus)/2)/3)**2,0)),mc=monteCarloSimulation({inputs:prepared.map(item=>({name:item.name.replace(/[^A-Za-z0-9_]/g,'_'),unit:item.unit,distribution:'uniform',parameters:{min:item.direction*item.nominal-(item.direction>0?item.minus:item.plus),max:item.direction*item.nominal+(item.direction>0?item.plus:item.minus)}})),expression:prepared.map(item=>item.name.replace(/[^A-Za-z0-9_]/g,'_')).join('+'),count,seed,lsl,usl,responseUnit:units[0]||''});return{method:'dimensional-tolerance-stack',methodVersion:PRODUCT_DEVELOPMENT_ENGINE_VERSION,unit:units[0]||'',nominalAssembly:nominal,worstCase:{minimum,maximum,assumption:'All contributors simultaneously reach the adverse extremes.'},rss:{threeSigma:rssSigma*3,minimum:nominal-rssSigma*3,maximum:nominal+rssSigma*3,assumption:'Independent, approximately centered contributors; entered tolerances interpreted as ±3σ.'},monteCarlo:mc,dominantContributors:prepared.map(item=>({name:item.name,range:item.minus+item.plus})).sort((a,b)=>b.range-a.range)}; }

export function tostMeans({ groupA = [], groupB = [], margin, alpha = .05, paired = false } = {}) { const a=groupA.map(Number),b=groupB.map(Number),delta=finite(margin,'Equivalence margin'),level=finite(alpha,'Alpha');if(!(delta>0)||!(level>0&&level<.5))throw new Error('Equivalence margin must be positive and alpha below 0.5.');if(a.some(value=>!Number.isFinite(value))||b.some(value=>!Number.isFinite(value))||a.length<2||b.length<2)throw new Error('Equivalence testing requires at least two finite observations per group.');let difference,se,df;if(paired){if(a.length!==b.length)throw new Error('Paired equivalence requires equal group lengths.');const differences=a.map((value,index)=>value-b[index]);difference=mean(differences);se=Math.sqrt(variance(differences)/differences.length);df=differences.length-1}else{difference=mean(a)-mean(b);se=Math.sqrt(variance(a)/a.length+variance(b)/b.length);const va=variance(a)/a.length,vb=variance(b)/b.length;df=(va+vb)**2/(va**2/(a.length-1)+vb**2/(b.length-1))}const critical=invNorm(1-level),ci=[difference-critical*se,difference+critical*se],zLower=(difference+delta)/se,zUpper=(difference-delta)/se,pLower=1-normCDF(zLower),pUpper=normCDF(zUpper),equivalent=pLower<level&&pUpper<level;return{method:paired?'paired-tost-equivalence':'welch-tost-equivalence',methodVersion:PRODUCT_DEVELOPMENT_ENGINE_VERSION,difference,standardError:se,df,equivalenceBounds:[-delta,delta],confidenceInterval:ci,alpha:level,pValues:{lower:pLower,upper:pUpper},equivalent,interpretation:equivalent?'Equivalence was demonstrated within the entered engineering margin.':'Equivalence was not demonstrated; this is not the same as proving a meaningful difference.',limitation:'Normal critical values are used; small-sample exact t critical values remain validation backlog.'}; }

export function engineeringSampleSize({ type='one-mean', alpha=.05, power=.8, difference, sigma, proportion, proportion2, groups=3 }={}) { const a=finite(alpha,'Alpha'),targetPower=finite(power,'Power');if(!(a>0&&a<.5&&targetPower>.5&&targetPower<1))throw new Error('Alpha must be below 0.5 and power must be between 0.5 and 1.');const z=invNorm(1-a/2)+invNorm(targetPower);let perGroup,total,formula;if(['one-mean','paired-mean'].includes(type)){const delta=Math.abs(finite(difference,'Practical difference')),sd=finite(sigma,'Engineering-unit standard deviation');if(!(delta>0&&sd>0))throw new Error('Practical difference and standard deviation must be positive.');perGroup=Math.ceil((z*sd/delta)**2);total=perGroup;formula='Normal approximation for a two-sided mean test using the direct engineering-unit difference.'}else if(type==='two-means'){const delta=Math.abs(finite(difference,'Practical difference')),sd=finite(sigma,'Pooled planning standard deviation');if(!(delta>0&&sd>0))throw new Error('Practical difference and standard deviation must be positive.');perGroup=Math.ceil(2*(z*sd/delta)**2);total=2*perGroup;formula='Equal-allocation normal approximation for two independent means.'}else if(type==='one-proportion'){const p=finite(proportion,'Planning proportion'),delta=Math.abs(finite(difference,'Practical proportion difference'));if(!(p>0&&p<1&&delta>0&&delta<1))throw new Error('Planning proportion and practical difference must be valid probabilities.');perGroup=Math.ceil(z*z*p*(1-p)/(delta*delta));total=perGroup;formula='Conservative normal-approximation planning around the entered proportion.'}else if(type==='two-proportions'){const p1=finite(proportion,'First proportion'),p2=finite(proportion2,'Second proportion'),delta=Math.abs(p1-p2);if(!(p1>0&&p1<1&&p2>0&&p2<1&&delta>0))throw new Error('Enter two distinct valid planning proportions.');perGroup=Math.ceil(z*z*(p1*(1-p1)+p2*(1-p2))/(delta*delta));total=2*perGroup;formula='Equal-allocation normal approximation for two proportions.'}else if(type==='anova'){const effect=Math.abs(finite(difference,'Minimum mean separation')),sd=finite(sigma,'Within-group standard deviation'),k=Math.round(finite(groups,'Group count'));if(!(effect>0&&sd>0&&k>=2))throw new Error('ANOVA planning needs positive separation/SD and at least two groups.');perGroup=Math.ceil(2*(z*sd/effect)**2*(1+1/k));total=k*perGroup;formula='Planning approximation based on minimum pairwise separation; confirm with a noncentral-F design for final protocol.'}else throw new Error('Unsupported sample-size planning type.');return{method:`engineering-sample-size-${type}`,methodVersion:PRODUCT_DEVELOPMENT_ENGINE_VERSION,type,alpha:a,power:targetPower,perGroup,total,formula,distinctions:'Power concerns detection probability for a practical effect. It is not confidence, equivalence, tolerance coverage, or reliability demonstration confidence.'}; }

export function verificationDecision(record) { if(!record?.requirementId||!record?.ctqId)throw new Error('Verification requires linked requirement and CTQ IDs.');const result=String(record.result||'Inconclusive');if(result==='Pass'&&!(String(record.evidence||'').trim()&&String(record.rationale||'').trim()&&record.linkedAnalysisId))throw new Error('PASS requires evidence, rationale, and a linked analysis.');if(!['Pass','Fail','Inconclusive'].includes(result))throw new Error('Verification result must be Pass, Fail, or Inconclusive.');return{...record,result,status:result==='Pass'?'Passed':result==='Fail'?'Failed':'Inconclusive',decidedAt:new Date().toISOString(),evidenceBacked:result!=='Pass'||Boolean(record.evidence&&record.rationale&&record.linkedAnalysisId)}; }

export function readinessSummary({ requirements = [], verifications = [], risks = [], evidence = [] } = {}) { const missingRequirements=requirements.filter(requirement=>!requirement.ctqIds?.length),failed=verifications.filter(item=>item.result==='Fail'),inconclusive=verifications.filter(item=>item.result==='Inconclusive'),missingEvidence=verifications.filter(item=>!item.evidence),openRisks=risks.filter(item=>item.status!=='Closed');return{method:'product-pilot-readiness-evidence-summary',methodVersion:PRODUCT_DEVELOPMENT_ENGINE_VERSION,counts:{requirements:requirements.length,verified:verifications.filter(item=>item.result==='Pass').length,failed:failed.length,inconclusive:inconclusive.length,missingEvidence:missingEvidence.length,openRisks:openRisks.length,evidence:evidence.length},ready:requirements.length>0&&!missingRequirements.length&&!failed.length&&!inconclusive.length&&!missingEvidence.length&&!openRisks.length,blockingItems:[...missingRequirements.map(item=>`Requirement ${item.id} has no CTQ.`),...failed.map(item=>`Verification ${item.id} failed.`),...inconclusive.map(item=>`Verification ${item.id} is inconclusive.`),...missingEvidence.map(item=>`Verification ${item.id} lacks evidence.`),...openRisks.map(item=>`Risk ${item.id} remains open.`)],warning:'This evidence summary is not a universal corporate release gate; organizations define approval policy.'}; }
