import { chiSquareCDF, invNorm, normCDF } from './statMath';

export const WAVE4_METHOD_VERSIONS = Object.freeze({ LIFE_DATA: '1.0.0', KAPLAN_MEIER: '1.0.0', LOG_RANK: '1.0.0', ALT: '1.0.0', WARRANTY: '1.0.0', REPAIRABLE: '1.0.0', DEMONSTRATION: '1.0.0', ACCEPTANCE: '1.0.0', TOLERANCE: '1.0.0' });
const finite = (value, label) => { const number = Number(value); if (!Number.isFinite(number)) throw new Error(`${label} must be a finite number.`); return number; };
const mean = values => values.reduce((sum, value) => sum + value, 0) / values.length;
const logGamma = value => { const coefficients = [676.5203681218851,-1259.1392167224028,771.32342877765313,-176.61502916214059,12.507343278686905,-.13857109526572012,9.984369578019572e-6,1.5056327351493116e-7]; if (value < .5) return Math.log(Math.PI) - Math.log(Math.sin(Math.PI * value)) - logGamma(1 - value); let x=.9999999999998099,z=value-1; coefficients.forEach((coefficient,index)=>{x+=coefficient/(z+index+1)}); const t=z+7.5; return .5*Math.log(2*Math.PI)+(z+.5)*Math.log(t)-t+Math.log(x); };

export function validateLifeData(rows) {
  if (!Array.isArray(rows) || !rows.length) throw new Error('Enter at least one life-data observation.');
  const observations = rows.map((row, index) => {
    const time = finite(row.time, `Lifetime on row ${index + 1}`);
    if (time <= 0) throw new Error(`Lifetime on row ${index + 1} must be greater than zero.`);
    const status = String(row.status ?? '').trim().toLowerCase();
    if (!['failure','failed','1','right','censored','suspended','0'].includes(status)) throw new Error(`Censoring status on row ${index + 1} must be Failure or Suspended / Right Censored.`);
    return { time, failed: ['failure','failed','1'].includes(status), group: String(row.group || 'All units'), unitId: String(row.unitId || index + 1), censoring: ['failure','failed','1'].includes(status) ? 'exact' : 'right' };
  });
  const failures = observations.filter(item => item.failed).length;
  return { observations, failures, censored: observations.length - failures, futureCensoringSupport: ['left','interval'] };
}

function optimize2(objective, initial) {
  let point=[...initial], step=[1,1], best=objective(point), iterations=0;
  for (;iterations<400;iterations+=1) { let improved=false; for(let axis=0;axis<2;axis+=1) for(const direction of [-1,1]) { const candidate=[...point]; candidate[axis]+=direction*step[axis]; const value=objective(candidate); if(Number.isFinite(value)&&value<best){point=candidate;best=value;improved=true;} } if(!improved){step=step.map(value=>value*.55); if(Math.max(...step)<1e-8)break;} }
  return { point, objective: best, iterations, converged: Math.max(...step)<1e-6 };
}

function covariance2(objective,point){const h=point.map(value=>1e-4*Math.max(1,Math.abs(value))),f=objective(point),p=(a,b)=>{const next=[...point];next[0]+=a*h[0];next[1]+=b*h[1];return objective(next)},h00=(p(1,0)-2*f+p(-1,0))/(h[0]**2),h11=(p(0,1)-2*f+p(0,-1))/(h[1]**2),h01=(p(1,1)-p(1,-1)-p(-1,1)+p(-1,-1))/(4*h[0]*h[1]),det=h00*h11-h01*h01;if(!(h00>0&&h11>0&&det>0))return null;return[[h11/det,-h01/det],[-h01/det,h00/det]]}
function deltaInterval(evaluate,point,covariance,transform=value=>value){if(!covariance)return null;const h=point.map(value=>1e-5*Math.max(1,Math.abs(value))),gradient=point.map((value,index)=>{const high=[...point],low=[...point];high[index]+=h[index];low[index]-=h[index];return(evaluate(high)-evaluate(low))/(2*h[index])}),variance=gradient.reduce((sum,left,i)=>sum+gradient.reduce((inner,right,j)=>inner+left*covariance[i][j]*right,0),0);if(!(variance>=0))return null;const estimate=evaluate(point),se=Math.sqrt(variance);return[transform(estimate-1.96*se),transform(estimate+1.96*se)]}

export function fitLifeDistribution(rows, distribution='weibull') {
  const data=validateLifeData(rows); if(!data.failures)throw new Error('Parametric life-data fitting requires at least one exact failure; all-censored data cannot identify the model.');
  const times=data.observations.map(item=>item.time), failures=data.observations.filter(item=>item.failed);
  let parameters, logLikelihood, survival, hazard,parameterPoint=null,covariance=null,parameterIntervals=null;
  if(distribution==='exponential') { const totalTime=times.reduce((sum,value)=>sum+value,0), rate=data.failures/totalTime,seLogRate=1/Math.sqrt(data.failures); parameters={rate,meanLife:1/rate,scale:1/rate};parameterPoint=[Math.log(rate)];parameterIntervals={rate:[Math.exp(Math.log(rate)-1.96*seLogRate),Math.exp(Math.log(rate)+1.96*seLogRate)],scale:[Math.exp(-Math.log(rate)-1.96*seLogRate),Math.exp(-Math.log(rate)+1.96*seLogRate)]}; logLikelihood=data.failures*Math.log(rate)-rate*totalTime; survival=time=>Math.exp(-rate*time); hazard=()=>rate; }
  else if(distribution==='weibull') { const objective=([logShape,logScale])=>{const shape=Math.exp(logShape),scale=Math.exp(logScale); return -data.observations.reduce((sum,item)=>{const z=(item.time/scale)**shape; return sum+(item.failed?Math.log(shape)-Math.log(scale)+(shape-1)*(Math.log(item.time)-Math.log(scale))-z:-z)},0)},result=optimize2(objective,[0,Math.log(mean(times))]); if(!result.converged)throw new Error('Weibull censored maximum-likelihood fit did not converge. Review the data, censoring, and sample size.'); const shape=Math.exp(result.point[0]),scale=Math.exp(result.point[1]);parameterPoint=result.point;covariance=covariance2(objective,result.point);parameterIntervals=covariance?{shape:deltaInterval(point=>point[0],result.point,covariance,Math.exp),scale:deltaInterval(point=>point[1],result.point,covariance,Math.exp)}:null; parameters={shape,scale,characteristicLife:scale}; logLikelihood=-result.objective; survival=time=>Math.exp(-((time/scale)**shape)); hazard=time=>(shape/scale)*(time/scale)**(shape-1); }
  else if(distribution==='lognormal') { const logs=failures.map(item=>Math.log(item.time)), initialMu=mean(logs), initialSigma=Math.sqrt(Math.max(1e-6,mean(logs.map(value=>(value-initialMu)**2)))),objective=([mu,logSigma])=>{const sigma=Math.exp(logSigma);return-data.observations.reduce((sum,item)=>{const z=(Math.log(item.time)-mu)/sigma; return sum+(item.failed?-.5*z*z-Math.log(item.time*sigma*Math.sqrt(2*Math.PI)):Math.log(Math.max(1e-15,1-normCDF(z))))},0)},result=optimize2(objective,[initialMu,Math.log(initialSigma)]); if(!result.converged)throw new Error('Lognormal censored maximum-likelihood fit did not converge.'); const mu=result.point[0],sigma=Math.exp(result.point[1]);parameterPoint=result.point;covariance=covariance2(objective,result.point);parameterIntervals=covariance?{mu:deltaInterval(point=>point[0],result.point,covariance),sigma:deltaInterval(point=>point[1],result.point,covariance,Math.exp)}:null; parameters={mu,sigma,scale:Math.exp(mu)}; logLikelihood=-result.objective; survival=time=>1-normCDF((Math.log(time)-mu)/sigma); hazard=time=>{const z=(Math.log(time)-mu)/sigma;return Math.exp(-z*z/2)/(time*sigma*Math.sqrt(2*Math.PI)*Math.max(1e-15,1-normCDF(z)))}; }
  else throw new Error('Supported reliability distributions are Weibull, Lognormal, and Exponential.');
  const k=Object.keys(parameters).filter(key=>!['characteristicLife','meanLife'].includes(key)).length;
  const quantile=probability=>{if(distribution==='weibull')return parameters.scale*(-Math.log(1-probability))**(1/parameters.shape);if(distribution==='exponential')return-Math.log(1-probability)/parameters.rate;return Math.exp(parameters.mu+parameters.sigma*invNorm(probability));};
  const vectorQuantile=(point,probability)=>distribution==='weibull'?Math.exp(point[1])*(-Math.log(1-probability))**(1/Math.exp(point[0])):distribution==='lognormal'?Math.exp(point[0]+Math.exp(point[1])*invNorm(probability)):-Math.log(1-probability)/Math.exp(point[0]),vectorSurvival=(point,time)=>distribution==='weibull'?Math.exp(-((time/Math.exp(point[1]))**Math.exp(point[0]))):distribution==='lognormal'?1-normCDF((Math.log(time)-point[0])/Math.exp(point[1])):Math.exp(-Math.exp(point[0])*time),bInterval=probability=>parameterPoint?(covariance?deltaInterval(point=>vectorQuantile(point,probability),parameterPoint,covariance,value=>Math.max(0,value)):distribution==='exponential'?[vectorQuantile([parameterPoint[0]+1.96/Math.sqrt(data.failures)],probability),vectorQuantile([parameterPoint[0]-1.96/Math.sqrt(data.failures)],probability)]:null):null,reliabilityInterval=time=>{if(distribution==='exponential'){const se=1/Math.sqrt(data.failures);return[Math.exp(-Math.exp(parameterPoint[0]+1.96*se)*time),Math.exp(-Math.exp(parameterPoint[0]-1.96*se)*time)]}const interval=deltaInterval(point=>vectorSurvival(point,time),parameterPoint,covariance,value=>Math.max(0,Math.min(1,value)));return interval?[Math.min(...interval),Math.max(...interval)]:null},maximum=Math.max(...times),curve=Array.from({length:41},(_,index)=>{const time=Math.max(maximum/1000,maximum*index/40);return{time,reliability:survival(time),unreliability:1-survival(time),hazard:hazard(time)}}),ordered=[...data.observations].sort((a,b)=>a.time-b.time),probabilityPlot=ordered.map((item,index)=>({time:item.time,failed:item.failed,plottingProbability:(index+.3)/(ordered.length+.4),censoring:item.censoring}));
  return { method:`${distribution}-censored-mle`,methodVersion:WAVE4_METHOD_VERSIONS.LIFE_DATA,distribution,observations:data.observations.length,failures:data.failures,censored:data.censored,parameters,parameterIntervals,logLikelihood,aic:2*k-2*logLikelihood,bic:k*Math.log(data.observations.length)-2*logLikelihood,reliabilityAt:time=>survival(finite(time,'Requested time')),reliabilityIntervalAt:time=>reliabilityInterval(finite(time,'Requested time')),unreliabilityAt:time=>1-survival(finite(time,'Requested time')),hazardAt:time=>hazard(finite(time,'Requested time')),cumulativeHazardAt:time=>-Math.log(Math.max(1e-15,survival(finite(time,'Requested time')))),b10:quantile(.1),b10Interval:bInterval(.1),b50:quantile(.5),b50Interval:bInterval(.5),bx:percent=>quantile(finite(percent,'B-life percentile')/100),bLifeInterval:percent=>bInterval(finite(percent,'B-life percentile')/100),meanLife:distribution==='weibull'?parameters.scale*Math.exp(logGamma(1+1/parameters.shape)):distribution==='lognormal'?Math.exp(parameters.mu+parameters.sigma**2/2):parameters.meanLife,medianLife:quantile(.5),curve,probabilityPlot,converged:true,intervalMethod:'Observed-information delta method, approximate 95% intervals',warnings:[...(parameterIntervals?[]:['Observed-information covariance was not positive definite; parameter and derived intervals are unavailable.']),'Probability-plot points are diagnostics only; model parameters come from the censored maximum-likelihood fit.']};
}

export function kaplanMeier(rows, confidence=.95) {
  const data=validateLifeData(rows), z=invNorm((1+confidence)/2), times=[...new Set(data.observations.map(item=>item.time))].sort((a,b)=>a-b); let survival=1,greenwood=0;
  const table=times.map(time=>{const atRisk=data.observations.filter(item=>item.time>=time).length,failures=data.observations.filter(item=>item.time===time&&item.failed).length,censored=data.observations.filter(item=>item.time===time&&!item.failed).length;survival*=1-failures/atRisk;if(atRisk>failures)greenwood+=failures/(atRisk*(atRisk-failures));let lower=survival,upper=survival;if(survival>0&&survival<1){const se=Math.sqrt(greenwood)/Math.abs(Math.log(survival)),loglog=Math.log(-Math.log(survival));lower=Math.exp(-Math.exp(loglog+z*se));upper=Math.exp(-Math.exp(loglog-z*se));}return{time,atRisk,failures,censored,survival,lower,upper}}); const median=table.find(item=>item.survival<=.5)?.time??null;
  return {method:'kaplan-meier',methodVersion:WAVE4_METHOD_VERSIONS.KAPLAN_MEIER,table,failures:data.failures,censored:data.censored,medianSurvival:median,medianLabel:median===null?'Not estimable from observed follow-up':String(median),survivalAt:time=>{const prior=[...table].reverse().find(item=>item.time<=time);return prior?.survival??1;}};
}

export function logRank(rows) { const data=validateLifeData(rows), groups=[...new Set(data.observations.map(item=>item.group))]; if(groups.length!==2)throw new Error('Log-rank comparison currently requires exactly two groups.'); const eventTimes=[...new Set(data.observations.filter(item=>item.failed).map(item=>item.time))];let observed=0,expected=0,variance=0;eventTimes.forEach(time=>{const n1=data.observations.filter(item=>item.group===groups[0]&&item.time>=time).length,n=data.observations.filter(item=>item.time>=time).length,d1=data.observations.filter(item=>item.group===groups[0]&&item.failed&&item.time===time).length,d=data.observations.filter(item=>item.failed&&item.time===time).length;observed+=d1;expected+=d*n1/n;if(n>1)variance+=n1*(n-n1)*d*(n-d)/(n*n*(n-1));});if(!variance)throw new Error('Log-rank comparison needs failures and risk-set variation in both groups.');const statistic=(observed-expected)**2/variance;return{method:'log-rank',methodVersion:WAVE4_METHOD_VERSIONS.LOG_RANK,groups,statistic,df:1,pValue:1-chiSquareCDF(statistic,1)}};

const combination=(n,k)=>{if(k<0||k>n)return 0;let value=1;for(let i=1;i<=Math.min(k,n-k);i++)value=value*(n-i+1)/i;return value};
const binomialCdf=(maximum,n,p)=>{let total=0;for(let value=0;value<=maximum;value+=1)total+=combination(n,value)*p**value*(1-p)**(n-value);return total};
export function acceptancePlan({lotSize,sampleSize,acceptanceNumber,defectRate,aql,ltpd}) { const N=Math.round(finite(lotSize,'Lot size')),n=Math.round(finite(sampleSize,'Sample size')),c=Math.round(finite(acceptanceNumber,'Acceptance number'));if(N<1||n<1||n>N)throw new Error('Sample size must be between 1 and the lot size.');if(c<0||c>=n)throw new Error('Acceptance number must be between 0 and sample size minus 1.');const probability=p=>{if(!(p>=0&&p<=1))throw new Error('Defect rate must be between 0 and 1.');let result=0;for(let x=0;x<=c;x++)result+=combination(n,x)*p**x*(1-p)**(n-x);return result};if(aql!==undefined&&ltpd!==undefined&&Number(aql)>=Number(ltpd))throw new Error('AQL must be lower than LTPD/RQL.');const curve=Array.from({length:21},(_,index)=>({defectRate:index/100,probabilityAcceptance:probability(index/100)}));const aoq=curve.map(item=>({...item,aoq:item.defectRate*item.probabilityAcceptance*(N-n)/N})),peak=aoq.reduce((best,item)=>item.aoq>best.aoq?item:best,aoq[0]);const p=finite(defectRate??.01,'Defect rate');return{method:'single-attribute-acceptance',methodVersion:WAVE4_METHOD_VERSIONS.ACCEPTANCE,acceptanceNumber:c,rejectionNumber:c+1,probabilityAcceptance:probability(p),producerRisk:aql===undefined?null:1-probability(Number(aql)),consumerRisk:ltpd===undefined?null:probability(Number(ltpd)),ocCurve:curve,aoq: p*probability(p)*(N-n)/N,aoql:peak.aoq,ati:n+(N-n)*(1-probability(p)),standardClaim:'Statistical acceptance-sampling plan; not an ANSI/ISO table plan.'}; }

export function zeroFailureDemonstration({targetReliability,confidence,allowedFailures=0}) { const reliability=finite(targetReliability,'Target reliability'),level=finite(confidence,'Confidence'),allowed=Math.round(finite(allowedFailures,'Allowed failures'));if(!(reliability>0&&reliability<1&&level>0&&level<1))throw new Error('Target reliability and confidence must be strictly between 0 and 1.');if(allowed<0)throw new Error('Allowed failures cannot be negative.');let units=Math.max(allowed+1,1);while(units<100000&&1-binomialCdf(allowed,units,1-reliability)<level)units+=1;if(units>=100000)throw new Error('No practical demonstration plan was found below 100,000 units. Review the reliability, confidence, and allowed-failure requirements.');return{method:'binomial-reliability-demonstration',methodVersion:WAVE4_METHOD_VERSIONS.DEMONSTRATION,requiredUnits:units,allowedFailures:allowed,targetReliability:reliability,confidence:level,achievedConfidence:1-binomialCdf(allowed,units,1-reliability),assumptions:['Independent identical units','Binomial pass/fail outcome at the stated mission time',`No more than ${allowed} observed failure${allowed===1?'':'s'}`]}; }

export function designAcceptancePlan({lotSize,aql,producerRisk,ltpd,consumerRisk,maxSampleSize=1000}) { const N=Math.round(finite(lotSize,'Lot size')),good=finite(aql,'AQL'),bad=finite(ltpd,'LTPD/RQL'),alpha=finite(producerRisk,'Producer risk'),beta=finite(consumerRisk,'Consumer risk');if(N<2)throw new Error('Lot size must be at least 2.');if(!(good>0&&good<bad&&bad<1))throw new Error('AQL must be positive and lower than LTPD/RQL, and both must be below 1.');if(!(alpha>0&&alpha<1&&beta>0&&beta<1))throw new Error('Producer and consumer risks must be strictly between 0 and 1.');const limit=Math.min(N,Math.round(maxSampleSize));for(let n=1;n<=limit;n+=1)for(let c=0;c<n;c+=1){const paAql=binomialCdf(c,n,good),paLtpd=binomialCdf(c,n,bad);if(paAql>=1-alpha&&paLtpd<=beta)return{...acceptancePlan({lotSize:N,sampleSize:n,acceptanceNumber:c,defectRate:good,aql:good,ltpd:bad}),designRequirements:{aql:good,producerRisk:alpha,ltpd:bad,consumerRisk:beta},paAtAql:paAql,paAtLtpd:paLtpd};}throw new Error(`No binomial plan satisfying both risks was found with n ≤ ${limit}. Increase the search limit or relax the risk requirements.`); }

export function normalToleranceInterval(values,{coverage=.99,confidence=.95,side='two-sided'}={}) { const clean=values.map(Number);if(clean.length<3||clean.some(value=>!Number.isFinite(value)))throw new Error('Normal tolerance intervals require at least 3 finite observations.');if(!(coverage>.5&&coverage<1&&confidence>.5&&confidence<1))throw new Error('Coverage and confidence must be between 0.5 and 1.');const n=clean.length,average=mean(clean),sd=Math.sqrt(clean.reduce((sum,value)=>sum+(value-average)**2,0)/(n-1));if(!sd)throw new Error('Tolerance interval is undefined for zero-variance data.');const zp=invNorm(side==='two-sided'?(1+coverage)/2:coverage),zg=invNorm(confidence),k=side==='two-sided'?zp*Math.sqrt((n-1)*(1+1/n)/(Math.max(1e-9,n-1-zg*Math.sqrt(2*(n-1))))):zp*Math.sqrt(1+1/n)+zg/Math.sqrt(n);if(!Number.isFinite(k)||k<=0)throw new Error('Sample size is insufficient for the requested tolerance coverage and confidence.');return{method:'normal-tolerance-interval-approximation',methodVersion:WAVE4_METHOD_VERSIONS.TOLERANCE,n,mean:average,standardDeviation:sd,coverage,confidence,side,k,lower:side==='upper'?null:average-k*sd,upper:side==='lower'?null:average+k*sd,warnings:['K-factor uses a documented large-sample normal approximation and remains UNVALIDATED.']}; }

export function warrantySummary({shipments=[],claims=[]}) { const shipped=shipments.reduce((sum,item)=>sum+Number(item.units||0),0),cost=claims.reduce((sum,item)=>sum+Number(item.cost||0),0),modes={},cohorts={};shipments.forEach(item=>{const cohort=item.cohort||'Unspecified';cohorts[cohort]={cohort,unitsExposed:Number(item.units||0),claims:0,cost:0}});claims.forEach(item=>{const mode=item.failureMode||'Unspecified',cohort=item.cohort||'Unspecified';modes[mode]=(modes[mode]||0)+1;cohorts[cohort]||(cohorts[cohort]={cohort,unitsExposed:0,claims:0,cost:0});cohorts[cohort].claims+=1;cohorts[cohort].cost+=Number(item.cost||0)});const cohortSummary=Object.values(cohorts).map(item=>({...item,claimRate:item.unitsExposed?item.claims/item.unitsExposed:null})),ageCounts={};claims.forEach(item=>{if(item.failureAge!==undefined&&item.failureAge!==''){const age=Number(item.failureAge);if(Number.isFinite(age)&&age>=0)ageCounts[age]=(ageCounts[age]||0)+1}});let cumulative=0;const failuresByAge=Object.entries(ageCounts).sort((a,b)=>Number(a[0])-Number(b[0])).map(([age,count])=>{cumulative+=count;return{age:Number(age),claims:count,cumulativeClaims:cumulative}});return{method:'warranty-exposure-summary',methodVersion:WAVE4_METHOD_VERSIONS.WARRANTY,unitsShipped:shipped,claimCount:claims.length,claimRate:shipped?claims.length/shipped:null,cumulativeCost:cost,averageClaimCost:claims.length?cost/claims.length:0,cohortSummary,failuresByAge,topFailureModes:Object.entries(modes).sort((a,b)=>b[1]-a[1]).map(([failureMode,count])=>({failureMode,count})),limitation:shipped?'Rates use supplied shipment exposure.':'No shipment exposure was supplied; claim counts alone do not estimate reliability.'}; }

export function repairableSystem(events) { if(!Array.isArray(events)||!events.length)throw new Error('Enter at least one repairable-system event.');const grouped={};events.forEach((event,index)=>{const id=String(event.systemId||'').trim(),time=finite(event.time,`Event time on row ${index+1}`);if(!id||time<=0)throw new Error('Every repair event needs a system ID and positive event time.');(grouped[id]||(grouped[id]={times:[],observationEnd:0})).times.push(time);const end=event.observationEnd===''||event.observationEnd===undefined?time:finite(event.observationEnd,`Observation end on row ${index+1}`);if(end<time)throw new Error(`Observation end for ${id} cannot precede a failure event.`);grouped[id].observationEnd=Math.max(grouped[id].observationEnd,end)});const systems=Object.entries(grouped).map(([systemId,item])=>{const ordered=[...item.times].sort((a,b)=>a-b);if(new Set(ordered).size!==ordered.length)throw new Error(`System ${systemId} contains duplicate event times.`);return{systemId,eventTimes:ordered,observationEnd:item.observationEnd,interarrivalTimes:ordered.map((value,index)=>index?value-ordered[index-1]:value)}}),failures=systems.reduce((sum,item)=>sum+item.eventTimes.length,0),totalExposure=systems.reduce((sum,item)=>sum+item.observationEnd,0),denominator=systems.reduce((sum,item)=>sum+item.eventTimes.reduce((inner,time)=>inner+Math.log(item.observationEnd/time),0),0),beta=failures>1&&denominator>0?failures/denominator:null,scale=beta?failures/systems.reduce((sum,item)=>sum+item.observationEnd**beta,0):null,seBeta=beta?beta/Math.sqrt(failures):null,cumulativeFailures=systems.flatMap(item=>item.eventTimes.map(time=>({systemId:item.systemId,time}))).sort((a,b)=>a.time-b.time).map((item,index)=>({...item,cumulativeFailures:index+1}));return{method:'crow-amsaa-power-law-process',methodVersion:WAVE4_METHOD_VERSIONS.REPAIRABLE,systems,failures,totalExposure,cumulativeFailures,mtbf:totalExposure/failures,cumulativeMtbf:totalExposure/failures,failureIntensity:failures/totalExposure,crowAmsaaBeta:beta,plpScale:scale,betaApproximate95Ci:beta?[Math.max(0,beta-1.96*seBeta),beta+1.96*seBeta]:null,trend:beta===null?'Not estimable':beta<.95?'Improving reliability trend':beta>1.05?'Deteriorating reliability trend':'Approximately constant failure intensity',diagnostics:{systemCount:systems.length,eventCount:failures,observationEndsExplicit:events.every(item=>item.observationEnd!==undefined&&item.observationEnd!=='')},warning:'Crow-AMSAA beta describes repairable-system event intensity; it is not Weibull lifetime shape beta.'}; }

export function arrheniusAcceleration({activationEnergyEv,testTemperature,useTemperature,testUnit='C'}) { const convert=value=>{const number=finite(value,'Temperature');const kelvin=testUnit==='K'?number:number+273.15;if(kelvin<=0)throw new Error('Temperature must be above absolute zero.');return kelvin};const testK=convert(testTemperature),useK=convert(useTemperature),activation=finite(activationEnergyEv,'Activation energy'),k=.00008617333262,accelerationFactor=Math.exp((activation/k)*(1/useK-1/testK));return{method:'arrhenius-acceleration-factor',methodVersion:WAVE4_METHOD_VERSIONS.ALT,testTemperatureKelvin:testK,useTemperatureKelvin:useK,accelerationFactor,extrapolationWarning:Math.abs(useK-testK)>50?'Use condition is substantially outside the test-stress temperature range.':null,assumptions:['Absolute temperature used internally','Specified activation energy is applicable','Failure mechanism is unchanged']}; }

export function fitStressLife(rows,{model='arrhenius',useStress,temperatureUnit='C'}={}) { if(!Array.isArray(rows)||rows.length<3)throw new Error('Stress-life modeling requires at least three observations across at least two stress levels.');if(rows.some(item=>String(item.status||'failure').toLowerCase()!=='failure'))throw new Error('Censored stress-life fitting is not yet supported; do not discard suspensions or treat them as failures.');const normalized=rows.map((item,index)=>{const life=finite(item.time,`Lifetime on row ${index+1}`),stress=finite(item.stress,`Stress on row ${index+1}`);if(life<=0||stress<=0)throw new Error('Lifetime and stress must be positive.');const transformed=model==='arrhenius'?1/(temperatureUnit==='K'?stress:stress+273.15):Math.log(stress);if(model==='arrhenius'&&(temperatureUnit!=='K'&&stress<=-273.15))throw new Error('Temperature must be above absolute zero.');return{life,stress,transformed,logLife:Math.log(life)}});if(new Set(normalized.map(item=>item.stress)).size<2)throw new Error('At least two distinct test stress levels are required.');const x=normalized.map(item=>item.transformed),y=normalized.map(item=>item.logLife),mx=mean(x),my=mean(y),sxx=x.reduce((sum,value)=>sum+(value-mx)**2,0),sxy=x.reduce((sum,value,index)=>sum+(value-mx)*(y[index]-my),0),slope=sxy/sxx,intercept=my-slope*mx,residuals=y.map((value,index)=>value-(intercept+slope*x[index])),residualStandardError=Math.sqrt(residuals.reduce((sum,value)=>sum+value**2,0)/(y.length-2)),use=finite(useStress,'Use-condition stress'),useX=model==='arrhenius'?1/(temperatureUnit==='K'?use:use+273.15):Math.log(use),predictedLife=Math.exp(intercept+slope*useX),testRange=[Math.min(...normalized.map(item=>item.stress)),Math.max(...normalized.map(item=>item.stress))],referenceStress=Math.max(...normalized.map(item=>item.stress)),referenceX=model==='arrhenius'?1/(temperatureUnit==='K'?referenceStress:referenceStress+273.15):Math.log(referenceStress),accelerationFactor=predictedLife/Math.exp(intercept+slope*referenceX),outside=use<testRange[0]||use>testRange[1];return{method:`${model}-stress-life`,methodVersion:WAVE4_METHOD_VERSIONS.ALT,model,coefficients:{intercept,slope},predictedLifeAtUse:predictedLife,useCondition:use,testStressRange:testRange,accelerationFactor,residualStandardError,converged:true,fitted:normalized.map(item=>({stress:item.stress,life:item.life,predictedLife:Math.exp(intercept+slope*item.transformed)})),diagnostics:{observations:rows.length,stressLevels:new Set(normalized.map(item=>item.stress)).size},extrapolationWarning:outside?'Use condition is outside the tested stress range; prediction requires extrapolation.':null,assumptions:[model==='arrhenius'?'Absolute temperature used internally':'Positive nonthermal stress used on a log scale','Log-linear stress-life relationship','Uncensored exact failures','Failure mechanism is unchanged']}; }
