import { acceptancePlan, arrheniusAcceleration, designAcceptancePlan, designFiniteLotAcceptancePlan, finiteLotAcceptancePlan, fitLifeDistribution, fitStressLife, kaplanMeier, logRank, nonparametricToleranceInterval, normalToleranceInterval, repairableSystem, validateLifeData, variablesAcceptancePlan, warrantySummary, zeroFailureDemonstration } from './qualityReliabilityEngine';

const life=[{time:10,status:'failure',group:'A'},{time:12,status:'censored',group:'A'},{time:15,status:'failure',group:'A'},{time:18,status:'failure',group:'B'},{time:20,status:'censored',group:'B'},{time:25,status:'failure',group:'B'}];

describe('Wave 4 life data and survival',()=>{
 test('preserves failures and right censoring and rejects invalid/all-censored parametric data',()=>{expect(validateLifeData(life)).toMatchObject({failures:4,censored:2});expect(()=>validateLifeData([{time:0,status:'failure'}])).toThrow('greater than zero');expect(()=>validateLifeData([{time:1,status:'unknown'}])).toThrow('Failure or Suspended');expect(()=>fitLifeDistribution([{time:2,status:'censored'}],'weibull')).toThrow('all-censored');});
 test.each(['weibull','lognormal','exponential'])('%s fits censored likelihood and returns B-life metrics with intervals',distribution=>{const result=fitLifeDistribution(life,distribution);expect(result.converged).toBe(true);expect(result.b10).toBeGreaterThan(0);expect(result.b50).toBeGreaterThan(result.b10);expect(result.b10Interval).toHaveLength(2);expect(result.reliabilityIntervalAt(12)).toHaveLength(2);expect(result.parameterIntervals).toBeTruthy();expect(result.aic).toBeGreaterThan(0);});
 test('Kaplan-Meier handles tied events, censoring, and unreached median honestly',()=>{const result=kaplanMeier([{time:1,status:'failure'},{time:1,status:'failure'},{time:3,status:'censored'},{time:4,status:'censored'}]);expect(result.table[0]).toMatchObject({atRisk:4,failures:2,survival:.5});expect(result.medianSurvival).toBe(1);expect(kaplanMeier([{time:1,status:'failure'},{time:2,status:'censored'},{time:3,status:'censored'}]).medianLabel).toBe('Not estimable from observed follow-up');});
 test('log-rank preserves groups and supports a global comparison',()=>{expect(logRank(life)).toMatchObject({groups:['A','B'],df:1});expect(()=>logRank(life.map(item=>({...item,group:'A'})))).toThrow('at least two groups');});
});

describe('Wave 4 practitioner calculators',()=>{
 test('Arrhenius always converts Celsius to absolute temperature and warns on extrapolation',()=>{const result=arrheniusAcceleration({activationEnergyEv:.7,testTemperature:125,useTemperature:25,testUnit:'C'});expect(result.testTemperatureKelvin).toBeCloseTo(398.15);expect(result.useTemperatureKelvin).toBeCloseTo(298.15);expect(result.accelerationFactor).toBeGreaterThan(1);expect(result.extrapolationWarning).toBeTruthy();expect(()=>arrheniusAcceleration({activationEnergyEv:.7,testTemperature:-300,useTemperature:25,testUnit:'C'})).toThrow('absolute zero');});
 test('zero-failure demonstration returns conservative integer units and rejects impossible inputs',()=>{const result=zeroFailureDemonstration({targetReliability:.9,confidence:.95});expect(result.requiredUnits).toBe(29);expect(result.achievedConfidence).toBeGreaterThanOrEqual(.95);expect(()=>zeroFailureDemonstration({targetReliability:1,confidence:.95})).toThrow('strictly between');});
 test('allowed-failure demonstration searches a valid conservative plan',()=>{const result=zeroFailureDemonstration({targetReliability:.95,confidence:.9,allowedFailures:1});expect(result.allowedFailures).toBe(1);expect(result.requiredUnits).toBeGreaterThan(1);expect(result.achievedConfidence).toBeGreaterThanOrEqual(.9);});
 test('acceptance plan evaluates risk and guards invalid c and AQL/LTPD ordering',()=>{const result=acceptancePlan({lotSize:1000,sampleSize:80,acceptanceNumber:2,defectRate:.01,aql:.01,ltpd:.06});expect(result.rejectionNumber).toBe(3);expect(result.ocCurve).toHaveLength(21);expect(()=>acceptancePlan({lotSize:100,sampleSize:10,acceptanceNumber:10})).toThrow('minus 1');expect(()=>acceptancePlan({lotSize:100,sampleSize:10,acceptanceNumber:1,aql:.1,ltpd:.05})).toThrow('lower');});
 test('acceptance plan design satisfies both entered risks',()=>{const result=designAcceptancePlan({lotSize:1000,aql:.01,producerRisk:.05,ltpd:.06,consumerRisk:.1});expect(result.paAtAql).toBeGreaterThanOrEqual(.95);expect(result.paAtLtpd).toBeLessThanOrEqual(.1);expect(result.rejectionNumber).toBe(result.acceptanceNumber+1);});
 test('normal tolerance interval uses numerical exact one-sided factors and conservative two-sided construction',()=>{const one=normalToleranceInterval(Array.from({length:43},(_,index)=>10+index/100),{coverage:.9,confidence:.99,side:'upper'}),two=normalToleranceInterval([9.8,10,10.1,10.2,10.4],{coverage:.9,confidence:.9});expect(one.k).toBeCloseTo(1.874,2);expect(one.factorMethod).toContain('Exact one-sided');expect(two.lower).toBeLessThan(two.mean);expect(two.upper).toBeGreaterThan(two.mean);expect(()=>normalToleranceInterval([1,2],{})).toThrow('at least 3');});
 test('distribution-free tolerance limits refuse unsupported sample sizes and report achieved confidence',()=>{expect(()=>nonparametricToleranceInterval([1,2,3],{coverage:.99,confidence:.95})).toThrow('Required sample size');const values=Array.from({length:60},(_,index)=>index+1),result=nonparametricToleranceInterval(values,{coverage:.9,confidence:.9,side:'upper'});expect(result.upper).toBe(60);expect(result.achievedConfidence).toBeGreaterThanOrEqual(.9);});
 test('warranty exposure limitation and repairable duplicate-event guard are explicit',()=>{expect(warrantySummary({claims:[{cost:10,failureMode:'Seal'}]}).claimRate).toBeNull();expect(warrantySummary({claims:[{cost:10}]}).limitation).toContain('do not estimate reliability');expect(()=>repairableSystem([{systemId:'A',time:10},{systemId:'A',time:10}])).toThrow('duplicate');expect(repairableSystem([{systemId:'A',time:10},{systemId:'A',time:20}]).warning).toContain('not Weibull');});
 test.each(['arrhenius','inverse-power'])('%s stress-life likelihood retains right-censored observations and prediction uncertainty',model=>{const rows=[{time:40,status:'failure',stress:120},{time:50,status:'censored',stress:120},{time:90,status:'failure',stress:100},{time:100,status:'censored',stress:100},{time:180,status:'failure',stress:80},{time:220,status:'censored',stress:80}];const result=fitStressLife(rows,{model,useStress:60});expect(result.converged).toBe(true);expect(result.censored).toBe(3);expect(result.analyzedObservations).toBe(6);expect(result.futureUnitPredictionInterval).toHaveLength(2);expect(result.predictedLifeAtUse).toBeGreaterThan(0);});
 test('finite-lot attribute plans expose hypergeometric treatment and design risks',()=>{const evaluated=finiteLotAcceptancePlan({lotSize:100,sampleSize:20,acceptanceNumber:1,defectRate:.03,aql:.01,ltpd:.08});expect(evaluated.probabilityModel).toBe('hypergeometric');expect(()=>finiteLotAcceptancePlan({lotSize:10,sampleSize:11,acceptanceNumber:0})).toThrow('exceed');const designed=designFiniteLotAcceptancePlan({lotSize:200,aql:.01,producerRisk:.1,ltpd:.08,consumerRisk:.1});expect(designed.paAtAql).toBeGreaterThanOrEqual(.9);expect(designed.paAtLtpd).toBeLessThanOrEqual(.1);});
 test('known-sigma one-sided variables plan returns design and decision and rejects unsupported variants',()=>{const design=variablesAcceptancePlan({specificationLimit:10,direction:'upper',sigma:.5,aql:.01,ltpd:.06,producerRisk:.05,consumerRisk:.1});expect(design.designedSampleSize).toBeGreaterThan(1);const values=Array.from({length:design.designedSampleSize},()=>9),decision=variablesAcceptancePlan({values,specificationLimit:10,direction:'upper',sigma:.5,aql:.01,ltpd:.06,producerRisk:.05,consumerRisk:.1});expect(decision.decision.accept).toBe(true);expect(()=>variablesAcceptancePlan({specificationLimit:10,direction:'two-sided',sigma:.5,aql:.01,ltpd:.06,producerRisk:.05,consumerRisk:.1})).toThrow('upper or lower');});
});
