import {fitLinearModel,predictLinearScenarios} from './modelEngine';

export const RSM_ENGINE_VERSION='1.0.0';
const seededRandom=seed=>{let state=(Number(seed)||1)>>>0;return()=>{state=(1664525*state+1013904223)>>>0;return state/4294967296}};
const shuffle=(items,seed)=>{const random=seededRandom(seed),copy=[...items];for(let i=copy.length-1;i>0;i--){const j=Math.floor(random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy};
const validateFactors=(factors,min=2)=>{if(!Array.isArray(factors)||factors.length<min)throw new Error(`Response surface design requires at least ${min} continuous factors.`);const normalized=factors.map((factor,index)=>({id:factor.id||`factor-${index+1}`,name:String(factor.name||'').trim(),low:Number(factor.low),high:Number(factor.high),unit:factor.unit||''}));if(normalized.some(factor=>!factor.name))throw new Error('Every factor requires a name.');if(new Set(normalized.map(factor=>factor.name.toLowerCase())).size!==normalized.length)throw new Error('Factor names must be unique.');if(normalized.some(factor=>!Number.isFinite(factor.low)||!Number.isFinite(factor.high)||factor.low>=factor.high))throw new Error('Every factor requires finite low and high values with low below high.');return normalized.map(factor=>({...factor,center:(factor.low+factor.high)/2,halfRange:(factor.high-factor.low)/2,type:'continuous'}))};
export const codedToNatural=(factor,code)=>factor.center+Number(code)*factor.halfRange;
export const naturalToCoded=(factor,value)=>(Number(value)-factor.center)/factor.halfRange;
const makeRun=(codes,factors,pointType,standardOrder,replicate=1)=>({standardOrder,replicate,pointType,isCenterPoint:pointType==='center',factorCodes:Object.fromEntries(factors.map((factor,index)=>[factor.name,codes[index]])),factorSettings:Object.fromEntries(factors.map((factor,index)=>[factor.name,codedToNatural(factor,codes[index])])),responses:{}});
const finalize=(base,input,factors,designType,metadata={})=>{const randomized=input.randomized!==false,randomSeed=Number(input.randomSeed)||20260809,ordered=randomized?shuffle(base,randomSeed):base;return{schemaVersion:1,method:'response-surface-design',methodVersion:RSM_ENGINE_VERSION,designType,factors,responses:input.responses||[{name:input.response||'Response',goal:'maximize'}],centerPoints:Number(input.centerPoints)||0,replicates:Math.max(1,Number(input.replicates)||1),blocks:Math.max(1,Number(input.blocks)||1),randomized,randomSeed,runs:ordered.map((run,index)=>({...run,runOrder:index+1,block:index%(Math.max(1,Number(input.blocks)||1))+1})),confirmationRuns:[],analysisResults:null,...metadata};};

export function generateCentralComposite(input={}){const factors=validateFactors(input.factors,2),k=factors.length,variant=input.variant||'rotatable',alpha=variant==='face-centered'?1:Math.pow(2,k/4),replicates=Math.max(1,Number(input.replicates)||1),centerPoints=Math.max(1,Number(input.centerPoints)||5),base=[];let order=1;for(let index=0;index<2**k;index++){const codes=factors.map((_,position)=>(index>>position)&1?1:-1);for(let replicate=1;replicate<=replicates;replicate++)base.push(makeRun(codes,factors,'factorial',order++,replicate))}for(let axis=0;axis<k;axis++)for(const sign of[-1,1])for(let replicate=1;replicate<=replicates;replicate++){const codes=new Array(k).fill(0);codes[axis]=sign*alpha;base.push(makeRun(codes,factors,'axial',order++,replicate))}for(let i=0;i<centerPoints;i++)base.push(makeRun(new Array(k).fill(0),factors,'center',order++,i+1));return finalize(base,{...input,centerPoints,replicates},factors,'central-composite',{variant,alpha,warnings:[...(variant==='rotatable'&&alpha>1?['Rotatable axial points extend beyond the entered low/high cube. Confirm those star settings are safe and feasible before running the experiment.']:[])]})}

export function generateBoxBehnken(input={}){const factors=validateFactors(input.factors,3),k=factors.length;if(k>7)throw new Error('This Box-Behnken workflow supports 3 to 7 factors.');const replicates=Math.max(1,Number(input.replicates)||1),centerPoints=Math.max(1,Number(input.centerPoints)||3),base=[];let order=1;for(let left=0;left<k;left++)for(let right=left+1;right<k;right++)for(const a of[-1,1])for(const b of[-1,1])for(let replicate=1;replicate<=replicates;replicate++){const codes=new Array(k).fill(0);codes[left]=a;codes[right]=b;base.push(makeRun(codes,factors,'edge',order++,replicate))}for(let i=0;i<centerPoints;i++)base.push(makeRun(new Array(k).fill(0),factors,'center',order++,i+1));return finalize(base,{...input,centerPoints,replicates},factors,'box-behnken',{alpha:null,warnings:['Box-Behnken avoids cube corners and is useful when simultaneous extreme settings are undesirable; it does not test axial points outside the factor ranges.']})}

const responseRows=(design,responseName)=>design.runs.map(run=>({...run.factorCodes,[responseName]:Number(run.responses?.[responseName]??run.response)}));
export function fitResponseSurface(design,responseName){if(!design?.runs?.length)throw new Error('Generate a response surface design before fitting a model.');const values=design.runs.map(run=>Number(run.responses?.[responseName]??run.response));if(values.some(value=>!Number.isFinite(value)))throw new Error(`Enter a finite ${responseName} response for every run.`);const names=design.factors.map(factor=>factor.name),rows=responseRows(design,responseName),interactions=names.flatMap((left,index)=>names.slice(index+1).map(right=>[left,right])),polynomialTerms=names.map(name=>({name,degree:2})),model=fitLinearModel({rows,specification:{response:responseName,predictors:names,interactions,polynomialTerms}}),pureErrorAvailable=design.runs.some((run,index)=>design.runs.some((other,otherIndex)=>otherIndex!==index&&names.every(name=>other.factorCodes[name]===run.factorCodes[name])));return{...model,method:'second-order-response-surface',methodVersion:RSM_ENGINE_VERSION,designType:design.designType,responseName,codedModel:true,anova:{ssModel:model.ssRegression,dfModel:model.dfModel,msModel:model.ssRegression/model.dfModel,ssError:model.ssResidual,dfError:model.dfResidual,msError:model.mse,F:model.F,pValue:model.pF},pureErrorAvailable,lackOfFit:null,effectInterpretation:{linear:model.coefficients.filter(term=>names.includes(term.name)),curvature:model.coefficients.filter(term=>term.name.endsWith('^2')),interactions:model.coefficients.filter(term=>term.name.includes(':'))},warnings:[...model.warnings,...(!pureErrorAvailable?['Pure error is unavailable, so lack-of-fit cannot be separated from residual error. Do not overstate model adequacy.']:[]),...(design.blocks>1?['Blocks are retained in design provenance and run execution metadata, but this first RSM model does not estimate a separate block effect. Review block balance before interpreting factor terms.']:[])]}}

const codedScenario=(design,settings)=>Object.fromEntries(design.factors.map(factor=>[factor.name,settings[factor.name]??0]));
export function predictResponseSurface(design,model,codedSettings,confidence=.95){const training=responseRows(design,model.responseName),scenario=codedScenario(design,codedSettings);return predictLinearScenarios(model,training,[scenario],confidence)[0]}
export function contourGrid(design,model,{xFactor,yFactor,hold={},steps=21}={}){if(xFactor===yFactor||!design.factors.some(f=>f.name===xFactor)||!design.factors.some(f=>f.name===yFactor))throw new Error('Choose two different response-surface factors for the contour plane.');const count=Math.max(5,Math.min(51,Number(steps)||21)),points=[];for(let yi=0;yi<count;yi++)for(let xi=0;xi<count;xi++){const settings={...hold,[xFactor]:-1+2*xi/(count-1),[yFactor]:-1+2*yi/(count-1)},prediction=predictResponseSurface(design,model,settings);points.push({xCode:settings[xFactor],yCode:settings[yFactor],x:codedToNatural(design.factors.find(f=>f.name===xFactor),settings[xFactor]),y:codedToNatural(design.factors.find(f=>f.name===yFactor),settings[yFactor]),predicted:prediction.estimate})}return{xFactor,yFactor,hold:Object.fromEntries(design.factors.filter(f=>![xFactor,yFactor].includes(f.name)).map(f=>[f.name,hold[f.name]??0])),steps:count,points,min:Math.min(...points.map(p=>p.predicted)),max:Math.max(...points.map(p=>p.predicted))}}
export function optimizeResponseSurface(design,model,goal={type:'maximize'},steps=21){const count=Math.max(5,Math.min(41,Number(steps)||21)),candidates=[];const walk=(index,settings)=>{if(index===design.factors.length){const prediction=predictResponseSurface(design,model,settings),target=Number(goal.target),score=goal.type==='minimize'?-prediction.estimate:goal.type==='target'?-Math.abs(prediction.estimate-target):prediction.estimate;candidates.push({factorCodes:{...settings},factorSettings:Object.fromEntries(design.factors.map(f=>[f.name,codedToNatural(f,settings[f.name])])),predicted:prediction.estimate,score});return}for(let step=0;step<count;step++)walk(index+1,{...settings,[design.factors[index].name]:-1+2*step/(count-1)})};walk(0,{});candidates.sort((a,b)=>b.score-a.score);return{method:'bounded-response-surface-grid-optimization',methodVersion:RSM_ENGINE_VERSION,goal,recommended:candidates[0],evaluated:candidates.length,rangePolicy:'coded cube [-1, 1]',warnings:['Optimization is constrained to the tested low/high factor cube and is model-based. Complete a confirmation run before operational adoption.']}}
export function recordRsmConfirmation(design,optimization,input={}){if(!optimization?.recommended)throw new Error('Optimize the response surface before recording a confirmation run.');const observed=Number(input.observed);if(!Number.isFinite(observed))throw new Error('Enter a finite observed confirmation response.');const predicted=optimization.recommended.predicted,record={id:input.id||`rsm-confirmation-${Date.now()}`,observed,predicted,deviation:observed-predicted,percentDeviation:predicted===0?null:(observed-predicted)/Math.abs(predicted)*100,settings:optimization.recommended.factorSettings,responseName:input.responseName||design.responses[0]?.name||'Response',notes:input.notes||'',recordedAt:new Date().toISOString(),provenance:{designType:design.designType,randomSeed:design.randomSeed,methodVersion:RSM_ENGINE_VERSION}};return{...design,confirmationRuns:[...(design.confirmationRuns||[]),record]}}
