import {contourGrid,generateBoxBehnken,generateCentralComposite,naturalToCoded,codedToNatural,fitResponseSurface,optimizeResponseSurface,predictResponseSurface,recordRsmConfirmation} from './rsmEngine';

const factors=[{name:'Temperature',low:100,high:200},{name:'Pressure',low:10,high:20},{name:'Time',low:30,high:60}];
const response=(codes)=>50+4*codes.Temperature-3*codes.Pressure+2*codes.Time+1.5*codes.Temperature*codes.Pressure-2*codes.Temperature**2-1*codes.Pressure**2-.5*codes.Time**2;
const populate=design=>({...design,runs:design.runs.map(run=>({...run,response:response(run.factorCodes)}))});

test('CCD generates cube, axial, center, coded and natural settings reproducibly',()=>{const a=generateCentralComposite({factors,variant:'rotatable',centerPoints:5,randomSeed:42}),b=generateCentralComposite({factors,variant:'rotatable',centerPoints:5,randomSeed:42});expect(a.runs).toEqual(b.runs);expect(a.runs.filter(run=>run.pointType==='factorial')).toHaveLength(8);expect(a.runs.filter(run=>run.pointType==='axial')).toHaveLength(6);expect(a.runs.filter(run=>run.pointType==='center')).toHaveLength(5);expect(a.alpha).toBeCloseTo(Math.pow(2,3/4));expect(a.runs.every(run=>Object.keys(run.factorSettings).length===3)).toBe(true)});
test('face-centered CCD keeps axial settings inside low/high range',()=>{const design=generateCentralComposite({factors,variant:'face-centered',centerPoints:3,randomized:false});expect(design.alpha).toBe(1);design.runs.forEach(run=>factors.forEach(f=>expect(run.factorSettings[f.name]).toBeGreaterThanOrEqual(f.low)))});
test('Box-Behnken supports three factors and rejects too few',()=>{const design=generateBoxBehnken({factors,centerPoints:3,randomized:false});expect(design.runs).toHaveLength(15);expect(design.runs.filter(run=>run.pointType==='edge')).toHaveLength(12);expect(()=>generateBoxBehnken({factors:factors.slice(0,2)})).toThrow(/at least 3/)});
test('coded and natural conversion round trip',()=>{const factor={low:10,high:30,center:20,halfRange:10};expect(codedToNatural(factor,.25)).toBe(22.5);expect(naturalToCoded(factor,22.5)).toBe(.25)});
test('quadratic model recovers prediction, interaction and curvature',()=>{const design=populate(generateCentralComposite({factors,variant:'face-centered',centerPoints:5,randomized:false})),model=fitResponseSurface(design,'Yield'),prediction=predictResponseSurface(design,model,{Temperature:.5,Pressure:-.5,Time:0});expect(prediction.estimate).toBeCloseTo(response({Temperature:.5,Pressure:-.5,Time:0}),8);expect(model.effectInterpretation.interactions.some(term=>term.name==='Temperature:Pressure'&&Math.abs(term.estimate-1.5)<1e-8)).toBe(true);expect(model.effectInterpretation.curvature.some(term=>term.name==='Temperature^2'&&Math.abs(term.estimate+2)<1e-8)).toBe(true)});
test('contour predictions and bounded optimization remain inside tested cube',()=>{const design=populate(generateCentralComposite({factors,variant:'face-centered',centerPoints:5,randomized:false})),model=fitResponseSurface(design,'Yield'),contour=contourGrid(design,model,{xFactor:'Temperature',yFactor:'Pressure',steps:7}),optimization=optimizeResponseSurface(design,model,{type:'maximize'},9);expect(contour.points).toHaveLength(49);expect(contour.max).toBeGreaterThan(contour.min);Object.values(optimization.recommended.factorCodes).forEach(code=>expect(code).toBeGreaterThanOrEqual(-1));Object.values(optimization.recommended.factorCodes).forEach(code=>expect(code).toBeLessThanOrEqual(1))});
test('confirmation run records observed versus predicted evidence',()=>{const design=populate(generateCentralComposite({factors,variant:'face-centered',centerPoints:5,randomized:false})),model=fitResponseSurface(design,'Yield'),optimization=optimizeResponseSurface(design,model,{type:'maximize'},5),updated=recordRsmConfirmation(design,optimization,{observed:52,responseName:'Yield'});expect(updated.confirmationRuns).toHaveLength(1);expect(updated.confirmationRuns[0]).toEqual(expect.objectContaining({observed:52,responseName:'Yield'}))});
test.each([[{factors:[{name:'A',low:1,high:1},{name:'B',low:0,high:1}]},/low below high/],[{factors:[{name:'A',low:0,high:1},{name:'A',low:2,high:3}]},/unique/]])('invalid CCD design is rejected inline-ready',(input,message)=>{expect(()=>generateCentralComposite(input)).toThrow(message)});
