import { attributeChart, detectSpcRules, imrChart, recommendControlChart, xbarRChart, xbarSChart } from './spcEngine';

const subgroupRows=(groups)=>groups.flatMap((values,i)=>values.map(value=>({subgroup:`S${i+1}`,value})));

describe('professional SPC engine',()=>{
 test('reproduces the existing NIST I-MR fixture and records structured signals',()=>{const result=imrChart({values:[49.6,47.6,49.9,51.3,47.8,51.2,52.6,52.4,53.6,52.1]});expect(result.centerLine).toBeCloseTo(50.81,8);expect(result.mrCenterLine).toBeCloseTo(1.8777777778,8);expect(result.ucl).toBeCloseTo(55.8041,3);expect(result.violations).toEqual([])});
 test('calculates Xbar-R and Xbar-S from shared subgroup contracts',()=>{const rows=subgroupRows([[1,2,3,4,5],[2,3,4,5,6],[3,4,5,6,7],[4,5,6,7,8]]),r=xbarRChart({rows}),s=xbarSChart({rows});expect(r).toMatchObject({n:5,k:4,xbarBar:4.5,rBar:4});expect(r.xbarUcl).toBeCloseTo(6.808);expect(s.n).toBe(5);expect(s.sBar).toBeCloseTo(Math.sqrt(2.5));expect(s.constants.A3).toBe(1.427)});
 test('supports historical limits and explicit stages without overlap',()=>{const historical=imrChart({values:[1,2,1,2,1,2,1,2],historical:{center:1.5,sigma:.5}});expect(historical).toMatchObject({limitBasis:'historical',centerLine:1.5,ucl:3,lcl:0});const staged=imrChart({values:[1,2,1,2,10,11,10,11],stages:[{id:'before',start:0,end:3},{id:'after',start:4,end:7}]});expect(staged.stages).toHaveLength(2);expect(()=>imrChart({values:[1,2,3,4],stages:[{id:'a',start:0,end:2},{id:'b',start:2,end:3}]})).toThrow('overlap')});
 test('detects traceable Western Electric and Nelson signals',()=>{const v=detectSpcRules([0,0,2.2,2.3,2.4,2.5,2.6,4],0,1);expect(v.some(x=>x.ruleId==='WE1')).toBe(true);v.forEach(x=>expect(x).toMatchObject({ruleVersion:'1.0.0',severity:expect.any(String),evidence:expect.any(Object)}))});
 test.each(['p','np','c','u'])('calculates valid %s attribute charts',type=>{const result=attributeChart(type==='p'?{type,counts:[1,3,2],sampleSizes:[100,150,80]}:type==='np'?{type,counts:[1,3,2],constantN:100}:type==='u'?{type,counts:[1,3,2],sampleSizes:[10,20,8]}:{type,counts:[1,3,2]});expect(result.points).toHaveLength(3);expect(result.center).toBeGreaterThan(0)});
 test('uses observation-specific varying-denominator limits and rejects invalid counts',()=>{const p=attributeChart({type:'p',counts:[1,1],sampleSizes:[10,100]});expect(p.points[0].ucl).not.toBe(p.points[1].ucl);expect(()=>attributeChart({type:'p',counts:[11,1],sampleSizes:[10,10]})).toThrow('exceed');expect(()=>attributeChart({type:'c',counts:[1,-1]})).toThrow('non-negative');expect(()=>xbarRChart({rows:subgroupRows([[1,2],[1,2,3]])})).toThrow('Constant subgroup')});
 test('provides deterministic chart guidance',()=>{expect(recommendControlChart({subgroupSize:1})).toBe('imr');expect(recommendControlChart({subgroupSize:5})).toBe('xbar-r');expect(recommendControlChart({subgroupSize:12})).toBe('xbar-s');expect(recommendControlChart({dataType:'attribute',countKind:'defects',varyingDenominator:true})).toBe('u')});
});
