import { individualsMovingRange } from './statisticalEngines';

export const SPC_ENGINE_VERSION='1.0.0';
export const SPC_VALIDATION_STATUS=Object.freeze({imr:'PARTIALLY VALIDATED','xbar-r':'UNVALIDATED','xbar-s':'UNVALIDATED',p:'UNVALIDATED',np:'UNVALIDATED',c:'UNVALIDATED',u:'UNVALIDATED'});
export const XBAR_R_CONSTANTS=Object.freeze({2:{A2:1.880,D3:0,D4:3.267,d2:1.128},3:{A2:1.023,D3:0,D4:2.574,d2:1.693},4:{A2:.729,D3:0,D4:2.282,d2:2.059},5:{A2:.577,D3:0,D4:2.114,d2:2.326},6:{A2:.483,D3:0,D4:2.004,d2:2.534},7:{A2:.419,D3:.076,D4:1.924,d2:2.704},8:{A2:.373,D3:.136,D4:1.864,d2:2.847},9:{A2:.337,D3:.184,D4:1.816,d2:2.970},10:{A2:.308,D3:.223,D4:1.777,d2:3.078}});
export const XBAR_S_CONSTANTS=Object.freeze({2:{A3:2.659,B3:0,B4:3.267,c4:.7979},3:{A3:1.954,B3:0,B4:2.568,c4:.8862},4:{A3:1.628,B3:0,B4:2.266,c4:.9213},5:{A3:1.427,B3:0,B4:2.089,c4:.9400},6:{A3:1.287,B3:.030,B4:1.970,c4:.9515},7:{A3:1.182,B3:.118,B4:1.882,c4:.9594},8:{A3:1.099,B3:.185,B4:1.815,c4:.9650},9:{A3:1.032,B3:.239,B4:1.761,c4:.9693},10:{A3:.975,B3:.284,B4:1.716,c4:.9727},11:{A3:.927,B3:.321,B4:1.679,c4:.9754},12:{A3:.886,B3:.354,B4:1.646,c4:.9776},13:{A3:.850,B3:.382,B4:1.618,c4:.9794},14:{A3:.817,B3:.406,B4:1.594,c4:.9810},15:{A3:.789,B3:.428,B4:1.572,c4:.9823},16:{A3:.763,B3:.448,B4:1.552,c4:.9835},17:{A3:.739,B3:.466,B4:1.534,c4:.9845},18:{A3:.718,B3:.482,B4:1.518,c4:.9854},19:{A3:.698,B3:.497,B4:1.503,c4:.9862},20:{A3:.680,B3:.510,B4:1.490,c4:.9869},25:{A3:.606,B3:.565,B4:1.435,c4:.9896}});
const mean=a=>a.reduce((s,v)=>s+v,0)/a.length;
const sd=a=>Math.sqrt(a.reduce((s,v)=>s+(v-mean(a))**2,0)/(a.length-1));
const finite=(a,label,min=2)=>{if(!Array.isArray(a)||a.length<min||a.some(v=>!Number.isFinite(v)))throw new Error(`${label} requires at least ${min} ordered finite observations.`);return a};

export function detectSpcRules(values,center,sigma,{rules=['WE1','WE2','WE3','WE4','N5','N6'],stageId='all'}={}){
 if(!(sigma>0))return [];
 const violations=[],add=(ruleId,indices,explanation,severity='warning')=>violations.push({ruleId,ruleVersion:'1.0.0',stageId,pointIndices:indices,points:indices.map(i=>values[i]),explanation,severity,evidence:{center,sigma,zScores:indices.map(i=>(values[i]-center)/sigma)}});
 if(rules.includes('WE1'))values.forEach((v,i)=>{if(Math.abs(v-center)>3*sigma)add('WE1',[i],'One point is beyond three sigma.','critical')});
 for(let i=2;i<values.length;i++){const w=[i-2,i-1,i],z=w.map(j=>(values[j]-center)/sigma);if(rules.includes('WE2')&&(z.filter(v=>v>2).length>=2||z.filter(v=>v< -2).length>=2))add('WE2',w,'Two of three consecutive points are beyond two sigma on the same side.')}
 for(let i=4;i<values.length;i++){const w=[i-4,i-3,i-2,i-1,i],z=w.map(j=>(values[j]-center)/sigma);if(rules.includes('WE3')&&(z.filter(v=>v>1).length>=4||z.filter(v=>v< -1).length>=4))add('WE3',w,'Four of five consecutive points are beyond one sigma on the same side.')}
 for(let i=7;i<values.length;i++){const w=Array.from({length:8},(_,k)=>i-7+k);if(rules.includes('WE4')&&(w.every(j=>values[j]>center)||w.every(j=>values[j]<center)))add('WE4',w,'Eight consecutive points are on one side of the center line.')}
 for(let i=5;i<values.length;i++){const w=Array.from({length:6},(_,k)=>i-5+k),d=w.slice(1).map((j,k)=>values[j]-values[w[k]]);if(rules.includes('N5')&&(d.every(v=>v>0)||d.every(v=>v<0)))add('N5',w,'Six consecutive points form a monotonic trend.')}
 for(let i=13;i<values.length;i++){const w=Array.from({length:14},(_,k)=>i-13+k),d=w.slice(1).map((j,k)=>Math.sign(values[j]-values[w[k]]));if(rules.includes('N6')&&d.every((v,k)=>Boolean(v)&&(k===0||v===-d[k-1])))add('N6',w,'Fourteen consecutive points alternate direction.')}
 return violations;
}

function subgroupRows(rows){if(!Array.isArray(rows)||!rows.length)throw new Error('Subgroup data are required.');const map=new Map();rows.forEach((row,i)=>{if(!Number.isFinite(row.value)||row.subgroup===null||row.subgroup===undefined||row.subgroup==='')throw new Error(`Invalid subgroup observation at row ${i+1}.`);if(!map.has(row.subgroup))map.set(row.subgroup,[]);map.get(row.subgroup).push(row.value)});const groups=[...map].map(([id,values])=>({id,values,n:values.length,mean:mean(values),range:Math.max(...values)-Math.min(...values),sd:values.length>1?sd(values):0}));const sizes=new Set(groups.map(g=>g.n));if(sizes.size!==1)throw new Error(`Constant subgroup size is required; found ${[...sizes].join(', ')}.`);return groups}
function stageEngine(items,stages,runner){if(!stages?.length)return runner(items,{id:'all',label:'All observations',start:0,end:items.length-1});const covered=new Set(),results=stages.map(stage=>{if(!Number.isInteger(stage.start)||!Number.isInteger(stage.end)||stage.start<0||stage.end<stage.start||stage.end>=items.length)throw new Error(`Invalid stage ${stage.label||stage.id}.`);const slice=items.slice(stage.start,stage.end+1);for(let i=stage.start;i<=stage.end;i++){if(covered.has(i))throw new Error('Stages may not overlap.');covered.add(i)}return runner(slice,stage)});return {method:'staged-spc',methodVersion:SPC_ENGINE_VERSION,stages:results,stageMetadata:stages}}

export function imrChart(input){const values=finite(input.values,'I-MR');return stageEngine(values,input.stages,(stageValues,stage)=>{const estimated=individualsMovingRange({values:stageValues});const center=input.historical?.center??estimated.centerLine,sigma=input.historical?.sigma??estimated.sigma,ucl=input.historical?.ucl??center+3*sigma,lcl=input.historical?.lcl??center-3*sigma;const violations=detectSpcRules(stageValues,center,sigma,{rules:input.rules,stageId:stage.id});return {...estimated,centerLine:center,sigma,ucl,lcl,violations,stable:violations.length===0,limitBasis:input.historical?'historical':'estimated',stage}})}
export function xbarRChart(input){const groups=subgroupRows(input.rows),run=stageGroups=>{const n=stageGroups[0].n,c=XBAR_R_CONSTANTS[n];if(!c)throw new Error('Xbar-R supports constant subgroup sizes 2 through 10.');const xbarBar=mean(stageGroups.map(g=>g.mean)),rBar=mean(stageGroups.map(g=>g.range)),center=input.historical?.center??xbarBar,sigmaWithin=input.historical?.sigma??rBar/c.d2,xbarUcl=input.historical?.ucl??center+3*sigmaWithin/Math.sqrt(n),xbarLcl=input.historical?.lcl??center-3*sigmaWithin/Math.sqrt(n),rUcl=c.D4*rBar,rLcl=c.D3*rBar,violations=detectSpcRules(stageGroups.map(g=>g.mean),center,sigmaWithin/Math.sqrt(n),{rules:input.rules});return{method:'xbar-r',methodVersion:SPC_ENGINE_VERSION,validationStatus:SPC_VALIDATION_STATUS['xbar-r'],subgroups:stageGroups,n,k:stageGroups.length,xbarBar,rBar,sigmaWithin,xbarUcl,xbarLcl,rUcl,rLcl,constants:c,violations,stable:violations.length===0&&!stageGroups.some(g=>g.range>rUcl||g.range<rLcl),limitBasis:input.historical?'historical':'estimated'}};return run(groups)}
export function xbarSChart(input){const groups=subgroupRows(input.rows),n=groups[0].n,c=XBAR_S_CONSTANTS[n];if(!c)throw new Error('Xbar-S supports published constant subgroup sizes 2 through 20 and 25.');const xbarBar=mean(groups.map(g=>g.mean)),sBar=mean(groups.map(g=>g.sd)),sigmaWithin=sBar/c.c4,center=input.historical?.center??xbarBar,xbarUcl=input.historical?.ucl??center+c.A3*sBar,xbarLcl=input.historical?.lcl??center-c.A3*sBar,sUcl=c.B4*sBar,sLcl=c.B3*sBar,violations=detectSpcRules(groups.map(g=>g.mean),center,sigmaWithin/Math.sqrt(n),{rules:input.rules});return{method:'xbar-s',methodVersion:SPC_ENGINE_VERSION,subgroups:groups,n,k:groups.length,xbarBar,sBar,sigmaWithin,xbarUcl,xbarLcl,sUcl,sLcl,constants:c,violations,stable:violations.length===0&&!groups.some(g=>g.sd>sUcl||g.sd<sLcl),limitBasis:input.historical?'historical':'estimated'}}

export function attributeChart({type,counts,sampleSizes,constantN}){finite(counts,`${type} chart`);if(counts.some(v=>v<0||!Number.isInteger(v)))throw new Error('Counts must be non-negative integers.');let sizes=sampleSizes;if(type==='np')sizes=counts.map(()=>Number(constantN));if(['p','u','np'].includes(type)){if(!sizes||sizes.length!==counts.length||sizes.some(n=>!Number.isFinite(n)||n<=0))throw new Error('Positive sample size/opportunity is required for every point.')}if(['p','np'].includes(type)&&counts.some((v,i)=>v>sizes[i]))throw new Error('Defective count cannot exceed sample size.');let center;if(type==='p'||type==='u')center=counts.reduce((s,v)=>s+v,0)/sizes.reduce((s,v)=>s+v,0);else center=mean(counts);const points=counts.map((count,i)=>{const n=sizes?.[i];let value=count,ucl,lcl;if(type==='p'){value=count/n;const se=Math.sqrt(center*(1-center)/n);ucl=Math.min(1,center+3*se);lcl=Math.max(0,center-3*se)}else if(type==='np'){const p=center/constantN,se=Math.sqrt(constantN*p*(1-p));ucl=Math.min(constantN,center+3*se);lcl=Math.max(0,center-3*se)}else if(type==='c'){const se=Math.sqrt(center);ucl=center+3*se;lcl=Math.max(0,center-3*se)}else if(type==='u'){value=count/n;const se=Math.sqrt(center/n);ucl=center+3*se;lcl=Math.max(0,center-3*se)}else throw new Error('Chart type must be p, np, c, or u.');return{index:i,count,n,value,ucl,lcl,outOfControl:value>ucl||value<lcl}});const violations=points.filter(p=>p.outOfControl).map(p=>({ruleId:'LIMIT',ruleVersion:'1.0.0',pointIndices:[p.index],points:[p.value],explanation:'Point is outside its observation-specific three-sigma limits.',severity:'critical',evidence:{ucl:p.ucl,lcl:p.lcl,center}}));return{method:`${type}-chart`,methodVersion:SPC_ENGINE_VERSION,type,center,points,violations,stable:!violations.length,limitBasis:'estimated'}}

export function recommendControlChart({dataType='continuous',subgroupSize=1,varyingDenominator=false,countKind='defective'}){if(dataType==='continuous')return subgroupSize<=1?'imr':subgroupSize<=10?'xbar-r':'xbar-s';if(countKind==='defective')return varyingDenominator?'p':'np';return varyingDenominator?'u':'c'}
