import React,{createContext,useCallback,useContext,useEffect,useMemo,useRef,useState}from'react';
import{isSupabaseConfigured,supabase}from'../lib/supabase';
const AuthContext=createContext(null);
const friendly=error=>{if(!error)return'';if(/invalid login/i.test(error.message))return'Email or password is incorrect.';if(/already registered/i.test(error.message))return'An account already exists for this email.';if(/network|fetch/i.test(error.message))return'Unable to reach Aureqin. Check your connection and try again.';return'We could not complete that request. Please try again.'};
export function AuthProvider({children}){
 const[user,setUser]=useState(null),[session,setSession]=useState(null),[profile,setProfile]=useState(null),[loading,setLoading]=useState(isSupabaseConfigured);
 const currentUserRef=useRef(null),profileRef=useRef(null),profileOwnerRef=useRef(null),profileRequestRef=useRef(null),mountedRef=useRef(true);
 const loadProfile=useCallback(async(current,{force=false}={})=>{if(!supabase||!current?.id){profileRef.current=null;profileOwnerRef.current=null;if(mountedRef.current)setProfile(null);return null}if(!force&&profileOwnerRef.current===current.id&&profileRef.current)return profileRef.current;if(profileRequestRef.current?.userId===current.id)return profileRequestRef.current.promise;const promise=(async()=>{const{data,error}=await supabase.from('profiles').select('*').eq('id',current.id).maybeSingle();if(error)throw new Error(friendly(error));if(currentUserRef.current?.id===current.id){profileRef.current=data;profileOwnerRef.current=current.id;if(mountedRef.current)setProfile(data)}return data})().finally(()=>{if(profileRequestRef.current?.promise===promise)profileRequestRef.current=null});profileRequestRef.current={userId:current.id,promise};return promise},[]);
 const refreshProfile=useCallback(current=>loadProfile(current||currentUserRef.current,{force:true}),[loadProfile]);
 useEffect(()=>{mountedRef.current=true;if(!supabase){setLoading(false);return()=>{mountedRef.current=false}}let alive=true;const applySession=(next,event)=>{if(!alive)return;const nextUser=next?.user||null;currentUserRef.current=nextUser;setSession(next);setUser(previous=>event==='USER_UPDATED'||previous?.id!==nextUser?.id?nextUser:previous);if(!nextUser){profileRef.current=null;profileOwnerRef.current=null;profileRequestRef.current=null;setProfile(null)}else if(event==='USER_UPDATED'){queueMicrotask(()=>loadProfile(nextUser,{force:true}).catch(()=>{}))}else if(profileOwnerRef.current!==nextUser.id){queueMicrotask(()=>loadProfile(nextUser).catch(()=>{}))}setLoading(false)};supabase.auth.getSession().then(({data})=>applySession(data.session,'INITIAL_SESSION')).catch(()=>{if(alive)setLoading(false)});const{data:listener}=supabase.auth.onAuthStateChange((event,next)=>applySession(next,event));return()=>{alive=false;mountedRef.current=false;listener.subscription.unsubscribe()}},[loadProfile]);
 const signUp=useCallback(async({email,password,...metadata})=>{if(!supabase)throw new Error('Cloud authentication is not configured.');const{data,error}=await supabase.auth.signUp({email,password,options:{data:metadata,emailRedirectTo:`${window.location.origin}/start`}});if(error)throw new Error(friendly(error));return data},[]);
 const signIn=useCallback(async({email,password})=>{if(!supabase)throw new Error('Cloud authentication is not configured.');const{data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw new Error(friendly(error));return data},[]);
 const signOut=useCallback(async()=>{if(supabase)await supabase.auth.signOut()},[]);
 const resetPassword=useCallback(async email=>{if(!supabase)throw new Error('Cloud authentication is not configured.');const{error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/reset-password`});if(error)throw new Error(friendly(error));return{status:'sent'}},[]);
 const updatePassword=useCallback(async password=>{if(!supabase)throw new Error('Cloud authentication is not configured.');const{error}=await supabase.auth.updateUser({password});if(error)throw new Error(friendly(error));return{status:'updated'}},[]);
 const value=useMemo(()=>({user,session,profile,loading,configured:isSupabaseConfigured,signUp,signIn,signOut,resetPassword,updatePassword,refreshProfile}),[loading,profile,refreshProfile,resetPassword,session,signIn,signOut,signUp,updatePassword,user]);
 return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>
}
export const useAuth=()=>useContext(AuthContext);
