import React,{createContext,useCallback,useContext,useEffect,useMemo,useState}from'react';
import{useAuth}from'./AuthContext';
import{supabase}from'../lib/supabase';
import{SUITES,SUITE_STATES}from'../config/suites';
import{effectiveEntitlement}from'../utils/entitlementModel';
const EntitlementContext=createContext(null);
const developmentOverride=process.env.NODE_ENV==='development'&&process.env.REACT_APP_ENTITLEMENT_MODE==='development';
const localDefaults=SUITES.filter(suite=>suite.status===SUITE_STATES.ACTIVE).map(suite=>({suiteId:suite.id,status:SUITE_STATES.ACTIVE,source:'development-default'}));
export function EntitlementProvider({children}){const{user,profile}=useAuth(),userId=user?.id,organizationId=profile?.default_organization_id;const[entitlements,setEntitlements]=useState(localDefaults);const[loading,setLoading]=useState(false);const[managed,setManaged]=useState(false);const refresh=useCallback(async()=>{if(!supabase||!userId||!organizationId){setManaged(false);setEntitlements(localDefaults);return}setLoading(true);const{data,error}=await supabase.from('suite_entitlements').select('suite_id,status,starts_at,ends_at,source').eq('organization_id',organizationId);if(error){setManaged(!developmentOverride);setEntitlements(developmentOverride?localDefaults:[])}else{setManaged(true);setEntitlements((data||[]).map(item=>({suiteId:item.suite_id,status:item.status,startsAt:item.starts_at,endsAt:item.ends_at,source:item.source})))}setLoading(false)},[organizationId,userId]);useEffect(()=>{refresh()},[refresh]);const entitlementFor=useCallback(id=>effectiveEntitlement(entitlements.find(entry=>entry.suiteId===id)),[entitlements]);const statusFor=useCallback(id=>entitlementFor(id)?.effectiveStatus||(managed?SUITE_STATES.LOCKED:SUITES.find(item=>item.id===id)?.status)||SUITE_STATES.LOCKED,[entitlementFor,managed]);const canAccess=useCallback(id=>[SUITE_STATES.ACTIVE,SUITE_STATES.TRIAL].includes(statusFor(id)),[statusFor]);const value=useMemo(()=>({entitlements,loading,managed,developmentOverride,refresh,entitlementFor,statusFor,canAccess}),[canAccess,entitlementFor,entitlements,loading,managed,refresh,statusFor]);return <EntitlementContext.Provider value={value}>{children}</EntitlementContext.Provider>}
export const useEntitlements=()=>useContext(EntitlementContext);
