import React,{createContext,useCallback,useContext,useEffect,useRef,useState} from 'react';
import './InteractionContext.css';

const InteractionContext=createContext(null);

export function InteractionProvider({children}){
 const [request,setRequest]=useState(null),[toasts,setToasts]=useState([]);
 const lastFocus=useRef(null),firstField=useRef(null);
 const finish=useCallback(value=>{setRequest(current=>{current?.resolve(value);return null});window.setTimeout(()=>lastFocus.current?.focus?.(),0)},[]);
 const open=useCallback(config=>new Promise(resolve=>{lastFocus.current=document.activeElement;setRequest({...config,resolve})}),[]);
 const confirm=useCallback(config=>open({kind:'confirm',title:'Confirm action',confirmLabel:'Confirm',...config}),[open]);
 const requestForm=useCallback(config=>open({kind:'form',title:'Enter details',submitLabel:'Save',fields:[],...config}),[open]);
 const toast=useCallback((message,tone='success')=>{const id=`toast-${Date.now()}-${Math.random()}`;setToasts(items=>[...items,{id,message,tone}]);window.setTimeout(()=>setToasts(items=>items.filter(item=>item.id!==id)),4200)},[]);
 useEffect(()=>{if(!request)return;const key=event=>{if(event.key==='Escape'&&request.dismissible!==false)finish(null);if(event.key==='Tab'){const nodes=[...document.querySelectorAll('.aq-dialog-card button:not([disabled]),.aq-dialog-card input,.aq-dialog-card textarea,.aq-dialog-card select')];if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}};document.addEventListener('keydown',key);window.setTimeout(()=>firstField.current?.focus(),0);return()=>document.removeEventListener('keydown',key)},[request,finish]);
 const submit=event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));const missing=(request.fields||[]).find(field=>field.required&&!String(values[field.name]||'').trim());if(missing){toast(`${missing.label} is required.`,'error');return}finish(values)};
 return <InteractionContext.Provider value={{confirm,requestForm,toast}}>{children}{request&&<div className="aq-dialog" role="dialog" aria-modal="true" aria-labelledby="aq-dialog-title"><button className="aq-dialog-backdrop" onClick={()=>request.dismissible===false?null:finish(null)} aria-label="Close dialog"/><section className="aq-dialog-card"><header><div><span>AUREQIN WORKSPACE</span><h2 id="aq-dialog-title">{request.title}</h2>{request.message&&<p>{request.message}</p>}</div><button onClick={()=>finish(null)} aria-label="Close dialog">×</button></header>{request.kind==='confirm'?<footer><button className="btn-secondary" ref={firstField} onClick={()=>finish(false)}>Cancel</button><button className={request.destructive?'aq-danger':'btn-primary'} onClick={()=>finish(true)}>{request.confirmLabel}</button></footer>:<form onSubmit={submit}>{request.fields.map((field,index)=><label key={field.name}>{field.label}{field.type==='textarea'?<textarea ref={index===0?firstField:null} name={field.name} defaultValue={field.value||''} rows={field.rows||4} placeholder={field.placeholder||''}/>:field.type==='select'?<select ref={index===0?firstField:null} name={field.name} defaultValue={field.value||''}>{(field.options||[]).map(option=><option key={typeof option==='string'?option:option.value} value={typeof option==='string'?option:option.value}>{typeof option==='string'?option:option.label}</option>)}</select>:<input ref={index===0?firstField:null} name={field.name} type={field.type||'text'} defaultValue={field.value||''} placeholder={field.placeholder||''} step={field.step}/>} {field.help&&<small>{field.help}</small>}</label>)}<footer><button type="button" className="btn-secondary" onClick={()=>finish(null)}>Cancel</button><button type="submit" className="btn-primary">{request.submitLabel}</button></footer></form>}</section></div>}<div className="aq-toast-region" aria-live="polite">{toasts.map(item=><div key={item.id} className={`aq-toast ${item.tone}`}>{item.message}</div>)}</div></InteractionContext.Provider>;
}

export function useInteractions(){const value=useContext(InteractionContext);if(!value)throw new Error('useInteractions must be used inside InteractionProvider.');return value}
