begin;
create extension if not exists pgcrypto;
create type public.organization_role as enum ('owner','admin','member','viewer');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,first_name text,last_name text,display_name text,job_role text,company text,industry text,company_size text,country text,primary_use_case text,avatar_url text,onboarding_completed boolean not null default false,default_organization_id uuid,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.organizations(id uuid primary key default gen_random_uuid(),name text not null,slug text unique,created_by uuid not null references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.organization_members(organization_id uuid references public.organizations(id) on delete cascade,user_id uuid references auth.users(id) on delete cascade,role public.organization_role not null default 'member',created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),primary key(organization_id,user_id));
alter table public.profiles add constraint profiles_default_org_fk foreign key(default_organization_id) references public.organizations(id) on delete set null;
create table public.projects(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,created_by uuid not null references auth.users(id),name text not null,status text not null default 'active',methodology text,current_phase text,target_date date,content jsonb not null default '{}'::jsonb,local_migration_key text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,local_migration_key));

create table public.project_documents(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,created_by uuid not null references auth.users(id),document_type text not null,methodology text,lifecycle_phase text,title text not null,schema_version integer not null default 1,content jsonb not null default '{}'::jsonb,completion_score numeric,quality_score numeric,status text not null default 'draft',last_edited_by uuid references auth.users(id),last_edited_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(project_id,document_type));
create table public.datasets(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,created_by uuid not null references auth.users(id),name text not null,description text,source_type text,row_count bigint not null default 0,column_count integer not null default 0,column_metadata jsonb not null default '[]'::jsonb,active_version_id uuid,status text not null default 'active',last_modified_at timestamptz not null default now(),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.dataset_versions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,dataset_id uuid not null references public.datasets(id) on delete cascade,created_by uuid not null references auth.users(id),version_number integer not null,structured_data jsonb,storage_path text,content_hash text,row_count bigint,column_count integer,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(dataset_id,version_number));
alter table public.datasets add constraint datasets_active_version_fk foreign key(active_version_id) references public.dataset_versions(id) on delete set null;
create table public.analyses(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,created_by uuid not null references auth.users(id),tool_type text not null,dataset_id uuid references public.datasets(id) on delete set null,dataset_version_id uuid references public.dataset_versions(id) on delete set null,input_config jsonb not null default '{}'::jsonb,result_data jsonb not null default '{}'::jsonb,interpretation text,status text not null default 'draft',completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.evidence_items(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,created_by uuid not null references auth.users(id),title text not null,evidence_type text,source_analysis_id uuid references public.analyses(id) on delete set null,summary text,chart_config jsonb not null default '{}'::jsonb,linked_document_ids uuid[] not null default '{}',linked_report_ids uuid[] not null default '{}',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.reports(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,created_by uuid not null references auth.users(id),title text not null,status text not null default 'draft',schema_version integer not null default 1,content jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.report_sections(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,report_id uuid not null references public.reports(id) on delete cascade,created_by uuid not null references auth.users(id),section_type text,title text,position integer not null default 0,content jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create table public.project_tasks(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,created_by uuid not null references auth.users(id),title text not null,status text,due_at timestamptz,owner_id uuid references auth.users(id),content jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.project_risks(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,created_by uuid not null references auth.users(id),title text not null,status text,probability numeric,impact numeric,owner_id uuid references auth.users(id),content jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.project_issues(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,created_by uuid not null references auth.users(id),title text not null,status text,owner_id uuid references auth.users(id),content jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.project_decisions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,created_by uuid not null references auth.users(id),title text not null,decision text,status text,decided_at timestamptz,content jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.project_activity(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,created_by uuid not null references auth.users(id),event_type text not null,summary text not null,asset_type text,asset_id uuid,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.user_preferences(id uuid primary key default gen_random_uuid(),user_id uuid not null unique references auth.users(id) on delete cascade,organization_id uuid references public.organizations(id) on delete set null,created_by uuid not null references auth.users(id),theme text,reduced_motion boolean,default_project_id uuid references public.projects(id) on delete set null,default_dataset_id uuid references public.datasets(id) on delete set null,sidebar_state jsonb not null default '{}'::jsonb,workspace_density text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.subscriptions(id uuid primary key default gen_random_uuid(),organization_id uuid not null unique references public.organizations(id) on delete cascade,user_id uuid references auth.users(id) on delete set null,created_by uuid not null references auth.users(id),stripe_customer_id text, stripe_subscription_id text,plan_key text,subscription_status text not null default 'inactive',trial_start timestamptz,trial_end timestamptz,current_period_end timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());

create or replace function public.touch_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end$$;
do $$declare t text;begin foreach t in array array['profiles','organizations','organization_members','projects','project_documents','datasets','dataset_versions','analyses','evidence_items','reports','report_sections','project_tasks','project_risks','project_issues','project_decisions','project_activity','user_preferences','subscriptions'] loop execute format('create trigger touch_%I before update on public.%I for each row execute function public.touch_updated_at()',t,t);end loop;end$$;
create or replace function public.is_org_member(org uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from organization_members where organization_id=org and user_id=auth.uid())$$;
create or replace function public.can_edit_org(org uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from organization_members where organization_id=org and user_id=auth.uid() and role in ('owner','admin','member'))$$;
create or replace function public.can_admin_org(org uuid) returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from organization_members where organization_id=org and user_id=auth.uid() and role in ('owner','admin'))$$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$declare org_id uuid;begin insert into profiles(id,first_name,last_name,display_name,job_role) values(new.id,new.raw_user_meta_data->>'first_name',new.raw_user_meta_data->>'last_name',coalesce(new.raw_user_meta_data->>'display_name',new.raw_user_meta_data->>'first_name'),new.raw_user_meta_data->>'job_role');insert into organizations(name,created_by) values(coalesce(new.raw_user_meta_data->>'company',new.email||'''s Workspace'),new.id) returning id into org_id;insert into organization_members(organization_id,user_id,role,created_by) values(org_id,new.id,'owner',new.id);update profiles set default_organization_id=org_id where id=new.id;return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

do $$declare t text;begin foreach t in array array['profiles','organizations','organization_members','projects','project_documents','datasets','dataset_versions','analyses','evidence_items','reports','report_sections','project_tasks','project_risks','project_issues','project_decisions','project_activity','user_preferences','subscriptions'] loop execute format('alter table public.%I enable row level security',t);end loop;end$$;
create policy profiles_self_select on profiles for select using(id=auth.uid());create policy profiles_self_update on profiles for update using(id=auth.uid()) with check(id=auth.uid());
create policy org_select on organizations for select using(is_org_member(id));create policy org_update on organizations for update using(can_admin_org(id));
create policy members_select on organization_members for select using(is_org_member(organization_id));create policy members_manage on organization_members for all using(can_admin_org(organization_id)) with check(can_admin_org(organization_id));
create policy projects_select on projects for select using(is_org_member(organization_id));create policy projects_write on projects for all using(can_edit_org(organization_id)) with check(can_edit_org(organization_id) and created_by=auth.uid());
do $$declare t text;begin foreach t in array array['project_documents','datasets','dataset_versions','analyses','evidence_items','reports','report_sections','project_tasks','project_risks','project_issues','project_decisions','project_activity'] loop execute format('create policy %I_select on public.%I for select using(public.is_org_member(organization_id))',t,t);execute format('create policy %I_write on public.%I for all using(public.can_edit_org(organization_id)) with check(public.can_edit_org(organization_id) and created_by=auth.uid())',t,t);end loop;end$$;
create policy preferences_self on user_preferences for all using(user_id=auth.uid()) with check(user_id=auth.uid() and created_by=auth.uid());
create policy subscriptions_select on subscriptions for select using(is_org_member(organization_id));create policy subscriptions_admin on subscriptions for all using(can_admin_org(organization_id)) with check(can_admin_org(organization_id));
create index projects_org_idx on projects(organization_id);create index documents_project_idx on project_documents(project_id);create index datasets_project_idx on datasets(project_id);create index versions_dataset_idx on dataset_versions(dataset_id);create index analyses_project_idx on analyses(project_id);create index evidence_project_idx on evidence_items(project_id);create index activity_project_idx on project_activity(project_id,created_at desc);
commit;
