-- Aureqin suite, commercial-product, entitlement, and AI-metering foundation.
-- Stripe/provider identifiers are references only; authorization remains in suite_entitlements.
create table if not exists public.suites(id text primary key,name text not null,status text not null check(status in('active','trial','locked','coming_soon')),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
insert into public.suites(id,name,status) values('operational-excellence','Operational Excellence','active'),('project-management','Project Management','active'),('supply-chain','Supply Chain','coming_soon'),('healthcare','Healthcare','coming_soon'),('manufacturing','Manufacturing','coming_soon'),('technology','Technology','coming_soon'),('financial-services','Financial Services','coming_soon'),('construction','Construction','locked') on conflict(id) do update set name=excluded.name;

create table if not exists public.subscription_products(id uuid primary key default gen_random_uuid(),code text not null unique,name text not null,product_type text not null check(product_type in('suite','bundle','addon','enterprise')),status text not null default 'active',provider_product_id text,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.subscription_plans(id uuid primary key default gen_random_uuid(),product_id uuid not null references public.subscription_products(id),code text not null unique,name text not null,audience text not null check(audience in('individual','team','enterprise')),seat_allowance integer,storage_bytes bigint,ai_token_allowance bigint,trial_days integer not null default 0,grandfatherable boolean not null default false,status text not null default 'active',metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.subscription_prices(id uuid primary key default gen_random_uuid(),plan_id uuid not null references public.subscription_plans(id),currency text not null default 'usd',unit_amount integer not null check(unit_amount>=0),billing_interval text check(billing_interval in('month','year','one_time','contract')),price_kind text not null check(price_kind in('founding','regular','contract','grandfathered')),provider_price_id text,status text not null default 'active',starts_at timestamptz,ends_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.subscriptions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,plan_id uuid references public.subscription_plans(id),price_id uuid references public.subscription_prices(id),status text not null check(status in('trialing','active','past_due','paused','canceled','expired')),provider text,provider_customer_id text,provider_subscription_id text,seat_quantity integer not null default 1,current_period_start timestamptz,current_period_end timestamptz,trial_ends_at timestamptz,cancel_at timestamptz,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.suite_entitlements(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,suite_id text not null references public.suites(id),subscription_id uuid references public.subscriptions(id) on delete set null,status text not null check(status in('active','trial','locked','coming_soon')),source text not null default 'manual',starts_at timestamptz,ends_at timestamptz,metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,suite_id));
create index if not exists subscriptions_organization_idx on public.subscriptions(organization_id,status);create index if not exists suite_entitlements_lookup_idx on public.suite_entitlements(organization_id,suite_id,status);

create table if not exists public.ai_usage_events(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,user_id uuid not null references auth.users(id),project_id uuid references public.projects(id) on delete set null,suite_id text references public.suites(id),operation_type text not null,model text not null,input_tokens bigint not null default 0 check(input_tokens>=0),output_tokens bigint not null default 0 check(output_tokens>=0),total_tokens bigint generated always as(input_tokens+output_tokens) stored,estimated_cost numeric(14,6) not null default 0 check(estimated_cost>=0),allowance_consumed bigint not null default 0 check(allowance_consumed>=0),occurred_at timestamptz not null default now(),metadata jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.ai_allowance_periods(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,subscription_id uuid references public.subscriptions(id) on delete set null,period_start timestamptz not null,period_end timestamptz not null,token_allowance bigint not null default 0,consumed_tokens bigint not null default 0,overage_tokens bigint not null default 0,status text not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(organization_id,period_start,period_end),check(period_end>period_start));
create index if not exists ai_usage_org_time_idx on public.ai_usage_events(organization_id,occurred_at desc);create index if not exists ai_usage_user_time_idx on public.ai_usage_events(user_id,occurred_at desc);create index if not exists ai_usage_project_time_idx on public.ai_usage_events(project_id,occurred_at desc);create index if not exists ai_usage_suite_time_idx on public.ai_usage_events(suite_id,occurred_at desc);

alter table public.suites enable row level security;alter table public.subscription_products enable row level security;alter table public.subscription_plans enable row level security;alter table public.subscription_prices enable row level security;alter table public.subscriptions enable row level security;alter table public.suite_entitlements enable row level security;alter table public.ai_usage_events enable row level security;alter table public.ai_allowance_periods enable row level security;
create policy suites_authenticated_read on public.suites for select to authenticated using(true);create policy products_authenticated_read on public.subscription_products for select to authenticated using(status='active');create policy plans_authenticated_read on public.subscription_plans for select to authenticated using(status='active');create policy prices_authenticated_read on public.subscription_prices for select to authenticated using(status='active');
create policy subscriptions_org_read on public.subscriptions for select to authenticated using(public.axentra_org_role(organization_id) is not null);
create policy entitlements_org_read on public.suite_entitlements for select to authenticated using(public.axentra_org_role(organization_id) is not null);
create policy ai_usage_org_read on public.ai_usage_events for select to authenticated using(public.axentra_org_role(organization_id) is not null);create policy ai_allowance_org_read on public.ai_allowance_periods for select to authenticated using(public.axentra_org_role(organization_id) is not null);
-- No client INSERT/UPDATE/DELETE policy exists for subscriptions, entitlements, AI usage, or allowances. Future billing webhooks and metering writes must use a trusted server/service role; provider secrets never reach the client.
