import React,{useMemo,useState}from'react';
import{CartesianGrid,Legend,ReferenceLine,ResponsiveContainer,Scatter,ScatterChart,Tooltip,XAxis,YAxis}from'recharts';
import{useWorksheet}from'../context/WorksheetContext';
import{useAnalysis}from'../context/AnalysisContext';
import{useReport}from'../context/ReportContext';
import{boxCoxTransform,fitDistributions}from'../utils/distributionEngine';
import'./Tool.css';

const format=value=>Number.isFinite(value)?Number(value).toPrecision(5):'—';
export default function DistributionAnalysis(){
 const{activeDataset,getNumericColumns,getColumnData}=useWorksheet(),{registerAnalysisResult}=useAnalysis(),{addReportItem}=useReport();
 const numeric=getNumericColumns(),[variable,setVariable]=useState(''),[result,setResult]=useState(null),[selectedFit,setSelectedFit]=useState(''),[boxCox,setBoxCox]=useState(null),[error,setError]=useState(''),[saved,setSaved]=useState(false);
 const fit=useMemo(()=>result?.fits.find(item=>item.name===selectedFit)||result?.fits[0]||null,[result,selectedFit]);
 const run=()=>{setError('');setSaved(false);setBoxCox(null);try{if(!variable)throw new Error('Select a numeric variable to analyze.');const values=getColumnData(variable);if(values.length<3)throw new Error(`${variable} contains fewer than 3 valid numeric observations.`);const next=fitDistributions({values});setResult(next);setSelectedFit(next.recommended||'')}catch(runError){setResult(null);setError(runError.message)}};
 const exploreBoxCox=()=>{setError('');try{setBoxCox(boxCoxTransform({values:getColumnData(variable)}))}catch(transformError){setBoxCox(null);setError(transformError.message)}};
 const save=()=>{if(!result)return;const structuredResult={...result,boxCoxExploration:boxCox};const payload={toolId:'distribution-analysis',toolType:'distribution-analysis',title:`Distribution Analysis — ${variable}`,phase:'Analyze',projectId:activeDataset?.projectId||'',datasetIds:activeDataset?[activeDataset.id]:[],datasetVersionIds:activeDataset?.versionId?[activeDataset.versionId]:[],inputConfiguration:{variable,candidates:result.fits.map(item=>item.name)},result:structuredResult,interpretation:`${result.recommended} has the lowest AIC among eligible candidates. Review its probability plot, K-S distance, BIC, process knowledge, and caveats before selecting a distribution.`,validationStatus:'UNVALIDATED'};registerAnalysisResult(payload);addReportItem({...payload,assetType:'analysis',statsSummary:Object.fromEntries(result.fits.map(item=>[`${item.name} AIC`,item.aic])),rawData:result.fits.map(item=>({distribution:item.name,...item.parameters,AIC:item.aic,BIC:item.bic,KS:item.ksStatistic})),provenance:{method:result.method,methodVersion:result.methodVersion,datasetId:activeDataset?.id,datasetVersionId:activeDataset?.versionId,variable,boxCoxExploration:boxCox}});setSaved(true)};
 return <div className="tool-content"><div className="card" style={{padding:'1.25rem',marginBottom:'1rem'}}><h3>Candidate distribution fitting</h3><p className="tool-hint">Compare transparent fit evidence for Normal, Lognormal, Weibull, Exponential, and Gamma candidates. No candidate is declared “true” from one score.</p><div className="form-grid"><div className="form-group"><label>Numeric variable</label><select value={variable} onChange={event=>{setVariable(event.target.value);setResult(null)}}><option value="">Select a measurement</option>{numeric.map(column=><option key={column.name}>{column.name}</option>)}</select></div></div><button className="btn-primary" onClick={run}>Fit distributions</button>{error&&<div className="alert alert-danger" role="alert" style={{marginTop:'1rem'}}><strong>Unable to fit distributions</strong><div>{error}</div></div>}</div>
 {result&&<><div className="card" style={{padding:'1.25rem',marginBottom:'1rem'}}><div className="results-header"><div><span className="results-eyebrow">WHAT AUREQIN FOUND</span><h3>{result.recommended} is the leading candidate by AIC</h3></div><span className="validation-badge">UNVALIDATED</span></div><p>{result.selectionBasis}</p><div className="results-table-wrap"><table><thead><tr><th>Distribution</th><th>Parameters</th><th>AIC</th><th>BIC</th><th>K-S distance</th></tr></thead><tbody>{result.fits.map(item=><tr key={item.name}><td><button className="btn-secondary" onClick={()=>setSelectedFit(item.name)}>{item.name}</button></td><td>{Object.entries(item.parameters).map(([key,value])=>`${key}: ${format(value)}`).join(' · ')}</td><td>{format(item.aic)}</td><td>{format(item.bic)}</td><td>{format(item.ksStatistic)}</td></tr>)}</tbody></table></div></div>
 {fit&&<div className="card" style={{padding:'1.25rem',marginBottom:'1rem'}}><h3>{fit.name} probability plot</h3><div style={{height:340}}><ResponsiveContainer><ScatterChart margin={{top:15,right:20,bottom:30,left:25}}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="theoretical" type="number" name="Theoretical quantile"/><YAxis dataKey="observed" type="number" name="Observed"/><Tooltip/><Legend/><Scatter data={fit.probabilityPlot} name="Ordered observations" fill="var(--accent)"/><ReferenceLine segment={[{x:fit.probabilityPlot[0].theoretical,y:fit.probabilityPlot[0].observed},{x:fit.probabilityPlot.at(-1).theoretical,y:fit.probabilityPlot.at(-1).observed}]} stroke="var(--orange)" strokeWidth={2}/></ScatterChart></ResponsiveContainer></div><div className="alert alert-info"><strong>WHY IT MATTERS</strong><div>Points that track a straight relationship support the fitted shape. Systematic curvature or tail departures indicate mismatch.</div></div><div className="alert alert-warning"><strong>WHAT TO CONSIDER NEXT</strong><div>{[...fit.caveats,...result.warnings].join(' ')}</div></div></div>}
 <div className="card" style={{padding:'1.25rem',marginBottom:'1rem'}}><h3>Box-Cox exploration</h3><p>Explore a profile-likelihood transformation without changing the worksheet or source dataset.</p><button className="btn-secondary" onClick={exploreBoxCox}>Explore Box-Cox</button>{boxCox&&<div className="alert alert-info" style={{marginTop:'.75rem'}}><strong>Suggested λ: {boxCox.lambda}</strong><div>{boxCox.warnings.join(' ')}</div></div>}</div><button className="btn-primary" onClick={save}>{saved?'Added to project and report':'Add structured result to project & report'}</button></>}
 </div>;
}
