import React,{act,useState}from'react';import{createRoot}from'react-dom/client';import{HeijunkaVisual,StandardWorkVisual,YamazumiVisual}from'./LeanFlowVisuals';
global.IS_REACT_ACT_ENVIRONMENT=true;
const mount=async element=>{const host=document.createElement('div'),root=createRoot(host);await act(async()=>root.render(element));return{host,root}};
const change=async(element,value)=>act(async()=>{const prototype=element.tagName==='SELECT'?window.HTMLSelectElement.prototype:window.HTMLInputElement.prototype,setter=Object.getOwnPropertyDescriptor(prototype,'value').set;setter.call(element,value);element.dispatchEvent(new Event('change',{bubbles:true}))});
const click=element=>act(async()=>element.dispatchEvent(new MouseEvent('click',{bubbles:true})));
function Harness({kind,initial,onState}){const[draft,setState]=useState(initial),setDraft=next=>{setState(next);onState?.(next)},Component=kind==='yamazumi'?YamazumiVisual:kind==='standard'?StandardWorkVisual:HeijunkaVisual;return <><Component draft={draft} setDraft={setDraft}/><output>{JSON.stringify(draft)}</output></>}
test('rendered Yamazumi stacks stations, shows takt and recalculates moved work',async()=>{let state;const{host,root}=await mount(<Harness kind="yamazumi" initial={{type:'yamazumi',takt:5,items:[{id:'a',name:'Load',station:'Station 1',duration:3,classification:'VA'},{id:'b',name:'Inspect',station:'Station 2',duration:4,classification:'NVA'}]}} onState={next=>state=next}/>);expect(host.querySelectorAll('.yama-station')).toHaveLength(2);expect(host.querySelector('.takt-line').textContent).toContain('Takt 5');await change(host.querySelector('[aria-label="Load station"]'),'Station 2');expect(state.items[0].station).toBe('Station 2');expect(host.querySelector('.flow-metrics').textContent).toContain('Bottleneck Station 2');await change(host.querySelector('[aria-label="Load duration"]'),'6');expect(host.textContent).toContain('Above takt');await act(async()=>root.unmount())});
test('rendered Yamazumi reopens exact serialized practitioner data',async()=>{const saved={type:'yamazumi',takt:4,items:[{id:'persisted',name:'Saved element',station:'Operator A',duration:2,classification:'VA'}]},{host,root}=await mount(<Harness kind="yamazumi" initial={JSON.parse(JSON.stringify(saved))}/>);expect(JSON.parse(host.querySelector('output').textContent)).toEqual(saved);expect(host.querySelector('input').value).toBe('4');await act(async()=>root.unmount())});
test('rendered Combination Sheet authors categories and updates visual totals',async()=>{let state;const{host,root}=await mount(<Harness kind="standard" initial={{type:'standard-work',takt:8,items:[],locations:[]}} onState={next=>state=next}/>);await click([...host.querySelectorAll('button')].find(x=>x.textContent==='Add work element'));await change(host.querySelector('[aria-label="New step manual time"]'),'2');await change(host.querySelector('[aria-label="New step machine time"]'),'3');await change(host.querySelector('[aria-label="New step walking time"]'),'1');expect(host.querySelector('.flow-metrics').textContent).toContain('Manual 2 · Machine 3 · Walking 1');expect(host.querySelector('.combo-track .machine')).not.toBeNull();expect(state.items[0].id).toBeTruthy();await act(async()=>root.unmount())});
test('rendered Standard Work Chart creates path and persists coordinates and markers',async()=>{let state;const{host,root}=await mount(<Harness kind="standard" initial={{type:'standard-work',takt:8,items:[],locations:[]}} onState={next=>state=next}/>);await click([...host.querySelectorAll('button')].find(x=>x.textContent==='Work Chart'));const add=()=>[...host.querySelectorAll('button')].find(x=>x.textContent==='Add work location');await click(add());await click(add());expect(host.querySelectorAll('.work-chart line')).toHaveLength(1);const safety=host.querySelector('.location-editors input[type="checkbox"]');await click(safety);expect(state.locations[0].safety).toBe(true);expect(state.locations[0]).toHaveProperty('x');expect(state.locations[1].sequence).toBe(2);await act(async()=>root.unmount())});
test('rendered Heijunka box edits slots and exposes infeasibility',async()=>{let state;const{host,root}=await mount(<Harness kind="heijunka" initial={{type:'heijunka',pitch:10,availableTime:20,changeoverTime:5,items:[{id:'a',name:'Family A',demand:30,duration:1,packQuantity:10}],sequence:[]}} onState={next=>state=next}/>);expect(host.querySelectorAll('.heijunka-box button')).toHaveLength(2);expect(host.querySelector('.flow-notice').textContent).toContain('Required slots 3');expect(host.querySelector('.flow-notice').textContent).toContain('Infeasible');const slot=()=>host.querySelector('[aria-label="Family A slot 1"]');await click(slot());expect(state.sequence[0]).toBe('');await click(slot());expect(state.sequence[0]).toBe('Family A');expect(JSON.parse(host.querySelector('output').textContent).items[0].name).toBe('Family A');await act(async()=>root.unmount())});
