import React,{useEffect,useMemo,useState}from'react';
import {useNavigate}from'react-router-dom';
import ProjectPlacementAction from'../components/ProjectPlacementAction';
import ReportInclusionAction from'../components/ReportInclusionAction';
import {useAnalysis}from'../context/AnalysisContext';
import {useAuth}from'../context/AuthContext';
import {useProjects}from'../context/ProjectsContext';
import {attachEvidence,createProductRecord,normalizeCtq,normalizeRequirement,normalizeVerification,productReadiness,reviseProductRecord,traceabilityRows,transitionVerification,VERIFICATION_STATES}from'../foundation/productDevelopmentRecords';
import {archivePersistedProductRecord,attachPersistedEvidence,createPersistedProductFinding,createPersistedProductRecord,loadProductDevelopmentRecords,savedEvidencePath,updatePersistedProductRecord}from'../services/productDevelopmentRepository';
import {engineeringSampleSize,fitMixtureModel,generateMixtureDesign,generatePlackettBurman,generateTaguchiDesign,monteCarloSimulation,taguchiSignalToNoise,toleranceStack,tostMeans}from'../utils/productDevelopmentEngine';
import {createPractitionerFinding,structuredReportPayload}from'../utils/practitionerWorkflow';
import'./Tool.css';

const TABS=['Requirements & CTQs','Verification Plan','Traceability','Pilot Readiness','Engineering Analytics'];
const blankRequirement={title:'',description:'',source:'',category:'Product',priority:'Medium',owner:'',status:'Draft',readinessState:'Not Assessable'};
const blankCtq={name:'',description:'',characteristicType:'Continuous',unit:'',target:'',lsl:'',usl:'',toleranceDirection:'Bilateral',measurementMethod:'',owner:'',status:'Draft',rationale:'',requirementIds:[]};
const blankVerification={testName:'',purpose:'',verificationMethod:'',testType:'',sampleSize:'',sampleDefinition:'',conditions:'',equipment:'',measurementSystem:'',acceptanceCriterion:'',owner:'',status:'Draft',result:'Inconclusive',rationale:'',comments:'',requirementIds:[],ctqIds:[],evidenceRequired:true,evidenceLinks:[],linkedAnalysisIds:[],linkedReliabilityAnalysisIds:[],linkedFindingIds:[]};
const analyticsDefaults={
 'Plackett-Burman':{factors:[{name:'A',low:0,high:1},{name:'B',low:0,high:1},{name:'C',low:0,high:1}],runs:8,seed:20260810},
 Taguchi:{array:'L9',factors:[{name:'A',levels:[1,2,3]},{name:'B',levels:[10,20,30]}],seed:20260810,objective:'nominal',replicates:[24.8,25.1,25]},
 Mixture:{components:['A','B','C'],type:'simplex-centroid',degree:2,total:1,model:'quadratic'},
 'Monte Carlo':{inputs:[{name:'A',unit:'mm',distribution:'normal',parameters:{mean:10,sd:.1}},{name:'B',unit:'mm',distribution:'uniform',parameters:{min:2,max:2.2}}],expression:'A-B',count:10000,seed:20260810,lsl:7.5,usl:8.5,responseUnit:'mm'},
 'Tolerance Stack':{contributors:[{name:'A',unit:'mm',nominal:10,direction:1,tolerance:.2},{name:'B',unit:'mm',nominal:2,direction:-1,minusTolerance:.1,plusTolerance:.1}],lsl:7.5,usl:8.5,count:10000,seed:20260810},
 TOST:{groupA:[10,10.1,9.9,10],groupB:[10.05,10,10.1,9.95],margin:.5,alpha:.05,paired:false},
 'Sample Size':{type:'two-means',alpha:.05,power:.9,difference:.5,sigma:1},
};
const parseJson=text=>{try{return JSON.parse(text)}catch{throw new Error('Configuration must be valid JSON.')}};

export default function ProductDevelopmentWorkspace(){
 const {user,profile,configured}=useAuth(),{projects}=useProjects(),analysis=useAnalysis(),navigate=useNavigate();
 const [projectId,setProjectId]=useState(analysis.projectId||projects[0]?.id||''),project=projects.find(item=>item.id===projectId),context={userId:user?.id||'',organizationId:project?.organizationId||profile?.default_organization_id||'',projectId};
 const [tab,setTab]=useState(TABS[0]),[records,setRecords]=useState({requirements:[],ctqs:[],verifications:[],revisions:[],links:[],findings:[]}),[selected,setSelected]=useState(null),[draft,setDraft]=useState(null),[recordType,setRecordType]=useState('requirement'),[filter,setFilter]=useState('All'),[search,setSearch]=useState(''),[saveState,setSaveState]=useState('Saved'),[error,setError]=useState(''),[notice,setNotice]=useState(''),[analyticsType,setAnalyticsType]=useState('Plackett-Burman'),[analyticsConfig,setAnalyticsConfig]=useState(JSON.stringify(analyticsDefaults['Plackett-Burman'],null,2)),[result,setResult]=useState(null);
 const load=async()=>{if(!configured||!context.userId||!context.organizationId||!context.projectId)return;setSaveState('Saving');try{setRecords(await loadProductDevelopmentRecords(context));setSaveState('Saved');setError('')}catch(problem){setSaveState('Unsaved');setError(problem.message)}};
 useEffect(()=>{load()},[configured,context.organizationId,context.projectId,context.userId]); // eslint-disable-line react-hooks/exhaustive-deps
 const choose=(type,record)=>{setRecordType(type);setSelected(record);setDraft({...record});setSaveState('Saved')};
 const createNew=type=>{const base=type==='requirement'?blankRequirement:type==='ctq'?blankCtq:blankVerification,setter=type==='requirement'?normalizeRequirement:type==='ctq'?normalizeCtq:normalizeVerification;setRecordType(type);setSelected(null);setDraft(setter(base,context));setSaveState('Unsaved')};
 const change=(field,value)=>{setDraft(previous=>({...previous,[field]:value}));setSaveState('Unsaved')};
 const save=async()=>{try{setError('');setSaveState('Saving');if(!draft)throw new Error('Select or create a record.');if(recordType==='requirement'&&!draft.title.trim())throw new Error('Requirement title is required.');if(recordType==='ctq'&&!draft.name.trim())throw new Error('CTQ name is required.');if(recordType==='verification'&&!draft.testName.trim())throw new Error('Verification test name is required.');let saved;if(selected){const revised=reviseProductRecord(recordType,selected,draft,context,draft.rationale||draft.comments||'Practitioner edit');saved=await updatePersistedProductRecord(recordType,selected,revised.record,revised.revision,context)}else saved=await createPersistedProductRecord(recordType,createProductRecord(recordType,draft,context),context);await load();setSelected(saved);setDraft(saved);setSaveState('Saved');setNotice(`${recordType} saved with revision history.`)}catch(problem){setSaveState('Unsaved');setError(problem.message)}};
 const archive=async()=>{try{await archivePersistedProductRecord(recordType,selected,context);setSelected(null);setDraft(null);await load();setNotice('Record archived; history was preserved.')}catch(problem){setError(problem.message)}};
 const duplicateVerification=()=>{if(!draft)return;setSelected(null);setDraft({...draft,id:undefined,verificationKey:undefined,testName:`${draft.testName} Copy`,status:'Draft',result:'Inconclusive',evidenceLinks:[],linkedFindingIds:[],revision:1});setSaveState('Unsaved')};
 const transition=async status=>{try{const transitioned=transitionVerification(draft,status,context),revised=reviseProductRecord('verification',selected,transitioned,context,`Execution decision: ${status}`);const saved=await updatePersistedProductRecord('verification',selected,revised.record,revised.revision,context);setDraft(saved);setSelected(saved);await load();setNotice(status==='Failed'?'Verification Failed':`${status} saved.`)}catch(problem){setError(problem.message)}};
 const attachAnalysis=async analysisId=>{try{const evidence=analysis.analysisResults.find(item=>item.id===analysisId);if(!evidence)throw new Error('Select an existing saved analysis.');await attachPersistedEvidence(draft,{type:'analysis',objectId:evidence.id,title:evidence.title||'Saved Analysis',organizationId:evidence.organizationId,projectId:evidence.projectId,owner:evidence.createdBy},context);const attached=attachEvidence({...draft,linkedAnalysisIds:[...new Set([...(draft.linkedAnalysisIds||[]),evidence.id])]},{type:'analysis',objectId:evidence.id,title:evidence.title||'Saved Analysis',organizationId:evidence.organizationId,projectId:evidence.projectId,owner:evidence.createdBy},context),revised=reviseProductRecord('verification',selected,attached,context,'Attached saved analysis evidence');const saved=await updatePersistedProductRecord('verification',selected,revised.record,revised.revision,context);setDraft(saved);setSelected(saved);await load();setNotice('Saved analysis linked by canonical identity.')}catch(problem){setError(problem.message)}};
 const findings=useMemo(()=>records.findings||[],[records.findings]);
 const rows=useMemo(()=>traceabilityRows({...records,risks:project?.risks||[],findings}),[findings,project,records]);
 const readiness=useMemo(()=>productReadiness({...records,risks:project?.risks||[],findings}),[findings,project,records]);
 const createFinding=async()=>{const condition=draft?.status==='Failed'?{type:'verification_failure',statement:'Verification failed.'}:draft?.status==='Inconclusive'?{type:'verification_inconclusive',statement:'Verification remains inconclusive.'}:null;if(!condition){setNotice('No evidence-supported finding condition was detected.');return}try{const finding=createPractitionerFinding({analysisId:draft.linkedAnalysisIds?.[0]||'',dataset:analysis.dataset,variable:draft.ctqIds?.join(', '),type:condition.type,severity:'warning',statement:condition.statement,evidence:{requirementIds:draft.requirementIds,ctqIds:draft.ctqIds,verificationId:draft.id,result:draft.result,status:draft.status,evidenceLinks:draft.evidenceLinks,method:'design-verification',methodVersion:'1.0.0'}});await createPersistedProductFinding({...finding,verificationId:draft.id},context);await load();setNotice('Finding Created. No PM task was generated.')}catch(problem){setError(problem.message)}};
 const runAnalytics=()=>{try{const config=parseJson(analyticsConfig);let output;if(analyticsType==='Plackett-Burman')output=generatePlackettBurman(config);else if(analyticsType==='Taguchi')output={...generateTaguchiDesign(config),signalToNoise:taguchiSignalToNoise(config.replicates,config.objective)};else if(analyticsType==='Mixture'){const design=generateMixtureDesign(config),rows=config.responses?design.runs.map((run,index)=>({...run.proportions,response:config.responses[index]})):null;output={...design,model:rows?fitMixtureModel(rows,config.components,config.model,config.total):null}}else if(analyticsType==='Monte Carlo')output=monteCarloSimulation(config);else if(analyticsType==='Tolerance Stack')output=toleranceStack(config);else if(analyticsType==='TOST')output=tostMeans(config);else output=engineeringSampleSize(config);setResult(output);setError('')}catch(problem){setResult(null);setError(problem.message)}};
 const changeAnalytics=type=>{setAnalyticsType(type);setAnalyticsConfig(JSON.stringify(analyticsDefaults[type],null,2));setResult(null)};
 const reportPayload=structuredReportPayload({method:result?.method||`product-development-${tab}`,methodVersion:result?.methodVersion||'1.0.0',configuration:{tab,analyticsType},metrics:result||readiness,tables:{requirements:records.requirements,ctqs:records.ctqs,verifications:records.verifications,traceability:rows.map(row=>({requirement:row.requirement?.requirementKey,ctq:row.ctq?.ctqKey,verification:row.verification?.verificationKey,flags:row.flags.join(', ')}))},interpretation:result?.warning||readiness.statement,evidence:{projectId,organizationId:context.organizationId}}),placementDraft={title:`Product Development — ${tab}`,toolId:'product-development',projectId,analysis:{toolId:'product-development',method:result?.method||`product-development-${tab}`,methodVersion:result?.methodVersion||'1.0.0',validationStatus:'UNVALIDATED',result:reportPayload,interpretation:reportPayload.interpretation},reportItem:{phase:['Requirements & CTQs'].includes(tab)?'Define':['Verification Plan','Pilot Readiness'].includes(tab)?'Control':'Improve',type:'analysis',structuredPayload:reportPayload,statsSummary:result||readiness,interpretation:reportPayload.interpretation}};
 const visibleVerifications=records.verifications.filter(item=>(filter==='All'||filter==='Missing Evidence'?!item.evidenceLinks?.length:filter==='Open Finding'?findings.some(finding=>finding.verificationId===item.id&&finding.status==='open'):item.status===filter)&&`${item.verificationKey} ${item.testName} ${item.owner}`.toLowerCase().includes(search.toLowerCase()));
 return <div className="practitioner-workflow"><header className="practitioner-hero"><div><span className="eyebrow">Product development evidence system</span><h1>Requirement-to-Verification Workspace</h1><p>Create, execute and trace product requirements through CTQs, design risk, canonical evidence, findings and readiness.</p></div><div className="context-chip"><strong>{saveState}</strong><span>{project?.name||'Select a project'}</span></div></header>
 <section className="workflow-card"><div className="form-grid"><label className="form-group"><span>Project</span><select value={projectId} onChange={event=>setProjectId(event.target.value)}><option value="">Select project</option>{projects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="form-group"><span>Workspace</span><select value={tab} onChange={event=>{setTab(event.target.value);setSelected(null);setDraft(null)}}>{TABS.map(item=><option key={item}>{item}</option>)}</select></label></div></section>
 {error&&<div className="alert alert-danger" role="alert">{error}</div>}{notice&&<div className="inline-notice" role="status">{notice}</div>}
 {tab==='Requirements & CTQs'&&<section className="workflow-card"><div className="workflow-card-heading"><h2>Requirements and CTQs</h2><div><button className="btn-secondary" onClick={()=>createNew('requirement')}>New Requirement</button><button className="btn-primary" onClick={()=>createNew('ctq')}>New CTQ</button></div></div><input placeholder="Search requirements and CTQs" value={search} onChange={event=>setSearch(event.target.value)}/><div className="table-scroll"><table className="professional-table"><thead><tr><th>ID</th><th>Title / CTQ</th><th>Owner</th><th>Status</th><th>Warnings</th></tr></thead><tbody>{[...records.requirements.map(item=>({type:'requirement',item})),...records.ctqs.map(item=>({type:'ctq',item}))].filter(({item})=>JSON.stringify(item).toLowerCase().includes(search.toLowerCase())).map(({type,item})=><tr key={item.id} onClick={()=>choose(type,item)}><td>{item.requirementKey||item.ctqKey}</td><td>{item.title||item.name}</td><td>{item.owner||'Missing'}</td><td>{item.status}</td><td>{[!item.owner&&'Missing owner',type==='ctq'&&item.lsl==null&&item.usl==null&&'Missing specification',type==='ctq'&&!item.measurementMethod&&'Missing test method'].filter(Boolean).join(', ')||'Traceable'}</td></tr>)}</tbody></table></div>{draft&&recordType!=='verification'&&<RecordEditor type={recordType} draft={draft} change={change} requirements={records.requirements}/>}</section>}
 {tab==='Verification Plan'&&<section className="workflow-card"><div className="workflow-card-heading"><h2>Operational Verification Matrix</h2><button className="btn-primary" onClick={()=>createNew('verification')}>New Verification</button></div><div className="form-grid"><input placeholder="Search" value={search} onChange={event=>setSearch(event.target.value)}/><select value={filter} onChange={event=>setFilter(event.target.value)}>{['All',...VERIFICATION_STATES,'Missing Evidence','Open Finding'].map(item=><option key={item}>{item}</option>)}</select></div><div className="table-scroll"><table className="professional-table"><thead><tr><th>Order</th><th>ID</th><th>Test</th><th>Owner</th><th>Status</th><th>Evidence</th><th>Finding</th></tr></thead><tbody>{visibleVerifications.map(item=><tr key={item.id} onClick={()=>choose('verification',item)}><td>{item.sortOrder}</td><td>{item.verificationKey}</td><td>{item.testName}</td><td>{item.owner||'Missing'}</td><td>{item.status}</td><td>{item.evidenceLinks?.length||0}</td><td>{findings.some(finding=>finding.verificationId===item.id&&finding.status==='open')?'Open':'—'}</td></tr>)}</tbody></table></div>{draft&&recordType==='verification'&&<VerificationEditor draft={draft} change={change} requirements={records.requirements} ctqs={records.ctqs} analyses={analysis.analysisResults.filter(item=>!item.projectId||item.projectId===projectId)} attachAnalysis={attachAnalysis} transition={transition} duplicate={duplicateVerification} createFinding={createFinding} openEvidence={evidence=>{const path=savedEvidencePath({...evidence,projectId});if(path)navigate(path)}}/>}</section>}
 {tab==='Traceability'&&<section className="workflow-card"><h2>Requirement Traceability Matrix</h2><div className="table-scroll"><table className="professional-table"><thead><tr><th>Requirement</th><th>CTQ</th><th>Risk</th><th>Verification</th><th>Evidence</th><th>Result</th><th>Finding / Gaps</th></tr></thead><tbody>{rows.map((row,index)=><tr key={index}><td>{row.requirement?.requirementKey}</td><td>{row.ctq?.ctqKey||'—'}</td><td>{row.risk?.id||'—'}</td><td>{row.verification?.verificationKey||'—'}</td><td>{row.evidence.length}</td><td>{row.verification?.status||'—'}</td><td>{row.flags.join(', ')||'Complete'}</td></tr>)}</tbody></table></div></section>}
 {tab==='Pilot Readiness'&&<section className="workflow-card"><div className={`assessment-banner ${readiness.status==='Ready'?'success':readiness.status==='Not Ready'?'danger':'warning'}`}><span>Evidence readiness</span><strong>{readiness.status}</strong></div><div className="stat-grid">{Object.entries(readiness.counts).map(([key,value])=><div className="stat-card" key={key}><div className="stat-value">{value}</div><div className="stat-label">{key}</div></div>)}</div><p>{readiness.statement}</p></section>}
 {tab==='Engineering Analytics'&&<section className="workflow-card"><h2>Configurable Engineering Studies</h2><div className="form-grid"><label className="form-group"><span>Study</span><select value={analyticsType} onChange={event=>changeAnalytics(event.target.value)}>{Object.keys(analyticsDefaults).map(item=><option key={item}>{item}</option>)}</select></label><label className="form-group"><span>Editable configuration</span><textarea rows="16" value={analyticsConfig} onChange={event=>setAnalyticsConfig(event.target.value)}/><small>Safe structured configuration; Monte Carlo expressions never use eval.</small></label></div><button className="btn-primary" onClick={runAnalytics}>Generate / Analyze</button>{result&&<pre className="definition-callout" style={{whiteSpace:'pre-wrap',maxHeight:420,overflow:'auto'}}>{JSON.stringify(result,null,2)}</pre>}</section>}
 {draft&&['requirement','ctq','verification'].includes(recordType)&&<div className="workflow-actions"><button className="btn-primary" onClick={save}>Save</button>{selected&&<button className="btn-secondary" onClick={archive}>Archive</button>}</div>}<section className="workflow-card"><div className="workflow-actions"><ProjectPlacementAction draft={placementDraft}>Add to Project</ProjectPlacementAction><ReportInclusionAction draft={placementDraft}/></div></section></div>}

function RecordEditor({type,draft,change,requirements}){const fields=type==='requirement'?['title','description','source','category','priority','owner','status','readinessState']:['name','description','characteristicType','unit','target','lsl','usl','toleranceDirection','measurementMethod','owner','status','rationale'];return <div><h3>{draft.id?'Edit':'Create'} {type}</h3><div className="form-grid">{fields.map(field=><label className="form-group" key={field}><span>{field.replace(/([A-Z])/g,' $1')}</span><input value={draft[field]??''} onChange={event=>change(field,event.target.value)}/></label>)}{type==='ctq'&&<label className="form-group"><span>Linked requirements</span><select multiple value={draft.requirementIds||[]} onChange={event=>change('requirementIds',[...event.target.selectedOptions].map(item=>item.value))}>{requirements.map(item=><option key={item.id} value={item.id}>{item.requirementKey} — {item.title}</option>)}</select></label>}</div><p>Revision {draft.revision||1}. Material changes create field-level history rather than overwriting the prior revision.</p></div>}
function VerificationEditor({draft,change,requirements,ctqs,analyses,attachAnalysis,transition,duplicate,createFinding,openEvidence}){const fields=['testName','purpose','verificationMethod','testType','sampleSize','sampleDefinition','conditions','equipment','measurementSystem','acceptanceCriterion','owner','plannedStart','plannedEnd','actualStart','actualEnd','rationale','comments','sortOrder'];return <div><h3>Execute {draft.verificationKey}</h3><div className="form-grid">{fields.map(field=><label className="form-group" key={field}><span>{field.replace(/([A-Z])/g,' $1')}</span><input value={draft[field]??''} onChange={event=>change(field,event.target.value)}/></label>)}<label className="form-group"><span>Requirements</span><select multiple value={draft.requirementIds||[]} onChange={event=>change('requirementIds',[...event.target.selectedOptions].map(item=>item.value))}>{requirements.map(item=><option key={item.id} value={item.id}>{item.requirementKey}</option>)}</select></label><label className="form-group"><span>CTQs</span><select multiple value={draft.ctqIds||[]} onChange={event=>change('ctqIds',[...event.target.selectedOptions].map(item=>item.value))}>{ctqs.map(item=><option key={item.id} value={item.id}>{item.ctqKey} — {item.name}</option>)}</select></label><label className="form-group"><span>Attach saved analysis</span><select defaultValue="" onChange={event=>event.target.value&&attachAnalysis(event.target.value)}><option value="">Select canonical analysis</option>{analyses.map(item=><option key={item.id} value={item.id}>{item.title||item.id}</option>)}</select></label></div><div className="definition-callout"><strong>Evidence:</strong> {draft.evidenceLinks?.length?draft.evidenceLinks.map(item=><button key={item.id} className="btn-secondary" onClick={()=>openEvidence(item)}>Open Evidence: {item.title}</button>):'Missing Evidence'}</div><div className="workflow-actions"><button className="btn-secondary" onClick={duplicate}>Duplicate Test</button>{['Planned','Ready','In Progress','Awaiting Evidence','Passed','Failed','Inconclusive','Waived'].map(status=><button key={status} className="btn-secondary" onClick={()=>transition(status)}>{status}</button>)}<button className="btn-secondary" onClick={createFinding}>Create Finding</button></div></div>}
