import React,{useMemo,useState}from'react';
import {CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Scatter,ScatterChart,Tooltip,XAxis,YAxis}from'recharts';
import {useAnalysis}from'../context/AnalysisContext';
import ProjectPlacementAction from'../components/ProjectPlacementAction';
import ReportInclusionAction from'../components/ReportInclusionAction';
import {acceptancePlan,designAcceptancePlan,fitLifeDistribution,fitStressLife,kaplanMeier,logRank,normalToleranceInterval,repairableSystem,warrantySummary,zeroFailureDemonstration}from'../utils/qualityReliabilityEngine';
import {createPractitionerFinding,structuredReportPayload}from'../utils/practitionerWorkflow';
import'./Tool.css';

const STUDIES=[['life','Life Data Analysis'],['km','Kaplan-Meier'],['alt','Accelerated Life Testing'],['warranty','Warranty Analysis'],['repairable','Repairable Systems'],['demonstration','Reliability Demonstration'],['acceptance','Acceptance Sampling'],['tolerance','Tolerance Intervals']];
const samples={life:'time,status,group,unitId\n120,failure,A,U1\n180,failure,A,U2\n220,censored,A,U3\n260,failure,A,U4\n310,censored,A,U5',km:'time,status,group,unitId\n6,failure,A,A1\n7,censored,A,A2\n10,failure,A,A3\n8,failure,B,B1\n12,censored,B,B2\n14,failure,B,B3',alt:'time,status,stress\n45,failure,125\n52,failure,125\n95,failure,100\n110,failure,100\n190,failure,80\n210,failure,80',warranty:'kind,cohort,units,cost,failureMode,failureAge\nshipment,2025-Q1,1000,,,\nshipment,2025-Q2,1200,,,\nclaim,2025-Q1,,120,Bearing,3\nclaim,2025-Q1,,85,Seal,5\nclaim,2025-Q2,,140,Bearing,2',repairable:'systemId,time,observationEnd\nPump-1,100,600\nPump-1,240,600\nPump-1,430,600\nPump-2,160,500\nPump-2,390,500',tolerance:'value\n10.1\n9.8\n10.4\n10.0\n9.9\n10.2'};
const parse=text=>{const lines=text.trim().split(/\r?\n/).filter(Boolean),headers=(lines.shift()||'').split(',').map(item=>item.trim());return lines.map(line=>Object.fromEntries(line.split(',').map((value,index)=>[headers[index],value.trim()]))) };
const serializable=value=>JSON.parse(JSON.stringify(value,(key,item)=>typeof item==='function'?undefined:item));

export default function ReliabilityWorkspace(){const analysis=useAnalysis(),[study,setStudy]=useState('life'),[text,setText]=useState(samples.life),[distribution,setDistribution]=useState('weibull'),[requestedTime,setRequestedTime]=useState('200'),[altModel,setAltModel]=useState('arrhenius'),[useStress,setUseStress]=useState('40'),[allowedFailures,setAllowedFailures]=useState('0'),[acceptanceMode,setAcceptanceMode]=useState('design'),[result,setResult]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const run=()=>{try{setError('');setNotice('');const rows=parse(text);let next;if(study==='life'){const fit=fitLifeDistribution(rows,distribution),comparison=['weibull','lognormal','exponential'].map(name=>fitLifeDistribution(rows,name)).map(item=>({distribution:item.distribution,logLikelihood:item.logLikelihood,aic:item.aic,bic:item.bic})).sort((a,b)=>a.aic-b.aic);next={...serializable(fit),requestedTime:Number(requestedTime),survivalProbability:fit.reliabilityAt(Number(requestedTime)),failureProbability:fit.unreliabilityAt(Number(requestedTime)),hazard:fit.hazardAt(Number(requestedTime)),comparison,bestFitLanguage:`${comparison[0].distribution} is best fitting among evaluated models by AIC; this does not prove the population follows that distribution.`,shapeInterpretation:distribution==='weibull'?(fit.parameters.shape<.95?'Decreasing failure rate / possible early-life pattern.':fit.parameters.shape>1.05?'Increasing failure rate / possible wear-out pattern.':'Approximately constant failure rate.'):null};}else if(study==='km'){const groups=[...new Set(rows.map(item=>item.group||'All units'))],groupResults=groups.map(group=>({group,...serializable(kaplanMeier(rows.filter(item=>(item.group||'All units')===group)))}));next={method:'grouped-kaplan-meier',methodVersion:'1.0.0',groups:groupResults,groupComparison:groups.length===2?logRank(rows):null};}else if(study==='alt')next=fitStressLife(rows,{model:altModel,useStress:Number(useStress),temperatureUnit:'C'});else if(study==='warranty')next=warrantySummary({shipments:rows.filter(item=>item.kind==='shipment'),claims:rows.filter(item=>item.kind==='claim')});else if(study==='repairable')next=repairableSystem(rows);else if(study==='demonstration')next=zeroFailureDemonstration({targetReliability:.9,confidence:.9,allowedFailures:Number(allowedFailures)});else if(study==='acceptance')next=acceptanceMode==='design'?designAcceptancePlan({lotSize:1000,aql:.01,producerRisk:.05,ltpd:.06,consumerRisk:.1}):acceptancePlan({lotSize:1000,sampleSize:80,acceptanceNumber:2,defectRate:.01,aql:.01,ltpd:.06});else next=normalToleranceInterval(rows.map(item=>item.value),{coverage:.99,confidence:.95});setResult(next);}catch(problem){setResult(null);setError(problem.message)}};
 const title=STUDIES.find(item=>item[0]===study)?.[1], payload=useMemo(()=>result?structuredReportPayload({method:result.method,methodVersion:result.methodVersion,configuration:{studyType:study,distribution,censoringDefinition:'Failure=exact event; Suspended/Censored=right censored'},metrics:result,tables:{eventTable:result.table||[],ocCurve:result.ocCurve||[]},interpretation:result.trend||result.limitation||`${title} completed.`,warnings:[...(result.warnings||[]),result.warning,result.extrapolationWarning].filter(Boolean),evidence:{datasetId:analysis.datasetId,datasetVersionId:analysis.dataset?.versionId||'',variableMappings:Object.keys(parse(text)[0]||{})}}):null,[analysis.dataset,analysis.datasetId,distribution,result,study,text,title]);
 const draft=result?{title:`${title} Result`,toolId:'reliability',projectId:analysis.projectId,analysis:{toolId:'reliability',method:result.method,methodVersion:result.methodVersion,validationStatus:'UNVALIDATED',inputConfiguration:{studyType:study,distribution},result:payload,interpretation:payload.interpretation},reportItem:{phase:study==='acceptance'?'Control':'Analyze',type:'analysis',statsSummary:result,interpretation:payload.interpretation,structuredPayload:payload}}:null;
 const changeStudy=value=>{setStudy(value);setText(samples[value]||'');setResult(null);setError('');setNotice('')};
 const createFinding=()=>{if(!draft)return;const analysisId=analysis.registerAnalysisResult({...draft.analysis,title:draft.title,projectId:draft.projectId}),type=study==='life'?(result.parameters?.shape<1?'early_life_failure_pattern':'wear_out_pattern'):study==='alt'?'alt_extrapolation_risk':study==='warranty'?'warranty_claim_rate_elevated':study==='repairable'?'reliability_deterioration':study==='acceptance'?'acceptance_risk_exceeded':study==='tolerance'?'tolerance_requirement_not_demonstrated':'reliability_below_target',finding=createPractitionerFinding({analysisId,dataset:analysis.dataset,variable:Object.keys(parse(text)[0]||{}).join(', '),type,severity:'warning',statement:`${title}: review the reported evidence and governing assumptions.`,evidence:{resultPath:'result',method:result.method,methodVersion:result.methodVersion,threshold:study==='life'?Number(requestedTime):null,metrics:serializable(result)}});localStorage.setItem('aureqin_latest_finding',JSON.stringify(finding));setNotice('Finding created with canonical analysis and dataset-version evidence.')};
 return <div className="practitioner-workflow"><header className="practitioner-hero"><div><span className="eyebrow">Enterprise quality & reliability</span><h1>Reliability Analysis Workspace</h1><p>Analyze censored life data, survival, accelerated testing, warranty exposure, repairable systems, demonstration tests, lot acceptance, and tolerance coverage.</p></div><div className="governance-chip"><strong>UNVALIDATED</strong><span>Wave 3B governance applies</span></div></header>
 <div className="study-selector">{STUDIES.map(([id,label])=><button key={id} className={study===id?'active':''} onClick={()=>changeStudy(id)}><strong>{label}</strong><span>{id==='life'?'Censored MLE and distribution comparison':id==='km'?'Nonparametric survival with suspensions':id==='acceptance'?'Attribute single-sampling risk':'Guided practitioner workflow'}</span></button>)}</div>
 <section className="workflow-card"><div className="workflow-card-heading"><div><span className="step-kicker">Study setup</span><h2>{title}</h2></div></div>{['life','km','alt','warranty','repairable','tolerance'].includes(study)&&<label className="form-group"><span>CSV observations</span><textarea rows="9" value={text} onChange={event=>setText(event.target.value)}/></label>}{study==='life'&&<div className="form-grid"><label className="form-group"><span>Distribution</span><select value={distribution} onChange={event=>setDistribution(event.target.value)}><option value="weibull">Weibull (2-parameter)</option><option value="lognormal">Lognormal</option><option value="exponential">Exponential</option></select></label><label className="form-group"><span>Requested time</span><input type="number" min="0" value={requestedTime} onChange={event=>setRequestedTime(event.target.value)}/></label></div>}{study==='alt'&&<div className="form-grid"><label className="form-group"><span>Stress-life model</span><select value={altModel} onChange={event=>setAltModel(event.target.value)}><option value="arrhenius">Arrhenius temperature</option><option value="inverse-power">Inverse power law</option></select></label><label className="form-group"><span>Use-condition stress</span><input type="number" value={useStress} onChange={event=>setUseStress(event.target.value)}/></label></div>}{study==='demonstration'&&<label className="form-group"><span>Allowed failures</span><input type="number" min="0" step="1" value={allowedFailures} onChange={event=>setAllowedFailures(event.target.value)}/></label>}{study==='acceptance'&&<label className="form-group"><span>Workflow</span><select value={acceptanceMode} onChange={event=>setAcceptanceMode(event.target.value)}><option value="design">Design from AQL/LTPD risks</option><option value="evaluate">Evaluate existing plan</option></select></label>}<button className="btn-primary" onClick={run}>Run {title}</button>{error&&<div className="alert alert-danger" role="alert">{error}</div>}</section>
 {result&&<section className="workflow-card results-card"><div className="workflow-card-heading"><div><span className="step-kicker">Saved-result ready</span><h2>{title} results</h2></div><span className="governance-chip">UNVALIDATED</span></div><div className="table-scroll"><table className="professional-table"><tbody>{Object.entries(result).filter(([,value])=>(['string','number'].includes(typeof value)&&Number.isFinite(value))||typeof value==='string').slice(0,18).map(([key,value])=><tr key={key}><th>{key.replace(/([A-Z])/g,' $1')}</th><td>{typeof value==='number'?value.toPrecision(6):value}</td></tr>)}</tbody></table></div>{result.table&&<div className="table-scroll"><table className="professional-table"><thead><tr>{Object.keys(result.table[0]||{}).map(key=><th key={key}>{key}</th>)}</tr></thead><tbody>{result.table.map((row,index)=><tr key={index}>{Object.values(row).map((value,column)=><td key={column}>{typeof value==='number'?value.toFixed(4):value}</td>)}</tr>)}</tbody></table></div>}
 {study==='life'&&<><h3>Fitted reliability and hazard</h3><ResponsiveContainer width="100%" height={260}><LineChart data={result.curve}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time"/><YAxis/><Tooltip/><Legend/><Line dataKey="reliability" stroke="var(--accent)" dot={false}/><Line dataKey="hazard" stroke="var(--red)" dot={false}/></LineChart></ResponsiveContainer><h3>Life-data probability diagnostic</h3><p className="interpretation-copy">Failure and suspension points are displayed separately. Parameters come from censored MLE, not probability-plot regression.</p><ResponsiveContainer width="100%" height={260}><ScatterChart><CartesianGrid/><XAxis dataKey="time" type="number"/><YAxis dataKey="plottingProbability" type="number" domain={[0,1]}/><Tooltip/><Legend/><Scatter name="Failures" data={result.probabilityPlot.filter(item=>item.failed)} fill="var(--accent)"/><Scatter name="Suspensions" data={result.probabilityPlot.filter(item=>!item.failed)} fill="var(--text-muted)" shape="cross"/></ScatterChart></ResponsiveContainer></>}
 {study==='km'&&<>{result.groups.map((group,index)=><div key={group.group}><h3>{group.group} · median {group.medianLabel}</h3><ResponsiveContainer width="100%" height={230}><LineChart data={group.table}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="time"/><YAxis domain={[0,1]}/><Tooltip/><Line type="stepAfter" dataKey="survival" stroke={index%2?'var(--red)':'var(--accent)'} dot/><Line type="stepAfter" dataKey="lower" stroke="var(--text-muted)" dot={false}/><Line type="stepAfter" dataKey="upper" stroke="var(--text-muted)" dot={false}/></LineChart></ResponsiveContainer><div className="table-scroll"><table className="professional-table"><thead><tr><th>Time</th><th>At risk</th><th>Failures</th><th>Censored</th><th>Survival</th></tr></thead><tbody>{group.table.map(row=><tr key={row.time}><td>{row.time}</td><td>{row.atRisk}</td><td>{row.failures}</td><td>{row.censored}</td><td>{row.survival.toFixed(4)}</td></tr>)}</tbody></table></div></div>)}</>}
 {study==='alt'&&result.fitted&&<ResponsiveContainer width="100%" height={260}><LineChart data={result.fitted}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="stress"/><YAxis/><Tooltip/><Legend/><Line dataKey="life" stroke="var(--accent)"/><Line dataKey="predictedLife" stroke="var(--red)"/></LineChart></ResponsiveContainer>}
 {study==='warranty'&&<><h3>Claims and rates by cohort</h3><div className="table-scroll"><table className="professional-table"><thead><tr><th>Cohort</th><th>Units exposed</th><th>Claims</th><th>Claim rate</th><th>Cost</th></tr></thead><tbody>{result.cohortSummary.map(row=><tr key={row.cohort}><td>{row.cohort}</td><td>{row.unitsExposed}</td><td>{row.claims}</td><td>{row.claimRate===null?'Exposure missing':`${(100*row.claimRate).toFixed(2)}%`}</td><td>{row.cost.toFixed(2)}</td></tr>)}</tbody></table></div><ResponsiveContainer width="100%" height={240}><LineChart data={result.failuresByAge}><CartesianGrid/><XAxis dataKey="age"/><YAxis/><Tooltip/><Line dataKey="claims" stroke="var(--accent)"/><Line dataKey="cumulativeClaims" stroke="var(--red)"/></LineChart></ResponsiveContainer></>}
 {study==='acceptance'&&<ResponsiveContainer width="100%" height={260}><LineChart data={result.ocCurve}><CartesianGrid/><XAxis dataKey="defectRate"/><YAxis domain={[0,1]}/><Tooltip/><Line dataKey="probabilityAcceptance" stroke="var(--accent)" dot={false}/></LineChart></ResponsiveContainer>}
 <div className="definition-callout"><strong>Interval terminology:</strong> A confidence interval estimates a parameter. A prediction interval predicts a future observation. A tolerance interval covers a stated population proportion at a stated confidence.</div><div className="workflow-actions"><button type="button" className="btn-secondary" onClick={createFinding}>Create Finding</button><ProjectPlacementAction draft={draft}>Add to Project</ProjectPlacementAction><ReportInclusionAction draft={draft}/></div>{notice&&<div className="inline-notice" role="status">{notice}</div>}</section>}</div>}
